### ISSUE TITLE
How can i config saml realms?

### ISSUE THREAD

**Issue by ming2020** [elastic/cloud-on-k8s#1002]
Is custom realms not support on this version?
How should clusters previously using SAML migrate to k8s.

**Comment by nkvoll** [comment]
SAML would not be supported in the alpha, but we're hoping to close the loop on the remaining foundational pieces to making it work as soon as we're able (e.g https://github.com/elastic/cloud-on-k8s/issues/740, which is needed to configure the Kibana side of things).
