### ISSUE TITLE
tls section in Elasticsearch Custom Resource Spec

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#1007]
In the Elasticsearch Custom Resource Spec is it possible to define only the tls section within the http block? Something like below:

spec:

  http:

    tls:

      selfSignedCertificate:

        subjectAltNames:

        - dns: hulk.example.com

instead of 

spec:

  http:

    service:

      spec:

        type: LoadBalancer

    tls:

      selfSignedCertificate:

        subjectAltNames:

        - ip: 35.193.255.203

The reason is, I want the ES Operator to only do the association of the IP that is provided with the Self-signed cert that it has internally created. I don't want the ES Operator to create a LoadBalancer. 

Let me know if this is possible.

The use-case is, I have nginx-ingress-controller in my setup which already has a LB associated with it. I want to use that LB IP to reach to ES. Note that in this case it is okay for ES to run as ClusterIP.

**Comment by sebgl** [comment]
Yes, it's absolutely possible. You can specify subjectAltNames to inject into the certificates, without requiring a LoadBalancer service. You'll end up with a default ClusterIP.

**Comment by devdattakulkarni** [comment]
Awesome!

**Comment by sebgl** [comment]
:)
