### ISSUE TITLE
ES Service name

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#1012]
Does the comment about name and namespace in ServiceTemplate definition here
https://github.com/elastic/cloud-on-k8s/blob/master/operators/pkg/apis/common/v1alpha1/common.go#L68

mean that users cannot configure name of the Service for ES?

If so, is the name always going to be following convention:
"name-of-ES-Custom-resource"-es?

**Comment by nkvoll** [comment]
That is a correct understanding of the comment as it stands. Do you have a specific use case in mind for being able to control the name of this service? It's of course also possible for you to create your own `Service` that selects your ES pods yourself, which would not be tied to the operator.

The name of the service is intended to be available in `Elasticsearch.status.service`, and currently follows the pattern `{es.name}-es-http` (though we reserve the right to break backwards compatibility here regarding naming and fields before GA).

**Comment by devdattakulkarni** [comment]
@nkvoll My use-case is outlined here https://github.com/elastic/cloud-on-k8s/issues/1010

I tried creating a separate service with appropriately set label selector. But that did not help as well with above use-case.

Any pointers on how to get above use-case working will be appreciated.

**Comment by sebgl** [comment]
@devdattakulkarni if this is related to setting up an ingress and dealing with TLS certificates, maybe we can continue the discussion in #1010? Can you report there?
Closing this one now.
