### ISSUE TITLE
Draft for discussion: ECK Operator and ES communication

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#1016]
Disclaimer: This is a rough draft of some ideas that came up during a chat over some coffee and is in very early stages of capturing ideas/possibilities.

Motivator:
- Talking to ES is always going to have the potential to cause issues:
    - Time to respond? Not possible to tell.
    - Blocking reconciliation goroutines?

Have:

`observer` package:
    - Takes a configured client
        - periodically requests cluster state (for routing table), cluster health?
        - also requests the PM to get keystore updater status
            - (note: maybe considered an extension of the ES API: perhaps something to suggest upstream?)
    - Why: Don't want to be polling ES during reconciliation.

Main problem:

- ES does not fully seperate control plane from data plane.
    - Data plane goes down or is overloaded: control plane is unresponsive.

Main goal:
- Don't want to be polling ES **or doing any IO** with ES during reconciliation.

### Random ideas(s):

- What if the reconciliation worked against this:

```go
interface LogicalElasticsearchCluster {
    // all interfaces are required to have that one weird method nobody knows what does
    Foo() error

    // these are a bit too specific
    DisableAllocation() error
    EnableAllocation() error

    // these are nice and logical operations / wants
    PrepareForNodeTermination(nodes []string) (bool, error)
    IsPreparedForNodeTermination(nodes []string) (bool, error)

    // some other example
    PrepareForNodeRestart(nodes []string) ([]string, error)
    IsReadyForNodeRestart(nodes []string) (bool, error)

    // probably too specific:
    MigrateDataAwayFrom(nodes []string) error
}
```

- Interface implementations are supposed to be constant/instant, not communicating directly with ES, but setting desired state etc.

- This is quite lite a seperate reconciliation loop, specifically for an Elasticsearch cluster.

- Could provide a means to have nicer tests for the reconciliation (e.g dont have to mock an ES cluster / client)

- Perhaps we can re-use a ton of functionality here from K8s? Indexers/Caches/Reconciliation queues etc etc? Who knows at this point.. Like a "synthetic reconciliation", in-memory local to the operator.

- May communicate wants/haves through status as well?

```yaml
status:
    want:
        disableShardAllocation: true/false
        prepareNodesForTermination: []string # migrate data away from these

        podChanges: some short version of mutation.Changes?
    have:
        ....
```

#### Obligatory off topic random thing at the bottom:

- Would be good if we were able to turn off ES comms, e.g only orchestrate /infrastructure/, not the cluster.
    - E.g not too far off from setting both `maxUnavailable/maxSurge: 0`.

**Comment by pebrc** [comment]
I am +1 on this. I had similar thoughts whenever I observed a blocking ES call delaying the progress in the reconciliation loop. Not sure about the Indexer, Caches etc. I would keep it simple. 
It seems we need more time to design the interface though.  I can see a justification for some low level methods ('apply license') and some more high level methods (as in the example  above 'prepare node termination') but it feels a bit arbitrary.

**Comment by nkvoll** [comment]
Looking a little further into the specifics, doing a full on synthetic reconciliation loop, caches, indexers etc seems both a little overkill and too much of a technical challenge, so yes, @pebrc simple is probably better here..

**Comment by nkvoll** [comment]
Closing in favor of https://github.com/elastic/cloud-on-k8s/issues/2086
