### ISSUE TITLE
Write Elasticsearch Spec documentation

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1031]
Should cover advanced usage such as:

* SetVMMaxMapCount
* Set JVM heap size
* Resource limits
* Volume claim templates
* Node configuration
* Pod Template
* Setup init containers for plugin downloads
* Pod disruption budget
* Change budget (maxUnavailable, maxSurge)
* HTTP settings & TLS SANs
* Custom HTTP cert
* Secure settings
* Custom plugins and bundles

**Comment by avloss** [comment]
Could this also cover how to disable password?

**Comment by pebrc** [comment]
Let's break this down into smaller issues that could be worked on in parallel

**Comment by alaudazzi** [comment]
After discussion with @sebgl, this documentation task is reorganised in two main sections, with relevant topic contributors:

## How to configure your cluster
Put a general introduction here [@alaudazzi]

Add a description for each feature and integrate one or more examples.

### Basic features (features everyone should know about)

- Set JVM heap size [@barkbay]
- Resource limits  [@barkbay]
- Volume claim templates [@barkbay]
- Node configuration [@thb]
- Pod Template [@sebgl]
- HTTP settings & TLS SANs [@thb] 
(examples for this feature already exist in https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-accessing-elastic-services.html)

### Advanced features (features for experienced users)

- SetVMMaxMapCount [@nkvoll]
- Setup init containers for plugin downloads [@pebrc]
- Pod disruption budget [@nkvoll]
- Change budget (maxUnavailable, maxSurge) [@sebgl] 
- Custom HTTP cert [@thb]
- Secure settings [@pebrc]
- Custom plugins and bundles [@pebrc]

**Comment by pebrc** [comment]
I have updated the break down to include all team members.

**Comment by alaudazzi** [comment]
Completed the doc reorg and editing in #1421.
