### ISSUE TITLE
Set defaults for init containers for Kibana and APM

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#1035]
In https://github.com/elastic/cloud-on-k8s/pull/1022, init containers by default will see the same volumes and image as the main container, but it was applied to Elasticsearch only.

The same behavior seems warranted across other resources (Kibana and APM) as well.

**Comment by charith-elastic** [comment]
Unless I have misunderstood the issue, it looks like both [Kibana](https://github.com/elastic/cloud-on-k8s/blob/c523e1045c11283136193a6e1c87925d29d15eb4/pkg/controller/kibana/pod/pod.go#L57) and [APM](https://github.com/elastic/cloud-on-k8s/blob/c523e1045c11283136193a6e1c87925d29d15eb4/pkg/controller/apmserver/pod.go#L83) controllers already make use of the code introduced in #1022 so I think we can close this.

**Comment by thbkrkr** [comment]
Yes, you are right. #1063 brings the changes related to the default init containers to Kibana and #1181 to the APM Server. Let's close this.
