### ISSUE TITLE
Ability to configure the default ES Pod affinity between hard and soft

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#1036]
https://github.com/elastic/cloud-on-k8s/pull/1026 adds a default `soft` pod anti affinity.

It would be great if this could be configurable between `hard` and `soft` (e.g `required` vs `preferred`).

**Comment by sebgl** [comment]
Not sure we need another way to configure it: users can set an explicit `required` policy?
Defaulting to `preferred` sounds like the right approach to me. I don't think we should do anything more.
