### ISSUE TITLE
Improve ES pod spec comparisons to take the entire podTemplate into consideration

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1046]
Most of the podTemplate section including are ignored during ES pod spec comparison. This includes:  

* labels
* annotations
* probes
* volumes
* init containers
* containers
* ports
* image pull policy
* termination grace period
* etc.

What we do take into consideration so far:
* pod name
* container name
* image name
* environment variables
* ES configuration
* resources
* PVCs

We should make sure we do compare the entire podTemplate content.

**Comment by sebgl** [comment]
I think there are several approaches we could use to perform the comparison:

1. Discrete fields comparison

That's what we do right now: compare pod name, then container name, then environment variables, then resources, etc.
Advantage: it allows us to do custom comparisons. For example: if the actual pod has more labels than the expected one, it's probably ok not to replace it.
Disadvantage: there are *many* fields to compare in a podSpec.

2. reflect.DeepEqual(actualPodSpec, expectedPodSpec)

It doesn't work well for us: actual pod contains fields that are defaulted by the apiserver upon resource creation. Expected does not have these fields, since not created yet. It 

3. Rely on controller revisions

This is what StatefulSets in Kubernetes seem to be using: a `controllerrevision` resource per "version" of the StatefulSet resource, storing the entire StatefulSet resource as JSON in an annotation, and a hash of that content in a label. The pod references this resource by name in its labels: `controller-revision-hash: web-6596ffb49b`. I think any difference in the statefulset template leads to rotating all pods.

**Comment by sebgl** [comment]
I think we can probably combine approaches 1 and 3:

* compare pod's labels and objectMeta manually: it's probably OK if the actual pod has more labels and annotations than the expected one (can be set by the user or the operator after initial resource creation)
* store a hash of the podSpec to create into the created pod annotations. Perform a strict hash comparison on actual vs. expected pod to know if the pod should be rotated. The hash needs to be consistent (ie. don't rely on string json serialization that could mess up map ordering?).

We can't rely only on the hash of the podTemplate from the ES spec (similar to StatefulSets) because we do append our own stuff on top of this podTemplate, which should be taken into consideration in comparisons. It needs to be the "final" computed PodSpec.

I don't think it's necessary to store this hash in another resource such as done by StatefulSets in `controllerrevision`.

**Comment by sebgl** [comment]
An interesting bit from the Deployments controller that simply checks deep equality of 2 pod templates (removing their custom revision hash label first): 

https://github.com/kubernetes/kubernetes/blob/8de1569ddae62e8fab559fe6bd210a5d6100a277/pkg/controller/deployment/util/deployment_util.go#L628-L640

**Comment by sebgl** [comment]
The hash mechanism used by StatefulSets seems to rely on fnv (hash function) + go-spew to hash a pretty-printed version (no pointers ref) of an object: https://github.com/kubernetes/kubernetes/blob/8de1569ddae62e8fab559fe6bd210a5d6100a277/pkg/controller/history/controller_history.go#L89-L101

**Comment by pebrc** [comment]
Not sure if this is strictly relevant here or has any influence on your decision, but wanted to mention that with whatever approach you take for things like #851 we also need the ability to be slightly more lenient in the comparison and ignore in this example certain classes of environment variables

**Comment by sebgl** [comment]
@pebrc I think that's why it's important not to compare an expected (computed) pod spec with the spec of an actual running pod, but instead compare with the computed pod spec that led to the creation of the actual pod, that we store somewhere. Or their corresponding hashes.

This way we ignore any value that may have been overridden at resource creation time (including defaulted values and cloud-provider specific environment variables injected in to the pod, I guess from admission/mutation controllers).

**Comment by sebgl** [comment]
From a team discussion, we sort of agreed on storing the pod spec (before pod creation) hash into the pod annotations, to be used for pod comparison.

**Comment by sebgl** [comment]
One challenge is to properly match references to external resources containing the pod name.

When we generate the pod spec, we don't have a name for the pod yet. At pod comparison time the spec is missing some resources:

* ref to an external PVC name
* ref to an external transport cert secret
* ref to an external config secret

These external resources are created (and added to the pod spec) only once we've decided we should actually create the pod (way after pod comparison time). At that time we generate the pod name, and derive resources names from the pod name.

We do want to include these important resource references in the pod spec hash comparison though; and I think it's not very clean that they aren't part of the initial spec to compare with but added later on in the process.

Let's add them early on! But with what name? For the spec hash to match, name references from the actual pod spec must match name references from the spec that is compared.

The best way I see to achieve that is to do the following changes:

Pod Spec creation:
* use `<POD_NAME_PLACEHOLDER>` when generating the pod spec, whenever pod name is required
* create a **complete** pod spec to start with (nothing missing in the spec)

Pod resource creation:
* generate the pod name
* replace references to `<POD_NAME_PLACEHOLDER>` by the actual pod name in the spec (that's the ugly part imo)
* the hash we store in the pod labels is based on the spec with the placeholder name, not derived spec with the real name: this allows the pod to be easily compared with any un-named spec

**Comment by pebrc** [comment]
You suggestion looks workable even though the placeholder replacement feels somewhat hacky. 
One alternative I can see would be stable pod names (ordinals ;-) )

**Comment by sebgl** [comment]
We can use `transport-certs` instead of `<POD_NAME_PLACEHOLDER>-transport-certs` if it feels less hacky 😄 
The important point being we do need to patch those 3 sections of the spec just before creating the actual pod. 
This is something we already do halfway btw: transport certs secret is already there in the spec (with "" as a name), then replaced before pod creation. Config and PV are appended though (not there in the initial spec). A bit inconsistent.
