### ISSUE TITLE
Documentation about adding plugins

### ISSUE THREAD

**Issue by mfouilleul** [elastic/cloud-on-k8s#1051]
Hello!

I can't find any resources to add new plugins, does the plugins list can be overrided in the initcontainers script? 

https://github.com/elastic/cloud-on-k8s/blob/90663df81752703015e1d51a25c18052e21a57f1/operators/pkg/controller/elasticsearch/initcontainer/prepare_fs_script.go#L21

I wanted to add the prom exporter https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.1.1.0/prometheus-exporter-7.1.1.0.zip

Thanks max.

**Comment by sebgl** [comment]
Hey Max,

Sorry that's not supported yet in release 0.8. We do have in mind to support and document it for the next release (0.9).

You can follow https://github.com/elastic/cloud-on-k8s/issues/35  that will track this feature.

PR https://github.com/elastic/cloud-on-k8s/pull/1022#issue-286271634 that has been merged into master recently adds support for user-provided init containers, in which you could download and install any custom plugin you want before ES nodes get started. That's probably the way it will work in 0.9 :)

I'm closing this for now, let's keep https://github.com/elastic/cloud-on-k8s/issues/35 open.

**Comment by mfouilleul** [comment]
Thanks for the answer.
