### ISSUE TITLE
Delete "Elasticsearch" CRD is hanging

### ISSUE THREAD

**Issue by mfouilleul** [elastic/cloud-on-k8s#1094]
Hello. 

I am testing the operator and I am facing a bad behaviour, I can't kubectl delete my cluster, it is hanging in "pending" since days. 

```
$ kubectl get es                                                                                                        
NAME   HEALTH   NODES   VERSION   PHASE     AGE
test   red              6.8.0     Pending   5d
```

There is nothing special in the operator's pod logs. 

This state happened after I deleted some pod and pvc. 

I am on GKE (1.13), I tried to kubectl all the related resources (services, secrets etc...), I recreated the operator, then I finally deleted the namespace, and when I recreated it the es resources get back from nowhere (probably etcd :p) with the same status...

I am on testing/benching phase so no problem but it is strange that I can't get back to a normal state no?

**Comment by jonsabo** [comment]
Hi @mfouilleul, would you be able to share a redacted version of the ES object please (e.g. `kubectl get es test -o yaml`)? I wonder if perhaps a finalizer is not getting removed for some reason.

**Comment by mfouilleul** [comment]
Hi, here the output.
{code}
kubectl get es test -o yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  annotations:
    flux.weave.works/sync-checksum: 3c59d93183f6f99c7a499a44ff1429a1ab8d8ee9
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"elasticsearch.k8s.elastic.co/v1alpha1","kind":"Elasticsearch","metadata":{"annotations":{"flux.weave.works/sync-checksum":"3c59d93183f6f99c7a499a44ff1429a1ab8d8ee9"},"labels":{"flux.weave.works/sync-gc-mark":"sha256.VYBzvfT3pxdkM5yr3U61Vif1q2o7ZF19lnjg3Va3nYM"},"name":"test","namespace":"dbre"},"spec":{"nodes":[{"config":{"cluster.routing.allocation.awareness.attributes":"zone","node.attr.zone":"europe-west4-a","node.data":false,"node.ingest":false,"node.master":true},"nodeCount":1,"podTemplate":"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"failure-domain.beta.kubernetes.io/zone","operator":"In","values":["europe-west4-a"]}]}]}}},"automountServiceAccountToken":true}},"volumeClaimTemplates":[{"metadata":{"name":"master"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"ssd"}}]},{"config":{"cluster.routing.allocation.awareness.attributes":"zone","node.attr.zone":"europe-west4-b","node.data":false,"node.ingest":false,"node.master":true},"nodeCount":1,"podTemplate":"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"failure-domain.beta.kubernetes.io/zone","operator":"In","values":["europe-west4-b"]}]}]}}},"automountServiceAccountToken":true}},"volumeClaimTemplates":[{"metadata":{"name":"master"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"ssd"}}]},{"config":{"cluster.routing.allocation.awareness.attributes":"zone","node.attr.zone":"europe-west4-c","node.data":false,"node.ingest":false,"node.master":true},"nodeCount":1,"podTemplate":"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"failure-domain.beta.kubernetes.io/zone","operator":"In","values":["europe-west4-c"]}]}]}}},"automountServiceAccountToken":true}},"volumeClaimTemplates":[{"metadata":{"name":"master"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"ssd"}}]},{"config":{"node.data":true,"node.ingest":true,"node.master":false},"nodeCount":3,"podTemplate":"volumeClaimTemplates":[{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"ssd"}}]}],"version":"6.8.0"}}
  creationTimestamp: "2019-06-12T14:12:01Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2019-06-18T07:27:07Z"
  finalizers:
  - dynamic-watches.finalizers.elasticsearch.k8s.elastic.co/http-certificates
  generation: 10
  labels:
    flux.weave.works/sync-gc-mark: sha256.VYBzvfT3pxdkM5yr3U61Vif1q2o7ZF19lnjg3Va3nYM
  name: test
  namespace: dbre
  resourceVersion: "13018074"
  selfLink: /apis/elasticsearch.k8s.elastic.co/v1alpha1/namespaces/dbre/elasticsearches/test
  uid: 0c7fd241-8d1c-11e9-8caa-4201c0a88019
spec:
  http:
    service:
      metadata: {}
      spec: {}
    tls: {}
  nodes:
  - config:
      cluster.routing.allocation.awareness.attributes: zone
      node.attr.zone: europe-west4-a
      node.data: false
      node.ingest: false
      node.master: true
    nodeCount: 1
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west4-a
        automountServiceAccountToken: true
    volumeClaimTemplates:
    - metadata:
        name: master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ssd
  - config:
      cluster.routing.allocation.awareness.attributes: zone
      node.attr.zone: europe-west4-b
      node.data: false
      node.ingest: false
      node.master: true
    nodeCount: 1
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west4-b
        automountServiceAccountToken: true
    volumeClaimTemplates:
    - metadata:
        name: master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ssd
  - config:
      cluster.routing.allocation.awareness.attributes: zone
      node.attr.zone: europe-west4-c
      node.data: false
      node.ingest: false
      node.master: true
    nodeCount: 1
    podTemplate:
      metadata:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west4-c
        automountServiceAccountToken: true
    volumeClaimTemplates:
    - metadata:
        name: master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ssd
  - config:
      node.data: true
      node.ingest: true
      node.master: false
    nodeCount: 3
    podTemplate:
      metadata:
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ssd
  updateStrategy: {}
  version: 6.8.0
status:
  clusterUUID: uANBo2UFRpO3vEHV5Yp_7A
  health: red
  masterNode: test-es-lg88csgfgb
  phase: Pending
  service: test-es
  zenDiscovery:
    minimumMasterNodes: 2
{code}

**Comment by mfouilleul** [comment]
Thanks for the hint. 

I patched the resource with an empty finalizers and it unlock the release. 

```
kubectl patch es/test -p '{"metadata":{"finalizers":[]}}' --type=merge
```

**Comment by sebgl** [comment]
@mfouilleul glad to know you managed to solve the situation by deleting the finalizers.
This can happen if you ran, for example, a recent version of the operator (from master), then an older version (0.8). Is that the case?

**Comment by dcvtruong** [comment]
@sebgl I'm running 0.9 and using kubectl to delete the crd kibanas.kibana.k8s.elastic.co hung.  How do I find out  if the finalizers is not getting deleted properly?

**Comment by bikkinamahesh369** [comment]
@sebgl same issue happened for us when we tried to install elastic 0.9.0 and after that, we downgraded to 0.8.1
