### ISSUE TITLE
Investigate possibility of using https://cloud-test-stats.elastic.co for collecting test data

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#1098]
We have https://cloud-test-stats.elastic.co for aggregating test data which is used for Scala code right now. It might be a good idea to put test stats there.

The main issue at the moment - we need to provide test results in xUnit XML compatible format. It should be possible, https://github.com/jstemmer/go-junit-report can do that, for example.

**Comment by artemnikitin** [comment]
Some additional info:
https://github.com/elastic/cloud/blob/master/scala-services/integration-tests/ci/docs/es-testreport.md
https://github.com/elastic/cloud/blob/master/scala-services/integration-tests/ci/scripts/testreport.groovy
https://github.com/elastic/cloud/blob/master/Jenkinsfile#L330-L337

**Comment by thbkrkr** [comment]
I like the idea to collect test data to have a consolidated view and to ease diagnostics when failures occur. 

I have little extra idea. It could also be an opportunity to eat our own food. We could use an Elasticsearch cluster managed by ECK to aggregate this test data. This would allow us to use the product we build, to stay alert to the user experience and see how it behaves over time.
This would allow us to use the product we are building, help us to stay attentive to the user experience and to see how it behaves over time.

**Comment by pebrc** [comment]
Closing in favour of #2270
