### ISSUE TITLE
Upgrade your cluster

### ISSUE THREAD

**Issue by alaudazzi** [elastic/cloud-on-k8s#1143]
This issue depends on how exhaustive the content is in #1031.
Possible structure:

### How to change the ES configuration

- 	link to ES doc
- 	provide 1/2 examples

### How to change the cluster topology

- explain what a “nod spec” is (possibly already covered in “How to configure”)
- provide examples on the current topology => dedicated master, hot-warm

### How to upgrade ES version

- one field to be changed
- limitation: you can only migrate from one version to another one

**Comment by pebrc** [comment]
I see some overlap here to the "node configuration" section of https://github.com/elastic/cloud-on-k8s/issues/1031
