### ISSUE TITLE
Debug your cluster

### ISSUE THREAD

**Issue by alaudazzi** [elastic/cloud-on-k8s#1145]
This doc is optional and might be completed after the beta.

## How to debug

Possible scenarios: 

- get ES nodes logs
- delete a pod
- change the config
- kubectl exec 
- rollback

**Comment by weeco** [comment]
What about docs about debugging performance issues (separated by search and writing performance)?

**Comment by sebgl** [comment]
@weeco I think this would be covered by Elasticsearch docs directly.
