### ISSUE TITLE
Add more rolling upgrade E2E tests

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1156]
We should improve E2E tests to cover the following PVC reuse scenarios:

- [x]  Add some data in the cluster and make sure it's still there once the upgrade is done (related: https://github.com/elastic/cloud-on-k8s/issues/608)

- [x] Test migrations from one node role to another: master nodes should not reuse data volumes and data nodes should not reuse master volumes.
- [x] Test mutations with an update strategy that implies both PVC reuse and data migration. Make sure one does not prevent the other to go through.
- [x] ~Test hot-warm topologies~ see #2077 for that
- [x] ~Test minor modifications in the VolumeClaimTemplate spec~ we don't allow changes to the volume claim template spec since moving to StatefulSets
- [x] Test a back-and-forth scenario: ask for a mutation, make sure it's initiated, then revert it

**Comment by pebrc** [comment]
> Test migrations from one node role to another: master nodes should not reuse data volumes and data nodes should not reuse master volumes.

I think this test scenario is somewhat redundant with the move to stateful sets as we would be testing that stateful sets work correctly at this point.

**Comment by pebrc** [comment]
> Test mutations with an update strategy that implies both PVC reuse and data migration. Make sure one does not prevent the other to go through.

https://github.com/elastic/cloud-on-k8s/blob/71de93fd9ba1c5d768dcfe01e8af4ab0156e9b8e/operators/test/e2e/es/mutation_test.go#L18-L30

does just that after #608 : it modifies the original sset to remove the `data` role which reuses the PV and it creates a new `data`-only sset to which the test data needs to be migrated.

**Comment by pebrc** [comment]
> Test hot-warm topologies

@sebgl I wonder what you had in mind here. What does testing hot-warm mean specifically? I don't think it makes sense to test that Elasticsearch allocation requirements and ILM works.  

Hot/warm/cold from an ECK perspective is just three data node sets with different volume claim templates. We can of course test that you can specify more than one data node set. But for example testing that these actually each get different volumes types assigned is quite hard I think.

**Comment by sebgl** [comment]
> @sebgl I wonder what you had in mind here. What does testing hot-warm mean specifically? I don't think it makes sense to test that Elasticsearch allocation requirements and ILM works.

You're right. I did not have anything particular in mind, I think this was mostly in the list as something to think about when we work on the issue, in case there might be something worth testing I don't know about.

> What could be interesting is testing that ILM allocation requirements don't interfere with our use of allocation requirements on node removal.

Indeed, sounds like a tricky bit.
