### ISSUE TITLE
Consider pod/nodes affinities when reusing PVCs

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1157]
What happens if:

* we decide to delete a pod in order to reuse a PVC
* the pod that will get this PVC assigned is scheduled in a zone where the PVC isn't available?

Should we consider including the pod affinity rules in the PVC resource? How do StatefulSets deal with that?

**Comment by barkbay** [comment]
IIRC it is handled by the default scheduler with the volume zone predicate: https://github.com/kubernetes/kubernetes/blob/07ee0c3e8b2697f0f06ed0bec2044ada571efb8b/pkg/scheduler/algorithm/predicates/predicates.go#L627

not 100% sure, but it should not happen

**Comment by sebgl** [comment]
The move to StatefulSets with https://github.com/elastic/cloud-on-k8s/issues/1173 means we'll entirely rely on the StatefulSet controller for this. If a user changes the zone affinity of a NodeSpec's podTemplate, to make it incompatible with PVC reuse, then the scheduling problem should be outputed in `kubectl describe pod <the-pod>`.

Closing as there is not much we can do.
