### ISSUE TITLE
Consider hot-warm-cold topologies when reusing PVCs

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1158]
Currently it's possible to reuse the volume of a hot node for a warm node, which does not make much sense and is quite inefficient.

Should we optimize for that situation? How can we know a hot is hot/warm since these are abstract concepts that can be expressed by any node attribute name in the ES config?

**Comment by pebrc** [comment]
Stateful sets would help. Reuse would happen only with the boundary of one stateful set and typically I would expect warm nodes to be in its own stateful set given that the underlying hardware would differ from the warmer nodes.

**Comment by sebgl** [comment]
Only if we don't reuse a stateful set name when something changes in the ES configuration? Which means we don't "reuse" statefulsets, so we don't reuse PVCs for config changes. Which is what we want to do here 😄 

I think the problem would be pretty similar if we had to deal with stateful sets: we need to map a given statefulset to a given conceptual group of nodes (represented by a node attribute that can be anything). Which doesn't come for free, and probably requires an "explicit" way to declare "these are my warm nodes" in the ES spec. If we have that explicit thing there, we can label pods, or name/label statefulsets, it does not make a big difference IMO.

**Comment by pebrc** [comment]
Yes we have to be more specific what kind of change we are talking about. I assume the relevant case is not full replacement of the whole population of nodes where a new set or sets of nodes completely replaces the existing sets. 

In any case you are right, and this is where the difference between stateful sets and our current approach becomes negligible: we don't have a strong concept of identity of groups of nodes at the moment, which is a prerequisite for the use of stateful sets but which also makes a lot of sense for the manual pod management we do as soon as you consider use cases as this one. 

So as you say, the only way to achieve a continuous mapping of sets of nodes across generations of change is if they have some form of identity that is stable. 

```golang
// NodeSpec defines a common topology for a set of Elasticsearch nodes
type NodeSpec struct {
	// Name is a logical name for this set of nodes. Used as a part of the managed Elasticsearch node.name setting.
	// +kubebuilder:validation:Pattern=[a-zA-Z0-9-]*
	// +kubebuilder:validation:MaxLength=12
	Name string `json:"name,omitempty"`
```
we actually already have an attribute that seems to fit this requirement.

**Comment by sebgl** [comment]
We decided in https://github.com/elastic/cloud-on-k8s/issues/1173 to move to a StatefulSet-based implementation.
PVC reuse is bound to a single `NodeSpec` in this new implementation, as suggested in the discussion above.
Closing this now.
