### ISSUE TITLE
 xpack.security.enabled is not user configurable

### ISSUE THREAD

**Issue by Pandoraemon** [elastic/cloud-on-k8s#1175]
I want create  xpack.security.enabled=false cluster, but get this error when I want to create it.

here is the yaml file
 apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: noauth
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      xpack.security.enabled: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 2Gi
              cpu: 1
  http:
    service:
      spec:
        type: NodePort

**Comment by pebrc** [comment]
This is by design: we don't support running clusters with security disabled.

**Comment by wangycc** [comment]
+1
It is better to let the users choose.

**Comment by Battleroid** [comment]
@wangycc @Pandoraemon You can disable it by setting on the node sets the following:

```
env:
- name: xpack.security.enabled
  value: "false"
- name: READINESS_PROBE_PROTOCOL
  value: http
```

This should disable it via the env var settings in the docker container's entrypoint and the latter should tell the readiness probe to use proper protocol.

**Comment by wangycc** [comment]
@Battleroid Thanks

**Comment by ajoskowski** [comment]
> @wangycc @Pandoraemon You can disable it by setting on the node sets the following:
> 
> ```
> env:
> - name: xpack.security.enabled
>   value: "false"
> - name: READINESS_PROBE_PROTOCOL
>   value: http
> ```
> 
> This should disable it via the env var settings in the docker container's entrypoint and the latter should tell the readiness probe to use proper protocol.

Is it safe for cluster upgrades?

**Comment by vanthome** [comment]
This is really crazy to not let the user decide whether they want security to be enabled or not. That means ES can no longer be considered a simple database.

**Comment by zffocussss** [comment]
> This is really crazy to not let the user decide whether they want security to be enabled or not. That means ES can no longer be considered a simple database.

I think so,because security settings are not useful in some simple cases.
