### ISSUE TITLE
Cache build/test dependencies by reusing the ci Docker image

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#1197]
For the moment, for each build we rebuild from scratch (several times, because in multiple pipelines, not always run on the same slave) the [Docker image](https://github.com/elastic/cloud-on-k8s/blob/master/build/ci/Dockerfile) to compile the Go source code, do some validations (license header, lint, fmt) and run unit and integration tests.

We could publish and reuse this Docker image to avoid to redownload and reinstall all the dependencies declared in the corresponding Dockerfile.

It might look like this:

```bash
lazy_build() {
  local tag=$(sha1sum Dockerfile | cut -c1-8)
  local image=$REGISTRY/$REPOSITORY/eck-ci:$tag

  docker pull $image || \
  (
    docker build -t $image . && \
    docker push $image
  )
}
```

**Comment by sebgl** [comment]
Should we also include a hash of the go dep file in the tag?

**Comment by artemnikitin** [comment]
In my previous company, we approached it a little bit differently. We had a separate CI job which builded and pushed new Docker image on every change in Dockerfile. We always used `latest` tag. And any Ci job automatically pulled latest Docker image.

**Comment by thbkrkr** [comment]
> Should we also include a hash of the go dep file in the tag?

Yes, that would be even better.
I think it implies a bit more modifications. Could be:

- Adding `dep ensure` in the `Dockerfile`:
```Dockerfile
WORKDIR /go/src/github.com/elastic/cloud-on-k8s/operators
COPY operators/Gopkg.lock .
COPY operators/Gopkg.toml .
RUN dep ensure --vendor-only -v
```

- Building the image from the root path to have the `Gopkg.*` files available in the Docker build context.
```sh
docker build -t eck-ci -f build/ci/Dockerfile .
```

**Comment by thbkrkr** [comment]
> In my previous company, we approached it a little bit differently. We had a separate CI job which builded and pushed new Docker image on every change in Dockerfile. We always used `latest` tag. And any CI job automatically pulled latest Docker image.

I'm also good with this approach.

Is it easy to have a job triggered only if a specific file or a set of files matching a regexp have been modified?

**Comment by artemnikitin** [comment]
> Is it easy to have a job triggered only if a specific file or a set of files matching a regexp have been modified?

Yes, will be something like https://github.com/elastic/cloud-on-k8s/pull/1216
