### ISSUE TITLE
Update the "access services" doc to retrieve the correct HTTP certs

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1206]
https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-accessing-elastic-services.html explains how to retrieve the CA used for generating ES transport protocol certs.

We now have another set of certificates (and a different CA) for the HTTP service.
The certificate we retrieve should be `<name>-es-http-certs-public`.

Let's make sure this works correctly and update the doc accordingly.

**Comment by thbkrkr** [comment]
The current documentation covers the certificates for the HTTP layer, not for the transport layer, but the names of the secrets have changed, so it's a little outdated.
Updating this documentation is an opportunity to add a section on configuring your own certificate.
