### ISSUE TITLE
Improve TLS docs to include details about secrets role

### ISSUE THREAD

**Issue by davidkarlsen** [elastic/cloud-on-k8s#1207]
Could the docs better describe what certificates are in use?

```
kubectl -n logging get secret
NAME                               TYPE                                  DATA   AGE
default-token-km8d2                kubernetes.io/service-account-token   3      25m
logging-ca                         Opaque                                1      25m
logging-ca-private-key             Opaque                                1      25m
logging-elastic-user               Opaque                                1      25m
logging-es-2lnmwk7jrh-certs        Opaque                                3      25m
logging-es-2lnmwk7jrh-config       Opaque                                1      25m
logging-es-ca                      Opaque                                1      25m
logging-es-roles-users             Opaque                                3      25m
logging-extrafiles                 Opaque                                1      25m
logging-fluent-bit-es-tls-secret   Opaque                                1      25m
logging-fluent-bit-token-2sdgm     kubernetes.io/service-account-token   3      25m
logging-internal-users             Opaque                                3      25m
logging-kibana-user                Opaque                                1      25m
logging-secure-settings            Opaque                                0      25m
root@main:~# kubectl -n logging get elasticsearch
NAME      HEALTH   NODES   VERSION   PHASE         AGE
logging   green    1       7.2.0     Operational   25m
root@main:~# 
```

A lot of the secrets seem to contain the same ca (logging-es-....-certs, logging-ca, logging-es-ca).

Also can it be made configurable to use SSL or not?

Additionally - will you add support for generating client-certificates?

**Comment by sebgl** [comment]
Hi @davidkarlsen,

> Could the docs better describe what certificates are in use?

Indeed, this is not very clear. Our plan is to include more documentation for the next release (0.9).
Currently with ECK v0.8, `logging-es-ca` is the main secret you should care about: it contains the public certificate of the CA that was used to sign Elasticsearch certificates. This is the CA your ES clients need to trust. 

On future release 0.9, you'll need to use a different secret name, see [this issue](https://github.com/elastic/cloud-on-k8s/issues/1206).

> Also can it be made configurable to use SSL or not?

We only support clusters with TLS (SSL) enabled, for security reasons. There is no plan for now to allow disabling TLS encryption.

> Additionally - will you add support for generating client-certificates?

Double-checking: you mean certificates presented to Elasticsearch from your client apps (for example: the Python Elasticsearch client)?
It is not planned yet, Elasticsearch is configured by default to trust any client-provided certificate (TLS is used for encryption only), and use the provided basic auth for authentication/authorization.
Can you detail a bit more your use case and why you'd like this to be implemented?

**Comment by davidkarlsen** [comment]
@sebgl Thanks for responding. For the client part I misunderstood a component which had this possibility (but not a requirement) - so a strong yagni-indicator. With TLS for crypto and usernames/pws we should be all clear IMHO.

**Comment by sebgl** [comment]
Thanks for the feedback @davidkarlsen. I'll close to his issue now, please reopen if needed.
