### ISSUE TITLE
Re-using existed e2e test job on CI to run tests with custom image

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#1225]
After merging https://github.com/elastic/cloud-on-k8s/pull/1135 we need to optimize CI to try to re-use existed e2e tests job https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/.

Possible ways of doing this:
- split e2e test jobs to 2 jobs: building and pushing image, running e2e tests 
- configure existed job to accept name of custom image as parameter

It might be also useful for running test on different K8s versions.

**Comment by pebrc** [comment]
This seems to be already implemented, we have: 
https://github.com/elastic/cloud-on-k8s/blob/f6e3cd69d6d9b2a60f8bb6cdbd272e1216ef400b/.ci/pipelines/e2e-tests-custom-operator-image-gke.Jenkinsfile
and 
https://github.com/elastic/cloud-on-k8s/blob/90888844f3ab84126bf07299cd234599fe893d53/.ci/pipelines/e2e-tests-stack-versions-gke.Jenkinsfile
is parameterized in a similar way to allow running against different operator images.
