### ISSUE TITLE
Break Jenkins pipeline into more granular stages

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#1230]
In the current pipeline, the "Run unit and integration tests" stage performs the following operations:

- Build and test operator
    - Download dependencies
    - Run linters
    - Generate code
    - Run unit tests
    - Run integration tests
    - Compile e2e tests
    - Build container image
- Build and test local volume
    - Download dependencies
    - Build
    - Run unit tests

![Screenshot from 2019-07-12 13-15-25](https://user-images.githubusercontent.com/52399125/61127443-33f99880-a4a7-11e9-9b03-86eef850f1a5.png)

If we add more stages to the pipeline declaration to match the above set of steps, it would make it very easy to locate a failure and jump to the relevant log section. It would also provide a nice visualisation of the current progress of the build as well.

### Pros
- Easy to visualise the build steps and locate the cause of failures

### Cons
- Jenkinsfile becomes more complicated
- Makefile and Jenkinsfile should be kept in sync to get the best results

**Comment by pebrc** [comment]
One idea we discussed and which would give us similar visualisation of the different steps would be to break up the current build into separate Jobs and call them as separate checks from GitHub. 

This would have the added benefit of making the steps immediately visible in each PR and remove the need to go to the Jenkins UI to see the result of a build. 

It comes with the downside of Jenkins jobs being comparatively heavy-weight. 
It also would only improve the situation for PR builds while the analysis of every other build would still mean that we have to inspect the raw build output in Jenkins.
