### ISSUE TITLE
admission webhook "validation.elasticsearch.elastic.co" does not support dry run

### ISSUE THREAD

**Issue by donbowman** [elastic/cloud-on-k8s#1233]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

running kubectl diff we get:
`Error from server (BadRequest): admission webhook "validation.elasticsearch.elastic.co" does not support dry run`

It would be nice if this could support dry-run, its part of our workflow.

**What did you expect to see?**

expected to see a diff

**What did you see instead? Under which circumstances?**

error message
`Error from server (BadRequest): admission webhook "validation.elasticsearch.elastic.co" does not support dry run`

**Environment**

* Version information:

	insert version or git commit id here

0.8.1 of operator,

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by jonsabo** [comment]
Thanks for bringing this up. I can definitely see how this would be useful, and in theory shouldn't be too much work to enable.

From the docs here:
https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff

looks like we would need to do this
>    Remove any side-effects when the dry-run parameter is specified on the webhook request,
>    Specify in the sideEffects field of the admissionregistration.k8s.io/v1beta1.Webhook object to indicate that the object doesn’t have side-effects on dry-run (or at all).


The sideEffects field doesn't look configurable in kubebuilder (or rather controller-runtime) and I'm not seeing an issue for it. You can see the type here:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#validatingwebhook-v1beta1-admissionregistration-k8s-io

I started looking to see if this was resolved in master but it looks like the webhooks part is in a bit of flux and there have been quite a few changes in how they handle it, so I wasn't able to find out just yet.

**Comment by pebrc** [comment]
We have #1188 to upgrade to a newer version of kubebuilder/controller-runtime which changes the webhook integration quite a bit. Maybe worth tackling this in connection with/after that upgrade.

**Comment by donbowman** [comment]
the license webhook does this too. That one I have no way of disabling, so its broken diff for all objects in my cluster (not just the ones for elastic cloud).

**Comment by donbowman** [comment]
is it possible for me to delete this webhook?
or can anyone think of another workaround?
diff is part of my workflow, and this cluster no longer functions with it.

**Comment by pebrc** [comment]
@donbowman yes, it is possible to delete this webhook. 

You can also make sure that the operator does not recreate it by starting the operator without the webhook role: 
```yaml
            spec:
              containers:
              - args:
                - manager
                - --operator-roles
                - global,namespace
```

**Comment by donbowman** [comment]
This doesn't seem to disable the `validation.license.elastic.co` webhook? This also blocks diffs cluster wide.

**Comment by anyasabo** [comment]
@mleklund I think we can likely take this on now so I opened a PR

**Comment by mleklund** [comment]
@anyasabo any issues with making these yaml changes now if I meet the minimum k8s version?

**Comment by anyasabo** [comment]
@mleklund no that should be fine

**Comment by tonybenchsci** [comment]
Our company gets this error as well when trying to do --server-dry-run. Any updates on the sideEffects fix?

**Comment by mleklund** [comment]
you could update your all-in-one with the changes here:
https://github.com/elastic/cloud-on-k8s/pull/3181/files


Looks like they are waiting for dropping of openshift 3.11 support.

**Comment by pebrc** [comment]
I wonder if we could add an option to the manifest generator/ Helm chart to conditionally add the `sideEffects` attribute for newer versions of Kubernetes. @charith-elastic thoughts?

**Comment by charith-elastic** [comment]
Yes, we should be able to do it now. I'll look into it.
