### ISSUE TITLE
TestUpdateConfiguration is flaky

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#1258]
Sometimes `TestUpdateConfiguration` fails.

```go
[2019-07-16T12:43:52.902Z]     
--- FAIL: TestUpdateConfiguration/ES_cluster_health_should_eventually_be_green (300.00s)
```
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/111/

```go
[2019-07-15T09:24:16.084Z]     
--- FAIL: TestUpdateConfiguration/ES_cluster_health_should_eventually_be_green (300.00s)
```
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/102/

**Comment by artemnikitin** [comment]
Also https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/113/
