### ISSUE TITLE
Dialer is broken in e2e tests

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1273]
`dialer` is broken in e2e tests.
I think it comes from https://github.com/elastic/cloud-on-k8s/commit/e1a30233f0d2fa80491b704beac81d4e59c2bc2d#diff-fcadcd8abc54d908e7568bc91579f44fL31

The namespace is needed in the url in order to get the pod with the `RESTClient` and without the `svc` it's trying to forward to a pod and not to a service.

**Comment by thbkrkr** [comment]
This happens when using `--auto-port-forward`.

The custom dev port forwarder expects that a pod address is composed of three parts `<name>.<namespace>.svc`:
https://github.com/elastic/cloud-on-k8s/blob/03fad111384cc03799cca5486fc98a4906694cee/operators/pkg/dev/portforward/pod_forwarder.go#L118-L124

**Comment by sebgl** [comment]
I guess we can either:

1. Revert the e2e change to keep using `name.namespace.svc`
2. Modify the port forward code to be able to forward `name` only

I'd vote for 2.

**Comment by thbkrkr** [comment]
> 2. Modify the port forward code to be able to forward `name` only

Do not we also need the namespace?

**Comment by sebgl** [comment]
Our [quickstart doc](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html#k8s-request_elasticsearch_access) advertises reaching the service from its name only (no namespace, no `.svc` extension):

> Get access to Elasticsearch.
From the Kubernetes cluster, use this URL:
https://quickstart-es:9200

However this longer-term E2E tests will probably work across multiple namespaces I guess it's fine to include the namespace here.
