### ISSUE TITLE
Refactor scheme setup for tests

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#1274]
The fake clients all need to add our custom types to the schemes to be able to process them. If you forget to do this, it will be a huge pain to debug (ask me how I know). We have similar scheme setup code in various places across our codebase (really any reference you see to `scheme.Scheme` is probably related) and we can likely refactor it out.

For example:
```golang
	if err := estype.AddToScheme(scheme.Scheme); err != nil {
		return nil, err
	}
	if err := kbtype.AddToScheme(scheme.Scheme); err != nil {
		return nil, err
	}
	if err := assoctype.AddToScheme(scheme.Scheme); err != nil {
		return nil, err
	}
	if err := apmtype.AddToScheme(scheme.Scheme); err != nil {
		return nil, err
	}
	client, err := k8sclient.New(cfg, k8sclient.Options{Scheme: scheme.Scheme})
	if err != nil {
		return nil, err
	}
```

**Comment by racevedoo** [comment]
Closed by #1955
