### ISSUE TITLE
NGINX Ingress configuration with multiple Kibana replicas

### ISSUE THREAD

**Issue by dazoakley** [elastic/cloud-on-k8s#1282]
## Bug Report

When you try to run more than one replica of Kibana you cannot log in to the Kibana UI.  We would like to run at least 2 replicas for HA.

Please see this repo for a reproducible test case:

https://github.com/dazoakley/eck-kibana-bug

* Version information:

	0.8.1

* Kubernetes information:

	* GKE - 1.12.8-gke.10
	* minikube 1.2.0 (k8s 1.15.0)

**Comment by sebgl** [comment]
Hi @dazoakley,
Thanks for reporting, I managed to reproduce the issue with instructions you provided.
When port-forwarding and requesting the `quickstart-kibana` directly, things seem to work as expected.
I think the issue here might be related to the ingress. I'm looking into it.

**Comment by sebgl** [comment]
I think this may be related to the automatic http->https redirection done by the ingress.
I tried removing the `host` from your ingress config to use the IP directly: I can't manage to not get an HTTPS redirect, even with `nginx.ingress.kubernetes.io/ssl-redirect: "false"` in the ingress annotation.

**Comment by dazoakley** [comment]
Hi @sebgl, thanks for getting back to me, sorry for the slow response.  Okey doke, I'll take a look at this some more today. :)

**Comment by dazoakley** [comment]
Hi @sebgl - finally got a fix for nginx ingress and Kibana!  Looks like we need to set an affinity setting for nginx to work correctly...  Adding the following annotation to the ingress fixed it:

```
nginx.ingress.kubernetes.io/affinity: "cookie"
```

Not sure about the issues you were having with the SSL redirect though - not been able to reproduce that problem here. :-/

**Comment by thbkrkr** [comment]
Thank you for reporting this and for finding a solution.
