### ISSUE TITLE
Increase default GKE size

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#1285]
## Proposal

We may want to increase the size of the GKE cluster created by `make bootstrap-gke` and enable autoscaling on the node group. Currently some e2e tests can cause resource contention issues depending on how pods are scheduled (and not scheduled). We may want to check the size of the cluster used for CI as well. It may also be possible to alter the resources for instances spun up as part of e2e testing to use less resources -- I think some ES instances request 2 CPUs for instance.

**Comment by artemnikitin** [comment]
In CI we are using `n1-standard-8` with 8 CPU and 30 GB RAM. 
https://github.com/elastic/cloud-on-k8s/blob/master/operators/Makefile#L340

**Comment by anyasabo** [comment]
No longer relevant
