### ISSUE TITLE
Account for maxSurge during StatefulSet replacements

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1292]
When one or many StatefulSet needs to be removed, and one or many StatefulSets need to be added, we add the new StatefulSets and migrate data away from the deprecated ones.

As a result, the cluster ends up with many more nodes than requested by the user. This is ignoring the `changeBudget.MaxSurge` setting.

Instead, we should slowly add nodes from new StatefulSets according to nodes from the old StatefulSets we remove.
This can be tricky since we need to make sure we add the necessary nodes so data can be migrated away from StatefulSets to remove. We should probably optimize for adding at least 1 node of each new StatefulSet to created (not create all nodes for a given StatefulSets while other StatefulSets would not be created yet).

**Comment by sebgl** [comment]
I'm wondering wether `maxUnavailable` would also make sense here? (remove replicas from the "old" statefulset before adding new ones on the "new" statefulset)

**Comment by pebrc** [comment]
We discussed this offline and few scenarios came to mind that we need to consider here:

Any kind of master/data splits are problematic e.g.

Mixed node types to dedicated master (maxSurge 1)
```
mdi -> m  di 
2      0   0   
1      0   1      (potentially stuck as depending on replica settings cluster now yellow)  
0      1   1
```
```
mdi -> m  di 
2      0   0   
1      1   0      (stuck as data has now nowhere to go)  
```

With a larger cluster and relaxed health checks between upgrade iterations we might be able to make progress in the first scenario. That means as @sebgl suggested use `maxUnvailable` in combination with #1155

**Comment by david-kow** [comment]
Some thoughts on this:
1. I think it makes sense to include maxUnavailable nodes here. We anyway have to assume something if maxSurge=0 to make progress.
2. There are cases where we can't even start:
```
ms=1, mu=1 
m  d1  d2
1  2   0
? (already at 3 nodes, can't remove, can't add)
1  0   1
```
3. There are cases where we will start, but fail at some point:
```
ms=1, mu=1 
m  d1  d2  ml
1  2   0   0
1  2   0   1
? (we started with ml node, so no capacity to move data and we can't remove last master)
1  0   1   1
```

4. It seems that the possible scenario space is rather large. To provide correct path (delete/add order) between current and desired state we would need to take into account:
- node types,
- node resources,
- allocation settings.

5. Even if we have a solution that satisfies all constraints at all times it might not be what user expects, eg. we remove too many masters at a time or decrease other capacity of the cluster too much (ingest, ml or hot/warm/cold data nodes subset). Currently, there is no way for users to specify if they care more about a particular nodeSpec than the other. 
6. I think the most complex scenarios won't be executed in practice and if they will, users always have option to apply desired spec in stages and/or increase maxUnavailable/maxSurge. Given the above, I don't think it's time efficient to solve this for general case and a suboptimal heuristic should be sufficient.

Having said that I'd propose the following steps:
1. Add constraints while adding/removing nodes.
2. Add detection/reporting of stuck update.
3. Add a heuristic for determining improved order of additions/removals.

Unless there are different opinions on this, I'll go ahead and start working on the above.

**Comment by david-kow** [comment]
> 1. Add constraints while adding/removing nodes.
> 2. Add detection/reporting of stuck update.
> 3. Add a heuristic for determining improved order of additions/removals.

I'd consider this issue to cover 1. and 2. 
3. should be tracked separately when we decide to do it.
