### ISSUE TITLE
Test both the vm.max_map_count and enforced PSP in E2E tests

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1303]
Currently, we enforce a default PSP forbidding privileged containers in our E2E tests.

Benefits:
* "simulate" OpenShift default restricted access in our E2E tests
* make sure ECK does not perform things that would require extra privilege

Concerns:
* we must explictly disable `SeVmMaxMapCount` on all E2E tests, because that would run a privileged init container which would not work
* we don't test the privileged init container in E2E tests (which is there by default)
* VMs spawned for E2E tests must be tweaked with the correct `vm.max_map_count`
* it's not possible to easily setup auto-scaling on the k8s clusters

We should find a way to run some tests with PSP enabled, and some E2E tests with PSP disabled.

Related: https://github.com/elastic/cloud-on-k8s/pull/1302.

**Comment by artemnikitin** [comment]
We can easy do this on CI side, no need to change in tests.
Either run all tests in 2 modes or we can run part of tests in one mode and another part in another mode

**Comment by sebgl** [comment]
@artemnikitin I think changes impact:

- the PSP flag in our Makefile to bootstrap the GKE cluster with or without a PSP
- a way for E2E tests to acknowledge they can either use the default SetVMMaxMapCount, or should disable it (and use a restricted security context)

**Comment by thbkrkr** [comment]
Closing because it is no longer relevant since we removed `setVMMaxMapCount` in #1712.
