### ISSUE TITLE
Flaky ES secure settings E2E test

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1325]
Got this while running the test locally:

```
--- FAIL: TestUpdateESSecureSettings (373.01s)
    --- PASS: TestUpdateESSecureSettings/Create_secure_settings_secret (0.06s)
    --- PASS: TestUpdateESSecureSettings/K8S_should_be_accessible (0.12s)
    --- PASS: TestUpdateESSecureSettings/Elasticsearch_CRDs_should_exist (0.03s)
    --- PASS: TestUpdateESSecureSettings/Remove_Elasticsearch_if_it_already_exists (0.10s)
    --- PASS: TestUpdateESSecureSettings/Creating_an_Elasticsearch_cluster_should_succeed (0.04s)
    --- PASS: TestUpdateESSecureSettings/Elasticsearch_cluster_should_be_created (0.03s)
    --- PASS: TestUpdateESSecureSettings/ES_certificate_authority_should_be_set_and_deployed (3.11s)
    --- PASS: TestUpdateESSecureSettings/ES_version_should_be_the_expected_one (6.12s)
    --- PASS: TestUpdateESSecureSettings/ES_pods_should_eventually_be_running (33.60s)
    --- PASS: TestUpdateESSecureSettings/ES_services_should_be_created (0.04s)
    --- PASS: TestUpdateESSecureSettings/ES_pods_should_eventually_be_ready (21.38s)
    --- PASS: TestUpdateESSecureSettings/ES_pods_should_eventually_have_a_certificate (0.16s)
    --- PASS: TestUpdateESSecureSettings/ES_services_should_have_endpoints (0.04s)
    --- PASS: TestUpdateESSecureSettings/ES_cluster_health_should_eventually_be_green (3.07s)
    --- PASS: TestUpdateESSecureSettings/ES_cluster_UUID_should_eventually_appear_in_the_ES_status (0.03s)
    --- PASS: TestUpdateESSecureSettings/Elastic_password_should_be_available (0.03s)
    --- PASS: TestUpdateESSecureSettings/Elasticsearch_data_volumes_should_be_of_the_specified_type (0.04s)
    --- PASS: TestUpdateESSecureSettings/Every_secret_should_be_set_so_that_we_can_build_an_ES_client (0.07s)
    --- PASS: TestUpdateESSecureSettings/ES_cluster_health_endpoint_should_eventually_be_reachable (1.68s)
    --- PASS: TestUpdateESSecureSettings/ES_version_should_be_the_expected_one#01 (0.03s)
    --- PASS: TestUpdateESSecureSettings/ES_endpoint_should_eventually_be_reachable (0.03s)
    --- PASS: TestUpdateESSecureSettings/ES_nodes_topology_should_eventually_be_the_expected_one (0.09s)
    --- PASS: TestUpdateESSecureSettings/Elasticsearch_secure_settings_should_eventually_be_set_in_all_nodes_keystore (1.95s)
    --- PASS: TestUpdateESSecureSettings/Modify_secure_settings_secret (0.03s)
    --- FAIL: TestUpdateESSecureSettings/Elasticsearch_secure_settings_should_eventually_be_set_in_all_nodes_keystore#01 (300.00s)
        require.go:794:
                Error Trace:    utils.go:80
                Error:          Received unexpected error:
                                invalid keystore entries. Expected: [path.logs]. Actual: [path.logs xpack.security.audit.enabled]
                Test:           TestUpdateESSecureSettings/Elasticsearch_secure_settings_should_eventually_be_set_in_all_nodes_keystore#01
```

**Comment by sebgl** [comment]
I think this happens when the rolling upgrade of all pods does not make progress because a pod stays pending.
Example output after a failing test (`kubectl get pods`):

```
13:02:57  pod/test-es-keystore-es-4hc4c8brx4         1/1     Running   0          10m
13:02:57  pod/test-es-keystore-es-j9pznvjbbg         0/1     Pending   0          9m8s
13:02:57  pod/test-es-keystore-es-rjf7rc4hxv         1/1     Running   0          11m
13:02:57  pod/test-es-keystore-es-sh4xz2hx48         1/1     Running   0          11m
```

The second pod stays pending, so the rolling upgrade of all keystores isn't finished.
This is a bit misleading in the test output: the actual failure is that the rolling upgrade could not succeed, not that something is wrong in our keystore handling.

**Comment by thbkrkr** [comment]
The pod is Pending because there is not enough CPU. Why?

> Warning   FailedScheduling    Pod                   0/3 nodes are available:
>       1 Insufficient cpu, 2 node(s) had volume node affinity conflict.

The default storage class with GKE does not have `WaitForFirstConsumer` set by default. This means PVs get bound before a pod is scheduled in its zone, which could lead to all nodes of a cluster being scheduled on the same host. This happens when all the PVs have been randomly created with the same node affinity (same zone => same host). 

As a quick fix, we will use a custom default storage class with `WaitForFirstConsumer` for all the E2E tests.

**Comment by artemnikitin** [comment]
@thbkrkr should we close this now?

**Comment by thbkrkr** [comment]
Soon! I think it's safer to wait a bit to have some green E2E tests.

**Comment by barkbay** [comment]
I think we can close this one.

**Comment by sebgl** [comment]
Looks like it happened again: 
```
12:57:58      --- FAIL: TestUpdateESSecureSettings/Elasticsearch_secure_settings_should_eventually_be_set_in_all_nodes_keystore#03 (300.00s)
12:57:58          require.go:794: 
12:57:58                  Error Trace:    utils.go:80
12:57:58                  Error:          Received unexpected error:
12:57:58                                  invalid keystore entries. Expected: []. Actual: [xpack.notification.email.account.foo.smtp.secure_password]
12:57:58                  Test:           TestUpdateESSecureSettings/Elasticsearch_secure_settings_should_eventually_be_set_in_all_nodes_keystore#03
12:57:58  FAIL
```

https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/363/console

**Comment by sebgl** [comment]
It is definitely flappy since worked correctly in other attempts.

I think here is what happens:

* When we change something in the secure settings secret, we then exec into all ES containers to inspect that the content of their keystore correctly reflects what we set in the secure settings secret (and we retry).
* Since we do 3 secure settings modification in this test, we do this 3 times.
* Whenever secure settings content change, we trigger a rolling upgrade (node by node)
* A node usually takes about 1 minute to be restarted (from deletion to being ready): a full 3-nodes cluster restart takes 3+minutes.
* When checking keystore content, we don't care about the node readiness or cluster health. Which means the keystore test passes right after the 3rd node has been restarted (but way before it's actually fully ready and the cluster is green again)
* Because of that last point, a single test attempt can take about 1min (time for the last node of the previous rolling upgrade to be fully started so the cluster becomes green) + 3min (time for the 3 nodes to be restarted, again), giving a 4 minutes total.
* The test timeout is 5 minutes, probably pretty close to that 4 minutes required. I think we reach that timeout in random situations.

Things we could do:

1. Make sure the cluster is back to green with all nodes running after the keystore test
2. Reduce the number of nodes so we don't wait 3*1min/5min but maybe 2*1min/5min
3. Increase the 5min timeout to give more room to most rolling upgrades

I'll start with 1) which is very specific to this test. Then we'll see whether 2 and 3 make sense; they also impact every other rolling-upgrade-based test.

**Comment by sebgl** [comment]
Let's reopen if it happens again.

**Comment by sebgl** [comment]
Looks like it's still flaky: https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/393/console

**Comment by sebgl** [comment]
From the logs:

```
{"reason":"FailedAttachVolume","message":"AttachVolume.Attach failed for volume \"pvc-24955664-e4ee-11e9-ab4c-42010a840069\" : GCE persistent disk not found: diskName=\"gke-jenkins-cloud-on-k-pvc-24955664-e4ee-11e9-ab4c-42010a840069\" zone=\"europe-west1-c\"","kind":"Pod","name":"test-es-keystore-xztk-es-masterdata-1","namespace":"e2e-o9dzw-mercury"}
10:36:14  {"reason":"FailedMount","message":"Unable to mount volumes for pod \"test-es-keystore-xztk-es-masterdata-1_e2e-o9dzw-mercury(2e82fff7-e4ef-11e9-ab4c-42010a840069)\": timeout expired waiting for volumes to attach or mount for pod \"e2e-o9dzw-mercury\"/\"test-es-keystore-xztk-es-masterdata-1\". list of unmounted volumes=[elasticsearch-data]. list of unattached volumes=[elasticsearch-data elastic-internal-elasticsearch-bin-local elastic-internal-elasticsearch-config elastic-internal-elasticsearch-config-local elastic-internal-elasticsearch-plugins-local elastic-internal-http-certificates elastic-internal-probe-user elastic-internal-scripts elastic-internal-transport-certificates elastic-internal-unicast-hosts elastic-internal-xpack-file-realm elasticsearch-logs]","kind":"Pod","name":"test-es-keystore-xztk-es-masterdata-1","namespace":"e2e-o9dzw-mercury"}
```

I think what happened is the second node failed to start, due to GCP persistent volumes errors. So we never rolled the last Pod since we're stuck with this one.
The reported E2E error is misleading, since it says at least one Pod does not have the correct keystore values. That's expected since the rolling upgrade is stuck!

I'll change things around to make the error returned by E2E tests more explicit (it's not a keystore error, it's a rolling upgrade/gke error).
