### ISSUE TITLE
Documentation of ECK 0.9.0 referencing 0.8.0 all-in-one.sh

### ISSUE THREAD

**Issue by Ofinka** [elastic/cloud-on-k8s#1331]
## Bug Report
**What did you do?**
I followed instructions from https://www.elastic.co/guide/en/cloud-on-k8s/0.9/k8s-quickstart.html which describes how to setup ES cluster along with Kibana and how to insert my own certificate so my applications are able to communicate with created ES cluster.

**What did you expect to see?**
I expected the configuration from documentation to be applied so ES cluster would work with provided certificate.

**What did you see instead? Under which circumstances?**
After some time of digging why is my configuration not taken into account I realized that all the time I was working with ECK 0.8.0 even though the documentation is focusing on version 0.9.0. 

Documentation guides you to download ECK 0.8.0 and configure it like ECK 0.9.0 which of course does not bring expected results.

Spend some time seeking _all-in-one.yaml_ of version 0.9.0 but have not managed to find any so I'm not sure if documentation was posted before suitable version of ECK will be released or it's just a typo in very first step (kubectl apply -f https://download.elastic.co/downloads/eck/**0.8.0**/all-in-one.yaml).

**Comment by thbkrkr** [comment]
Hi,

ECK `0.9` is not yet available and will be released next week.
The documentation is going to be updated in #1326.

Thank you for reporting this.
