### ISSUE TITLE
Can't access kibana on 0.9.0-rc3

### ISSUE THREAD

**Issue by dazoakley** [elastic/cloud-on-k8s#1333]
## Bug Report

Using the newly released 0.9.0-rc3 you can't access kibana - it's getting SSL errors in the logs.

Please see this repo for a reproducible test case:

https://github.com/dazoakley/eck-kibana-bug/tree/0.9.0-rc3-kibana-access

* Version information:

	0.9.0-rc3

* Kubernetes information:

	* GKE - 1.12.8-gke.10
	* minikube 1.2.0 (k8s 1.15.0)

* Logs (from kibana pod):
```
{"type":"error","@timestamp":"2019-07-22T14:42:32Z","tags":["connection","client","error"],"pid":1,"level":"error","error":{"message":"139711542253440:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n","name":"Error","stack":"Error: 139711542253440:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"},"message":"139711542253440:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"}
```

**Comment by sebgl** [comment]
Hey @dazoakley,

Starting 0.9 we enforce TLS by default in Kibana. See the [updated quickstart doc](https://github.com/elastic/cloud-on-k8s/blob/master/docs/k8s-quickstart.asciidoc#deploy-the-kibana-instance) (not live on elastic.co yet).

You can explicitly disable TLS in Kibana spec if you want to:

```yaml
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

**Comment by dazoakley** [comment]
Ah perfect :+1: - we handle TLS on the ingress side here so no probs.

Thanks @sebgl
