### ISSUE TITLE
EKS with custom CNI: operator needs hostNetwork enabled

### ISSUE THREAD

**Issue by gree-gorey** [elastic/cloud-on-k8s#1369]
## Bug Report
**What did you do?**

Followed quickstart guide provided to install ECK on EKS.

**What did you expect to see?**

Deployment succeeded.

**What did you see instead? Under which circumstances?**

Deployment of `Elasticsearch` resource failed with error:
```
failed calling admission webhook "validation.elasticsearch.elastic.co": post https://elastic-webhook-service.elastic-system.svc:443/validate-elasticsearches?timeout=30s: address is not allowed
```

**Environment**

* Version information: `0.9.0-rc3`

* Kubernetes information: EKS with custom CNI (Calico)
	
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"
```

* Logs:
```
failed calling admission webhook "validation.elasticsearch.elastic.co": post https://elastic-webhook-service.elastic-system.svc:443/validate-elasticsearches?timeout=30s: address is not allowed
```

## Solution

The issue with EKS using custom CNI is that control-plane managed by AWS cannot communicate with pods' IP CIDR. The solution to that would be for users with such a setup to use `hostNetwork: true` in operator StatefulSet spec. This way it will receive node IP address and would be reachable from Kubernetes API.  
But then we need also `dnsPolicy: ClusterFirstWithHostNet` because otherwise internal DNS names of services inside Kubernetes won't be resolved.  
  
Maybe just add it to documentation, or make this fields customizable.  
  
I solved this problem by applying the following patch:
```yaml
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```
```console
$ kubectl patch statefulset -n elastic-system elastic-operator \
    --patch "$(cat patch.yaml)"
```

**Comment by thbkrkr** [comment]
Thank you for reporting this and for providing a solution.
We are going to see if we integrate it into the documentation.
