### ISSUE TITLE
Cannot delete resources created with ECK 0.8 if 0.9 is running

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1384]
How to reproduce:

* deploy ECK 0.8
* deploy ES and Kibana
* deploy ECK 0.9
* ES and Kibana are kept unmodified, as expected
* delete Elasticsearch and Kibana: this never succeeds

Remaining finalizers on the ES resource:

```
finalizers:
  - expectations.finalizers.elasticsearch.k8s.elastic.co
  - observer.finalizers.elasticsearch.k8s.elastic.co
  - secure-settings.finalizers.elasticsearch.k8s.elastic.co
  - licenses.finalizers.elasticsearch.k8s.elastic.co
```

I think we have these finalizer names in both 0.8 and 0.9 (to be checked). Should we execute finalizers before we check the controller version compatibility?

**Comment by pebrc** [comment]
Is that not expected? Most finalizers have anything to do in the 0.9 operator (because the listener registrations they are cleaning up are not there to begin with)

**Comment by sebgl** [comment]
You're right, maybe it's good enough to document how finalizers should be removed in the 0.8 -> 0.9 documentation.

**Comment by sebgl** [comment]
Documented as part of https://github.com/elastic/cloud-on-k8s/pull/1378.

**Comment by anyasabo** [comment]
One thing we may be able to do is also remove the finalizers when we mark the resource as created by an older operator. But that's both more invasive and I'm not sure worth the effort at this point.

**Comment by sebgl** [comment]
Let's close this since expected and documented in #1378.
