### ISSUE TITLE
Re-structure documentation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1388]
Capturing a discussion with @alaudazzi  here. I am suggesting to restructure our docs a little bit to be more consistent in terms of hierarchy and to respect the fact that we have APM server now as well as a new resource:

* Overview
* Quickstart
* Running ECK
   * Deploying ECK on OpenShift
* Accessing Elastic Stack services
* Managing Compute Resources
* Running Elasticsearch on ECK
   * Advanced node scheduling
   * Node configuration
   * Volume Claim Templates
   * HTTP settings & TLS SANs
   * Custom HTTP certificate
   * Secure Settings
   * Customer Configuration Files and Plugins
   * Virtual memory
   * Update strategy 
* Running APM Server on ECK
* Troubleshooting
* Release Highlights
* Release Notes

**Comment by alaudazzi** [comment]
@sebgl The section [How to create automated sbapshots](https://www.elastic.co/guide/en/cloud-on-k8s/0.9/k8s-how-to-snapshot.html) is not included in this structure. Where should it go?

**Comment by pebrc** [comment]
It should go below Running Elasticsearch on ECK

**Comment by alaudazzi** [comment]
Fixed in #1417 and #1423.
