### ISSUE TITLE
Installation over OperatorHub.io does not work

### ISSUE THREAD

**Issue by a-hat** [elastic/cloud-on-k8s#1396]
## Bug Report
**What did you do?**
Install the Operator Lifecyle Manager in a fresh k8s cluster with this [script](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/scripts/install.sh)

Install the Operator from OperatorHub.io with

    kubectl create -f https://operatorhub.io/install/elastic-cloud-eck.yaml

**What did you expect to see?**

The operator should be created in the cluster by OLM.

**What did you see instead? Under which circumstances?**

The installation first fails because the namespace `operators` does not exist. After creating the namespace manually and applying the yaml from OperatorHub.io again, nothing happens.

**Environment**

* Version information:

It is the version from https://operatorhub.io/install/elastic-cloud-eck.yaml

* Kubernetes information:

AWS EKS 1.13

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Logs:

I cannot find anything interesting in the OLM logs.

**Comment by pebrc** [comment]
Thanks for your bug report. I just went through the installation instructions myself and OLM and the operator installed fine on EKS. 

I suspect your problem stems from the way you chose to install OLM. If you check on https://operatorhub.io/operator/elastic-cloud-eck you will find different installation instructions:

![Screenshot 2019-07-26 at 09 30 09](https://user-images.githubusercontent.com/697790/61934404-826b6480-af88-11e9-8ddb-bfffc39f8015.png)

Following those instructions you should get a working installation. 

I am closing this for now.

**Comment by a-hat** [comment]
Thanks @pebrc. I tried again with a fresh cluster and the install script from 0.10.0, and now everything seems to work as intended.
