### ISSUE TITLE
APM Pod fails to start when using a keystore

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1399]
When using a keystore the APM Pod fails to start:

```
+ echo 'Initializing keystore.'
+ /usr/share/apm-server/apm-server keystore create --force
Initializing keystore.
Created apm-server keystore
+ for filename in '/mnt/elastic-internal/secure-settings/*'
+ [[ -e /mnt/elastic-internal/secure-settings/logging.verbose ]]
++ basename /mnt/elastic-internal/secure-settings/logging.verbose
+ key=logging.verbose
+ echo 'Adding logging.verbose to the keystore.'
Adding logging.verbose to the keystore.
+ /usr/share/apm-server/apm-server keystore add logging.verbose /mnt/elastic-internal/secure-settings/logging.verbose
could not create secret for: [logging.verbose /mnt/elastic-internal/secure-settings/logging.verbose], you can only provide one key per invocation
```

Seems related to https://github.com/elastic/cloud-on-k8s/pull/1377/files#diff-a45727bb5c0ed9ac8b2a53155dfb83b8L100

**Comment by barkbay** [comment]
According to https://www.elastic.co/guide/en/apm/server/current/keystore.html the APM keystore only accepts new values in interactive mode or from stdin.

**Comment by thbkrkr** [comment]
I confirm. I naively thought that keystores worked the same way for Elasticsearch, Kibana and APM Server.

Only the Elastisearch keystore supports settings additions using a file path.
https://github.com/elastic/cloud-on-k8s/blob/8099f3dd2952737d36abe727b96ac62b2dfd1760/operators/pkg/controller/common/keystore/initcontainer.go#L47

Kibana and APM Server supports only this syntax:
```
/keystore/bin/keystore add "$key" --stdin < "$filename"
```

**Comment by pebrc** [comment]
Would it make sense to leave the  new way for ES and fix APM + Kibana to use the `stdin`?
