### ISSUE TITLE
Setup corrected ES naming length conventions

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1474]
We don't have to name pods anymore, and our naming length conventions were based on computing cluster name +pod suffix + longest secret per pod suffix.

We now manipulate secrets like:
* cluster name - es - nodespec name - config
* cluster name - es  - transport-certs-public

We should come up with proper length restrictions for both the cluster name and the nodespec name.

**Comment by charith-elastic** [comment]
There was some discussion about this in #1647 and the results of the following investigation is as follows. Note that the code base is huge and it is not possible to find all the places where names are concatenated with other suffixes and prefixes so this list is probably not exhaustive.

#### Elasticsearch 

| suffix | length |
| --- | --- |
|`-transport-certificates`|23|
|`-transport-ca-internal`|22|
|`-transport-ca-public`|20|
|`-xpack-file-realm`|17|
|`-http-ca-internal`|17|
|`-internal-users`|15|
|`-http-ca-public`|15|
|`-unicast-hosts`|14|
|`-elastic-user`|13|
|`-scripts`|8|
|`-license`|8|
|`-default`|8|
|`-http`|5|
| **`-<nodeSpec name>`**|?|
| **`-<nodeSpec name>`**`-config`|?+7|

Only the Elasticsearch name and SSet name (`ES+nodeSpec`) seems to be used as labels. Therefore, we can probably keep the existing ES name length restriction of **36** but extend the nodeSpec name length restriction to **27**.

#### APM Server

| suffix | length |
| --- | --- |
|`-apm-es-ca`|10|
|`-apm-user`|9|

We currently do not validate APM objects at all but we probably should.

#### Kibana 

| suffix | length |
| --- | --- |
|`-kibana-user`|12|
|`-kb-es-ca`|9|

We currently do not validate Kibana objects at all but we probably should.

### Actions
- Increase nodeSpec name length to 27
- Validate APM and Kibana objects
- Add E2E test to exercise the path where names are at their maximum length
