### ISSUE TITLE
ECK uninstall needs edit of CRD's to fully uninstall

### ISSUE THREAD

**Issue by dan-evolvere** [elastic/cloud-on-k8s#1542]
## Bug Report
Tried to uninstall ECK

**What did you expect to see?**
ECK uninstalls and able to remove namespace from k8s cluster
**What did you see instead? Under which circumstances?**
Namespace stuck in deleting indefinitely
**Environment**
Test
* Version information:

0.9.0

* Kubernetes information:

	Rancher on prem 2.2.4, k8s 1.14.1
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

* Resource definition:
"https://download.elastic.co/downloads/eck/0.9.0/all-in-one.yaml"

* Relevant info:

Two things to resolve this;
1. typo in the docs for uninstall has a misspelled --all-namespaces flag in the first command to copy
2. Had to edit the CRD for elasticsearches and kibanas to remove the finalizer;
kubectl edit customresourcedefinition elasticsearches.elasticsearch.k8s.elastic.co
delete/remove the finalizer
repeat for kibanas.kibana.k8s.elastic.co

Only then would the namespace delete.

**Comment by david-kow** [comment]
Hi @dan-evolvere, thanks for your bug report.

Typo is fixed, but regarding the other part - could you share what finalizers were there? I don't believe we put one on the CRD. Is it possible that it came from somewhere else? Maybe to prevent accidental deletion?

```
$ k apply -f https://download.elastic.co/downloads/eck/0.9.0/all-in-one.yaml
...
$ k describe crd elasticsearches.elasticsearch.k8s.elastic.co | grep Finalizers
$
```

**Comment by a1exus** [comment]
sorry for off topic question, where are uninstall instructions?

**Comment by david-kow** [comment]
Closing this - feel free to reopen if there is a need.
