### ISSUE TITLE
E2E TestUpdateESSecureSettings is failing with 7.2/7.3

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1558]
```
21:00:12      --- FAIL: TestUpdateESSecureSettings/ES_pods_should_eventually_be_ready (300.00s)
21:00:12          require.go:794: 
21:00:12                  Error Trace:    utils.go:80
21:00:12                  Error:          Received unexpected error:
21:00:12                                  pod test-es-keystore-6h8c-es-masterdata-0 is not ready yet
21:00:12                  Test:           TestUpdateESSecureSettings/ES_pods_should_eventually_be_ready
```

Log:
```
Exception in thread "main" java.lang.IllegalArgumentException: Setting [path.logs] is a non-secure setting and must be stored inside elasticsearch.yml, but was found inside the Elasticsearch keystore
    at org.elasticsearch.common.settings.Setting.innerGetRaw(Setting.java:492)
    at org.elasticsearch.common.settings.Setting.getRaw(Setting.java:479)
    at org.elasticsearch.common.settings.Setting.get(Setting.java:430)
```

According to https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-settings.html:

> Important: 
Only some settings are designed to be read from the keystore. However, the keystore has no validation to block unsupported settings. Adding unsupported settings to the keystore will cause Elasticsearch Additional unsupported settings being added to the keystore will cause Elasticsearch to fail to start. See documentation for each setting to see if it is supported as part of the keystore.

**Comment by pebrc** [comment]
We could replace it with a secure setting that is 
* always present (so no storage plugin credentials)
* existed in 6.x

For example: `xpack.notification.email.account.name.smtp.secure_password` from watcher.

**Comment by maxisam** [comment]
I tried to setup s3.client.pminio.endpoint and I got the same error.
