### ISSUE TITLE
Document details of our CI setup

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#1564]
There was a proposal to document our CI setup because it's became more and more complicated.
It can be also useful for https://github.com/elastic/cloud-on-k8s/issues/1528

**Comment by david-kow** [comment]
Would we consider that https://github.com/elastic/cloud-on-k8s/blob/master/build/ci/README.md is enough to close this?

**Comment by pebrc** [comment]
@david-kow agreed
