### ISSUE TITLE
Elasticsearch - Token API

### ISSUE THREAD

**Issue by Ofinka** [elastic/cloud-on-k8s#1570]
## Proposal

Hi, 
I set up ES with my own certificate which works fine but now I would like to use token API as it is here: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/security-api-get-token.html

when issuing:
```
curl --request POST \
  --url https://elastic.mydomain/_xpack/security/oauth2/token \
  --header 'authorization: Basic ZWxhc3RpYzpteXBhc3N3b3Jk' \
  --header 'content-type: application/json' \
  --data '{
  "grant_type" : "password",
  "username" : "elastic",
  "password" : "mypassword"
}'
```
I get typicall response "current license is non-compliant for [security tokens]" which as I know should be irrelevant since security has been enabled in version 6.8. The documentation says that token API is automatically enabled when TLS is configured on HTTP interface.

I suppose ECK does not support this feature yet.

**Comment by david-kow** [comment]
Hi @Ofinka,

Elasticsearch Token Service which exposes token API is available with ES Gold/Platinum and ECK enterprise licences. You can start a trial and unlock this feature now. See [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-trial.html) for more information.

**Comment by Ofinka** [comment]
Ah, so its just a misunderstanding on my side. Thanks for clarification.
