### ISSUE TITLE
Investigate object comparison methods

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#1584]
We heavily use [`reflect.DeepEquals`](https://godoc.org/reflect#DeepEqual) for object comparison but it is a very blunt tool for the purpose with [some caveats](https://banzaicloud.com/blog/k8s-objectmatcher/) in the context of Kubernetes operators. 

We should investigate whether certain parts of the code could benefit from other alternatives (Eg.  using a custom [hashing function](https://github.com/pebrc/cloud-on-k8s/blob/d495796116a956d4d09c773bfd55921b8ddd0702/operators/pkg/controller/common/hash/hash.go#L47) for [Secret comparison](https://github.com/elastic/cloud-on-k8s/blob/8ddf40610dd3c60fc9e1170813fc5992a389ab7a/operators/pkg/controller/common/certificates/http/public_secret.go#L51)).

Options to consider (among others)
- [k8s-objectmatcher](https://github.com/banzaicloud/k8s-objectmatcher)
- [go-cmp](https://github.com/google/go-cmp)

**Comment by anyasabo** [comment]
object matcher looks interesting, thanks for sharing. I had looked into go-cmp but I think we would need to write our own custom equality funcs for a lot (most?) types. Which granted might be necessary, but for places where deepequal works it seemed like unnecessary overhead. I do feel bad every time I reach for deepequal though so would definitely be interested in alternatives

**Comment by pebrc** [comment]
https://github.com/elastic/cloud-on-k8s/pull/2232 add go-cmp for object comparison. Closing this.
