### ISSUE TITLE
Memory leak in Expectations

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1611]
There is a [TODO](https://github.com/elastic/cloud-on-k8s/blob/61c6acc489637ee049baf9b547258e90ba85ab84/operators/pkg/controller/common/reconciler/expectations.go#L12) in the source code but I want to be sure to track this one with an issue.

I have observed a small memory leak in the `Expectations`, `UIDs` are added but never removed.

**Comment by sebgl** [comment]
Things we don't handle perfectly well:

* when a StatefulSet is removed
    * its expectations will stay in-memory forever (generations map)
* when a cluster is removed
    * generation expectations of all its StatefulSets will stay in memory
    * deletion expectations of Pods that may have been deleted right before cluster removal will stay in memory

When/how should we garbage-collect expectations?
1. Whenever they are checked for a particular cluster, go through expectations of the corresponding cluster and garbage-collect the ones that are not needed
2. When an Elasticsearch resource is removed, remove all corresponding expectations
