### ISSUE TITLE
Kibana has wrong ELASTICSEARCH_HOSTS env variable set

### ISSUE THREAD

**Issue by msvechla** [elastic/cloud-on-k8s#1624]
## Bug Report
**What did you do?**
Newly created kibana instance can no longer connect to Elasticsearch, because the wrong `ELASTICSEARCH_HOSTS` environment variable is set on the kibana deployment:

```
 - env:
    - name: ELASTICSEARCH_HOSTS
      value: https://efk-es.monitoring.svc.cluster.local:9200
```

It looks like with operator 0.9.0 the URL has a new `-http` suffix, which is missing.

**What did you expect to see?**
```
 - env:
    - name: ELASTICSEARCH_HOSTS
      value: https://efk-es-http.monitoring.svc.cluster.local:9200
```
**What did you see instead? Under which circumstances?**
see above
**Environment**

* ECK version: 0.9.0

* Kubernetes information:

EKS

```
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Looks like the http suffix was added, but not changed in the kibana deployment. Is this an operator issue?

Thanks and best regards!

**Comment by pebrc** [comment]
Hm, odd https://github.com/elastic/cloud-on-k8s/blob/194ca6d68080bdad08c64c6c1ccd81d378f74040/operators/pkg/controller/elasticsearch/services/services.go#L34 

does use the service name suffixed with `http`. Is there an older version of the operator running at the same time?

If not, could you share the full Kibana and Elasticsearch resources you used?

**Comment by msvechla** [comment]
Thanks for the quick response!
I found the issue: earlier we upgraded the operator and then noticed that the new operator will no longer work with resources created by an older operator. We fixed the annotation for elasticsearch, but did not adapt it for the kibana.

By the way, what is the recommended approach for upgrading the operator?

Thanks for your help

**Comment by pebrc** [comment]
We currently don't support upgrades between 0.8 and 0.9 see
https://www.elastic.co/guide/en/cloud-on-k8s/0.9/release-highlights-0.9.0.html#k8s_breaking_changes

But we will work on supporting seamless operator upgrades in future releases.

**Comment by msvechla** [comment]
Perfect, thanks!

**Comment by huyngo81** [comment]
Hi I got the same issue with: 

`apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: euw1
  namespace: logging

spec:
  version: 7.5.1
  count: 1
  
  elasticsearchRef:
    name: euw1
  
  podTemplate: 
    spec:
      containers: 
        - name: kibana
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://euw1-es-http:9200"
          - name: xpack.security.enabled
            value: "false"
          - name: xpack.monitoring.enabled
            value: "false"
          - name: xpack.ml.enabled
            value: "false"
          - name: xpack.graph.enabled
            value: "false"
          - name: xpack.watcher.enabled
            value: "false"
      nodeSelector: 
        mine/group: default`

The problem is "we only want http Elasticsearch not https Elasticsearch". How can we access http only?
