### ISSUE TITLE
GKE: volumeBindingMode is set to Immediate

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1630]
With GKE we used to create a new storage class with the `volumeBindingMode` field set to `WaitForFirstConsumer` : https://github.com/elastic/cloud-on-k8s/blob/ee0645187e48e282a9af18425aa846c6fe6655ec/operators/hack/gke-cluster.sh#L90

It seems that #1594 removes this feature. This could lead to Pod that can't be scheduled in our e2e tests.

**Comment by david-kow** [comment]
Sorry for this omission, I'll fix it.
