### ISSUE TITLE
Fix vendor/ caching in CI Dockerfile

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1633]
During docker build we populate reporoot/vendor folder, but then we mount reporoot/ from host under reporoot/ in the container which "overwrites" the vendor folder.

This is visible in https://devops-ci.elastic.co/job/cloud-on-k8s-pr/1150/ where #1610 removed dep ensure from CI targets. This layer has over 2GB which we effectively don't use.

With volume mount:
```
$ export A=/go/src/github.com/elastic/cloud-on-k8s
$ docker run --rm -it -v $A:$A -w $A 791dde78d750 bash
# ls vendor
ls: cannot access 'vendor': No such file or directory
```

Without volume mount:
```
$ export A=/go/src/github.com/elastic/cloud-on-k8s
$ docker run --rm -it -w $A 791dde78d750 bash
# ls vendor/
cloud.google.com  github.com  go.uber.org  golang.org  google.golang.org  gopkg.in  k8s.io  sigs.k8s.io
```

**Comment by pebrc** [comment]
I think this is no longer an issue with the move to Go modules as we don't shadow the module cache with the volume mount iiuc
