### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#1635]
## Bug Report
**What did you do?**

Setup a fresh cluster last night. Come this morning, 2 nodes have been evicted.

**What did you expect to see?**

No evictions! ;)

**What did you see instead? Under which circumstances?**

Evictions :'(

**Environment**

* ECK version: 0.9.0

* Kubernetes information: GKE 1.12

-----

I'm still working on gathering details, but overnight this is what the memory usage looked like (per Google Stackdriver):

First container that was evicted. This was a master-only node.

![image](https://user-images.githubusercontent.com/131818/63704497-0b6ff880-c7e0-11e9-9634-807f46f7f5b4.png)

Relevant logs for this one container (elasticsearch reporting JVM args)

```
JVM arguments [-Xms1g, -Xmx1g, 
```

Resource requests: `2Gb` memory.

Symptom: Memory grew to ~25gb used before kubernetes evicted it.

Second container that was evicted. 

![image](https://user-images.githubusercontent.com/131818/63704852-c8faeb80-c7e0-11e9-8be0-19864fccca44.png)

Relevant logs for this one container (elasticsearch reporting JVM args)

```
2019-08-26 00:10:20.845 PDT JVM arguments [-Xms1g, -Xmx1g,
```

Resource requests: `20Gb` memory[1]

[1] Note, the resource request vs java heap size difference is a mistake on my part to not set Xmx on these nodes to match the resource request. However, I do not believe this related to the leak, as the JVM would still assume 1GB is the max, and yet, the graph shows it approach 20GB.

**Comment by j-rewerts** [comment]
@jordansissel I'm also experiencing this. Would you mind posting a link to your other issues you've filed?

**Comment by jordansissel** [comment]
@j-rewerts unfortunately most of the discussions for this issue are on private repositories (google support tickets, internal issue trackers, etc).

The short version is this:
* ECK 0.9.0 had Elasticsearch pods being evicted due to memory pressure
* We tracked this memory "pressure" being created by `curl https://...` as used in the `readinessProbe`.
* Strongest hypothesis is that there is a kernel bug causing file system cache usage to be charged to a pod.
* Workaround is two possible solutions:
  * to set a special ENV var for `curl` so it doesn't create so much noise in the filesystem cache.
  * make sure you set a `limit` for memory usage on all pods as a safety measure which implicitly causes the caches to purge when memory limit is hit, which you will hit if you are encountering this bug.

Public references to this problem of ECK 0.9.0 Elasticsearch pods being evicted or "using" too much memory:
* https://github.com/elastic/cloud-on-k8s/issues/1581#issuecomment-525142107
* Tracking upstream at Google: https://issuetracker.google.com/issues/140577001
