### ISSUE TITLE
Single master cluster upgrades will fail

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1642]
When there is only a single master node and we restart it, we can’t continue the upgrade as rolling upgrade anymore. After coming back, master will conclude the upgrade is done and other nodes have to be upgraded to join back the cluster.

**Comment by pebrc** [comment]
Did you have something like this in mind @david-kow 
```golang
// TestVersionUpgrade680To720 creates a cluster in version 6.8.0,
// and upgrades it to 7.2.0.
func TestVersionUpgradeSingle680To720(t *testing.T) {
	// create an ES cluster with 3 x 6.8.0 nodes
	initial := elasticsearch.NewBuilder("test-version-up-680-to-720").
		WithVersion("6.8.0").
		WithESMasterNodes(1, elasticsearch.DefaultResources).
		WithESDataNodes(2, elasticsearch.DefaultResources)
	// mutate it to 3 x 7.2.0 nodes
	mutated := initial.WithNoESTopology().
		WithVersion("7.2.0").
		WithESMasterNodes(1, elasticsearch.DefaultResources).
		WithESDataNodes(2, elasticsearch.DefaultResources)

	RunESMutation(t, initial, mutated)
}
```
> After coming back, master will conclude the upgrade is done and other nodes have to be upgraded to join back the cluster.

I am not sure I follow here. The problem seems to be that after upgrading the only master node we need to set `initial_master_nodes` because there is not cluster to 'join' anymore. See:

```
{"type": "server", "timestamp": "2019-08-28T08:40:52,511+0000", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHe │
│ lper", "cluster.name": "test-version-up-680-to-720-5mzk", "node.name": "test-version-up-680-to-720-5mzk-es-master-0",  "message": "master not discovered yet, this node has not previously │
│  joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered []; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0 │
│ .1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, [::1]:9300, [::1]:9301, [::1]:9302, [::1]:9303, [::1]:9304, [::1]:9305] from hosts providers and [{test-version-up-680-to-720-5mz │
│ k-es-master-0}{-tcsez3jRuC0AC1Abber9w}{CWn_dGq_QlSPE96wJSZi8Q}{10.32.1.122}{10.32.1.122:9300}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}] from last-known cl │
│ uster state; node term 0, last-accepted version 0 in term 0"  }   
```

Interestingly, it upgraded the data nodes first to 7.2.0. Don't think it makes any difference though.

**Comment by david-kow** [comment]
The issue is based off the ES docs, I'll try to repro it, but:
1. Were there any indices on that cluster? The upgrade won't progress based on yellow status that's coming from not being able to place replicas.
1. If data nodes were upgraded first, the issue won't be triggered. But the order is not deterministic right now.

**Comment by sebgl** [comment]
Quoting the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/rolling-upgrades.html): 

> Similarly, if you run a testing/development environment with only one master node, the master node should be upgraded last. Restarting a single master node forces the cluster to be reformed. The new cluster will initially only have the upgraded master node and will thus reject the older nodes when they re-join the cluster. Nodes that have already been upgraded will successfully re-join the upgraded master.

When doing rolling upgrades, we could make sure we upgrade data nodes first and master nodes last (then, sort by alphabetical order?). Currently we don't do any sorting on StatefulSets to upgrade.

**Comment by pebrc** [comment]
> Were there any indices on that cluster? The upgrade won't progress based on yellow status that's coming from not being able to place replicas.

I think we have an issue to move away from the 'no progress unless cluster green' rule during rolling upgrades that would accommodate allocation exclusions that result from nodes running different versions of Elasticsearch #1155

**Comment by sebgl** [comment]
https://github.com/elastic/cloud-on-k8s/pull/1661 should help with that, but will not handle more complex cases.

**Comment by sebgl** [comment]
An example of a more complex case:

We have 2 nodes, one master and one non-master:
```
spec:
  version: 7.3.0
  nodes:
  - name: a
    nodeCount: 1
    config:
       master: true
       data: true
  - name: b
    nodeCount: 1
    config:
       master: false
       data: true
```
We flip the master bit from one node to another:
```
spec:
  version: 7.3.0
  nodes:
  - name: a
    nodeCount: 1
    config:
       master: false
       data: true
  - name: b
    nodeCount: 1
    config:
       master: true
       data: true
```
In the current rolling upgrade implementation, we'll roll node `a` first, leaving the cluster with no master node. It won't respond to the operator requests anymore.

We should probably delay current master nodes rolling upgrade and give priority to other nodes if the master node is the last running master in the cluster.

**Comment by pebrc** [comment]
> An example of a more complex case:

Why would you start with `a`? We should start with node `b` which is data only currently. So we should base the order on the current state of the cluster and not the desired state.

**Comment by david-kow** [comment]
Closing as this is solved with recent ondelete changes. @sebgl please reopen if needed.
