### ISSUE TITLE
Version upgrades could stop making progress if replicas need to be placed on not upgraded nodes

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1643]
When we upgraded less nodes than there are replicas for a primary than is on one of the upgraded nodes, the cluster could stay yellow. Replicas can't be placed if new version contains internal representation changes that are incompatible with older version.

**Comment by barkbay** [comment]
So it means that we should be more lenient when dealing with Pod restarts if the cluster is in a yellow status.
Maybe we should allow a Pod restart even if the managed cluster is in a yellow state under the condition that restarting a Pod does not make an index unavailable (with the exception of index with no replicas)

**Comment by barkbay** [comment]
We agreed to implement the idea described in the comment above. An additional check to ensure that there are several versions of Elasticsearch running in the cluster will be added.
