### ISSUE TITLE
Change CertInitializerContainer's default imagePullPolicy to IfNotPresent

### ISSUE THREAD

**Issue by lord63** [elastic/cloud-on-k8s#1659]
# Proposal

Change CertInitializerContainer's default imagePullPolicy to IfNotPresent in v0.8.x

**Use case. Why is this important?**

1. other init containers' image pull policy is IfNotPresent
2. it can be used in offline environment, the original way will failed when init containers

Let me know if there are any intentional reasons that I don't know.

**Comment by charith-elastic** [comment]
Hi, we have removed cert-initializer since 0.9 in order to simplify the workflow. Is there a particular reason why you are still on 0.8.x and cannot upgrade to 0.9?

**Comment by lord63** [comment]
There are some historical reasons that we're still use it. Is version 0.8.x officially deprecated?  I didn't see any documents.

**Comment by charith-elastic** [comment]
We are still in the alpha stage so we don't maintain older versions. The recommendation is to upgrade to the latest version.

**Comment by lord63** [comment]
Thank you for your response, we'll patch the old version and will update in the future.
