### ISSUE TITLE
Upgrading 1 node from 6.X to 7.X fails since cluster appears already bootstrapped

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1660]
Upgrading a 1-node cluster from 6.X to 7.X fails, because we don't set initial_master_nodes on that node, since we consider the cluster is already bootstrapped.

We annotate the cluster as "bootstrapped" with its UUID from the cluster state once observed by the observers. Then, we don't set zen2 initial master nodes anymore.

However when we migrate a 1-node cluster from 6.X to 7.X, there is no master node to join.

We should probably differentiate:
* cluster being bootstrapped in the sense "already exists" (concept used in https://github.com/elastic/cloud-on-k8s/pull/1654)
* cluster being bootstrapped for zen2 (has seen initial master nodes already)

Related comment in a PR: https://github.com/elastic/cloud-on-k8s/pull/1654#discussion_r318964828
Related discussion: https://github.com/elastic/cloud-on-k8s/issues/1281#issuecomment-524832319

**Comment by pebrc** [comment]
Is this somewhat of a duplicate to #1642 ?

**Comment by sebgl** [comment]
I think we can separate:

* problem with handling initial master nodes and cluster bootstrap (this issue): probably needs to fix the way we consider a cluster as bootstrapped for zen2
* problem with handling rolling upgrades in general with a single master, which should be upgraded last (https://github.com/elastic/cloud-on-k8s/issues/1642): probably needs to sort the StatefulSets we process during a rolling upgrade to have master nodes last
