### ISSUE TITLE
Add licenses for dependencies

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#1664]
We need to summarises all licenses of our deps to be sure that we are complying with them.

Probably we can re-use https://github.com/elastic/beats/blob/master/dev-tools/generate_notice.py for that. 

Also we need not only to put it in repo, but add it to docs as well.

**Comment by artemnikitin** [comment]
It looks like we willn't be able to simply re-use https://github.com/elastic/beats/blob/master/dev-tools/generate_notice.py. They are using `govendor` for managing dependencies and this Python script expects some specific `govendor`-related files to process.

**Comment by pebrc** [comment]
Probably worth writing something in Go :-)

Something else to keep in mind is that we are working on kubebuilder v2 which moves us to go modules

**Comment by charith-elastic** [comment]
Something like https://github.com/ribice/glice perhaps? We might be able to write a tool of our own using https://github.com/src-d/go-license-detector as well.

**Comment by charith-elastic** [comment]
Fixed by #1764
