### ISSUE TITLE
ES custom resource phase is never updated

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1669]
We use a phase attribute in the status of the Elasticsearch resource. It seems to be stuck in 'Pending' state forever. 

I wonder if we run into a version conflict here that prevents the status update from going through.

**Comment by thbkrkr** [comment]
We removed the call to `UpdateElasticsearchOperational` with our move to the statefulsets.
https://github.com/elastic/cloud-on-k8s/blob/79d57c1d8b84e08eae9d5d220b11eb0d44998858/operators/pkg/controller/elasticsearch/driver/default.go#L384-L388

I'm not very comfortable wih this part. Here are a few notes that I compiled.

#### State of the art

4 `ElasticsearchOrchestrationPhase` exist: `Invalid`, `Pending`, `MigratingData` and `Operational`.

We have a set of `UpdateElasticsearchXXX` methods that update only the current status phase or call `updateWithPhase(p)` that performs a full status update:

`UpdateElasticsearchInvalid` (s.status.Phase=Invalid)
	- in `ReconcileElasticsearch.internalReconcile`
	- if validation.Validate(es) has violations

`UpdateElasticsearchPending` (s.status.Phase=Pending)
	- in `driver.reconcileNodeSpecs`
	- if !esReachable

`UpdateElasticsearchMigrating`   (updateWithPhase(MigratingData))
	- in `driver.reconcileNodeSpecs`
	- if downscale (HandleDownscale > attemptDownscale > calculatePerformableDownscale)

`UpdateElasticsearchOperational` (updateWithPhase(Operational))
	- not called

`UpdateElasticsearchState`       (updateWithPhase(s.status.Phase))
	- in `driver.Reconcile`
	- after retrieving the observedState
	- and at the end of method

#### What is the current lifecycle of the ES orchestration phase?

When applying for an ES resource, after passing the validation, the resource becomes `Pending` until the pods are alive. As soon as the cluster is green, the phase becomes `Operational`, even if all pods are not ready yet.

As long as the cluster is green, the phase stays `Operational`. An upscale or a rolling upgrade (which handle configuration changes) leave the cluster `Operational`. Only a downscale updates the phase to `MigratingData`.

I'm not sure of the reasoning behind that. I feel it may also be informative to know that an upscale or a rolling upgrade is in progress.

#### What is meant by operational for us?

AFAIU it's a valid green cluster without ongoing downscale.



I'm not sure what's the best place to call `UpdateElasticsearchOperational`.
It seems to me that we need to check there is no change in progress (upscale, downscale, or rolling upgrade) to set the phase to `Operational`, which must be equivalent to check that the statefulset is reconciled.

**Comment by pebrc** [comment]
We could revisit the phases and introduce one that represents 'upgrades' (meaning all of upscale, downscale, rolling upgrade). Or we surface each of the three different conditions. The problem with that is that they might overlap (but I think we are converging towards an approach where we want to separate them) So we could have `ScalingUp`, `ScalingDown`, `Upgrading` and `Operational` WDYT? Alternatively just `ApplyingChanges` and `Operational` 

Side note:  I find `Operational` sounds odd and is not really a 'phase', maybe it should be replaced with `Running`?

**Comment by thbkrkr** [comment]
Thinking again, I'm a little reluctant to add complexity primarily to satisfy curiosity. Let's start by reintroducing the lost `Operational` phase. We can still decide to split the `Pending/ApplyingChanges` phase later.

Not to blame someone but out of curiosity, I went back in time. The "phase" (~ Elasticsearch orchestration status) was introduced in the PR #79 resolving the issue #59. Naming is (often) hard! Yes, `Operational` is a bit odd but I think I prefer it over `Running`. Most of the time, an ES cluster should be running during a rolling upgrade. I'm thinking about `Reconciled` but it's uncommon, then found [this](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.OrchestrationRuntimeStatus.html) and feel `Completed` not so bad.
```

**Comment by david-kow** [comment]
It feels to me that we try to mix few different dimensions - ES status (`Operational`, ie. green ES), operator progress towards current spec (`Upgrade`, `Scaling*`) and infra readiness. This might get complicated quickly: if ES is green and we are scaling up and all nodes are ready, what phase is that? `ScalingUp`? Would that mean that it's not operational?
I think the most basic approach is having two as @pebrc said, meaning that given current spec something is going to change (`ApplyingChanges`) or isn't (`Ready`? - for me `Operational` implicates that it works now, but it might not be fully ready. Given that, it also feels that `Operational`, once set, shouldn't ever go away).

**Comment by pebrc** [comment]
I am fine with just restoring the original behaviour. 

But just to clarify:

> Completed [is] not so bad.

`Completed` for me indicates a one off thing, like a k8s job that runs to completion.

> It feels to me that we try to mix few different dimensions 

We have two separate attributes for cluster health (`green`/`yellow`/`red`) and orchestration status (`Operational` (I like `ready` btw), `Pending` (admittedly vage, `ApplyingChanges` seems better), `MigratingData` etc. So `ScalingUp`, `ScalingDown`, `Upgrading` seem to fit as they are just detailing the more general phases we had. 

There is some overlap though: `ScalingDown` will typicaly involve `MigratingData` so I think that sense I agree with @david-kow 's statement that they are somewhat conflating.

So maybe `ApplyingChanges` and `Ready` for now?

**Comment by thbkrkr** [comment]
`Operational` is definitively ambiguous. `ApplyingChanges` and `Ready` sounds good to me.

I know we say we restore the original behaviour but I still hesitate about one thing: do we take into account pod health to set `Ready` ([comment](https://github.com/elastic/cloud-on-k8s/pull/1719#discussion_r323667239))?

**Comment by david-kow** [comment]
@thbkrkr I'd say yes. That leads to the question what happens if a pod can't come up. It's confusing to keep it at ApplyingChanges forever, but we can deal with that separately.
