### ISSUE TITLE
Add latest tag for nightly builds

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#1671]
Currently our nightly builds looks like `docker.elastic.co/eck-snapshots/eck-operator:0.10.0-SNAPSHOT-2019-08-30-4512d18`. It make sense to also have a `latest` tag for users to be able simply get latest image.

**Comment by charith-elastic** [comment]
There are some well-known caveats with using `latest` so we have to be careful about using it. I have raised a more generic issue related to this so I am closing this issue to continue the discussion there. See #3548.
