### ISSUE TITLE
Webhook name

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1675]
As [it has been pointed out by a user](https://github.com/elastic/cloud-on-k8s/issues/896#issuecomment-516835285) the name of the webhook is pretty generic : `validating-webhook-configuration`.

Since it would be a breaking change I'm wondering if we should change the name sooner rather than later.

**Comment by pebrc** [comment]
Keeping this open, but depending on the outcome of our kubebuilder v2 webhook might disappear for a while until we figure out how to do them.

**Comment by pebrc** [comment]
We have renamed the webhook to `elastic-webhook.k8s.elastic.co ` in #2126
