### ISSUE TITLE
Remove Grouping definition

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1694]
As noted in https://github.com/elastic/cloud-on-k8s/pull/1683#discussion_r320488087 we should discussed if we still need the `GroupingDefinition` or define how it can be used in the context of the statefulsets.

Somewhat related to #1141

**Comment by pebrc** [comment]
We decided after moving to StatefulSets grouping definition does not make much sense anymore and the grouping is implicit in the sets.
