### ISSUE TITLE
Deleting CRD hangs forever on kubectl delete

### ISSUE THREAD

**Issue by sarjeet2013** [elastic/cloud-on-k8s#1701]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

kubectl delete -f all-in-one.yaml <hangs..>
kubectl delete crd apmservers.apm.k8s.elastic.co <hangs..>

**What did you expect to see?**

CRDs get deleted without any hang.

**What did you see instead? Under which circumstances?**

kubectl command hangs forever (>10 min)

**Environment**

minikube

* ECK version:

	7.3.0/master-branch built operator

* Kubernetes information:

	minikube/1.15.2 (client/server)

* Logs:

apiserver logs:

```
E0909 22:54:07.594370       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:54:07.746561       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition

E0909 22:55:07.795640       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:55:07.898099       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition

E0909 22:56:07.918107       1 crd_finalizer.go:135] Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "apmservers.apm.k8s.elastic.co": the object has been modified; please apply your changes to the latest version and try again
E0909 22:56:07.918141       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:56:07.982243       1 crd_finalizer.go:135] Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "elasticsearches.elasticsearch.k8s.elastic.co": the object has been modified; please apply your changes to the latest version and try again
E0909 22:56:07.991623       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition

E0909 22:57:08.004505       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:57:08.050641       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:58:08.035081       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:58:08.173384       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:58:40.748549       1 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
E0909 22:59:08.132981       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 22:59:08.256787       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition
E0909 23:00:08.182833       1 crd_finalizer.go:288] apmservers.apm.k8s.elastic.co failed with: timed out waiting for the condition
E0909 23:00:08.273715       1 crd_finalizer.go:288] elasticsearches.elasticsearch.k8s.elastic.co failed with: timed out waiting for the condition
```

**Comment by anyasabo** [comment]
Hello, did you happen to have any existing CRs before deleting the CRDs (`kubectl get elastic --all-namespaces` should indicate)? If so it may be hanging on deleting the finalizers. This would normally be handled by the operator, but the operator was deleted in your step 1. If there are still CRs, removing the finalizers manually should allow the CRD deletion to go through.


We tried to document the uninstall process here which _should_ work, but let us know if you have issues:
https://github.com/elastic/cloud-on-k8s/blob/master/docs/uninstall.asciidoc

**Comment by sarjeet2013** [comment]
@anyasabo You're right. There seems some CR references being left over from the previous smoke run (non sure how?) on a non-existent namespace.

```
➜  kubectl get elastic --all-namespaces
NAMESPACE     NAME                                                           HEALTH   NODES   VERSION   AGE
e2e-mercury   apmserver.apm.k8s.elastic.co/test-apm-del-referenced-es-ntpf   green    1       7.3.0     11d

NAMESPACE     NAME                                                                         HEALTH   NODES   VERSION   PHASE     AGE
e2e-mercury   elasticsearch.elasticsearch.k8s.elastic.co/test-apm-del-referenced-es-7gl8   green    2       7.3.0     Pending   11d

➜  kubectl get ns
NAME              STATUS   AGE
default           Active   18d
kube-node-lease   Active   18d
kube-public       Active   18d
kube-system       Active   18d
``` 
I have maually removed these and able to cleanup the CRD's now which were hanging earlier. 

Thanks again for your help. I'll close the issue.

**Comment by ftyuuu** [comment]
hang here? what should i do?
```
kubectl get namespaces --no-headers -o custom-columns=:metadata.name \
  | xargs -n1 kubectl delete elastic --all -n
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-sample" deleted
elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-test" deleted
```

**Comment by ftyuuu** [comment]
> hang here? what should i do?
> 
> ```
> kubectl get namespaces --no-headers -o custom-columns=:metadata.name \
>   | xargs -n1 kubectl delete elastic --all -n
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> No resources found
> elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-sample" deleted
> elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-test" deleted
> ```

i delete resource‘s namespace forcibly, and then 

```
kubectl get elasticsearch --all-namespaces
NAMESPACE           NAME                   HEALTH   NODES   VERSION   PHASE   AGE
nes-elasticsearch   elasticsearch-sample                    6.8.4             1h
nes-elasticsearch   elasticsearch-test                      6.8.4             34m
```
```
kubectl delete elastic elasticsearch-test
Error from server (NotFound): elasticsearches.elasticsearch.k8s.elastic.co "elasticsearch-test" not found
```
what should i do to delete these cr and crd?

**Comment by ftyuuu** [comment]
> > hang here? what should i do?
> > ```
> > kubectl get namespaces --no-headers -o custom-columns=:metadata.name \
> >   | xargs -n1 kubectl delete elastic --all -n
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > No resources found
> > elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-sample" deleted
> > elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-test" deleted
> > ```
> 
> i delete resource‘s namespace forcibly, and then
> 
> ```
> kubectl get elasticsearch --all-namespaces
> NAMESPACE           NAME                   HEALTH   NODES   VERSION   PHASE   AGE
> nes-elasticsearch   elasticsearch-sample                    6.8.4             1h
> nes-elasticsearch   elasticsearch-test                      6.8.4             34m
> ```
> 
> ```
> kubectl delete elastic elasticsearch-test
> Error from server (NotFound): elasticsearches.elasticsearch.k8s.elastic.co "elasticsearch-test" not found
> ```
> 
> what should i do to delete these cr and crd?

Finally, i solve this problem according to https://github.com/kubernetes/kubernetes/issues/60538
