### ISSUE TITLE
Documentation missing for ECK stack with non-default namespace

### ISSUE THREAD

**Issue by sarjeet2013** [elastic/cloud-on-k8s#1702]
See also: https://discuss.elastic.co/t/missing-documentation-for-eck-stack-in-non-default-namespace/198802

**Comment by anyasabo** [comment]
To clarify from the discuss thread, this issue is about making the namespace of the elastic resources (CRs not CRDs) explicit in the examples (or otherwise indicating to people how to do so) so people can know how to deploy them to a namespace that is not their current default.

**Comment by pebrc** [comment]
I am tempted to close this as this would just duplicate existing Kubernetes documentation https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

Please reopen if you think otherwise.
