### ISSUE TITLE
Where the features such as frozen indices for dense storage, Kibana Spaces, Canvas, Elastic Maps?

### ISSUE THREAD

**Issue by simply-news** [elastic/cloud-on-k8s#1704]

**Comment by pebrc** [comment]
Thanks very much for your interest in Elastic Cloud on Kubernetes.

This appears to be a user question, and we'd like to direct these kinds of things to the [ECK forum](https://discuss.elastic.co/eck). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/eck) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
