### ISSUE TITLE
Switch to controller-runtime v0.2 logging package

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#1708]
Depends on #1188 and relates to #1699 

- `pkg/runtime/log` package is now deprecated and we should switch to `pkg/log` instead.
- `pkg/log/zap` provides configuration functions that can be used to simplify our logging configuration at `pkg/utils/log`

**Comment by racevedoo** [comment]
@charith-elastic Can I take a look at this? I'd like to start contributing

**Comment by charith-elastic** [comment]
Sure; I don't think anyone else has started working on it.

**Comment by racevedoo** [comment]
great! I'll ping when I have a PR ready

**Comment by racevedoo** [comment]
@charith-elastic just opened a PR (#1808) for the `pkg/runtime/log` part. Another will follow for the zap refactor you mentioned.

**Comment by racevedoo** [comment]
@charith-elastic Remaining PR opened! #1828

**Comment by charith-elastic** [comment]
Fixed by #1808 and #1828 
Thanks @racevedoo
