### ISSUE TITLE
Deployer should only delete disks belonging to the cluster being deleted

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#1722]
When deleting a GKE cluster the Deployer first issues a command to delete the cluster and then finds all disks without an owner and deletes them as well. This is a bit confusing and potentially dangerous because it could inadvertently delete disks belonging someone else using the same GCP project.

A possible solution might be to swap the steps in the deletion logic:
- Obtain a list of disks belonging to the cluster (`gcloud compute disks list --filter='users:cluster-name'`) 
- Delete the cluster
- Go through the list of disks obtained in the first step and delete any that still exists

**Comment by david-kow** [comment]
To add some context and help with prioritization:
1. this mirrors previous behavior (so not a regression),
2. it deletes disks not attached to any instance.

**Comment by barkbay** [comment]
@charith-elastic since only orphaned disk are deleted do you think we should keep this one open ?

**Comment by charith-elastic** [comment]
My concern is that a community user might attempt using this and accidentally delete disks they are not meant to. Given that the fix is not complicated, I am inclined to just do it.

**Comment by barkbay** [comment]
> it deletes disks not attached to any instance

I can confirm that it is not enough:
1. A `Pod` is using a disk though a `PVC`
2. When the `Pod` is deleted the disk is no longer attached to a compute instance:
```
> gcloud compute disks list --filter='-users:*' --project elastic-cloud-dev --format="json"
[
  {
    "creationTimestamp": "2019-10-07T23:58:02.643-07:00",
    "description": "{\"kubernetes.io/created-for/pv/name\":\"pvc-c42938c6-e998-11e9-ae21-42010a84008a\",\"kubernetes.io/created-for/pvc/name\":\"a-pvc-claim\",\"kubernetes.io/created-for/pvc/namespace\":\"e2e-mercury\"}",
    "id": "7749440439613230485",
    "kind": "compute#disk",
    "labelFingerprint": "42WmSpB8rSM=",
    "lastAttachTimestamp": "2019-10-07T23:58:10.000-07:00",
    "lastDetachTimestamp": "2019-10-08T00:01:07.093-07:00",
    "name": "gke-michael-dev-cluste-pvc-c42938c7-e999-11f9-a551-42010a8408a",
    "physicalBlockSizeBytes": "4096",
    "selfLink": "https://www.googleapis.com/compute/v1/projects/elastic-cloud-dev/zones/europe-west1-d/disks/gke-michael-dev-cluste-pvc-c42938c7-e999-11f9-a551-42010a8408a",
    "sizeGb": "1",
    "status": "READY",
    "type": "https://www.googleapis.com/compute/v1/projects/elastic-cloud-dev/zones/europe-west1-d/diskTypes/pd-standard",
    "zone": "https://www.googleapis.com/compute/v1/projects/elastic-cloud-dev/zones/europe-west1-d"
  }
]
```
3. At this point it might happen that the underlying disk is deleted by an other instance of the deployer because it is considered as orphaned
4. When the `Pod` comes back the disk can't be attached and the following error is raised:

```
 0s          Warning   FailedAttachVolume       pod/task-pv-pod                     AttachVolume.Attach failed for volume "pvc-c42938c6-e998-11e9-ae21-42010a84008a" : GCE persistent disk not found: diskName="gke-michael-dev-cluste-pvc-c42938c6-e998-11e9-ae21-42010a84008a" zone="europe-west1-d"
```

The bad news is that it seems that there is no way to know to which cluster a disk was previously attached. 😞 

The only solution I see so far is:
1. to prefix the name of the cluster with an ID, for example `jenkins-cloud-on-k8s-e2e-tests-436` would be renamed into `eck-XXXX-e2e-tests-436`
2. delete PVC using the prefix: `gcloud compute disks list --filter="-users:* AND name~'eck-XXXX'" --project elastic-cloud-dev` It should work because the name of the PVC contains a truncated string based on the name of the cluster.

**Comment by barkbay** [comment]
An other thing to consider is that an orphaned disk is not immediately detected with `-users:*`
While I'm doing some tests it takes a few seconds before the disk appears in the list. So the deployer might not be able to detect an orphaned disk for the cluster is currently managing.

**Comment by sebgl** [comment]
I guess this may be the reason we see so many of those in the E2E tests output:

```
10:36:14  {"reason":"FailedAttachVolume","message":"AttachVolume.Attach failed for volume \"pvc-24955664-e4ee-11e9-ab4c-42010a840069\" : GCE persistent disk not found: diskName=\"gke-jenkins-cloud-on-k-pvc-24955664-e4ee-11e9-ab4c-42010a840069\" zone=\"europe-west1-c\"","kind":"Pod","name":"test-es-keystore-xztk-es-masterdata-1","namespace":"e2e-o9dzw-mercury"}
10:36:14  {"reason":"FailedMount","message":"Unable to mount volumes for pod \"test-es-keystore-xztk-es-masterdata-1_e2e-o9dzw-mercury(2e82fff7-e4ef-11e9-ab4c-42010a840069)\": timeout expired waiting for volumes to attach or mount for pod \"e2e-o9dzw-mercury\"/\"test-es-keystore-xztk-es-masterdata-1\". list of unmounted volumes=[elasticsearch-data]. list of unattached volumes=[elasticsearch-data elastic-internal-elasticsearch-bin-local elastic-internal-elasticsearch-config elastic-internal-elasticsearch-config-local elastic-internal-elasticsearch-plugins-local elastic-internal-http-certificates elastic-internal-probe-user elastic-internal-scripts elastic-internal-transport-certificates elastic-internal-unicast-hosts elastic-internal-xpack-file-realm elasticsearch-logs]","kind":"Pod","name":"test-es-keystore-xztk-es-masterdata-1","namespace":"e2e-o9dzw-mercury"}
```

**Comment by barkbay** [comment]
@sebgl yes, I think so

I would be tempted to create clusters with a unique prefix and delete **all**  the disks for which the name contain this prefix, regardless they are orphaned or not.

Problem is that it is really dirty as it would not work for developer clusters _(if cluster name is too long)_  and it is completely dependent on the Google implementation.

@charith-elastic:
> Given that the fix is not complicated

Could you share the fix you had in mind ?

**Comment by pebrc** [comment]
> I guess this may be the reason we see so many of those in the E2E tests output:

I have seen this error also outside of e2e tests, where the deployer is not involved.

**Comment by barkbay** [comment]
> I have seen this error also outside of e2e tests, where the deployer is not involved.

As long as the disk is in the same Google project _(and in the same zone ?)_  it could be deleted, wether or not it is involved in an e2e test.

**Comment by charith-elastic** [comment]
> @charith-elastic:
> 
> > Given that the fix is not complicated
> 
> Could you share the fix you had in mind ?

https://github.com/elastic/cloud-on-k8s/issues/1722#issue-492858722 is the fix I came up with off the top of my head. 

> I guess this may be the reason we see so many of those in the E2E tests output:

This could be one of the factors (especially when two or more E2E tests kick off around the same time). However, some of the past issues I read on that error seem to suggest that it is caused by pods with PVs getting re-scheduled on to different nodes. I think  the root cause is our E2E tests causing too much pod churn too quickly. Maybe we should try using affinity rules or something similar to reduce it.

**Comment by barkbay** [comment]
> gcloud compute disks list --filter='users:cluster-name'

This does not work for me, I did a test on cluster `jenkins-cloud-on-k8s-e2e-tests-439`:

List of PV retrieved with `kubectl get pv`:

```
persistentvolume/pvc-abff69c4-e9bf-11e9-b25b-42010a84005f   1Gi        RWO            Delete           Bound    e2e-gse9t-mercury/elasticsearch-data-test-change-budget-6vxg-es-master-0   standard-customized            50s
persistentvolume/pvc-ac20ceda-e9bf-11e9-b25b-42010a84005f   1Gi        RWO            Delete           Bound    e2e-gse9t-mercury/elasticsearch-data-test-change-budget-6vxg-es-data1-0    standard-customized            50s
persistentvolume/pvc-ac2a848e-e9bf-11e9-b25b-42010a84005f   1Gi        RWO            Delete           Bound    e2e-gse9t-mercury/elasticsearch-data-test-change-budget-6vxg-es-data1-1    standard-customized            50s
persistentvolume/pvc-ac36d8e8-e9bf-11e9-b25b-42010a84005f   1Gi        RWO            Delete           Bound    e2e-gse9t-mercury/elasticsearch-data-test-change-budget-6vxg-es-data1-2    standard-customized            49s
persistentvolume/pvc-ac4b0c08-e9bf-11e9-b25b-42010a84005f   1Gi        RWO            Delete           Bound    e2e-gse9t-mercury/elasticsearch-data-test-change-budget-6vxg-es-data1-3    standard-customized            49s
persistentvolume/pvc-ac69bcce-e9bf-11e9-b25b-42010a84005f   1Gi        RWO            Delete           Bound    e2e-gse9t-mercury/elasticsearch-data-test-change-budget-6vxg-es-data1-4    standard-customized            49s
```

```
$ gcloud compute disks list --filter='users:jenkins-cloud-on-k8s-e2e-tests-439'
Listed 0 items.
```

**Comment by charith-elastic** [comment]
I was testing with a short cluster name. I think the reason you can't list the disks using the full name of the E2E test cluster is because it gets truncated:

```shell
gcloud compute disks describe gke-jenkins-cloud-on-k-pvc-4a835f53-e9c6-11e9-a33a-42010a84016c --zone europe-west1-b
...
users:
- https://www.googleapis.com/compute/v1/projects/elastic-cloud-dev/zones/europe-west1-b/instances/gke-jenkins-cloud-on-k8s-default-pool-c2e7fafd-0342
....
```
So, your suggestion of using a short unique prefix for the cluster name is probably the most fool-proof method.
