### ISSUE TITLE
container ls

### ISSUE THREAD

**Issue by nigel-jones** [elastic/cloud-on-k8s#1725]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by sebgl** [comment]
Looks like a mistake, closing :)
