### ISSUE TITLE
ECK short glossary

### ISSUE THREAD

**Issue by alaudazzi** [elastic/cloud-on-k8s#1744]
Now that the ECK doc is growing, it makes sense to have a list of basic terms that are commonly used in ECK.
Something similar to: https://www.elastic.co/guide/en/cloud-enterprise/current/ece-glossary.html.

CC: @elastic/cloud-k8s

**Comment by sebgl** [comment]
A few that come to mind:

- ECK
- k8s
- PVC
- NodeSet
- operator
- CRD
- apiserver
- cluster mutation
- RBAC
- Pod
- StatefulSet
- Service

**Comment by pebrc** [comment]
I would vote for excluding k8s terms (or at least just linking to k8s docs)

**Comment by artemnikitin** [comment]
I think we can also explain all the short names of different managed k8s services, like:
- GKE
- AKS
- EKS
and so on...

**Comment by thbkrkr** [comment]
Closed in #1787.
