### ISSUE TITLE
Should we include the pods readiness in the ES phase?

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#1749]
While working on the restoration of the ~`Operational`~`Ready` ES phase (#1669), we had [some](https://github.com/elastic/cloud-on-k8s/issues/1669#issuecomment-532109614) [discussions](https://github.com/elastic/cloud-on-k8s/pull/1719#discussion_r323667239) whether or not to take into consideration the pods readiness to set `Ready`.

The actual behaviour does not take into consideration the pods readiness and allows to have the ES resource `Ready` with pods not `Running`:
```shell
> k get es,sts,po
NAME                                              HEALTH   NODES   VERSION   PHASE         AGE
elasticsearch.elasticsearch.k8s.elastic.co/abcd   green    2       7.3.0     Ready   1h

NAME                              DESIRED   CURRENT   AGE
statefulset.apps/abcd-es-master   3         3         97m

NAME                   READY   STATUS     RESTARTS   AGE
pod/abcd-es-master-0   1/1     Running    0          24m
pod/abcd-es-master-1   1/1     Running    0          20m
pod/abcd-es-master-2   0/1     Init:0/2   0          5s
```

**Comment by pebrc** [comment]
I like the idea, otherwise our phase value would be somewhat misleading. Giving the impression that the cluster has reached a steady state when it actually might not have.

**Comment by anyasabo** [comment]
Agreed, since we're already reporting the health separately it seems to make sense that we would want something to indicate that there's still changes taking place, even if the cluster is still green.

**Comment by thbkrkr** [comment]
After discussing this offline, we ended up deciding to keep the pods readiness separate from the operating phase, especially given the next [enhancement](https://github.com/elastic/cloud-on-k8s/issues/1786) of replacing the `nodes` field of the reconciler status with ` readyPods` so to better surface the number of ready pods in relation to the total number of pods and have something that works not only for Elasticsearch but also for Kibana and APM Server.

**Comment by sarjeet2013** [comment]
@thbkrkr  Even the `readyPods` may be misleading if there are multiple nodeSets and each may have different pods (counts) to it. The cumulative `readyPods` may mislead that there are enough pods shown as ready but a specific nodeSet may have all pods in bad state or stuck in scheduling. It could lead to a failover disaster case.

Also, I would think it would be appropriate to explore health with the Topology (nodeSets) with their corresponding roles, so it's easier to get overall status of each nodeSet with specific role pods health status.
