### ISSUE TITLE
TestMutationResizeMemoryDown is flaky

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1752]
```
    --- FAIL: TestMutationResizeMemoryDown/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process (0.00s)
        steps_mutation.go:85: 
            	Error Trace:	steps_mutation.go:85
            	Error:      	Not equal: 
            	            	expected: 0
            	            	actual  : 2
```

This is a one node cluster, it happens to be red for a very short amount of time when the node is starting:

```
{"type": "server", "timestamp": "2019-09-18T18:06:50,518+0000", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "test-mutation-resize-mem-down-8nsh", "node.name": "test-mutation-resize-mem-down-8nsh-es-masterdata-0", "cluster.uuid": "LT2UZs_bRWOLEnCnXWlyNw", "node.id": "SpZCjxgUQmSh5zGo2vctYQ",
 "message": "Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[data-integrity-check][43]] ...])."  }
```

I'm not sure that you should expect 0 failure here: https://github.com/elastic/cloud-on-k8s/blob/master/test/e2e/test/elasticsearch/steps_mutation.go#L82
I think we should tolerate a few errors during a short period of time, at least when there's only one node and the red status seems unavoidable.

**Comment by barkbay** [comment]
It turns out that I hit this one because I changed some settings in the `DataIntegrityCheck`

I would be tempted to close this one as it is unlikely to happen on the CI given the few number of document created.
But it means that this test is passing on our CI because of the timing, not really because it is relevant.

**Comment by barkbay** [comment]
We had this one on the CI: https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-stack/detail/cloud-on-k8s-stack/37/pipeline/25

```
[2019-09-25T15:46:08.578Z]     --- PASS: TestMutationResizeMemoryDown/Master_change_budget_must_not_have_been_exceeded (0.00s)
[2019-09-25T15:46:08.578Z]     --- FAIL: TestMutationResizeMemoryDown/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process (0.00s)
[2019-09-25T15:46:08.578Z]         steps_mutation.go:85: 
[2019-09-25T15:46:08.578Z]             	Error Trace:	steps_mutation.go:85
[2019-09-25T15:46:08.578Z]             	Error:      	Not equal: 
[2019-09-25T15:46:08.578Z]             	            	expected: 0
[2019-09-25T15:46:08.578Z]             	            	actual  : 1
[2019-09-25T15:46:08.578Z]             	Test:       	TestMutationResizeMemoryDown/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process
[2019-09-25T15:46:08.578Z]         steps_mutation.go:87: Elasticsearch cluster health check failure at 2019-09-25 15:46:05.78884578 +0000 UTC m=+1866.576638256: cluster health red
```

**Comment by sebgl** [comment]
This test spins up a 1-node cluster and does a rolling upgrade. While shards initialize after the upgrade, the cluster health turns red, which is expected.

We can either:
1. change the cluster health test to not consider 1-node clusters
2. change this test to deploy more than 1 node

I tend to think the 2nd option is better: it takes more time but it also checks we correctly handle rolling upgrades when downscaling nodes.

**Comment by barkbay** [comment]
I think the problem is that we have some other tests with a single node: TestVersionUpgradeSingle680To720 or TestVersionUpgradeSingle710To720
And I think it makes sense to have some tests with only one node.

**Comment by sebgl** [comment]
> I think the problem is that we have some other tests with a single node: TestVersionUpgradeSingle680To720 or TestVersionUpgradeSingle710To720

Indeed! Missed those. So I guess it makes sense to modify the cluster health check to discard red health "errors" for one-node clusters?

I think #1803 still makes sense: in most rolling upgrades scenarios we probably want to test clusters with more than 1 node, for which we want to ensure no disruption. Which does not prevent from having other tests with only one node as you pointed out.
