### ISSUE TITLE
Add a new section about node orchestration (StatefulSet related)

### ISSUE THREAD

**Issue by alaudazzi** [elastic/cloud-on-k8s#1758]
This issue is to create a new section about node orchestration (or cluster upgrade), containing the following subsections:

- How to upgrade your cluster
- How to orchestrate the topology changes (#1144)
- Implementation details (about StatefulSet)
- Limitations linked to the upgrade
       - rename a group of nodes
       - change the disk size

Relates to #1734

**Comment by sebgl** [comment]
I'll start working on it.
