### ISSUE TITLE
Re-enable API reference generation

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#1771]
Parent issue https://github.com/elastic/cloud-on-k8s/issues/1188

As part of moving to kubebuilder v2 in https://github.com/elastic/cloud-on-k8s/pull/1723, reference API documentation generation was disabled as the last tagged release was not compatible with go modules. We should re-enable it.

**Comment by charith-elastic** [comment]
There's an open issue in the upstream repo to support Kubebuilder v2: https://github.com/ahmetb/gen-crd-api-reference-docs/issues/15
