### ISSUE TITLE
Update PDB instead of delete + create on k8s > 1.15

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1773]
PDB resources are immutable before k8s 1.15: they cannot be updated. Hence, when an update is required, we perform a deletion, then a creation. Which leaves us with a small time window where there is no PDB anymore.

We can't really do better for k8s<1.15, but if we can detect we're running on a 1.15+ cluster, we can optimize by doing an update instead, and reduce the risk of something going wrong during the update.

**Comment by pebrc** [comment]
We dropped support for k8s < 1.19 so removing this workaround is now a possibility.

**Comment by barkbay** [comment]
Should be fixed by https://github.com/elastic/cloud-on-k8s/pull/5709
