### ISSUE TITLE
Any plan to upgrade without migrate data?

### ISSUE THREAD

**Issue by yitian134** [elastic/cloud-on-k8s#1780]
In doc/elasticsearch-spec.asciidoc, noted
`It is possible to configure the changeBudget to optimize the reuse of persistent volumes, instead of migrating data across nodes. This feature is not supported yet, more details to come in the next release.`
We have a strong desire to this feature. Because data migrate is harmful for online serving.

When would you support this feature? Would you posted some design point? 
thanks

**Comment by barkbay** [comment]
Hi,

Persistent volume are reused by default in `master`, it will be part of an upcoming beta release that should be out in a few weeks.
