### ISSUE TITLE
Handle mixed v6/v7 rolling upgrade failure case

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1792]
Forking https://github.com/elastic/cloud-on-k8s/issues/1281#issuecomment-524768463 to a new issue.

The following corner case can happen when upgrading a cluster from v6 to v7:

- 3/5 nodes are upgraded
- the 2 remaining v6 nodes are disconnected from the cluster for whatever reason (eg. blame the network)
- as a result, a node in v7 becomes the new master
- the cluster is now using zen2, and not zen1
- the 2 v6 nodes will attempt to join the cluster again when they're back online, but will fail
- rolling upgrade will be stuck at this point, since the cluster may never become green (one of our pre-conditions to move on with the upgrade)

To handle that case, we probably need to still force-upgrade the remaining v6 nodes if we detect the cluster is using zen2 already.

**Comment by david-kow** [comment]
Duplicate of #1644?

**Comment by sebgl** [comment]
Indeed there are very similar. I'll close this one, post OP in https://github.com/elastic/cloud-on-k8s/issues/1644, and rename https://github.com/elastic/cloud-on-k8s/issues/1644 to something more generic.
