### ISSUE TITLE
_cat/shards does not (only) returns the node name

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1796]
Looking at the source code of Elasticsearch:

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/rest/action/cat/RestShardsAction.java#L246-L256

When a shard is relocating the `"node"` field does not only contains the name of the node.

Here is an example:

```
[{
	"index": "data-integrity-check",
	"shard": "1",
	"state": "RELOCATING",
	"node": "test-mutation-less-nodes-sqn9-es-masterdata-1 -> 10.56.2.33 8DqGuLtrSNyMfE2EfKNDgg test-mutation-less-nodes-sqn9-es-masterdata-0"
}, {
	"index": "data-integrity-check",
	"shard": "2",
	"state": "RELOCATING",
	"node": "test-mutation-less-nodes-sqn9-es-masterdata-2 -> 10.56.2.33 8DqGuLtrSNyMfE2EfKNDgg test-mutation-less-nodes-sqn9-es-masterdata-0"
}, {
	"index": "data-integrity-check",
	"shard": "0",
	"state": "STARTED",
	"node": "test-mutation-less-nodes-sqn9-es-masterdata-0"
}]
```

I think this is the new root cause of #1750

**Comment by barkbay** [comment]
copy/pasting a discussion with @DaveCTurner :

> I think you have to ask the node itself - even if it has no shards allocated it might still be serving a scroll that would fail if you shut it down
> something like GET /_nodes/node-0/stats/indices and check for zeroes in all the right places, but I can’t say exactly what all those places are

**Comment by barkbay** [comment]
`GET /_stats/docs?level=shards` does not return the name of the nodes, it means that it would require an other API call to get the mapping between the node ids and the name of the nodes:

```json
      "shards" : {
        "0" : [
          {
            "routing" : {
              "state" : "STARTED",
              "primary" : false,
              "node" : "ntwAF7N7TBWyK7bKBGOSuQ",
              "relocating_node" : null
            },
```

Here is a full sample output: https://gist.github.com/barkbay/92bad4568940857dfed607f11e042b2a

**Comment by barkbay** [comment]
I think I will stick with `cat/shards` and add a dirty hack to retrieve the name of the node in the `node` field. But I think we should discuss with the Elasticsearch team to have a stable and more suitable API in the future.

I'm not sure we want to check if the node is serving a scroll from an "open but not assigned" shard, it sounds like an optimization we can discuss later.

wdyt ?

**Comment by sebgl** [comment]
+1 with doing whatever's simpler now, and optimise later if need to.

Parsing the output of `_cat/shards` sounds like the simpler solution now.
Parsing other/multiple APIs, and handling open scrolls sound like 2 optimisations for later. Which are just "internal" optimization (no impact on the users, ie. easy to change).

**Comment by pebrc** [comment]
I agree. Let's use `_cat/shards` for now and as @sebgl said, everything else is a API-neutral optimisation we can do later.
