### ISSUE TITLE
Remove `Kind()` funcs

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#1831]
Related to https://github.com/elastic/cloud-on-k8s/issues/338

Since we upgraded to kubebuilder v2 I think we can remove the extra `Kind` funcs on our CR types that we added to work around the behavior.

Upstream issue: https://github.com/kubernetes-sigs/controller-runtime/issues/406

**Comment by anyasabo** [comment]
Would definitely welcome a PR @racevedoo  :)

**Comment by racevedoo** [comment]
PR opened #1837
