### ISSUE TITLE
TLS best practices?

### ISSUE THREAD

**Issue by ejsmith** [elastic/cloud-on-k8s#1835]
Sorry for asking a question here. Not sure where else to ask.

From digging through the code it seems like you are creating a self-signed certificate and automatically renewing it. That is great and seems like I should probably just leave that alone instead of trying to create my own CA and certificate and then having to manage the process of renewing it.

My question is, how would I go about trusting the ES certificate that you generated from other docker images? I'm guessing that I need to grab the certificate from a secret somewhere and then install it on the docker image somehow. Could you please provide some hints on how this whole process would work and what the best practices are?

**Comment by anyasabo** [comment]
Hey @ejsmith , this is documented here if you didn't see it:
https://github.com/elastic/cloud-on-k8s/blob/master/docs/accessing-services.asciidoc#tls-certificates

But if that doesn't answer your question, or if you have suggestions on how to lay it out to make it more discoverable please let us know

**Comment by ejsmith** [comment]
Yes, that is very helpful. Not really sure how I missed that. Sorry for wasting your time.
