### ISSUE TITLE
Make ECK requirements more explicit in the documentation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1858]
We mention that you have to run k8s > 1.11 in the quickstart guide, but maybe it would be helpful to document that in a more prominent place (Overview, maybe or dedicated page) basically replicating what we have in the README for this repo at the moment (supported stack versions + supported k8s versions)

**Comment by agup006** [comment]
@pebrc, ++ to docs that go over this, for more detailed view we can add to the following page: https://www.elastic.co/support/matrix

**Comment by alaudazzi** [comment]
@pebrc do you refer to https://github.com/elastic/cloud-on-k8s/blob/master/README.md?
