### ISSUE TITLE
Upload and document usage of different all-in-one flavors

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#1876]
https://github.com/elastic/cloud-on-k8s/pull/1852 introduced the building of more than one `all-in-one` bundles. This was done to best support different K8s versions (e.g 1.14 and later can have more apiserver-side validation on custom resource definitions with multiple versions).

This means that for K8s <= 1.13, users will have to install the `trivial-versions` flavor.

We need to:

- [x] Upload multiple flavors from CI release jobs (#1904).
- [x] Point users to the correct flavor for their K8s cluster version (#1959).
- [ ] Document what the flavors are.

**Comment by artemnikitin** [comment]
@nkvoll Am I correctly understand, that all CRD flavors will be generated during `make generate` and from CI we simply need to upload them? Or we also need to generate missing flavors too?

**Comment by alaudazzi** [comment]
@nkvoll  which documentation pages are impacted by this issue?

**Comment by thbkrkr** [comment]
> @nkvoll which documentation pages are impacted by this issue?

Regarding "Point users to the correct flavor for their K8s cluster version.", all the pages that reference the `all-in-one.yaml`. For the moment, I see:
- https://www.elastic.co/downloads/elastic-cloud-on-kubernetes
- https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html

Regarding "Document what the flavors are.", we need to choose if we create a new page or update an existing one.

**Comment by thbkrkr** [comment]
Closed in #1904 and #1959.
