### ISSUE TITLE
Unified e2e test job

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#1892]
Instead of having several jobs for e2e tests (3 at the moment and potentially more) we can have just 1 e2e test job which can run all type of tests. 

Job should:
1) Run test against both operator built from master and from externally provided image.
2) Run tests on all supported cloud K8s services

**Comment by pebrc** [comment]
We have continued to build out the single job pattern. Also I am not sure what the benefit of a single job would be. The single jobs allow us to run tests against just one cloud provider if desired while a single job would be all or nothing? 

I am closing this for now, let's reopen if we want to reconsider.
