### ISSUE TITLE
Pod deletion during forced upgrade should include resource version precondition check

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1916]
This will allow for a safer delete pod operation in case of race condition where we could be trying to delete a pod that is no longer Pending.

**Comment by anyasabo** [comment]
I'm +1 for this. Do you think just for forced upgrades or any time we delete a pod? My inclination is only for forced upgrades

**Comment by david-kow** [comment]
> Do you think just for forced upgrades or any time we delete a pod? My inclination is only for forced upgrades

I think in other (happy path) case we don't care whether it's pending or not when we remove it, so I'd say yes, only for forced upgrades.
