### ISSUE TITLE
Revisit OpenShift docs

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#1934]
With the change to recommending mmap be disabled for the quickstart we should update the openshift docs accordingly

**Comment by thbkrkr** [comment]
I think #1839 covered this.

https://github.com/elastic/cloud-on-k8s/blob/383f59e64f2bf81dae874a108441eadefe223626/docs/openshift.asciidoc#L97

Did you think of something else?

**Comment by anyasabo** [comment]
I meant primarily #2 here:
https://github.com/elastic/cloud-on-k8s/blob/383f59e64f2bf81dae874a108441eadefe223626/docs/openshift.asciidoc#before-you-begin
