### ISSUE TITLE
Current state of custom elastic-search images/ offline usage?

### ISSUE THREAD

**Issue by DJDANNY123** [elastic/cloud-on-k8s#1947]
## Bug Report
**What did you do?**

Installed the elastic operator on offline kubernetes cluster and attempted to install custom image using old documentation from git history (has this feature been removed, despite recommended in recent documentation?)

Used the following definition to start a cluster:
```apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  image: <custom-image-repo>/elasticsearch:6.2.4
  version: 6.2.4
  nodes:
    - nodeCount: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
```

**What did you expect to see?**

Healthy elasticsearch cluster with one node and a given state

**What did you see instead? Under which circumstances?**

NAME             HEALTH   NODES   VERSION   PHASE   AGE
quickstart                                      6.2.4                      10m

**Environment**

* ECK version:
Attempting to use "custom image" of 6.2.4 (identical to default 6.2.4, but hosted on private docker registry)
	insert version or git commit id here

* Kubernetes information:
On premise offline/air-gapped Kubernetes cluster, with Istio 1.2.3 deployed
	
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by barkbay** [comment]
As stated in the [README](https://github.com/elastic/cloud-on-k8s/blob/master/README.md) for Elasticsearch 6.x only 6.8.0 and above are supported.
Feel free to reopen if there's still a problem with the private registry but it should work with ES 6.8.
