### ISSUE TITLE
Clean test output for gotestsum

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#1967]
Side effect of #1962:

```
14:42:38  gotestsum: Error: failed to parse test output: rpc error: code = Unknown desc = Error: 
  No such container: 385257478d2fb705cb510d7e30f30640450cdcaa98ba2a021b0816eb4dc6202d: 
  invalid character 'r' looking for beginning of value
14:42:38  Makefile:369: recipe for target 'e2e-generate-xml' failed
```
https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/86/execution/node/84/log/

It looks like the test output can be composed of non-test inputs and needs to be cleaned before being passed to gotestsum.

**Comment by anyasabo** [comment]
I didn't repro it but I didn't see that error in gotestsum directly, it looks like an error that json.Unmarshal returns:

https://github.com/gotestyourself/gotestsum/blob/master/testjson/execution.go#L383
