### ISSUE TITLE
Fix cluster UUID race condition during bootstrap

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1975]
There seem to be a race condition during cluster bootstrap.

When ES is started, but not yet bootstrapped, the http endpoint is available and responds with cluster UUID `_na_` (see first note in this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html)). We use that to populate ES CRDs clusteruuid annotation which is used to check whether cluster is already bootstrapped. When we think it is bootstrapped, we don't set `initial_master_nodes` that is required for the cluster to really bootstrap:

```
master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node
```

 This leaves the cluster in permanently broken state.

When deciding whether the cluster is bootstrapped we should also check if uuid is not `_na_`.

**Comment by pebrc** [comment]
Well spotted, we actually check for that in the e2e tests:
https://github.com/elastic/cloud-on-k8s/blob/25caaf104217d387f47e4d588b0550476c7c4957/test/e2e/test/elasticsearch/cluster_uuid.go#L42

But did not take it into consideration in the bootstrap detection :-(
