### ISSUE TITLE
Version upgrade might get stuck if new index is created

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1993]
* Upgrade to newer Elasticsearch version with breaking Lucene change
* Create new index with at least one replica, make sure it is allocated on node with newer version
* Replica cannot be created on remaining nodes b/c of incompatible Lucene version
* Cluster health is now yellow
* Upgrade cannot proceed

**Comment by david-kow** [comment]
https://github.com/elastic/cloud-on-k8s/issues/1643 seems related.

**Comment by pebrc** [comment]
@david-kow oh you are right, my seems almost like a duplicate. I did not remember that you had mentioned 'internal representation changes' which a Lucene version difference would constitute

**Comment by barkbay** [comment]
Fixed by #2330
