### ISSUE TITLE
Investigate if it's possible to get or generate URL for failed test in Jenkins

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#2010]
Can we obtain or generate URl to failed test like https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/493/testReport/github/com_elastic_cloud-on-k8s_test_e2e_es/TestMutationMdiToDedicated_All_expected_Pods_should_eventually_be_ready_01/?

At the moment, it looks like there is no out-of-the-box way of doing this.

**Comment by pebrc** [comment]
Closing this for now.
