### ISSUE TITLE
Test operator behavior after failover

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2012]
As a stateless service we expect the operator to be resilient to downtime, but we don't currently test for it. We should at least have a sanity test around correctness of what operator is doing when being randomly restarted. Somewhat related to general chaos testing.

**Comment by anyasabo** [comment]
Related: https://github.com/elastic/cloud-on-k8s/issues/709

**Comment by david-kow** [comment]
We should create a separate test pipeline where we would randomly delete the operator pod while the entire E2E test suite is running. This way we don't introduce noise into existing pipelines and we have a good coverage of different test scenarios. We should log and preserve timestamps when the operator pod is being removed for potential issues investigation.

**Comment by barkbay** [comment]
Fixed by #3706
