### ISSUE TITLE
Introduce availability testing to e2e tests

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2013]
While we do check for cluster health and correct pod count we don't try to continuously hit ES endpoints. Doing that (especially at high rate) would increase our confidence about the safety of the updates/topology changes that the operator is doing. It would also help to detect and asses severity of issues like #1927 (this might be even prerequisite for a fix to that particular issue).

**Comment by pebrc** [comment]
IIUC https://github.com/elastic/cloud-on-k8s/blob/5375865666c37f4c2f55e1b607211d8976b45f08/test/e2e/es/mutation_test.go#L244 covers that. It should be noted that in practice we did run into occasional unavailability during testing which we were not able to fully explain. Currently those test run therefore while allowing up to 5 failed connection attempts. 

We are tracking this problem in https://github.com/elastic/cloud-on-k8s/issues/5659
