### ISSUE TITLE
Enable native realm in addition to the file realm

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2037]
It seems that the native realm is only enabled by default if no other realms have been defined. In #1698 we explicitly enabled the file realm -- which results in the native realm getting disabled and preventing users from authenticating using the credentials they create using the UI. See #2036.

**Comment by eedugon** [comment]
For reference purposes, there's a valid workaround explained here:
https://discuss.elastic.co/t/new-user-cant-login-kibana/204810/2

It consists of explicitly enabling the native realm.

**Comment by ransoor2** [comment]
I did the workaround. Now I'm able to log in, but I get "Error in visualization [esaggs] > Internal Server Error" when trying to access Kibana dashboards.
Elastic version 7.4.2
![elastic](https://user-images.githubusercontent.com/38324610/69161026-2c03d200-0af3-11ea-8056-5bca491f40e8.PNG)

**Comment by sebgl** [comment]
@ransoor2 this looks unrelated to the native realm issue. Please check both Kibana and Elasticsearch logs and create a new issue or [discuss topic](https://discuss.elastic.co/c/eckhttps://discuss.elastic.co/c/eck) where appropriate.
