### ISSUE TITLE
1.0.0-beta1 Cannot log in after creating a user in kibana

### ISSUE THREAD

**Issue by andy199** [elastic/cloud-on-k8s#2045]
After the user is created in kibana, I can't log in. Is there any way to solve it, or need those roles?

 
![1571793912(1)](https://user-images.githubusercontent.com/12758575/67348312-14c6d880-f577-11e9-941c-fa6ca75a26f4.png)
![2](https://user-images.githubusercontent.com/12758575/67348353-3627c480-f577-11e9-9580-d5daa0cf4d99.png)

**Comment by charith-elastic** [comment]
Hi, this is a known issue that we have already fixed in master. You can work around for the time being 
 by enabling the native realm as described here: https://github.com/elastic/cloud-on-k8s/issues/2036#issuecomment-544838578
