### ISSUE TITLE
Use filebeta to report the following certificate error, how to turn off https and use http

### ISSUE THREAD

**Issue by andy199** [elastic/cloud-on-k8s#2046]
2019-10-23T10:54:14.539Z    INFO    log/harvester.go:251    Harvester started for file: /var/log/containers/zok-2_kube-ops_kubernetes-zookeeper │
│ -17d9449e1e44488172e8fa37adbbbebf7db1f9d2dfa2f1f4eac4fa323d1960ef.log                                                                           │
│ 2019-10-23T10:54:14.610Z    INFO    pipeline/output.go:95    Connecting to backoff(elasticsearch(https://elastic-es-http.elastic-system:9200))  │
│ 2019-10-23T10:54:15.791Z    ERROR    pipeline/output.go:100    Failed to connect to backoff(elasticsearch(https://elastic-es-http.elastic-syste │
│ m:9200)): Get https://elastic-es-http.elastic-system:9200: x509: certificate signed by unknown authority                                        │
│ 2019-10-23T10:54:15.791Z    INFO    pipeline/output.go:93    Attempting to reconnect to backoff(elasticsearch(https://elastic-es-http.elastic-s │
│ ystem:9200)) with 1 reconnect attempt(s)                                                                                                        │
│ 2019-10-23T10:54:18.614Z    ERROR    pipeline/output.go:100    Failed to connect to backoff(elasticsearch(https://elastic-es-http.elastic-syste │
│ m:9200)): Get https://elastic-es-http.elastic-system:9200: x509: certificate signed by unknown authority                                        │
│ 2019-10-23T10:54:18.614Z    INFO    pipeline/output.go:93    Attempting to reconnect to backoff(elasticsearch(https://elastic-es-http.elastic-s │
│ ystem:9200)) with 2 reconnect attempt(s)                                                                                                        │
│ 2019-10-23T10:54:24.005Z    ERROR    pipeline/output.go:100    Failed to connect to backoff(elasticsearch(https://elastic-es-http.elastic-syste │
│ m:9200)): Get https://elastic-es-http.elastic-system:9200: x509: certificate signed by unknown authority                                        │
│ 2019-10-23T10:54:24.005Z    INFO    pipeline/output.go:93    Attempting to reconnect to backoff(elasticsearch(https://elastic-es-http.elastic-s │
│ ystem:9200)) with 3 reconnect attempt(s)                                                                                                        │
│ 2019-10-23T10:54:24.005Z    INFO    [publisher]    pipeline/retry.go:166    retryer: send wait signal to consumer                               │
│ 2019-10-23T10:54:24.005Z    INFO    [publisher]    pipeline/retry.go:168      done                                                              │
│ 2019-10-23T10:54:39.070Z    ERROR    pipeline/output.go:100    Failed to connect to backoff(elasticsearch(https://elastic-es-http.elastic-syste │
│ m:9200)): Get https://elastic-es-http.elastic-system:9200: x509: certificate signed by unknown authority                                        │
│ 2019-10-23T10:54:39.070Z    INFO    pipeline/output.go:93    Attempting to reconnect to backoff(elasticsearch(https://elastic-es-http.elastic-s │
│ ystem:9200)) with 4 reconnect attempt(s)                                                                                                        │
│ 2019-10-23T10:54:39.070Z    INFO    [publisher]    pipeline/retry.go:189    retryer: send unwait-signal to consumer                             │
│ 2019-10-23T10:54:39.070Z    INFO    [publisher]    pipeline/retry.go:191      done                                                              │
│ 2019-10-23T10:54:39.070Z    INFO    [publisher]    pipeline/retry.go:166    retryer: send wait signal to consumer                               │
│ 2019-10-23T10:54:39.070Z    INFO    [publisher]    pipeline/retry.go:168      done                                                              │
│ 2019-10-23T10:54:41.535Z    INFO    [monitoring]    log/log.go:145    Non-zero metrics in the last 30s    {"monitoring": {"metrics": {"beat":{" │
│ cpu":{"system":{"ticks":150,"time":{"ms":155}},"total":{"ticks":510,"time":{"ms":521},"value":510},"user":{"ticks":360,"time":{"ms":366}}},"han │
│ dles":{"limit":{"hard":1048576,"soft":1048576},"open":30},"info":{"ephemeral_id":"892ca995-f9d5-4632-82de-fa5583d80f70","uptime":{"ms":30034}}, │
│ "memstats":{"gc_next":53234224,"memory_alloc":27228408,"memory_total":67310928,"rss":65638400},"runtime":{"goroutines":121}},"filebeat":{"event │
│ s":{"active":4143,"added":4156,"done":13},"harvester":{"open_files":22,"running":22,"started":22}},"libbeat":{"config":{"module":{"running":0}} │
│ ,"output":{"type":"elasticsearch"},"pipeline":{"clients":1,"events":{"active":4117,"filtered":34,"published":4116,"retry":100,"total":4151}}}," │
│ registrar":{"states":{"current":12,"update":13},"writes":{"success":13,"total":13}},"system":{"cpu":{"cores":4},"load":{"1":0.16,"15":0.07,"5": │
│ 0.1,"norm":{"1":0.04,"15":0.0175,"5":0.025}}}}}}

**Comment by pebrc** [comment]
See https://github.com/elastic/cloud-on-k8s/pull/2041 for an example beats setup.
