### ISSUE TITLE
Can ECK support master/data structure?

### ISSUE THREAD

**Issue by ximenzaoshi** [elastic/cloud-on-k8s#2079]
In a cluster, we have three master-only nodes, and the left are data nodes. Can ECK support this?

**Comment by sebgl** [comment]
Yes, [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-define-elasticsearch-nodes-roles) is a doc snippet for a cluster with 3 dedicated master nodes.
