### ISSUE TITLE
 Is there rollback operation for change failure  ? 

### ISSUE THREAD

**Issue by FANLIYANG-OPS** [elastic/cloud-on-k8s#2091]
Is there rollback operation for change failure

**Comment by FANLIYANG-OPS** [comment]
hey @sebgl  Does this feature not exist in the current version ? ECK

**Comment by sebgl** [comment]
No, it does not exist in the current version.
As I said earlier, you can still re-apply the previous yaml manifest so ECK re-transforms your cluster to its previous configuration.

Do you have a particular use case or problem in mind?

**Comment by FANLIYANG-OPS** [comment]
Thank you. I'm developing the rollback function. I want to find some references here ; @sebelga
