### ISSUE TITLE
Allow unsafe rolling upgrades if specified by the user

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2092]
Currently we make sure the cluster has a green health before moving on with rolling upgrades.
There are cases where the cluster cannot be green:

* because there is a single node in the cluster, and it has indices with 1 replica (default).
* because there is a problem with some shards, from which we won't recover

In these situations it could make sense to "force" the upgrade, even though it may cause unavailability on the cluster (and a risk of data loss). At the user's own risks, basically. It could be expressed through a particular field in the `updateStrategy` of the Elasticsearch manifest.

**Comment by anyasabo** [comment]
```
updateStrategy:
    YOLO: true
```
? 😄 

It seems challenging to evaluate situations where the cluster will never be green. It seems okay to not support these configurations? If it is configured with one node then indices could be configured with 0 replicas (not the default, but then neither is one node) if I understand correctly.

**Comment by jasper-d** [comment]
We use single node clusters (1 master, 1 data) in some testing/integration environments to save resources. Availability isn't really a concern there, but upgrades are currently stuck because the cluster is never green. Having the option to ignore the upgrade predicates in such environments would really help.

**Comment by ZackMattor** [comment]
For wary travelers who may end up here - it will successfully update if you just delete the existing pod for Elasticsearch :) 

Note that this will take down the cluster if it's the only node in the cluster.
