### ISSUE TITLE
Support init container to install Kibana plugins

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2123]
We already support installing plugins for Elasticsearch with init containers.

Should we do the same for Kibana?

**Comment by pebrc** [comment]
One thing to keep in mind when introducing support for this is that Kibana does an `optimize` run after removing plugins https://www.elastic.co/guide/en/kibana/current/update-remove-plugin.html which leads to a spike in resource usage and can prevent a Kibana instance from starting up if users run it with tight resource limits/requests

**Comment by thbkrkr** [comment]
Good point. This seems to be a good reason to promote the use of a Kibana custom image rather than the use of init containers to install plugins. I think that is still relevant but with a low priority.

**Comment by thbkrkr** [comment]
Closing because due to the `optimize` phase, the custom image is the way to go.
