### ISSUE TITLE
Stack versions e2e test failing since Oct 14th

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2133]
https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-stack/

**Comment by thbkrkr** [comment]
I went through to the last 12 builds. 2 of them were succesful! So it's not completely broken :)

Here is a summary of "interesting" failures:
- 3x Cluster_UUID_should_have_been_preserved (#1927)
- 2x the init fs container took a lot of time to wait the certificates.
- 1x pulling Elasticsearch image took a lot of time
- 1x LOCAL_SSD_TOTAL_GB quota reached
- 1x ? TestDeleteServices/ES_services_should_have_endpoints
- 1x ? TestMutationSecondMasterSet/Master_change_budget_must_not_have_been_exceeded
- 1x ? TestUpdateKibanaSecureSettings/Delete_secure_settings_secret

What do we do with that?
I suggest to close this issue and open separate issue for each failure?

--

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/103/

#### SSD quota error

```
[2019-11-28T11:19:37.739Z] ERROR: (gcloud.beta.container.clusters.create) 
ResponseError: code=403, message=Insufficient regional quota to satisfy request:
 resource "LOCAL_SSD_TOTAL_GB": request requires '1125.0' and is short '375.0'. 
 project has a quota of '30000.0' with '750.0' available. 
 View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project=****.
```
https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-stack/detail/cloud-on-k8s-stack/103/pipeline/35

#### [2019-11-28T12:41:28.668Z]     --- FAIL: TestMutationSecondMasterSet/Master_change_budget_must_not_have_been_exceeded (0.00s)

```
[2019-11-28T12:41:28.668Z]     --- FAIL: TestMutationSecondMasterSet/Master_change_budget_must_not_have_been_exceeded (0.00s)
[2019-11-28T12:41:28.668Z]         steps_mutation.go:104: 
[2019-11-28T12:41:28.668Z]             	Error Trace:	steps_mutation.go:104
[2019-11-28T12:41:28.668Z]             	Error:      	Received unexpected error:
[2019-11-28T12:41:28.668Z]             	            	2 master changes in one observation, expected max 1
[2019-11-28T12:41:28.668Z]             	Test:       	TestMutationSecondMasterSet/Master_change_budget_must_not_have_been_exceeded
```

???

#### [2019-11-28T12:53:05.467Z]     --- FAIL: TestMutationNodeSetReplacementWithChangeBudget/All_expected_Pods_should_eventually_be_ready#01 (300.00s)

initContainers{elastic-internal-init-filesystem} of test-1-change-budget-hk2d-es-data2-4 took 134 sec.

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/102/

#### [2019-11-28T10:15:53.071Z]     --- FAIL: TestMutationLessNodes/Cluster_UUID_should_have_been_preserved (18.61s)

```
[2019-11-28T10:15:53.071Z]     --- FAIL: TestMutationLessNodes/Cluster_UUID_should_have_been_preserved (18.61s)
[2019-11-28T10:15:53.071Z]         cluster_uuid.go:58: 
[2019-11-28T10:15:53.071Z]             	Error Trace:	cluster_uuid.go:58
[2019-11-28T10:15:53.071Z]             	Error:      	Received unexpected error:
[2019-11-28T10:15:53.071Z]             	            	Get https://test-mutation-less-nodes-g7q2-es-http.e2e-xdr26-mercury.svc:9200/: dial tcp 10.71.245.81:9200: connect: no route to host
```

#1927

#### [2019-11-28T10:28:58.753Z]     --- FAIL: TestMutationSecondMasterSetDown/All_expected_Pods_should_eventually_be_ready#01 (300.00s)

```
[2019-11-28T10:28:58.753Z]     --- FAIL: TestMutationSecondMasterSetDown/All_expected_Pods_should_eventually_be_ready#01 (300.00s)
[2019-11-28T10:28:58.753Z]         utils.go:80: 
[2019-11-28T10:28:58.753Z]             	Error Trace:	utils.go:80
[2019-11-28T10:28:58.753Z]             	Error:      	Received unexpected error:
[2019-11-28T10:28:58.753Z]             	            	invalid StatefulSets: expected map[test-mutation-2nd-master-set-wm9x-es-masterdata:1], got map[test-mutation-2nd-master-set-wm9x-es-master:1 test-mutation-2nd-master-set-wm9x-es-masterdata:1]
[2019-11-28T10:28:58.753Z]             	Test:       	TestMutationSecondMasterSetDown/All_expected_Pods_should_eventually_be_ready#01
```

???

I don't know what caused this. It seems that the `test-mutation-2nd-master-set-wm9x-es-master-1` pod deletion never happened after the pod was killed.

```
{"t":"2019-11-28T10:21:33Z","m":"Requested topology change delayed by data migration","n":"test-mutation-2nd-master-set-wm9x","z":null,"k":"event"}
{"t":"2019-11-28T10:21:34Z","m":"delete Pod test-mutation-2nd-master-set-wm9x-es-masterdata-1 in StatefulSet test-mutation-2nd-master-set-wm9x-es-masterdata successful","n":"test-mutation-2nd-master-set-wm9x-es-masterdata","z":null,"k":"event"}
{"t":"2019-11-28T10:21:35Z","m":"Killing container with id docker://elasticsearch:Need to kill Pod","n":"test-mutation-2nd-master-set-wm9x-es-masterdata-1","z":"spec.containers{elasticsearch}","k":"event"}
{"t":"2019-11-28T10:22:31Z","m":"delete Pod test-mutation-2nd-master-set-wm9x-es-master-2 in StatefulSet test-mutation-2nd-master-set-wm9x-es-master successful","n":"test-mutation-2nd-master-set-wm9x-es-master","z":null,"k":"event"}
{"t":"2019-11-28T10:22:31Z","m":"Killing container with id docker://elasticsearch:Need to kill Pod","n":"test-mutation-2nd-master-set-wm9x-es-master-2","z":"spec.containers{elasticsearch}","k":"event"}
{"t":"2019-11-28T10:23:25Z","m":"delete Pod test-mutation-2nd-master-set-wm9x-es-master-1 in StatefulSet test-mutation-2nd-master-set-wm9x-es-master successful","n":"test-mutation-2nd-master-set-wm9x-es-master","z":null,"k":"event"}
{"t":"2019-11-28T10:23:25Z","m":"Killing container with id docker://elasticsearch:Need to kill Pod","n":"test-mutation-2nd-master-set-wm9x-es-master-1","z":"spec.containers{elasticsearch}","k":"event"}
{"t":"2019-11-28T10:26:08Z","m":"Could not update cluster license: 503 Service Unavailable: ","n":"test-mutation-2nd-master-set-wm9x","z":null,"k":"event"}
```

#### [2019-11-28T10:41:52.427Z]     --- FAIL: TestMutationNodeSetReplacementWithChangeBudget/All_expected_Pods_should_eventually_be_ready#01 (300.00s)

initContainers{elastic-internal-init-filesystem} of test-1-change-budget-nvrf-es-data2-4 took 132 sec.

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/101/

#### [2019-11-28T01:01:15.202Z]     --- FAIL: TestDeleteServices/ES_services_should_have_endpoints#01 (300.00s)

```
    --- FAIL: TestDeleteServices/ES_services_should_have_endpoints#01 (300.00s)
        utils.go:80: 
            	Error Trace:	utils.go:80
            	Error:      	Received unexpected error:
            	            	endpoints "test-failure-delete-services-5qgz-es-http" not found
            	Test:       	TestDeleteServices/ES_services_should_have_endpoints#01
```

#1927

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/100/

Successful! :-)

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/99/

Successful! :-)

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/98/

#### [2019-11-26T01:41:13.894Z]     --- FAIL: TestMutationSecondMasterSetDown/Cluster_UUID_should_have_been_preserved (7.64s)

#1927

#### [2019-11-26T02:12:44.680Z]     --- FAIL: TestVersionUpgrade680To720/All_expected_Pods_should_eventually_be_ready (300.00s)

```
{"t":"2019-11-26T02:05:37Z","m":"pulling image \"docker.elastic.co/elasticsearch/elasticsearch:6.8.0\"","n":"test-version-up-3-680-to-720-75b6-es-masterdata-0","z":"spec.initContainers{elastic-internal-init-filesystem}"}
{"t":"2019-11-26T02:09:48Z","m":"Successfully pulled image \"docker.elastic.co/elasticsearch/elasticsearch:6.8.0\"","n":"test-version-up-3-680-to-720-75b6-es-masterdata-0","z":"spec.initContainers{elastic-internal-init-filesystem}"}

{"t":"2019-11-26T02:05:36Z","m":"pulling image \"docker.elastic.co/elasticsearch/elasticsearch:6.8.0\"","n":"test-version-up-3-680-to-720-75b6-es-masterdata-1","z":"spec.initContainers{elastic-internal-init-filesystem}"}
{"t":"2019-11-26T02:09:48Z","m":"Successfully pulled image \"docker.elastic.co/elasticsearch/elasticsearch:6.8.0\"","n":"test-version-up-3-680-to-720-75b6-es-masterdata-1","z":"spec.initContainers{elastic-internal-init-filesystem}"}

{"t":"2019-11-26T02:05:28Z","m":"pulling image \"docker.elastic.co/elasticsearch/elasticsearch:6.8.0\"","n":"test-version-up-3-680-to-720-75b6-es-masterdata-2","z":"spec.initContainers{elastic-internal-init-filesystem}"}
{"t":"2019-11-26T02:05:41Z","m":"Successfully pulled image \"docker.elastic.co/elasticsearch/elasticsearch:6.8.0\"","n":"test-version-up-3-680-to-720-75b6-es-masterdata-2","z":"spec.initContainers{elastic-internal-init-filesystem}"}
```

Pulling Elasticsearch image took 4min for pods masterdata-0 and masterdata-1 while it often took between 10s and 1min.

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/97/

#### [2019-11-25T02:32:59.064Z]     --- FAIL: TestUpdateKibanaSecureSettings/Delete_secure_settings_secret (0.00s)

```
    --- FAIL: TestUpdateKibanaSecureSettings/Delete_secure_settings_secret (0.00s)
        keystore_test.go:109: 
            	Error Trace:	keystore_test.go:109
            	Error:      	Received unexpected error:
            	            	secrets "secure-settings-secret" not found
            	Test:       	TestUpdateKibanaSecureSettings/Delete_secure_settings_secret
```

???

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/96/

#### [2019-11-23T15:12:29.218Z]     --- FAIL: TestMutationLessNodes/Cluster_UUID_should_have_been_preserved (18.64s)

#1927

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/95/

Already resolved issue that was related to a misconfiguration of the job for the E2E license test.

#### [2019-11-22T01:30:31.283Z]     --- FAIL: TestEnterpriseLicenseSingle/Elasticsearch_license_should_be_[gold_platinum] (300.00s)

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/94/

Same.

#### [2019-11-21T18:00:42.145Z]     --- FAIL: TestEnterpriseLicenseSingle/Elasticsearch_license_should_be_[gold_platinum] (300.00s)

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/93/

Same.

#### [2019-11-21T15:51:18.683Z]     --- FAIL: TestSamples/apm/apm_es_kibana (300.62s)

### Build https://devops-ci.elastic.co/job/cloud-on-k8s-stack/92/

Same.

#### [2019-11-21T15:27:23.953Z]     --- FAIL: TestSamples/apm/apm_es_kibana (300.67s)

**Comment by barkbay** [comment]
Build [110](https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-stack/detail/cloud-on-k8s-stack/110/pipeline/36)

7.2.1 and 7.3.2 failed but no dump has been generated.

Re the failure on 7.1.1:

```
[2019-12-03T01:59:10.348Z]     --- FAIL: TestMutationNodeSetReplacementWithChangeBudget/All_expected_Pods_should_eventually_be_ready#01 (300.00s)

[2019-12-03T01:59:10.348Z]         utils.go:80: 
[2019-12-03T01:59:10.348Z]             	Error Trace:	utils.go:80
[2019-12-03T01:59:10.348Z]             	Error:      	Received unexpected error:
[2019-12-03T01:59:10.348Z]             	            	pod test-1-change-budget-fhxm-es-data2-4 is not Ready.
```

* Timeout is at 1:56:39, which means that the test started at 1:51:39
* Pod has been assigned at 01:53:51
* Volume has been attached at 01:53:59
* Pod was ready during the build of the dump:

```
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2019-12-03T01:56:21Z",
                        "status": "True",
                        "type": "Initialized"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2019-12-03T01:56:40Z",
                        "status": "True",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2019-12-03T01:56:40Z",
                        "status": "True",
                        "type": "ContainersReady"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2019-12-03T01:53:51Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
                ],
```

Took 131 seconds to get the certs:
```
Starting init script
....
waiting for the transport certificates (/mnt/elastic-internal/transport-certificates/test-1-change-budget-fhxm-es-data2-4.tls.key)
wait duration: 131 sec.
....
Init script successful
Script duration: 131 sec.
```

ECK logs: 
```
{"level":"info","@timestamp":"2019-12-03T01:53:47.311Z","logger":"transport","message":"Skipping pod because it has no IP yet","ver":"1.0.0-beta1-3326d27d","namespace":"e2e-sr80l-mercury","pod_name":"test-1-change-budget-fhxm-es-data2-4"}
....
{"level":"info","@timestamp":"2019-12-03T01:54:05.121Z","logger":"transport","message":"Skipping pod because it has no IP yet","ver":"1.0.0-beta1-3326d27d","namespace":"e2e-sr80l-mercury","pod_name":"test-1-change-budget-fhxm-es-data2-4"}
...
{"level":"info","@timestamp":"2019-12-03T01:56:19.081Z","logger":"transport","message":"No tls certificate found in secret","ver":"1.0.0-beta1-3326d27d","namespace":"e2e-sr80l-mercury","pod_name":"test-1-change-budget-fhxm-es-data2-4"}
{"level":"info","@timestamp":"2019-12-03T01:56:19.081Z","logger":"transport","message":"Issuing new certificate","ver":"1.0.0-beta1-3326d27d","pod_name":"test-1-change-budget-fhxm-es-data2-4"}
```

**Comment by barkbay** [comment]
Roughly the same behaviour [for this one](https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-stack/detail/cloud-on-k8s-stack/113/pipeline/38), looks like everything is just slow :

```
 {"Time":"2019-12-05T01:22:58.32778843Z","  --- FAIL: TestUpdateESSecureSettings/Elasticsearch_secure_settings_should_eventually_be_set_in_all_nodes_keystore#03 (300.00s)\n"}
 {"Time":"2019-12-05T01:22:58.327798703Z",       utils.go:80: \n"}
 {"Time":"2019-12-05T01:22:58.327812996Z",           \tError Trace:\tutils.go:80\n"}
 {"Time":"2019-12-05T01:22:58.327821988Z",           \tError:      \tReceived unexpected error:\n"}
 {"Time":"2019-12-05T01:22:58.327846208Z",           \t            \tpod test-es-keystore-jdcv-es-masterdata-0 is not Ready.\n"}
```


According to the timestamps in the events:
* 2019-12-05T01:18:05Z masterdata-2 scheduled
* 2019-12-05T01:19:01Z masterdata-2 ready
* 2019-12-05T01:19:17Z masterdata-1 scheduled
* 2019-12-05T01:19:56Z masterdata-1 ready
* 2019-12-05T01:22:27Z masterdata-0 scheduled
* 2019-12-05T01:23:00Z masterdata-0 ready

It took more than 5 minutes for the 3 pods to be ready

**Comment by thbkrkr** [comment]
I close this because the job has been successful multiple times since the creation of this issue.
The next job failure should be created in a dedicated new issue.
