### ISSUE TITLE
Certmanager Let's Encrypt certificates not working in 1.0.0beta

### ISSUE THREAD

**Issue by psalaberria002** [elastic/cloud-on-k8s#2136]
## Bug Report
**What did you do?**
I upgraded from 0.9 to 1.0.0beta, and a custom TLS certificate stopped working due to a new feature added in https://github.com/elastic/cloud-on-k8s/pull/1742 (related to ca.crt). 

**What did you expect to see?**
Certificate should be loaded without issues by ES.

**What did you see instead? Under which circumstances?**
ES could not parse the certificate at boot. I suspect this is because certmanager sets ca.crt to an empty string. See https://github.com/jetstack/cert-manager/issues/1571 .

**Environment**

* ECK version:

	0.9 to 1.0.0beta

* Kubernetes information:
	* Cloud: GKE 1.13

**Comment by barkbay** [comment]
Yes you're right, even if `ca.crt` is empty the operator still considers that a certificate authority is provided.
I'm working on a workaround and a fix. Please could you tell me what is the content of the `tls.crt` field in the secret ? Is it just one certificate or a chain ?

**Comment by psalaberria002** [comment]
It's two certificates.
