### ISSUE TITLE
Downgrade to basic if user deletes license secret

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2146]
Should we revert all managed clusters to a basic license if a user decides to delete the license secret from the ECK installation. 

Currently we do nothing which means clusters stay on a platinum/enterprise license until that license reaches its expiry date, at which point the clusters go into degraded mode. 

We could instead, as soon as the license secret is deleted [revert to basic](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-basic.html) by calling 

```
POST /_license/start_basic?acknowledge=true
```

cc @agup006

**Comment by thbkrkr** [comment]
+1!

There is also the case where the license secret was created to enable the **trial** license 
and deleting the license secret would also be the way to revert from trial to basic. 

IMHO this seems pretty natural:
- default state is the basic license
- create the secret to enable a trial/entreprise license
- delete the secret to revert the license to basic

**Comment by pebrc** [comment]
Notes from discussions offline:

* check if removing the license can lead to bootlooping clusters
* kubectl: delete and create to update secret might have undesirable effects on the cluster (ie disruption of service, temporary unavailability of features)
* suggestion: only delete after a timeout of for example 15 minutes (in memory)

**Comment by pebrc** [comment]
> check if removing the license can lead to bootlooping clusters
Don't think this is the case, degradation seems graceful even with ML jobs running.

**Comment by pebrc** [comment]
After discussing the suggested timeout with @sebgl and @thbkrkr we realised that this feature is not necessary and just complicates the implementation unnecessarily:

For license replacement (i.e. user received a new license) we can just install the new license secret next to the existing license secret, just use a different name. ECK will pick the right one. Once the new license secret is created the user can delete the old one. No interruption or accidental downgrade of license should happen.

The removal of the timeout will not only make the code simpler, and facilitate e2e testing, it will also make the user experience better for the case where the user deliberately wants to delete the license secret (e.g. when aborting a trial and going back to basic) because the effect will be immediate.
