### ISSUE TITLE
Create OpenShift 4.x e2e testing environment

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2170]
We need an automated OpenShift 4.x environment to run our e2e tests on. The idea is to integrate the OpenShift installer with our existing deployer tooling to stand up an Openshift installation
* we need to be able to create and teardown these environments from Jenkins
* we would like to be able to do the same from a local machine for debugging and development purposes

**Comment by thbkrkr** [comment]
Looks like [Red Hat CodeReady Containers](https://developers.redhat.com/products/codeready-containers) might be an option to achieve that.

**Comment by barkbay** [comment]
> Looks like [Red Hat CodeReady Containers](https://developers.redhat.com/products/codeready-containers) might be an option to achieve that.

CodeReady is mostly for development:
> CodeReady Containers is designed for local development and testing on an OpenShift 4 cluster

I think that for e2e tests we need something more closed to what is done in production.

**Comment by flaper87** [comment]
Just a quick update on this. I've tested the `openshift-installer` and gone through the required steps for us to be able to run openshift deployments on our GCP projects. The screenshot below shows a successful installation of OCP 4.2 on GCP.

I'll start looking into the deployer next and what's needed to integrate the `openshift-installer`.

![2020-01-08-093647_1304x48_scrot](https://user-images.githubusercontent.com/13816/71967039-93d4c000-31fa-11ea-93e3-582535bae3d4.png)
