### ISSUE TITLE
How should I debug the code

### ISSUE THREAD

**Issue by JamesIsHuang** [elastic/cloud-on-k8s#2176]
I and my colleague want to add some code on cloud-on-k8s, but we don't understand how to debug code, and not search any useful info.

**Comment by barkbay** [comment]
I would advise you to have a look at the [go-run](https://github.com/elastic/cloud-on-k8s/blob/master/Makefile#L153-L165) target in the [Makefile](https://github.com/elastic/cloud-on-k8s/blob/master/Makefile)

I think that from that point you can create some run/debug configurations for your favorite IDE.

[dev-setup.md](https://github.com/elastic/cloud-on-k8s/blob/master/dev-setup.md) may also give you some additional information.

**Comment by pebrc** [comment]
@JamesIsHuang thanks for your interest in ECK. Please use https://discuss.elastic.co/c/eck for questions like this and let's reserve Github for bug reports and feature requests.
