### ISSUE TITLE
Phantom reconciliations

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2189]
Even after all the associated objects have been deleted and more than a few minutes have elapsed since the deletion, the operator logs still show the deleted resource as being reconciled.

```
{"level":"info","@timestamp":"2019-11-29T08:25:01.278Z","logger":"elasticsearch-controller","message":"Starting reconciliation run","ver":"1.0.0-beta1-b559ec38","iteration":9737,"namespace":"default","name":"ekpmn-0064"}
{"level":"info","@timestamp":"2019-11-29T08:25:01.278Z","logger":"elasticsearch-controller","message":"Ending reconciliation run","ver":"1.0.0-beta1-b559ec38","iteration":9737,"namespace":"default","name":"ekpmn-0064","took":0.000389278}
```

These logs were observed more than 10 minutes after the resource was deleted. None of the Kubernetes objects associated with the resource seem to exist in the cluster and the operator caches should have been refreshed by this point.

**Comment by matootie** [comment]
I'm getting the same result. Is there a solution to this? What is the cause?

**Comment by naemono** [comment]
@charith-elastic I cannot replicate this issue in the current version of ECK.

The only logs I see 1 minute after deleting Elasticsearch+Kibana+Agent from a cluster were runs of the licensing reconciler, which is expected.

Please re-open if this issue persists, thank you.
