### ISSUE TITLE
[e2e] TestEnterpriseTrialLicense is failing

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2194]
Trial is not started for the ES cluster:

```go
[2019-11-29T10:58:33.519Z]     --- FAIL: TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial] (300.00s)
[2019-11-29T10:58:33.519Z]         utils.go:80: 
[2019-11-29T10:58:33.519Z]             	Error Trace:	utils.go:80
[2019-11-29T10:58:33.519Z]             	Error:      	Received unexpected error:
[2019-11-29T10:58:33.519Z]             	            	expectedTypes license type [trial] got basic
[2019-11-29T10:58:33.519Z]             	Test:       	TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]
```

The operator can not find the `trial-status` secret to get the public key to check the license validity:
```js
{
  "level": "error",
  "@timestamp": "2019-11-29T10:49:01.065Z",
  "logger": "license",
  "message": "while checking license validity",
  "ver": "1.0.0-beta1-3faf9cfb",
  "error": "while loading signature secret: Secret \"trial-status\" not found"
}
```

The `trial-status` secret is created in the managed namespace instead of the namespace of the global operator.

**Comment by pebrc** [comment]
@thbkrkr are you sure about this? https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests/571/testReport/github/com_elastic_cloud-on-k8s_test_e2e_es/TestEnterpriseTrialLicense/ looks ok to me. 

Also note I have made some changes in #2188 that also affect the trial mechanism

**Comment by thbkrkr** [comment]
I created this issue after that `cloud-on-k8s-stack/107/` and `cloud-on-k8s-versions-gke/141/` failed:

https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-stack/107/

Run tests for different ELK stack versions in GKE / 7.1.1 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]
Run tests for different ELK stack versions in GKE / 7.2.1 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]
Run tests for different ELK stack versions in GKE / 7.4.1 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]
Run tests for different ELK stack versions in GKE / 6.8.4 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]

https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/141/

Run tests for different k8s versions in GKE / 1.14 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]
Run tests for different k8s versions in GKE / 1.13 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]
Run tests for different k8s versions in GKE / 1.12 / github.com/elastic/cloud-on-k8s/test/e2e/es.TestEnterpriseTrialLicense/Elasticsearch_license_should_be_[trial]

`TestEnterpriseTrialLicense` failed for all stages. I downloaded the dump and found what I mentioned above.

Lastly, in https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-stack/108/, `TestEnterpriseLicenseSingle` also failed for all stages.

BUT last builds were successful. So I don't understand what's going on.

I close this as now it looks ok but would reopen if it starts again.
