### ISSUE TITLE
Cannot remove v1alpha1 from CRD storedVersions with kubectl

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2196]
Applying the current manifests with v1beta1 only (and potentially an additional v1 version):
- works fine if there was no CRD installed
- does not work it's updating a CRD that listed the v1alpha1 version as storedVersion in the status

```
CustomResourceDefinition.apiextensions.k8s.io "kibanas.kibana.k8s.elastic.co" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
```

We should probably reconsider [the removal of v1alpha1](https://github.com/elastic/cloud-on-k8s/pull/2119). We could instead set it as `served: false` so it still technically exists but no resource can be read nor written using `v1alpha1`.

**Comment by sebgl** [comment]
IIUC correctly the way CRDs are validated, it seems impossible to update a CRD in order to remove an old version.

When a CRD is updated:
- the list of expected storedVersions is built from status.StoredVersions in the previous CRD + newer storedVersions in the new CRD ([source](https://github.com/kubernetes/kubernetes/blob/cf16e4988f58a5b816385898271e70c3346b9651/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/strategy.go#L75))
- this list of storedVersions is passed to a validation function that checks all expected storedVersions are still present in the new CRD ([source](https://github.com/kubernetes/kubernetes/blob/cf16e4988f58a5b816385898271e70c3346b9651/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L143))

All served versions in the history of the CRD end up in the Status. Any update to the CRD Status is impossible. Any update to the CRD versions that would consist in removing a version that exists in the status is impossible.

So I think it's just not possible to remove a version that was the stored version at some point in history.

However it looks like the [operator-lifecycle-manager](https://github.com/operator-framework/operator-lifecycle-manager/blob/5a5389cb8d831e79acade535d947d4ad4a5c40a7/doc/design/dependency-resolution.md#deprecateremove-a-version-of-crd) is able to do it. Digging more into the code, it seems like it is [updating the status subresource of the CRD to remove the storedVersion](https://github.com/operator-framework/operator-lifecycle-manager/commit/b873c798b91bb24dc02b4ce44b876f5c5b3d3297#diff-efdf1c2d694e58ab3f44e9e02a4900b9R1331-R1336), bypassing validation of the CRD storedVersions. Which is something that can be done programatically but, afaik, not something that could happen automatically when updating a CRD manifest with `kubectl`.

**Comment by sebgl** [comment]
Programatically updating the CRD status sub-resource works fine:

```go

package main

import (
	"fmt"
	"os"

	apiextension "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
)

func exitOnErr(err error) {
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func main() {
	//  create k8s client
	cfg := config.GetConfigOrDie()
	client, err := apiextension.NewForConfig(cfg)
	if err != nil {
		panic(err)
	}

	// retrieve CRD
	crd, err := client.ApiextensionsV1beta1().CustomResourceDefinitions().Get("elasticsearches.elasticsearch.k8s.elastic.co", v1.GetOptions{})
	exitOnErr(err)
	// remove v1alpha1 from its status
	oldStoredVersions := crd.Status.StoredVersions
	newStoredVersions := make([]string, 0, len(oldStoredVersions))
	for _, stored := range oldStoredVersions {
		if stored != "v1alpha1" {
			newStoredVersions = append(newStoredVersions, stored)
		}
	}
	crd.Status.StoredVersions = newStoredVersions
	// update the status sub-resource
	crd, err = client.ApiextensionsV1beta1().CustomResourceDefinitions().UpdateStatus(crd)
	exitOnErr(err)
	fmt.Println("updated CRD status storedVersions:", crd.Status.StoredVersions)
}
```

**Comment by sebgl** [comment]
It's totally an option for us to keep the `v1alpha1` version in the CRD. If specified with `served: false`, any get/create/update operation on a `v1alpha1` resource is prevented. Almost as if it didn't exist.
In terms of implementation we can either:
* restore the `v1alpha1` codebase and auto-generate the v1alpha1 CRD
* remove the `v1alpha1` codebase and patch the CRD to add it to the list of existing versions

**Comment by oliverisaac** [comment]
@sebgl 's [script above](https://github.com/elastic/cloud-on-k8s/issues/2196#issuecomment-560318404) is still relevant apparently...

I've update the script to work as of Aug 2023:

```go
package main

import (
	"context"
	"fmt"
	"os"

	apiextension "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
)

var versionToStrip = "v1alpha1"
var crds = []string{
	"vaultauths.secrets.hashicorp.com",
	"vaultconnections.secrets.hashicorp.com",
	"vaultdynamicsecrets.secrets.hashicorp.com",
	"vaultpkisecrets.secrets.hashicorp.com",
	"vaultstaticsecrets.secrets.hashicorp.com",
}

func exitOnErr(err error) {
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func main() {
	//  create k8s client
	cfg := config.GetConfigOrDie()
	client, err := apiextension.NewForConfig(cfg)
	exitOnErr(err)

	for _, crdName := range crds {
		cleanCRD(client, crdName)
	}
}

func cleanCRD(client *apiextension.Clientset, crdName string) {
	// retrieve CRD
	crd, err := client.ApiextensionsV1().CustomResourceDefinitions().Get(context.Background(), crdName, v1.GetOptions{})
	exitOnErr(err)
	// remove v1alpha1 from its status
	oldStoredVersions := crd.Status.StoredVersions
	newStoredVersions := make([]string, 0, len(oldStoredVersions))
	for _, stored := range oldStoredVersions {
		if stored != versionToStrip {
			newStoredVersions = append(newStoredVersions, stored)
		}
	}
	crd.Status.StoredVersions = newStoredVersions
	// update the status sub-resource
	crd, err = client.ApiextensionsV1().CustomResourceDefinitions().UpdateStatus(context.Background(), crd, v1.UpdateOptions{})
	exitOnErr(err)
	fmt.Println("updated CRD %s status storedVersions:", crdName, crd.Status.StoredVersions)
}
```
