### ISSUE TITLE
New Release with bugfixes?

### ISSUE THREAD

**Issue by ironsalsa** [elastic/cloud-on-k8s#2204]
Could we get a new release of the operator? There's a few bugs that have been fixed in master that aren't in the October release that need workarounds as is.

**Comment by david-kow** [comment]
Hey @ironsalsa, thanks for your question. Next release is being worked on right now and we are planning for it to happen early next year. 

(Btw, https://discuss.elastic.co/c/eck may be even better suited for these kind of inquiries.)
