### ISSUE TITLE
Support custom registry address in operator command line flags

### ISSUE THREAD

**Issue by LoadingZhang** [elastic/cloud-on-k8s#2223]
In private network eviroment, I can't download docker images from `docker.elastic.co` .
if we could set operator command line flags such as: `--default-registry=xxx.xxx.xxx`, would be more convenience to use eck where can not access internet directly.

I knew docker image can be specified, but sometimes would get confused when using image with version field, so if we can specify registry, the yaml config would be more concise.

**Comment by sebgl** [comment]
To give a bit more context: users can already set `spec.image = xx.xx.xx/elasticsearch:7.5.0` in Elasticsearch, Kibana and APM manifests. But those need to be updated along with the `version` field with no mismatch.
Allowing users to set a default registry if they use the same image and versioning as the official ones could maybe make things easier.
