### ISSUE TITLE
Licence reconciliation error prevents cluster state from being updated

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2244]
If [licence reconciliation](https://github.com/elastic/cloud-on-k8s/blob/d1bba3df9bc4b11938ebd0a8e343d804398b2e8b/pkg/controller/elasticsearch/driver/driver.go#L189-L212) returns an error, it still [gets recorded in the result aggregator](https://github.com/elastic/cloud-on-k8s/blob/d1bba3df9bc4b11938ebd0a8e343d804398b2e8b/pkg/controller/common/reconciler/results.go#L53-L59) and causes the reconciliation loop to [exit without updating cluster state](https://github.com/elastic/cloud-on-k8s/blob/d1bba3df9bc4b11938ebd0a8e343d804398b2e8b/pkg/controller/elasticsearch/driver/driver.go#L238).

The options here are:
1. Ignore the error (log and discard) and continue with the reconciliation
2. Prevent further reconciliation until the licence is correctly applied

**Comment by barkbay** [comment]
> Ignore the error (log and discard) and continue with the reconciliation

Could be a transient error, so we might want to try to reconcile again later ?

> Prevent further reconciliation until the licence is correctly applied

No sure it would be a good idea, it may block further updates of the cluster that we may want to apply even if there's an issue with the license.

**Comment by charith-elastic** [comment]
> Could be a transient error, so we might want to try to reconcile again later ?

Are you suggesting that instead of using [`Results.Apply`](https://github.com/elastic/cloud-on-k8s/blob/d1bba3df9bc4b11938ebd0a8e343d804398b2e8b/pkg/controller/common/reconciler/results.go#L53-L59), we treat licence reconciliation as just another "normal" step in the [driver reconciliation function](https://github.com/elastic/cloud-on-k8s/blob/d1bba3df9bc4b11938ebd0a8e343d804398b2e8b/pkg/controller/elasticsearch/driver/driver.go#L110) and return immediately with the error (which will cause the item to be re-queued almost immediately (depending on rate-limits).

I am fine with that approach. However, if the error is not transient, it would mean that we won't make any progress at all. Is there a reliable way to determine whether the licence reconciliation error is transient or not?

**Comment by barkbay** [comment]
No, I was just thinking that the current behaviour makes sense, I think we should eventually try to reconcile later.

What if we update the cluster state before checking that we have some errors ?

**Comment by charith-elastic** [comment]
Sure, that could work. I'll give that a go.
