### ISSUE TITLE
`make deploy` does not work out of the box

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2251]
It looks like our `make deploy` targets needs some adjustments, and/or some additional documentation in `dev-setup.md`.

* it requires `$MANAGED_NAMESPACE` to be set (not sure why, we should have a default?)
* it requires `$GCLOUD_PROJECT` to be set (could be mentioned in `dev-setup.md`)
* it builds, pushes and sets the docker image name in the yaml manifests, but I think there are consistencies and the same docker image name is not used for all of them

Also we may want to simplify the deployment and deploy a single `all-in-one` version of the operator when using `make deploy`.

**Comment by pebrc** [comment]
The issue described here don't apply in the same way anymore. `MANAGED_NAMESPACE` is optional and defaults to empty which means all namespaces. There is a check for `GCLOUD_PROJECT` in the Makefile to make users aware that it is needed. The single all-in-one deploy is what happens today anyway.
