### ISSUE TITLE
Disable Kibana license UI

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2252]
Turn off Kibana license UI with 
* `xpack.license_management.enabled: false` for 7.x
* `license_management.enabled: false` for 6.x
 in favour of ECK license management as documented in  https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-licensing.html

One tricky gotcha is that Kibana will do an 'optimize' run when changing this setting and subsequently run out of memory when configured with defaults. At the very least this slows down the time to boot up a new Kibana instance significantly and as I understand it this will be repeated on any configuration change. 

* 4G 4CPU optimize run 104.59 secs
* 4G 2CPU optmize run 176.55 secs
* 2G 1CPU optimize run 544.00 secs or OOM 
* 1G 100m CPU (defaults) OOM

I don't see a good way around the optimize step, stopping short of building custom images for Kibana. 

Kibana issue https://github.com/elastic/kibana/issues/52709

cc @agup006

**Comment by sebgl** [comment]
I feel like it's not worth implementing our own workaround for this, it's probably best to have this fixed in Kibana directly.
Then we could only apply the settings in Kibana versions that contain the [corresponding fix](https://github.com/elastic/kibana/issues/52709).

**Comment by pebrc** [comment]
Kibana issue https://github.com/elastic/kibana/issues/52709
