### ISSUE TITLE
Test 7.5.x to 7.6.0 upgrades

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2253]
Test 7.5.0 to 7.6.0 upgrades. Watch out for unassigned primary shards or anything potentially related to https://github.com/elastic/elasticsearch/pull/48974 . 

Currently only development builds exists afaik. Once we have official build candidates we should automate this test as an e2e test.

**Comment by thbkrkr** [comment]
This is now covered with #2570 and #2586.

> Watch out for unassigned primary shards [1]
> or anything potentially related to elastic/elasticsearch#48974 [2].

I think [1] is fairly well managed with our existing [`MutationTestSteps`](https://github.com/elastic/cloud-on-k8s/blob/551e456c72c289ef64414f21d8f60701a22c62cd/test/e2e/test/elasticsearch/steps_mutation.go#L62-L130) which:
* Add some data to the ES cluster before starting the mutation
* Start querying the ES cluster health while mutation is going on
* Run the mutation (version upgrade for example here)
* Check that the ES cluster health was not red during mutation process
* Check that all k8s and Elastic Stack resources are healthy

Not sure for [2]. Did you have something particular in mind?
