### ISSUE TITLE
Instrument e2e tests and feed results into a permanent ES cluster

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2270]
As discussed previously we should instrument our e2e test environments with beats and feed the data into a long lived Elasticsearch cluster managed by ECK. This should help us
* investigate issues with our e2e test suite
* identify potential feature gaps in ECK wrt to monitoring and metrics
* create a long running ECK environment that might be useful in itself (memory leaks, version upgrades, etc) 

We should set up an ILM policy to configure the data retention in that cluster to limit the overall amount of data stored.

**Comment by sebgl** [comment]
Having Elasticsearch logs available would have helped to troubleshoot https://github.com/elastic/cloud-on-k8s/issues/2380.
