### ISSUE TITLE
Ensure ECK v1 and crd v1 work fine with operatorhub

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2276]
The next release includes a bump of the CRD to `v1`, and marks `v1alpha1` as `served: false`.
Let's make sure this does not cause any trouble in operatorhub, does work with the operator lifecycle manager, then finally update the operatorhub manifests.

**Comment by barkbay** [comment]
I have prepared a PR [here](https://github.com/operator-framework/community-operators/compare/master...barkbay:eck-1.0.0) _(I will update the `image` before doing the PR)_

I just did a few tests and upgrading using OLM on Openshift 4.2 works fine. 

fyi I have created a `stable` channel. People that are already using the `beta` channel will also receive the update. Note that it seems easy to move from a channel to the other one, people that are using the `beta` channel but want to move to the `stable` one should be able to do so:

![image](https://user-images.githubusercontent.com/976373/71414248-4da62b00-2656-11ea-9c17-6162dd740e24.png)

**Comment by barkbay** [comment]
Closing this issue since the operator hub is up to date.

It is worth to mention that we should have a cluster running the previous version of ECK before updating the operator hub. The reason is that it is not possible to install a previous version of the operator with the operator hub.
