### ISSUE TITLE
Single node cluster upgrade from 6.X to 7.X does not have cluster.initial_master_nodes set

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2291]
Spotted in an E2E test: https://github.com/elastic/cloud-on-k8s/issues/2288

A single-node cluster upgrade from 6.X to 7.X seems to fail because the restarted 7.X node does not have `cluster.initial_master_nodes` set:

```
{"type": "server", "timestamp": "2019-12-18T02:16:51,944+0000", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "test-version-up-1-685-to-732-grq9", "node.name": "test-version-up-1-685-to-732-grq9-es-masterdata-0",  "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{test-version-up-1-685-to-732-grq9-es-masterdata-0}{qrttZLBcQRifqkZmtte6xg}{Kr-otzquS2mllFoK02HECA}{10.64.1.70}{10.64.1.70:9300}{dim}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305] from hosts providers and [{test-version-up-1-685-to-732-grq9-es-masterdata-0}{qrttZLBcQRifqkZmtte6xg}{Kr-otzquS2mllFoK02HECA}{10.64.1.70}{10.64.1.70:9300}{dim}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 13 in term 0"  }
```

This was supposed to be fixed in https://github.com/elastic/cloud-on-k8s/pull/1681 but it looks like we might have a bug or race condition somewhere.
[Elasticsearch 7.3 pod logs.txt](https://github.com/elastic/cloud-on-k8s/files/3978778/logs.txt)
[Operator pod logs.txt](https://github.com/elastic/cloud-on-k8s/files/3978782/logs.txt)

**Comment by sebgl** [comment]
Investigating the logs.

Elasticsearch instance reports `cluster.initial_master_nodes` not set:

```
{"type": "server", "timestamp": "2019-12-18T02:12:51,900+0000", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "test-version-up-1-685-to-732-grq9", "node.name": "test-version-up-1-685-to-732-grq9-es-masterdata-0",  "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{test-version-up-1-685-to-732-grq9-es-masterdata-0}{qrttZLBcQRifqkZmtte6xg}{Kr-otzquS2mllFoK02HECA}{10.64.1.70}{10.64.1.70:9300}{dim}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305] from hosts providers and [{test-version-up-1-685-to-732-grq9-es-masterdata-0}{qrttZLBcQRifqkZmtte6xg}{Kr-otzquS2mllFoK02HECA}{10.64.1.70}{10.64.1.70:9300}{dim}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 13 in term 0"  }
```

Operator reports (in order):
- a re-bootstrap was performed
```
{"level":"info","@timestamp":"2019-12-18T02:12:05.057Z","logger":"driver","message":"cluster re-bootstrap necessary","ver":"1.0.0-beta1-7d697e3d","version":"7.3.2","namespace":"e2e-5bkwo-mercury","name":"test-version-up-1-685-to-732-grq9"}
```
- node was deleted (in the next reconciliation)
```
{"level":"info","@timestamp":"2019-12-18T02:12:06.226Z","logger":"driver","message":"Deleting pod for rolling upgrade","ver":"1.0.0-beta1-7d697e3d","es_name":"test-version-up-1-685-to-732-grq9","namespace":"e2e-5bkwo-mercury","pod_name":"test-version-up-1-685-to-732-grq9-es-masterdata-0","pod_uid":"b30165d9-213b-11ea-aaa7-42010a840204"}
```
- seed hosts updated & annotating cluster with its UUID for bootstrap
```
{"level":"info","@timestamp":"2019-12-18T02:12:10.398Z","logger":"settings","message":"Seed hosts updated","ver":"1.0.0-beta1-7d697e3d","namespace":"e2e-5bkwo-mercury","es_name":"test-version-up-1-685-to-732-grq9","hosts":[]}
{"level":"info","@timestamp":"2019-12-18T02:12:10.453Z","logger":"driver","message":"Annotating bootstrapped cluster with its UUID","ver":"1.0.0-beta1-7d697e3d","namespace":"e2e-5bkwo-mercury","es_name":"test-version-up-1-685-to-732-grq9"}
```

**Comment by sebgl** [comment]
I think this may be what happens:

- single-node should be upgraded to 7.x
- we detect a re-bootstrap is necessary hence perform it (remove the clusterUUID annotation)
- we update the statefulset with the new spec & new config that does correctly have `cluster.initial_master_nodes` set
- we delete the 6.x pod so it gets replaced by the 7.x pod
- the 7.x pod gets created
- we annotate the cluster for bootstrap because the following gets executed:
```go
	if clusterIsBootstrapped(observedState) && !reBootstrap {
		// cluster bootstrapped but not annotated yet
		return annotateWithUUID(cluster, observedState, c)
	}
```
- in the above, `reBootstrap` is false since the 7.x pod is already there (starting...), and `clusterIsBootstrapped(observedState)` since we cache the cluster UUID from X seconds ago
- we update the Elasticsearch configuration to not have `cluster.initial_master_nodes`
- the Elasticsearch instance starts up, picking up the latest configuration that does not contain `cluster.initial_master_nodes`

**Comment by sebgl** [comment]
So I guess we can fix the above problem while keeping the current way of doing things. However I tend to think the way we use the ClusterUUID annotation to also hold the fact a zen2 cluster is bootstrapped makes things confusing.

It would make more sense IMO to decouple both and have a dedicated annotation for zen2 bootstrapped clusters: `elasticsearch.k8s.elastic.co/zen2-bootstrapped: true`.

In the reconciliation, we can do the following:
- if we have some zen2-compatible Pods running && the annotation is not set
    - `GET /_nodes/_master`
    - if the returned master node is running version 7.x+
          - set `elasticsearch.k8s.elastic.co/zen2-bootstrapped: true` 
    - schedule a requeue in X seconds without returning an error if any of the above fails, so we eventually set the annotation for a 7.x cluster
- if the cluster is zen2 bootstrapped (annotation set):
    - remove `cluster.initial_master_nodes` from the Elasticsearch configuration

**Comment by pebrc** [comment]
Sounds good to me! Introducing a new annotation does indeed reduce the mental overhead when trying to understand how this algorithm works significantly. 

The only downside is that the annotation is effectively useless or not very informative the moment this bootstrapping problem is solved but will be forever visible on the Elasticsearch resource, but I don't see a good way to avoid that.

**Comment by DaveCTurner** [comment]
Would it instead be possible to record the correct `initial_master_nodes` value as an annotation before starting any nodes in the cluster (or upgrading from 6.x in small clusters) and then remove it to indicate that bootstrapping was successful? This would avoid the issues that can arise if `initial_master_nodes` were to vary over time and would also avoid leaving this vestigial annotation around.

**Comment by sebgl** [comment]
@DaveCTurner I think that would make sense.
The algorithm would look like the following:

* if the cluster is annotated with `initial_master_nodes=a,b,c`:
    * if we have some zen2-compatible Pods running (v7+) and we detect a running v7 master (`GET /_nodes/_master`):
        * remove the `initial_master_nodes` annotation to indicate the cluster is done bootstrapping

* for each expected v7+ Elasticsearch instance:
    * if the cluster is annotated with  `initial_master_nodes=a,b,c`, use that value in the Elasticsearch configuration file
    * else if there is no cluster running yet (no ClusterUUID annotation exists):
        * compute `initial_master_nodes`, store it in an annotation, and set the v7 instance configuration file accordingly 
    * else if there is a single v6 master running that will be replaced by a v7:
        * compute `initial_master_nodes`, store it in an annotation, and set the v7 instance configuration file accordingly
    * else, nothing to do w.r.t `initial_master_nodes`. We should be in a situation where a v7 cluster already exists, or a v6 cluster with multiple masters is running and will be rolling upgraded to v7.

**Comment by DaveCTurner** [comment]
Yep I think that sounds good to me. I think this should also work ok for upgrades from v6 to v7 involving two master-eligible nodes which are kinda special too: they are not really "rolling" since when you shut one of the v6 master-eligible nodes down the cluster loses quorum and won't have a master until that node comes back once it's been upgraded. That said, I recommend testing this case too.
