### ISSUE TITLE
E2E tests run on GKE 1.12 aborted

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2293]
Since december 12, the E2E tests run on GKE 1.12 are always aborted.

![2019-12-18-163145_2281x1664_scrot](https://user-images.githubusercontent.com/582883/71099734-10ecb680-21b4-11ea-9524-08970c246add.png)

The last sucessful build was on 7f6bf926.
The execution seems to take too long since 71d639e5.
We have not added any new tests between these two sha1.
So I wonder if anything has changed on the GKE side.

**Comment by david-kow** [comment]
This seems to be fine now and relevant logs are lost, hence closing.

<img width="881" alt="Screenshot 2020-01-10 at 09 17 14" src="https://user-images.githubusercontent.com/50632861/72136871-0cb65200-338a-11ea-82f6-32038793d890.png">
