### ISSUE TITLE
disable https authentication 

### ISSUE THREAD

**Issue by jayenzo** [elastic/cloud-on-k8s#2322]
Hey 

Are there any options to completely disable the default security I have the following config. 
basically what options can I include in the elasticsearch.yaml file for the operator to disable auth and https ? 

`ApiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.5.0
  nodeSets:
  - name: elastic
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
      XPackSecurityAuthcReservedRealmEnabled: false
      XPackSecurityEnabled: false
      XPackSecurityHttpSslCertificate: false
      XPackSecurityHttpSslEnabled: false
      XPackSecurityHttpSslKey: false
      XPackSecurityTransportSslCertificate: false
      XPackSecurityTransportSslEnabled: false
      XPackSecurityTransportSslKey: false
      XPackSecurityTransportSslVerificationMode: false 
    spec:
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                limits:
                  memory: 4Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
       request 2Gi of persistent data storage for pods in this topology element
          volumeClaimTemplates:
            - metadata:
                name: elasticsearch-data
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 400Gi
                storageClassName: standard
          http:
            service:
              spec:
                ports:
                  - name: http
                    port: 9200
                type: ClusterIP
            tls:
              selfSignedCertificate:
                disabled: true
              Certificate:
                 disabled: true
`

**Comment by barkbay** [comment]
Please check the documentation and the following discussion:
* https://www.elastic.co/guide/en/cloud-on-k8s/1.0-beta/k8s-accessing-elastic-services.html#k8s-disable-tls
* https://discuss.elastic.co/t/dont-want-to-use-https-and-user-password/202332
