### ISSUE TITLE
how can i generate olm?

### ISSUE THREAD

**Issue by ftyuuu** [elastic/cloud-on-k8s#2323]
how can i generate olm like:
`operator-sdk olm-catalog gen-csv --csv-version 0.0.1`

**Comment by barkbay** [comment]
ECK is already available [in the operator hub](https://operatorhub.io/operator/elastic-cloud-eck ) ([sources](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/elastic-cloud))
