### ISSUE TITLE
TestKibanaStandalone E2E test fails on Kibana 6.8.5

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2325]
In Kibana 6.x the association configuration should be `elasticsearch.url` but the test is not version aware and uses the newer `elasticsearch.hosts` setting which causes Kibana to fail with a config validation error.

```
FATAL  ValidationError: child "elasticsearch" fails because [child "hosts" fails because [single value of "hosts" fails because ["hosts" is not allowed to be empty, "hosts" must be a valid uri with a scheme matching the http|https pattern]]]
```

**Comment by barkbay** [comment]
Could it be related to https://github.com/elastic/cloud-on-k8s/pull/2286/files#diff-87664dee582ff3c203328b64d2cd0383L291 ?

IIRC the way to specify the host/url is not consistent across the versions of Kibana 6.x

Do you know for how long it has been failing ?

**Comment by charith-elastic** [comment]
That commit seems like a very likely candidate for the root cause of this failure. I don't recall this test failing before so it makes sense. Since the 6.x settings factory adds the `elasticsearch.url` field to the config and the test manifest adds `elasticsearch.hosts`, I think it causes a problem with the validation logic when both settings are present.

**Comment by barkbay** [comment]
My understanding is that [as of Kibana 6.8.x](https://github.com/elastic/dockerfiles/blob/v6.8.0/kibana/bin/kibana-docker#L22) `elasticsearch.hosts` is supported the same way it is in 7.x

Since only Kibana > 6.8 is supported, should we not get rid of this dichotomy and only rely on `version7.SettingsFactory(...)`?

**Comment by charith-elastic** [comment]
I am in favour of removing the 6.x settings factory. I'll create a new PR.
