### ISSUE TITLE
Operator changes the order of environment variables provided in the Elasticsearch CR

### ISSUE THREAD

**Issue by xyphr** [elastic/cloud-on-k8s#2327]
## Bug Report
**What did you do?**
Added env vars to the podTemplate in the following order:
```
B = firstpart
C = secondpart
A = $(B).$(C)
```
**What did you expect to see?**
```
echo $A
firstpart.secondpart
```
**What did you see instead? Under which circumstances?**
```
echo $A
$B.$C
```
If ordering is changed then we are not able to use the [variable reference expansion](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#envvar-v1-core) feature provided by Kubernetes
**Environment**

* ECK version:

	1.0.0-beta1

* Kubernetes information:

	on AWS EKS
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by barkbay** [comment]
You're right we should preserve the order of the provided env. variables.

I'm wondering if we should allow a user to override the ones automatically provided by the operator and/or allow duplicates ? ([It's not the case today](https://github.com/elastic/cloud-on-k8s/blob/ebc71c80ae28c9afb6c7736ca606ee4af022e51e/pkg/controller/common/defaults/pod_template.go#L203)) I did a quick test and K8S does allow the user to do that with the ones provided by the controllers. In case of duplicate variables the last ones take precedence. My initial inclination would be to allow that but print a warning in that case.

**Comment by xyphr** [comment]
Yes that sounds like a good approach to me as well, preserving the order would also let the operator override any env vars required for its functioning.
