### ISSUE TITLE
can eck support the es version of 6.6.0?

### ISSUE THREAD

**Issue by ftyuuu** [elastic/cloud-on-k8s#2335]
I modify the code of version check, and it also work. Are there some compatibility errors I don't know about the es version of 6.6.0 
```
            case 6:
		return &LowestHighestSupportedVersions{
			// Min. version is 6.8.0.
			LowestSupportedVersion: version.MustParse("6.6.0"),
			// higher may be possible, but not proven yet, lower may also be a requirement...
			HighestSupportedVersion: version.MustParse("6.99.99"),
		}
```

**Comment by sebgl** [comment]
ES 6.8.0 includes security with TLS in the basic license.
We consider it's a must-have in Kubernetes world where multiple applications potentially share the same network.

That's why it is the lowest supported value.

**Comment by ftyuuu** [comment]
@sebgl thank you for your reply!
