### ISSUE TITLE
Review documentation topic hierarchy

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2351]
<details>
<summary>The set of help topics we have in the documentation has become a bit fragmented.</summary>

- Overview
- Quickstart
- Upgrading the Elastic stack version
- Deploying ECK on OpenShift
- Accessing Elastic Stack services
- Managing compute resources
- Running Elasticsearch on ECK
	- Pod Template
	- JVM heap size
	- Node configuration
	- Volume claim templates
	- HTTP settings & TLS SANs
	- Virtual memory
	- Custom HTTP certificate
	- Settings managed by ECK
	- Secure settings
	- Custom configuration files and plugins
	- Init containers for plugin downloads
	- Update strategy
	- Pod disruption budget
	- Nodes orchestration
	- Advanced Elasticsearch node scheduling
	- Create automated snapshots
	- Readiness probe
- Running Kibana on ECK
- Running APM Server on ECK
- Creating custom images
- Configuring ECK
	- Validating webhook
- Managing licenses in ECK
- Troubleshooting
- Upgrading ECK
- Uninstalling ECK
- Glossary
</details>

We can probably group some of the related topics together for easier comprehension and sort the Elasticsearch sections by name to make them easier to find.

For example, one possible hierarchy might be:

- Overview
- Quickstart
- Deploying ECK on OpenShift
- Operating ECK    
    - Configuring ECK
    - Validating webhook
    - Creating custom images
    - Managing licenses    
    - Upgrading ECK
    - Uninstalling ECK
    - Troubleshooting
- Orchestrating Elastic stack applications
    - Accessing Elastic Stack services
    - Managing compute resources
    - Upgrading the Elastic stack version
    - Running Elasticsearch on ECK
        - Advanced Elasticsearch node scheduling
        - Create automated snapshots
        - Custom configuration files and plugins
        - Custom HTTP certificate
        - HTTP settings & TLS SANs
        - Init containers for plugin downloads
        - JVM heap size
        - Node configuration
        - Nodes orchestration
        - Pod disruption budget
        - Pod Template
        - Readiness probe
        - Secure settings
        - Settings managed by ECK
        - Update strategy
        - Virtual memory
        - Volume claim templates
    - Running Kibana on ECK
    - Running APM Server on ECK
- Glossary

**Comment by alaudazzi** [comment]
@charith-elastic makes sense to reorganise the overall structure and make it more "compact". Maybe we can further optimise the section _Running Elasticsearch on ECK_.

**Comment by charith-elastic** [comment]
> Maybe we can further optimise the section _Running Elasticsearch on ECK_.
I agree. It looks like the sidebar only displays two levels of links so maybe moving the _Running Elasticsearch on ECK_ section to the second level as proposed will automatically hide those links anyway.

**Comment by charith-elastic** [comment]
I think we should tackle this issue in two stages:
1. Settle on a top-level topic hierarchy.
1. Re-organise the _Running Elasticsearch on ECK_ section.

For (1), I propose the following structure:

- Overview
- Quickstart
- Operating ECK    
    - Configuring ECK
    - Validating webhook
    - Managing licenses    
    - Upgrading ECK
    - Uninstalling ECK
    - Troubleshooting    
- Advanced Topics
    - Deploying ECK on OpenShift
    - Creating custom images
    - Service meshes
    - Remote clusters
- Orchestrating Elastic Stack applications
    - Accessing Elastic Stack services
    - Managing compute resources
    - Upgrading the Elastic stack version
    - Running Elasticsearch on ECK
    - Running Kibana on ECK
    - Running APM Server on ECK
- Reference
    - API Reference
    - Glossary
    - Third-party dependencies
    - Release highlights
    - Release notes

@alaudazzi thoughts?

**Comment by alaudazzi** [comment]
@charith-elastic the overall structure looks much better and well organized!
A couple of comments:
- To stay consistent with the rest of Elastic docs structure, let's remove the gerund form for H2 topics
- I wonder if "Advanced Topics" should follow "Orchestrating Elastic Stack applications".

**Comment by alaudazzi** [comment]
@charith-elastic the overall structure looks much better and well organized!
A couple of comments:
- To stay consistent with the rest of Elastic docs structure, let's remove the gerund form for H2 topics
- I wonder if "Advanced Topics" should follow "Orchestrating Elastic Stack applications".

**Comment by alaudazzi** [comment]
@charith-elastic the overall structure looks much better and well organized!
A couple of comments:
- To stay consistent with the rest of Elastic docs structure, let's remove the gerund form for H2 topics
- I wonder if "Advanced Topics" should follow "Orchestrating Elastic Stack applications".

**Comment by charith-elastic** [comment]
As the topic hierarchy has been reviewed and merged to master, I am closing this issue and creating #2673 to follow-up on the Elasticsearch section.
