### ISSUE TITLE
Update upgrade process for 1.0.0

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2357]
Follow up of #2308 

[Upgrade documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html) must state that upgrading resources from beta to 1.0 is not supported on K8S < 1.13 and Openshift 3.11.

**Comment by barkbay** [comment]
@anyasabo thanks for taking care of this!

I think that we should also document that when the new version of the operator is deployed the Elasticsearch Pods will restart, this is an expected behaviour.
wdyt ?

**Comment by anyasabo** [comment]
👍 definitely
