### ISSUE TITLE
Disabling http ssl results in error when accessing es nodes via ingress

### ISSUE THREAD

**Issue by gdoctor** [elastic/cloud-on-k8s#2364]
## Bug Report
**What did you do?**

I disabled http ssl (corresponds to xpack.security.http.ssl.enabled) as shown below:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: internal
spec:
  version: 7.5.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    .....
```

Since we are running in kubernetes now, it often makes sense for users to do this. Instead, I am exposing elasticsearch via an in-house ingress solution that uses traefik. This solution already handles https so no need to double down there.

At this point, elasticsearch is up and running fine. ES has a ClusterIP of 10.96.26.35. I can curl ES at this endpoint (ie `curl -u "elastic:$PASSWORD" -k "http://10.96.26.35:9200"`) and receive a 200 OK. 

However, when I put ES behind an ingress object and try to curl it via my new ingress object's hostname, I receive 500 Internal Server Error (ie `curl -u "elastic:$PASSWORD" -k "http://example-es-name.com"`). When I look through the elasticsearch logs, I can see:

```
500 Internal Server Error caused by: tls: oversized record received with length 20527
```

Going a bit deeper, I look through the traefik logs and see:

```
time="2020-01-07T20:02:06Z" level=debug msg="Creating server internal-es-nodes-0 at https://192.168.154.25:9200 with weight 1"
time="2020-01-07T20:02:06Z" level=debug msg="Creating server internal-es-nodes-1 at https://192.168.78.46:9200 with weight 1"
time="2020-01-07T20:02:06Z" level=debug msg="Creating server internal-es-nodes-2 at https://192.168.130.162:9200 with weight 1"
```

Notice that the endpoints are getting set to **https**, which is resulting in the 500 Internal Server Error in the ES nodes. Instead, this should be set to http, and that would resolve all issues.

I believe removing the https designation from the es-http service (shown below) would resolve this issue. I tried to remove it manually, but the elasticsearch operator overrides my changes to the resource. In my opinion, the https designation should correspond to whether http ssl is enabled or not.

```
[root@my-host ~]# kubectl describe svc internal-es-http
Name:              internal-es-http
Namespace:         default
Labels:            common.k8s.elastic.co/type=elasticsearch
                   elasticsearch.k8s.elastic.co/cluster-name=internal
Annotations:       <none>
Selector:          common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=internal
Type:              ClusterIP
IP:                10.96.26.35
Port:              https  9200/TCP
TargetPort:        9200/TCP
Endpoints:         192.168.130.162:9200,192.168.154.25:9200,192.168.78.46:9200
Session Affinity:  None
Events:            <none>
[root@ks-idev-nprd-rcdn-master-0 ~]#
```

**Comment by anyasabo** [comment]
Sorry you're running into this. This was resolved in https://github.com/elastic/cloud-on-k8s/pull/2083 and will go out in the next release. In the meantime that PR has a workaround listed at the end
