### ISSUE TITLE
Cleanup usages of ReconcileState.UpdateElasticsearchState

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2403]
We call `d.ReconcileState.UpdateElasticsearchState` twice in the main Elasticsearch driver. Is that necessary?
Moreover it looks like we also update the state in multiple places while reconciling node specs.

This can maybe be handled differently, or at least would require some comments.

**Comment by pebrc** [comment]
This has been fundamentally refactored since this issue was opened in https://github.com/elastic/cloud-on-k8s/pull/5328
