### ISSUE TITLE
Unable to authenticate using an API key or a token

### ISSUE THREAD

**Issue by pgillet** [elastic/cloud-on-k8s#2431]
## Proposal

**Use case. Why is this important?**
I try to connect to the elasticsearch cluster with an API key and/or a token.

## Bug Report
**What did you do?**
Token and API key services are normally automatically enabled when TLS is configured, which is the case by default.

**What did you expect to see?**
I expect to authenticate to Elasticsearch from another service within the Kubernetes cluster, using an API key or a token, not only basic auth.

**What did you see instead? Under which circumstances?**
I can create API keys but I cannot use them:

```
curl -H "Authorization: ApiKey <ID:API_KEY_BASE64_ENCODED>" https://localhost:9200/_cluster/health -k 
```
```
Handling connection for 9200
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}
```
(I use ```kubectl port-forward``` to test the connection outside Kubernetes)

And this happens when I try to create a token:

```
curl -u elastic:$PASSWORD -k -X POST "https://localhost:9200/_security/oauth2/token?pretty" -H 'Content-Type: application/json' -d'
{
  "grant_type" : "client_credentials"
}
'
```
```
Handling connection for 9200
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "current license is non-compliant for [security tokens]",
        "license.expired.feature" : "security tokens"
      }
    ],
    "type" : "security_exception",
    "reason" : "current license is non-compliant for [security tokens]",
    "license.expired.feature" : "security tokens"
  },
  "status" : 403
}
```

**Environment**

* ECK version:

	insert version or git commit id here
        [https://download.elastic.co/downloads/eck/1.0.0-beta1/all-in-one.yaml](https://download.elastic.co/downloads/eck/1.0.0-beta1/all-in-one.yaml)

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: **GKE** / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by barkbay** [comment]
I just did the test with the `ApiKey` authentication on ECK 1.0.0 / ES 7.5.1 and it is working as expected.
Could you check that there is no new line at the end of your base64 encoded key ? It is easy to fall into the trap and hard to find out that the new line character at the end of the string causes the authentication to fail.

**Comment by pgillet** [comment]
Damned, you are right about the API key. So now it works but I still cannot create tokens (see the error message above).
Note that I tested with ECK 1.0.0.

**Comment by anyasabo** [comment]
@pgillet have you applied a license as described here?
https://www.elastic.co/guide/en/cloud-on-k8s/1.0/k8s-licensing.html

It appears tokens are gold+, which would explain the error message you are receiving: https://www.elastic.co/subscriptions

**Comment by pgillet** [comment]
Ok, so I am all wrong here! Thanks for your replies. I am closing the issue.
