### ISSUE TITLE
E2E Tests on K8S 1.12

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2443]
We need a way to run the E2E Tests on K8S 1.12 as long as we support this version.

Since 1.12 has been removed from GKE we have to find an alternative, a possible option would be to revive our effort on Kind.

**Comment by thbkrkr** [comment]
The `cloud-on-k8s-e2e-tests-kind-k8s-versions` job is functional.

![2020-02-28-103846_1196x631_scrot](https://user-images.githubusercontent.com/582883/75537016-84ae0980-5a16-11ea-860f-6b693ef28f32.png)
