### ISSUE TITLE
1.0.0 failing to validate license

### ISSUE THREAD

**Issue by bdefeyter** [elastic/cloud-on-k8s#2444]
## Bug Report
**What did you do?**

Upgraded a licensed cluster managed by ECK v1.0.0-beta1 to v1.0.0

**What did you expect to see?**

Continue to function as an Enterprise-licensed environment

**What did you see instead? Under which circumstances?**

The cluster gets downgraded to a Basic license and the operator logs that it is unable to validate the signature (the operator log message and secret resource definition included below)

Note, this license file is accepted by the cluster when uploaded directly. However, it is again overwritten with a basic license when the operator-managed version can't be verified.

I have created the `eck-license` secret within the operator namespace both per the documentation instructions and/or creating the secret directly. Neither approach seems to work (and both resulted in the same base64 encoded secret)

**Environment**

* ECK version:

1.0.0

* Kubernetes information:

EKS v1.14

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
$ kubectl get secret eck-license -n elastic-system -o yaml

apiVersion: v1
data:
  <redacted>-v5.json:<redacted-base64>
kind: Secret
metadata:
  creationTimestamp: "2020-01-17T19:49:22Z"
  labels:
    license.k8s.elastic.co/scope: operator
  name: eck-license
  namespace: elastic-system
  resourceVersion: "24865715"
  selfLink: /api/v1/namespaces/elastic-system/secrets/eck-license
  uid: 75710a13-3962-11ea-b793-06af42fa1212
type: Opaque
```

* Logs:
```
{"level":"error","@timestamp":"2020-01-17T19:54:24.487Z","logger":"license","message":"Failed signature check","ver":"1.0.0-6881438d","error":"crypto/rsa: verification error","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/license.(*Verifier).Valid\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/license/verifier.go:35\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/license.(*checker).Valid\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/license/check.go:101\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/license.(*checker).CurrentEnterpriseLicense\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/license/check.go:68\ngithub.com/elastic/cloud-on-k8s/pkg/license.LicensingResolver.getOperatorLicense\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/license.go:103\ngithub.com/elastic/cloud-on-k8s/pkg/license.LicensingResolver.ToInfo\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/license.go:52\ngithub.com/elastic/cloud-on-k8s/pkg/license.ResourceReporter.Get\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:74\ngithub.com/elastic/cloud-on-k8s/pkg/license.ResourceReporter.Report\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:59\ngithub.com/elastic/cloud-on-k8s/pkg/license.ResourceReporter.Start\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:50\ngithub.com/elastic/cloud-on-k8s/cmd/manager.execute.func2\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:336"}
```

**Comment by pebrc** [comment]
@bdefeyter your license secret looks good. Can you check whether you have any other secrets defined with the `license.k8s.elastic.co/scope: operator` label that might get in the way?

If that is not the case I would suggest to open a support case with Elastic, that would allow you to share the exact license file you are using with us and we can take a closer look and try to reproduce your issue.

**Comment by bdefeyter** [comment]
It looks like no additional secrets matching the label exist. Will open a support case to proceed, thanks!

**Comment by TomaszKlosinski** [comment]
I have the same issue. I followed this docs:
https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-licensing.html

And I get this error in the operator logs:
```
{"level":"error","@timestamp":"2020-01-21T15:34:52.231Z","logger":"license","message":"Failed signature check","ver":"1.0.0-6881438d","error":"crypto/rsa: verification error","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error
  /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/elastic/cloud-on-k8s/pkg/controller/common/license.(*Verifier).Valid
  /go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/license/verifier.go:35
github.com/elastic/cloud-on-k8s/pkg/controller/common/license.(*checker).Valid
  /go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/license/check.go:101
github.com/elastic/cloud-on-k8s/pkg/controller/common/license.(*checker).CurrentEnterpriseLicense
  /go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/license/check.go:68
github.com/elastic/cloud-on-k8s/pkg/license.LicensingResolver.getOperatorLicense
  /go/src/github.com/elastic/cloud-on-k8s/pkg/license/license.go:103
github.com/elastic/cloud-on-k8s/pkg/license.LicensingResolver.ToInfo
  /go/src/github.com/elastic/cloud-on-k8s/pkg/license/license.go:52
github.com/elastic/cloud-on-k8s/pkg/license.ResourceReporter.Get
  /go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:74
github.com/elastic/cloud-on-k8s/pkg/license.ResourceReporter.Report
  /go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:59
github.com/elastic/cloud-on-k8s/pkg/license.ResourceReporter.Start
  /go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:50
github.com/elastic/cloud-on-k8s/cmd/manager.execute.func2
  /go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:336"}
```

**Comment by anyasabo** [comment]
@TomaszKlosinski please open a support case to be able to troubleshoot further. As @pebrc mentioned this will let us examine the actual license file you are using

**Comment by TomaszKlosinski** [comment]
@anyasabo , ok, thanks, I'll open support ticket tomorrow.

**Comment by pebrc** [comment]
Maybe one additional thing to mention here is that ECK only supports so called Enterprise licenses 
https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-licensing.html

It does not support single Platinum (or any other subscription level) cluster licenses.

**Comment by TomaszKlosinski** [comment]
> Maybe one additional thing to mention here is that ECK only supports so called Enterprise licenses
> https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-licensing.html
> 
> It does not support single Platinum (or any other subscription level) cluster licenses.

That might explain the problem. Our license is Platinum. Does it mean we have to upgrade to Enterprise license to be able to deploy Elasticsearch with X-Pack on K8s with your operator? I guess, we need to ask for the price then, but if it's too high, we'll use another operator instead (or we will stick to basic, or we will switch to completely different solution). It's a bit disappointing, as we pay crazy amount of money for the Platinum license and we can't even deploy it now.

**Comment by agup006** [comment]
Heya @TomaszKlosinski ,
>“Does it mean we have to upgrade to Enterprise license to be able to deploy Elasticsearch with X-Pack on K8s with your operator?”

You are correct, our gold, platinum features require the enterprise subscription for ECK. I recommend syncing with your Elastic rep on the differences as ECK is one benefit, but there are also additional enterprise features today with endpoint and on the horizon for both the Elastic Stack and ECK. We do have plans to make this a bit more clear in the product itself, similar to our subscription page (https://www.elastic.co/subscriptions/enterprise), and agree we can help clarify this more in the documentation. 

Appreciate your input

**Comment by agup006** [comment]
Going to close, as issues are now being handled by support
