### ISSUE TITLE
elastic-operator scheduled to Windows node

### ISSUE THREAD

**Issue by zhiweiv** [elastic/cloud-on-k8s#2447]
## Bug Report
**What did you do?**
I applied eck to a hybrid cluster(Windows nodes + Linux nodes).
kubectl apply -f https://download.elastic.co/downloads/eck/1.0.0/all-in-one.yaml

**What did you expect to see?**
elastic-operator starts successfully.

**What did you see instead?**
The elastic-operator was scheduled to Windows node, and failed to start.
Output:
```
C:\Users\zwliu>kubectl -n elastic-system get pods -o wide
NAME                 READY   STATUS             RESTARTS   AGE   IP            NODE         
elastic-operator-0   0/1     ImagePullBackOff   0          64s   10.10.0.113   akswin1000000
```

* ECK version:
1.0.0

Can we add node selector to force it scheduled to linux nodes?
```
nodeSelector:
    kubernetes.io/os: linux
```

**Comment by barkbay** [comment]
Speaking of the operator itself it is deployed on K8S with a `Statefulset` _(as long as you are using the all in one manifest you have mentioned)_

If you want to add a `nodeSelector` you can edit the `StatefulSet` or patch it with something like that:

```bash
$ kubectl patch statefulset elastic-operator  -p '{"spec": {"template": {"spec": {"nodeSelector": {"kubernetes.io/os": "linux"}}}}}'
```

_Note that on some deployment the right could be `beta.kubernetes.io/os`_

**Comment by zhiweiv** [comment]
Thanks for the workaround, since the operator can only run in Linux nodes,  will the nodeSelector added to default all-in-one.yaml by default in future release?

**Comment by barkbay** [comment]
Unfortunately some deployments are still relying on the old label (`beta.kubernetes.io/os`). It would break the user experience for them. Assuming that most people are not using hybrid environments and until this label is more widely used I'm not sure it is an option for the moment.

**Comment by zhiweiv** [comment]
OK, got it.

**Comment by zhiweiv** [comment]
@barkbay 
It has been two years since then, is it safe to add **nodeSelector: kubernetes.io/os: linux** to elastic-operator by default now?

**Comment by jmp601** [comment]
Premium customer here would like to know the same thing. How do we specify the Elastic ECK operator to go to a specific node?

**Comment by barkbay** [comment]
> Premium customer here would like to know the same thing. How do we specify the Elastic ECK operator to go to a specific node?

The Helm chart allows you to specify a `nodeSelector`:

```
helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace --set nodeSelector."kubernetes\.io/hostname"=my-node-name
```

If you are not using the Helm chart the `StatefulSet` must be updated manually, either in the manifest or by using the [patch command](https://github.com/elastic/cloud-on-k8s/issues/2447#issuecomment-576135443).
