### ISSUE TITLE
Document known storage options for use with ECK

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2456]
Since it's a common question, we should write up a doc and refer to it. It would be a good opportunity to share recommendations if we decide we want to provide any.

**Comment by shubhaat** [comment]
This is internally documented at : https://github.com/elastic/k8s-dev/blob/master/eck-storage-recommendations.md

**Comment by shubhaat** [comment]
Can we make this public, this is the single most popular questions from customers.

**Comment by shubhaat** [comment]
@pebrc - can this be scheduled for current milestone or next milestone?
