### ISSUE TITLE
Operator upgrade crashes helm upgrades

### ISSUE THREAD

**Issue by kaufmo** [elastic/cloud-on-k8s#2470]
Since I've upgraded the operator from 1.0.0-beta1 to 1.0.0 (`kubectl apply -f https://download.elastic.co/downloads/eck/1.0.0/all-in-one.yaml`) my helm install/upgrade still fails when I'm using v1 for the elasticsearch template. Does anyone know what I've made wrong?

Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Elasticsearch, namespace: xxx, name: xxx

```
$ kubectl version
```
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`

```
$ helm version
```
`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

**Comment by sebgl** [comment]
Hi @kaufmo,

Can you paste the exact error provided by Helm (I guess the `xxx` are an example in your post).
How are you using Helm with ECK? We don't provide any Helm charts at the moment.

**Comment by anyasabo** [comment]
I believe this is a [known issue](https://github.com/helm/helm/issues/6850#issuecomment-559552700) with helm -- my understanding is that it does not support changing the api version of an already-deployed resource in a chart. My understanding is also that until that is fixed you would need to remove the previous chart deployment and re-install it.
