### ISSUE TITLE
Document how to set up Ingress with a Google Cloud HTTP load balancer

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2489]
https://discuss.elastic.co/t/possible-problem-with-elasticsearch-readinessprobe/217094

highlights issues setting up an Ingress with Google Cloud's HTTP load balancer. We should write documentation that gives an example of how to do that and addresses issues around: 
* ECK's self-signed TLS certificates (if run in default configuration)
* HTTP vs. HTTP health checks run by the load balancer

**Comment by tadgh** [comment]
To elaborate on my discuss forum topic: What I Essentially wanted is to use GCP Ingress with a google ManagedCertificate to handle TLS termination from the various filebeat clients that will be connecting. My previous solution was to just expose a LoadBalancer from the Elasticsearch service, but then filebeat was reliant on the self-signed cert, which I would have to roll around replacing once a year.
