### ISSUE TITLE
Check for go => 1.13 in the dev requirements

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2526]
Reported by a friendly developer:

After running `make bootstrap-k8s`, I am getting:
```sh
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [Makefile:271: build-deployer] Error 2
```
It turns out that he had go in version `1.10` and you need at least go `1.11`.

`make check-requisites` should reflect that requirement.

**Comment by charith-elastic** [comment]
Also related: #2494

**Comment by thbkrkr** [comment]
go1.11 could be enough. But as the project uses go1.13 to build and test the operator, it is better to requite at least the same version.
