### ISSUE TITLE
How to change initial boot up password for running cluster

### ISSUE THREAD

**Issue by bikkinamahesh369** [elastic/cloud-on-k8s#2532]
I brought up an elastic cluster with a certain username and password through Elastic Cloud Kubernetes.
Now I want to change the password of bootup user for an existing cluster
Is there any way?

**Comment by charith-elastic** [comment]
> I brought up an elastic cluster with a certain username and password through Elastic Cloud Kubernetes.

Did you do this by creating the `[cluster]-es-elastic-user` secret manually?

> Now I want to change the password of bootup user for an existing cluster
> Is there any way?

I am assuming that by "bootup user" you are referring to the `elastic` user created by the operator. Unfortunately, there is no non-disruptive way of changing the password of operator-generated users once the cluster is running. If you want a user whose credentials need to be changed,  you should create a [native realm user](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/security-api.html#security-user-apis) (or, any other authentication realm you prefer).

**Comment by charith-elastic** [comment]
If you have further questions that are not bug reports, please post on https://discuss.elastic.co/c/eck. GitHub issues are mainly for discussing bugs and technical details pertaining to the operator.
