### ISSUE TITLE
Improve Elasticsearch memory requirements documentation

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2557]
I think the current doc could be improved. JVM heap size and memory requirements documentation is spread over 3 different pages:
  * the [podTemplate page] demonstrates how the JVM heap size can be overridden, but does not mention resource reqs
  * the [managing compute resources page](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-compute-resources-elasticsearch) descibes resource requests and limits but not JVM heap size. The example does override the JVM heap size though.
  * the [JVM heap size page](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-jvm-heap-size.html) mentions the `JAVA_OPTS` environment variable and resource reqs but does not provide any example.

I think we also want to make it clear that we recommend setting memory requests and limits to twice the JVM heap size.

**Comment by alaudazzi** [comment]
After discussion with @sebgl: 

- https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-pod-template.html:
Keep it and replace the latest example (related to JVM heap size) with a different example

- https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-jvm-heap-size.html:
remove it as it duplicates content already available on https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html
(before removing, make sure all the info is maintained in Managing compute resources)

**Comment by alaudazzi** [comment]
@sebgl can you please provide an appropriate example for https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-pod-template.html?

**Comment by sebgl** [comment]
> @sebgl can you please provide an appropriate example for https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-pod-template.html?

Looking at it I think it is fine to just remove this example. The other example and the links to the Kubernetes documentation seem enough to me.

**Comment by charith-elastic** [comment]
I was thinking of suggesting that we move the pod template document out of the Elasticsearch section because pod templates are applicable to Kibana and APM Server as well. We should probably provide an example each because the location of `podTemplate` in the manifest is different.

**Comment by alaudazzi** [comment]
Further discussing with @charith-elastic:
Let's reconsider the https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-jvm-heap-size.html removal when we get to a more global reorg of the [Run Elasticsearch on ECK](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-elasticsearch-specification.html) section.

**Comment by alaudazzi** [comment]
This issue might be closed in favour of #2673, where the section https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-jvm-heap-size.html will be part of a general reorganisation of the topics currently under [Run Elastic on ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elasticsearch-specification.html).

**Comment by alaudazzi** [comment]
Close in favour of #2673.
