### ISSUE TITLE
E2E Tests: test snapshot releases of the stack

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2565]
In order to improve our confidence in the compatibility of ECK with future releases of the stack we should have some e2e tests to check that ECK can deploy and manage (e.g. upgrade) current snapshot releases of the stack.

Related to:
https://github.com/elastic/cloud-on-k8s/issues/2560
https://github.com/elastic/cloud-on-k8s/issues/2253

Example of issue that should be catch in advance:
https://github.com/elastic/cloud-on-k8s/issues/2445

**Comment by pebrc** [comment]
Reopening as the initial implementation was based on a misunderstanding of our Jenkins build pipelines :-(
