### ISSUE TITLE
Do not set the default elasticsearch-data volume if some other claims are provided in the ES manifest

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2574]
Discovered while investigating https://discuss.elastic.co/t/how-to-define-multiple-path-data-pointing-to-separate-volumes-or-pvc-using-eck/218644.

If I provide my custom `VolumeClaimTemplates`, decide to give them my own name, and handle the volume and mount point stuff myself, ECK still triggers the creation of a default `elasticsearch-data` PersistentVolume that I don't want to use.

It means that if I want to use multiple data volumes as described in https://discuss.elastic.co/t/how-to-define-multiple-path-data-pointing-to-separate-volumes-or-pvc-using-eck/218644, I need to make sure one of them is named `elasticsearch-data`, whereas I would probably have prefered `elasticsearch-data1`, `elasticsearch-data2`, etc.

I think if any VolumeClaimTemplates is provided, we should not set the default one.

**Comment by pebrc** [comment]
Is there a use case where you want to mount additional volumes e.g. to log to a file but don't want to actually change the data volumes, where this suggested change would be problem?
