### ISSUE TITLE
WebhookServiceName and WebhookConfigurationName are not configurable

### ISSUE THREAD

**Issue by vaishali-prophecy** [elastic/cloud-on-k8s#2581]
I am writing helm chart for ECK deployment and seems like webhook service name and configuration name cannot be changed in their manifests. Any reasons for hardcoding it?

Also how can multiple labels be passed to WEBHOOK_PODS_LABEL env variable?

**Comment by sebgl** [comment]
> I am writing helm chart for ECK deployment and seems like webhook service name and configuration name cannot be changed in their manifests. Any reasons for hardcoding it?

No good reason AFAIK. It seems legit to allow passing them through an optional operator flag.

> Also how can multiple labels be passed to WEBHOOK_PODS_LABEL env variable?

Interesting. Looking at the code and the manifests I don't see this variable being used anywhere. I think it may come from an old version of the operator. We should remove it. I created a dedicated issue: https://github.com/elastic/cloud-on-k8s/issues/2582.
The webhook pod selector is achieved through:

```
  selector:
    control-plane: elastic-operator
```

This can be customized in the `elastic-webhook-server` service spec, in ECK yaml manifest.

**Comment by vaishali-prophecy** [comment]
@sebgl For the label part, do you mean that whatever selector label I would configure for the elastic-webhook-server, the webhook pods would be created with the same label by the operator?

**Comment by sebgl** [comment]
There are no additional webhook Pods: the webhook is the operator Pod itself (it does both act as operator + webhook receiver).
The selector label you configure for the `elastic-webhook-server ` service must match labels set on the operator Pod.

**Comment by sebgl** [comment]
@vaishali-prophecy please let me know if that works for you, and reopen if needed!
