### ISSUE TITLE
$WEBHOOK_PODS_LABEL specified in the operator manifest does not seem useful

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2582]
Forked from https://github.com/elastic/cloud-on-k8s/issues/2581.

We specify a misleading `$WEBHOOK_PODS_LABEL` environment variable in the webhook manifest. Looking through the code I don't see where this is used.
The Webhook specification explicitly targets the `elastic-webhook-server` service, which itself targets Pods with this label:
`control-plane: elastic-operator`

**Comment by thbkrkr** [comment]
jenkins test this please
