### ISSUE TITLE
Rename pause annotation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2594]
`common.k8s.elastic.co/pause: "true"` is somewhat misleading as it might indicate to users that it pauses the managed containers i.e. the Elasticsearch processes which is of course not the case. 

* Let's find a better name. A few ideas:
  * `common.k8s.elastic.co/suspend-reconciliation` (or `pause-reconciliation`)
  * `common.k8s.elastic.co/freeze` (or `freeze-config`)
  * `common.k8s.elastic.co/cordon` (maybe problematic as you can cordon k8s nodes as well)
  * `common.k8s.elastic.co/lock-config`  
* Rename and document the new annotation

**Comment by thbkrkr** [comment]
Another proposal: `common.k8s.elastic.co/managed`.

Influenced by Google Config Sync which has a similar mechanism with an annotation [to start and stop managing an object without deleting it](https://cloud.google.com/kubernetes-engine/docs/add-on/config-sync/how-to/managing-objects).

**Comment by charith-elastic** [comment]
+1 for `managed` but maybe like `eck.k8s.elastic.co/managed` to make it explicit that they are opting out of ECK management.

Alternatively, `eck.k8s.elastic.co/ignore` might be simpler.

**Comment by thbkrkr** [comment]
+1 for `eck.k8s.elastic.co/.*` instead of `common.k8s.elastic.co/.*` if we can :]
