### ISSUE TITLE
Setting up an ES cluster with ECK operator 1.0.0 and official ES 7.6.0 image fails on EKS

### ISSUE THREAD

**Issue by jgoeres** [elastic/cloud-on-k8s#2620]
Hi,

I had successfully used ECK 1.0.0 with the official ES 7.5.2 image on minikube and EKS environments.
I recently updated to ES 7.6.0. On minikube environments this still works as before, on EKS the pods go into CrashLoopBackoff.
The log message is 

ERROR: File ..data/elastic-internal-probe (target of symlink /mnt/elastic-internal/probe-user/elastic-internal-probe from PROBE_PASSWORD_FILE) must have file permissions 400 or 600, but actually has: 644

This has already been mentioned here:
https://discuss.elastic.co/t/error-migrating-elastic-search-from-7-5-0-to-7-6-0/219841

Regards

jugo

**Comment by barkbay** [comment]
This should be fixed by https://github.com/elastic/cloud-on-k8s/pull/2180 

I would suggest to check that you are actually using the latest version of ECK (1.0.1) when using ES 7.6
