### ISSUE TITLE
cloud-on-k8s-e2e-tests-ocp can no longer push images

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2622]
The merge of #2502 causes a regression that prevents the`cloud-on-k8s-e2e-tests-ocp` job from pushing Docker images.

It is 07824ff64 that breaks it up by splitting the `ci-e2e` target (note: `docker-push` is no longer a subtask of it).

I had identified that `docker-push` and `e2e-docker-push` implicitly obtains access to the GCR docker registry via the `run-deployer`. I knew it was bad. I did not dare to question it at that time because there were already many other changes in the PR.

For OCP, it is currently `docker-push` that takes care of configuring the Docker auth (c17a127e7b3cd). I found this suspicious but [didn't really understand why](https://github.com/elastic/cloud-on-k8s/pull/2432#discussion_r377648088).

**Comment by thbkrkr** [comment]
We need to choose where we call `gcloud auth configure-docker --quiet`.

It can be in the deployer like we do in the gke provider of the deployer:

```diff
diff --git a/hack/deployer/runner/ocp.go b/hack/deployer/runner/ocp.go
index d58b3508..77d36005 100644
--- a/hack/deployer/runner/ocp.go
+++ b/hack/deployer/runner/ocp.go
@@ -170,6 +170,10 @@ func (d *OcpDriver) Execute() error {
                        return err
                }
 
+               if err := d.configureDocker(); err != nil {
+                       return err
+               }
+
                if err := createStorageClass(DefaultStorageClass); err != nil {
                        return err
                }
@@ -181,6 +185,12 @@ func (d *OcpDriver) Execute() error {
        return err
 }
 
+func (d *OcpDriver) configureDocker() error {
+       log.Println("Configuring Docker...")
+       return NewCommand("gcloud auth configure-docker --quiet").Run()
+}
+
+
```

Or in the `e2e-docker-push` target:

```diff
diff --git a/Makefile b/Makefile
index d0f05752..1431e04d 100644
--- a/Makefile
+++ b/Makefile
@@ -360,6 +360,9 @@ e2e-docker-build: clean
        docker build --build-arg E2E_JSON=$(E2E_JSON) -t $(E2E_IMG) -f test/e2e/Dockerfile .
 
 e2e-docker-push:
+ifeq ($(REGISTRY), eu.gcr.io)
+       gcloud auth configure-docker --quiet
+endif
```

I dislike option 1 because this is implicit for the push make targets which need it.
I dislike option 2 because it adds an `if` in the Makefile which is already quite complicated.
But to choose, I would tend towards 2.

**Comment by pebrc** [comment]
I take an extra `if` anytime over an implicit step.

**Comment by thbkrkr** [comment]
It's a little more complex than what I explained because I forgot to take into account the AKS case.

For AKS, the deployer calls `az acr login --name {{.AcrName}}` with the ACR name retrieved from Vault. It seems bad to do an exception for AKS. To move the Docker auth for AKS in the Makefile, we need to introduce a new ACR_NAME variable set in the Jenkinsfile.

If we are consistent with what we are doing for the GCloud project, we managed it using a Jenkins credential. We can also reconsider how this information is sensitive. I don't have a strong opinion about this.

**Comment by david-kow** [comment]
Maybe it's worth to consider moving to a single Docker repo now? We wouldn't have this problem then. Also, with EKS support (#1257) we would be adding another registry and another auth we need to support.

If not, then I'd be for reconsidering how sensitive is that (as @thbkrkr mentioned). Preferably, I'd do the same with GCloudProject.

I'd be against using more Jenkins credentials if at all possible as, IIUC, it's harder to manage.

**Comment by thbkrkr** [comment]
> Maybe it's worth to consider moving to a single Docker repo now?

Agree and favorable to do the move.

**Comment by pebrc** [comment]
As this will be solved by moving to `docker.elastic.co` can we close this?

**Comment by thbkrkr** [comment]
Yes.
