### ISSUE TITLE
Refactor cert generation

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#2624]
Follow up to https://github.com/elastic/cloud-on-k8s/pull/2541

As discussed in the earlier PR, there's likely room to refactor the certificate generation across different products. In each product we generate certificate chains, only to right away re-parse the output to grab the primary certificate so we can schedule a requeue before it expires. This can likely be simplified, perhaps by returning a `Results` inside of the certificate generation.

**Comment by charith-elastic** [comment]
Related: #1841

**Comment by anyasabo** [comment]
Closing in favor of the existing issue I missed, thanks @charith-elastic
