### ISSUE TITLE
Potential data loss when downscaling nodes

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2627]
We are currently migrating shards away via allocation excludes from nodes that are about to be removed from the cluster. But our migration logic declares the migration to be finished as soon as it sees at least one copy of each shard in `STARTED` state on any other node in the cluster. 

This opens up a small window for data loss in the case where we don't wait for a shard that has copies elsewhere in the cluster to migrate away: 
* if the shard is a primary a write might not be replicated yet to its replicas at the time we kill the node
* if the shard is a replica it might be promoted to primary at any time and then the above applies here as well

We should therefore fully evacuate Elasticsearch nodes before downscaling to avoid this scenario.

cc @DaveCTurner

**Comment by DaveCTurner** [comment]
Exactly.

Relates https://github.com/elastic/elasticsearch/issues/49064 in which we hope to implement an API that tells orchestration tools like ECK when it is safe to shut down a node, and to help them get nodes into that safe state. Until that arrives, "don't shut down nonempty nodes" is a good workaround.

**Comment by pebrc** [comment]
Replicating the high-level recipe for this discussed in another context:


> *    set the numbers of replicas according to the target cluster size (as far as possible)
> *    disable shard allocation to the node
> *    wait for all shards to move elsewhere, or until no further shard movement is possible

This one is tricky for us to implement I guess, how do we detect that condition and how long to we wait? Do we look at ongoing recoveries for the remaining shards?
> *    if any shards remain on the node, and there are copies of that shard elsewhere, then forcibly evacuate them from the node by cancelling their allocations
> *    wait for the cluster to be in yellow or green health with no shards on the node
> *    shut the node down
> *    ensure the master has removed the node from the cluster and yet it still has yellow or green health
> *   destroy the node

> If the cluster isn't at least at yellow health after shutting the node down then the node should be restarted since despite our efforts it may still contain the only good copy of one or more shards.

That one is interesting as well: would we upscale again, ignoring the node count in the spec if the cluster goes red after this operation?

**Comment by DaveCTurner** [comment]
> how do we detect that condition and how long to we wait? Do we look at ongoing recoveries for the remaining shards?

A sufficient condition for "no further shard movement is possible" is that `GET _cluster/health?wait_for_no_relocating_shards&wait_for_no_initializing_shards&wait_for_events=languid` returns successfully. If the cluster is large and messy enough then it may always have relocating/initializing shards so that this cluster health call will never return successfully, but I expect clusters that large to have less trouble evacuating nodes too.

> That one is interesting as well: would we upscale again

It depends what you mean by "upscale". You must start the node that was shut down (but not destroyed) earlier in the process, using exactly the same data path that it had before, since the fact that the cluster went `red` when it shut down means that this data path contains the only good copy of at least one shard. That means we failed to evacuate it properly earlier on.

**Comment by DaveCTurner** [comment]
On reflection this last bit about restarting the node might be excessively paranoid. It only matters if another node fails during the downscaling process, taking a `yellow` shard to `red`. However another node could fail a bit later and take a `yellow` shard to `red` anyway, independently of any downscaling that's going on, so maybe it doesn't gain us anything.

**Comment by pebrc** [comment]
Ah OK, we were just wondering the same thing offline. That makes the implementation a lot easier.

**Comment by pebrc** [comment]
Trying to deriving a more low level ECK-specific recipe from this: 

> * set the numbers of replicas according to the target cluster size (as far as possible)

We can update all indices at once if necessary. 
```
PUT /_all/_settings
{
    "index" : {
        "number_of_replicas" :$NUM_REPLICAS
    }
}
```
But there are a couple of questions: 
* what is the right value for `NUM_REPLICAS` here? `new_num_data_nodes -1`? 
* users might have chosen to run with different replica settings per index to begin with
* should we try to evacuate the node with the existing settings first before trying to change settings
* should we try to change the settings only for those indices that have shards on the node that is about to be retired (we would need to disable shard allocation first)
* can we avoid this step altogether and just try cancellation instead? 

> * disable shard allocation to the node
> * wait for all shards to move elsewhere, or until no further shard movement is possible

We could do as Dave suggested:
1.  `GET _cluster/health?wait_for_no_relocating_shards&wait_for_no_initializing_shards&wait_for_events=languid&timeout=1s` (note the added timeout to minimize blocking the reconciliation loop too long)
2. check the returned value for `"timed_out":false`
    * if `"timed_out":true` re-queue the reconciliation and increment an in-memory counter that tracks how many times we have re-queued the reconciliation at this step for this particular cluster. Once we exceed a max number of re-queues (or an overall timeout value for this step if we want to track a timestamp instead)  mark the counter as completed (we don't remove the counter just yet to avoid getting stuck at this step) and continue 
    * if `"timed_out": false` mark the counter as completed

> * if any shards remain on the node, and there are copies of that shard elsewhere, then forcibly evacuate them from the node by cancelling their allocations

The reroute  API has a `commands attribute that can contain multiple `cancel` commands one for each shard remaining on the node.

```
POST _cluster/reroute
{
    "commands" : [
        {
          "cancel": {
                "index" : "my-index", "shard" : 0,
                "node" : "remote-tgt-es-default-2"
          },
          "cancel": {
                "index" : "my-other-index", "shard" : 0,
                "node" : "remote-tgt-es-default-2"
          }

        }
    ]
}
```

If we re-issue this command on subsequent reconciliation loop iterations I wonder if might get `HTTP 400 illegal_argument_exception` which we need to deal with (I assume this could only happen if cancelling the allocation is not instantaneous. So that the shard is still on the node when we make the branching decision to (re-)try the `reroute` call but gone when the actual call is made) 

> * wait for the cluster to be in yellow or green health with no shards on the node
> * shut the node down

This means deleting the pod in ECK terms and at this point we can clear the in-memory counter that keeps track of how long we waited for shards to move away from the now destroyed node.


#### Why only an in-memory counter?
Because in the worst case, if we lose the in-memory state, we wait a bit longer than we wanted. Persistent state e.g. as an annotation seems too heavy-weight for this, we are already doing a lot of annotation updates etc

**Comment by pebrc** [comment]
Discussed with @sebgl offline and we think we want to break this down into smaller steps as follows:
1. avoid data loss by changing our 'safe to delete' check to only allow node deletion if no shards reside on the node that is about to be removed #2710 
    This will lead to downscale operations that get stuck. We will address this through documentation and support and adivse users to adjust their replica settings
2. create a mechanism to track timeouts on operations in ECK #2712
    Use this mechanism to create an event warning users of stuck node evacuations and pointing them towards reconfiguring their replica settings
3. force node evacuation by cancelling allocations #2713
    This means largely implementing the recipe outlined in this issue. 

The one thing we still shy away from is actually touching index settings, which seems like an overreach for the orchestrator and leaves a few questions open (see https://github.com/elastic/cloud-on-k8s/issues/2627#issuecomment-599741359)

**Comment by pebrc** [comment]
Since #4597 we are using the new node shutdown API to orchestrate scaling down Elasticsearch clusters. I am therefore closing this issue as we are not going to implement any further workarounds beyond #2710 for older versions of Elasticsearch.
