### ISSUE TITLE
How to add own config to elasticsearch.yml?

### ISSUE THREAD

**Issue by cxnam** [elastic/cloud-on-k8s#2628]
I need to use Reindex from a remote. How do I add **_reindex.remote.whitelist:_** to elasticsearch.yml

I have read the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-bundles-plugins.html), but not understanding more so overwriting the elasticsearch.yml file of the operator created? Can you explain it to me? Tks

**Comment by pebrc** [comment]
Have look at https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html 

Also can I ask you to take this discussion to https://discuss.elastic.co/c/eck and reserve Github issues for bug reports an feature requests. Happy to discuss more there if needed.
