### ISSUE TITLE
failed to reserve container name for e2e tests on kind 1.17

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2632]
[cloud-on-k8s-e2e-tests-kind-k8s-versions/6/](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-kind-k8s-versions/6/) and [cloud-on-k8s-e2e-tests-kind-k8s-versions/10/](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-kind-k8s-versions/10/) fail on kind `1.17` to start the pods of the operator (`e2e-savgl-operator-0`) and the e2e test job (`eck-e2e-savgl-rlfn6`) because "_their container name is already reserved_":

```sh
{"@ts":"2020-02-28T00:30:09.498Z","msg":"Waiting for test job to start"}
{"@ts":"2020-02-28T00:30:09.520Z","msg":"Pod added","name":"eck-e2e-savgl-rlfn6"}
{"@ts":"2020-02-28T00:30:19.520Z","msg":"Waiting for pod to be ready","name":"eck-e2e-savgl-rlfn6","status":"Pending"}
{"@ts":"2020-02-28T00:32:19.523Z","msg":"Waiting for pod to be ready","name":"eck-e2e-savgl-rlfn6","status":"Pending"}
{"@ts":"2020-02-28T00:32:25.541Z","msg":"Pod is in failed state","name":"eck-e2e-savgl-rlfn6"}
{"@ts":"2020-02-28T00:32:25.542Z","msg":"Cluster event log"}
01:32:26  {
    "reason": "Failed",
    "msg": "Error: context deadline exceeded",
    "kind": "Pod",
    "name": "e2e-savgl-operator-0",
    "namespace": "e2e-savgl-elastic-system"
}
01:32:26  {
    "reason": "Failed",
    "msg": "Error: context deadline exceeded",
    "kind": "Pod",
    "name": "eck-e2e-savgl-rlfn6",
    "namespace": "e2e-savgl"
}
01:32:26  {
    "reason": "Failed",
    "msg": "Error: failed to reserve container name \"manager_e2e-savgl-operator-0_e2e-savgl-elastic-system_a0b09fa1-4f0f-4451-bc9c-c8ab03057fab_0\": name \"manager_e2e-savgl-operator-0_e2e-savgl-elastic-system_a0b09fa1-4f0f-4451-bc9c-c8ab03057fab_0\" is reserved for \"2319a07601bbb0803e436597c11c85dd36a46a26cbbd0ac926e22a8a0856be9f\"",
    "kind": "Pod",
    "name": "e2e-savgl-operator-0",
    "namespace": "e2e-savgl-elastic-system"
}
01:32:26  {
    "reason": "Failed",
    "msg": "Error: failed to reserve container name \"e2e_eck-e2e-savgl-rlfn6_e2e-savgl_e70645a4-fca1-4e5c-9d15-588e699688be_0\": name \"e2e_eck-e2e-savgl-rlfn6_e2e-savgl_e70645a4-fca1-4e5c-9d15-588e699688be_0\" is reserved for \"e0700e73d6877e064c68531247f70b5bc64ac86de01878750910755d4cfd8fde\"",
    "kind": "Pod",
    "name": "eck-e2e-savgl-rlfn6",
    "namespace": "e2e-savgl"
}
```

I don't know if the k8s version has a role.
I will try to reproduce.

**Comment by sebgl** [comment]
Also happened in https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-kind-k8s-versions/detail/cloud-on-k8s-e2e-tests-kind-k8s-versions/74/pipeline.

**Comment by thbkrkr** [comment]
I never succeeded to reproduce the problem locally but I finally reproduced it once using almost the same machine as in CI: n1-standard-16 (16 vCPUs, 60 GB memory) + ubuntu-16.04.

[Here](https://gist.github.com/thbkrkr/6aef2c4e36c01fbc0cf2cd6f47e0baba) are the log of the kubelet of the 3 workers. I don't know what to think. They are full of errors. I also have a lot of these errors in local but never `"failed to reserve container name"`.

During the test, the operator pod failed to start on worker3. We can see the `"failed to reserve container name"` error occurred 21 times between 09:04:49 and 09:09:01 in the kubelet log of this worker.

As soon as I saw the error, I interrupted the e2e tests runner to not delete the k8s resources. It's interesting to note that the operator pod was eventually created and running (first start at 09:09:14Z when the error `"failed to reserve container name"` stopped) after 1 restart (due to `Timeout elapsed waiting for webhook certificate to be available`).

My first feeling is that running a `kind` 3-nodes cluster seems to be very resources intensive. This issue happens only with k8s 1.16.4 and 1.17.0, never with 1.12.10. It might make sense that newer versions of k8s required a little more resources.

**Comment by thbkrkr** [comment]
#3123 decreases the failure rate but does not completely solve the problem (2 in the last 14 executions have encountered this problem).

**Comment by sebgl** [comment]
@thbkrkr do you think increasing the timeout even more could help?

**Comment by thbkrkr** [comment]
Certainly but I don't really know. 3 minutes seems already pretty big to just start the operator pod. I'm afraid the docker demon is really in bad shape. However, it does not cost much to increase the timeout to 5 min.

**Comment by thbkrkr** [comment]
Closing as the error has not reappeared for almost two months.
