### ISSUE TITLE
Users should be able to customize the transport service

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2644]
#2543 introduced a transport service to let Elasticsearch nodes communicate to remote Elasticsearch clusters.

A user should be able to control the spec of this service like we do for the HTTP service (e.g. set the type to `LoadBalancer`)

**Comment by pebrc** [comment]
I assume something like this will work: 

```yaml
transport:
   service:
      metadata:
      spec: 
```

Mirroring the format we use for the `http` side but leaving out the `tls` options as we cannot offer TLS configuration on the transport layer (yet)
