### ISSUE TITLE
File based configuration for remote clusters

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2645]
Remote clusters can be configured via [elasticsearch.yaml](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html#configuring-remote-clusters)

Following-up #2543 we should discuss if we want to switch remote clusters configuration to a file based config.

**Comment by pebrc** [comment]
We discussed it already on the PR here https://github.com/elastic/cloud-on-k8s/pull/2543#discussion_r384379195

The arguments against using the file based configuration in `elasticsearch.yml` are
*  it would require a cluster restart to change the settings
*  it is recommended to use `elasticsearch.yml` for node specific settings or settings that need to exist to bootstrap the cluster,  both are not the case here

The only advantage I can see is:
* we would do one less API request against Elasticsearch but we are already optimizing this aspect in https://github.com/elastic/cloud-on-k8s/pull/2891

So maybe OK to close this? Unless ofc there are additional arguments I missing

**Comment by barkbay** [comment]
👍 to close it, the cons seem to outweigh the only advantage this feature would bring.
