### ISSUE TITLE
Add a "HasLabel" utility function

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2646]
There are at least 2 places (remote cluster controller and Kibana assoc. controller) where we are checking if some labels are set on a object.

Let's add a utility function like `label.HasLabel(obj runtime.Object, labels ...string)`

**Comment by bharatnc** [comment]
@barkbay I would like to contribute if this is not yet done. I'll send a PR.

**Comment by bharatnc** [comment]
@barkbay  thanks! I have just submitted a PR: https://github.com/elastic/cloud-on-k8s/pull/2677. Requesting some reviews.
