### ISSUE TITLE
[question]  How do I remove  the first k8s cluster node  of all es used nodes?

### ISSUE THREAD

**Issue by xm5646** [elastic/cloud-on-k8s#2658]
**Why**
I used three nodes as an ES cluster node by label selector "role=es-node", whit names "node1, node2, node3",  And now, the sts-master create three pods on those nodes,  mapping with node1: sts-0,  node2:sts-1, node3:sts-2,   I want remove "node1",  and add new "node4", "node5" into this ES cluster

**My step**

 1. I removed "node1" label "role=es-node",  and add same label to "node4" 
2. I changed the count to 4 from 3 of nodeset in ES 
3. I use the kubectl cmd to delete the pods on  "node1" 

**Result**

The pod was create by sts-0  now is on "node4"

so,  Is there any way to do this node switching in a friendly way?

**Comment by sebgl** [comment]
Your approach looks correct. Deleting a pod manually will force that Pod to be re-scheduled, potentially on a different Kubernetes node. In your situation, from node1 to node4.
I am not aware of any better way to force-reschedule an existing Pod to a different Pod. It would end up in deleting the Pod anyway. Which is fine as long as it is backed by a PersistentVolume that can be moved around.
We could technically implement something using annotations so you can mark a Pod for deletion, but I'm not sure that's necessary.

If your goal is to completely remove node1 from the Kubernetes cluster, the Kubernetes way (TM) of doing this is to drain the node: https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/
The idea would be to run `kubectl drain node <node name>`. The workload on that node, including the Elasticsearch Pod, will be deleted and rescheduled elsewhere.

Please let us know if that makes sense, and reopen the issue if needed.

**Comment by xm5646** [comment]
Thank you, I will consider using 'drain' to delete the Pod, because of my env the selected node is only used by ES cluster, is none of other Pod for application.  This way look a little smoother.
