### ISSUE TITLE
Review error messages

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#2670]
Validation errors and events are some of the main ways we communicate information back to users. We should take a look and make sure they're appropriately helpful. For example, the validation error for resizing PVCs should probably give people an indication of what they can do to resolve it (spin up a new nodeSet, go to the docs, etc.). Some tips from our friendly writing team when reviewing:

![Screen Shot 2020-03-05 at 11 41 13 AM](https://user-images.githubusercontent.com/1638148/76009130-5331b400-5ed6-11ea-96a4-943073bdca7a.png)
![Screen Shot 2020-03-05 at 11 41 25 AM](https://user-images.githubusercontent.com/1638148/76009140-562ca480-5ed6-11ea-848e-ddaaf9c3d3d1.png)

**Comment by alaudazzi** [comment]
Some of the error messages that need to be reviewed:
https://github.com/elastic/cloud-on-k8s/blob/master/pkg/apis/elasticsearch/v1/validations.go#L20

**Comment by alaudazzi** [comment]
@anyasabo 

Back to our meeting on this topic, we might want to refine/complete the error messages as discussed:

cfgInvalidMsg = "Configuration invalid"
=> Can we explain why? How do I get a valid configuration?

masterRequiredMsg = "Elasticsearch needs to have at least one master node"
=> OK

parseVersionErrMsg = "Cannot parse Elasticsearch version"
=> Can we explain why?

parseStoredVersionErrMsg = "Cannot parse current Elasticsearch version"
=> Can we explain why?

invalidSanIPErrMsg = "Invalid SAN IP address"
=> Explain what a valid SAN IP address is.

pvcImmutableMsg = "Volume claim templates cannot be modified"
=> OK

invalidNamesErrMsg = "Elasticsearch configuration would generate resources with invalid names"
=> OK

unsupportedVersionErrMsg = "Unsupported version"
=> Is it worth mentioning what the supported versions are? Might have a maintenance issue.

unsupportedConfigErrMsg  = "Configuration setting is reserved for internal use. User-configured use is unsupported"
=> Probably OK

duplicateNodeSets = "NodeSet names must be unique"
=> OK

noDowngradesMsg = "Downgrades are not supported"
=> OK

unsupportedVersionMsg = "Unsupported version"
=> Is it worth mentioning what the supported versions are? Might have a maintenance issue.

unsupportedUpgradeMsg = "Unsupported version upgrade path"
=> Explain what is supported?

**Comment by anyasabo** [comment]
Sorry for the delay getting back to you @alaudazzi 

>cfgInvalidMsg = "Configuration invalid"
>=> Can we explain why? How do I get a valid configuration?

In this case it is that we fail to parse it. We don't do any validation that it is a sensible Elasticsearch config or anything like that. We use a third party library to try and parse it. I'm not sure what can lead to an error here, I'll need to experiment or maybe someone else has ideas. We do swallow the error and not return it though. I wonder if we want to also return the error we get when parsing.



>parseVersionErrMsg = "Cannot parse Elasticsearch version"
>=> Can we explain why?

Again this is a parsing error. I think we can specify the format though. From the doc of the function we're calling:
>// Parse returns a parsed version of a string from the format {major}.{minor}.{patch}[-{label}]

So if the version doesn't match that it will error out. Again we swallow the error here, it might be worth returning though?

>unsupportedVersionErrMsg = "Unsupported version"
>=> Is it worth mentioning what the supported versions are? Might have a maintenance issue.

Agreed this might be a maintenance burden since we will have the function, the error message, and the doc page to update if anything changes. I'm not totally opposed to it though. We have docs here:
https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s_supported_versions.html

>unsupportedUpgradeMsg = "Unsupported version upgrade path"
>=> Explain what is supported?

It reflects the Elasticsearch [supported upgrade paths](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html). I'm not sure how to clarify that other than adding a lot of some extra logic to explain what a valid upgrade path would be, or linking them to the docs.

**Comment by alaudazzi** [comment]
Thank you @anyasabo. Based on your feedback, let's change the text where it makes sense. The rest should be OK:

### Messages that need to be reworked
**parseVersionErrMsg** = "Cannot parse Elasticsearch version"
=> Cannot parse Elasticsearch version. String format must be {major}.{minor}.{patch}[-{label}.

**parseStoredVersionErrMsg** = "Cannot parse current Elasticsearch version"
=> Is it also related to the format?

**unsupportedUpgradeMsg** = "Unsupported version upgrade path"
=> Unsupported version upgrade path. Check [Elasticsearch supported upgrade paths](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html).

**invalidSanIPErrMsg** = "Invalid SAN IP address"
=> Can we provide the standard format of a valid SAN IP address?

### Messages that are OK
cfgInvalidMsg = "Configuration invalid"
pvcImmutableMsg = "Volume claim templates cannot be modified"
masterRequiredMsg = "Elasticsearch needs to have at least one master node"
invalidNamesErrMsg = "Elasticsearch configuration would generate resources with invalid names"
unsupportedConfigErrMsg = "Configuration setting is reserved for internal use. User-configured use is unsupported"
duplicateNodeSets = "NodeSet names must be unique"
noDowngradesMsg = "Downgrades are not supported"
unsupportedVersionErrMsg = "Unsupported version"
unsupportedVersionMsg = "Unsupported version"

**Comment by alaudazzi** [comment]
@anyasabo can you please check the following ones:
invalidSanIPErrMsg = "Invalid SAN IP address"
invalidNamesErrMsg = "Elasticsearch configuration would generate resources with invalid names"

**Comment by anyasabo** [comment]
>invalidSanIPErrMsg = "Invalid SAN IP address"

This can be clarified with "Invalid SAN IP address. Must be a valid IPv4 address"


>invalidNamesErrMsg = "Elasticsearch configuration would generate resources with invalid names"

I think this is actually okay because when we use it we do include the more specific underlying error message-- it's too long, the name is duplicated, etc

**Comment by alaudazzi** [comment]
Documented as requested.
