### ISSUE TITLE
Review ECK Elasticsearch documentation

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2673]
Follow-up from #2351 

There are currently a lot of topics under the "Run Elastic on ECK" heading in the "Orchestrating Elastic Stack applications" chapter. There is no discernible order or theme to the topics -- which can be confusing to a user trying to read the entire section from top to bottom. Furthermore, some topics such as TLS configuration is not specific to Elasticsearch and should be moved elsewhere in the documentation.

**Comment by alaudazzi** [comment]
@charith-elastic sorry for the late reply on this issue.

To alleviate the overloaded section **Run Elasticsearch on ECK**, I propose to start with the following:

1. Move one level up these sections:
    Run ES on ECK, Run Kibana on ECK, APM on ECK, Access Elastic Stack Services
1. Create a new section **Securing your Elastic Stack** and collect/combine here these topics:
  - Secure settings
  - Security
  - Custom HTTP certificate
  - TLS Certificates
  - HTTP settings and TLS SANs

Let me know if this starting reorg is acceptable. In the meanwhile I'll see how we can further simplify the long section on _Run ES on ECK_.

**Comment by charith-elastic** [comment]
I like your idea about adding a new subsection on security topics. In my mind, the structure is:
- Orchestrating Elastic Stack applications
    - Run Elasticsearch on ECK
    - Run Kibana on ECK
    - Run APM Server on ECK
    - Access Elastic Stack services
    - Customize Pods
    - Manage compute resources
    - Upgrade the Elastic Stack version
    - **Secure the Elastic Stack**
        - Manage Custom certificates
        - Customise TLS settings
        - Manage users and roles
        - Rotate auto-generated credentials

This would be a notable improvement already. The remaining topics under __Run Elasticsearch on ECK__ still lack cohesion but we can address those separately.

**Comment by alaudazzi** [comment]
@charith-elastic I would reuse the content from [Access Elastic Stack services » Security](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-security.html) to create the landing page for **Secure the Elastic Stack**.
What do you think?

**Comment by charith-elastic** [comment]
That sounds OK to me. Maybe later, when the PR is ready and I have more context, I might have a few tweaks to suggest :smile:

**Comment by pebrc** [comment]
Can this be closed? I see the secure setting section is merged into master?
