### ISSUE TITLE
Better warn about volumeBindingMode: WaitForFirstConsumer in the docs

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2686]
We mention `volumeBindingMode: WaitForFirstConsumer ` in https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s_local_persistent_volume_constraints.

That's hidden in the "local storage" section, but it also applies to network attached storage.

We should mentioned it in the volume claim templates section instead: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html

**Comment by pebrc** [comment]
#3708 should be enough for now.
