### ISSUE TITLE
Custom Resource API Reference Docs

### ISSUE THREAD

**Issue by Vad1mo** [elastic/cloud-on-k8s#2754]
The CRD is well documented it would be easy to generate a Custom Resource API Reference Docs

The project https://github.com/ahmetb/gen-crd-api-reference-docs can generate nice API Docs. KNative is using it as well https://knative.dev/docs/reference/eventing/

Would be nice to see  something as well with ECK.

**Comment by pebrc** [comment]
We have that already here https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-reference.html
