### ISSUE TITLE
e2e: remote cluster test on 6.x needs soft deletes enabled

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2761]
CCR on 6.x Elasticsearch versions needs explicit enablement of soft-deletes
```
400 Bad Request: leader index [data-integrity-check] does not have soft deletes enabled. soft deletes must be enabled when the index is created by setting index.soft_deletes.enabled to true
```

See https://www.elastic.co/guide/en/elasticsearch/reference/6.8/ccr-requirements.html

cc @barkbay

**Comment by barkbay** [comment]
My bad, will take care of this one
