### ISSUE TITLE
Error in ECK licensing documentation

### ISSUE THREAD

**Issue by ferozsalam** [elastic/cloud-on-k8s#2787]
## Bug Report
The ECK [licensing documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-licensing.html) states that the `eck-license` secret

> must be in the same namespace as the operator

However we have a setup wherein the operator runs in a different namespace to the Elastic cluster itself. When I applied the license to the operator's namespace, the change did not apply. I enabled verbose logging on the operator and saw that it was searching the Elastic cluster namespace for the license. Adding the secret to the cluster's namespace resolved the issue and the license successfully applied.

The documentation line should be changed to "must be in the same namespace as the cluster" OR there behaviour is not as expected and ECK itself needs changing.

Happy to put in a PR for this myself, if there's agreement that it's just the documentation that needs changing.

**Environment**
ECK version 1.0.1
Kubernetes 1.14
Elasticsearch 7.6.0

**Comment by anyasabo** [comment]
I didn't get a chance to try to reproduce it, but it looks like it is correctly plumbed through with the `operator-namespace` flag in the operator config. Is this set correctly in your operator? By default it should just use the [downward API](https://github.com/elastic/cloud-on-k8s/blob/master/config/operator/all-in-one/operator.template.yaml#L28) and so should be set correctly, but want to double check that is the case here.

**Comment by ferozsalam** [comment]
Some more debugging information in case it helps:

This is from the operator logs - note that it appears to be looking for a license in the `logs` namespace`:

``` 76 {"level":"debug","@timestamp":"2020-03-30T16:17:04.876Z","logger":"es-validation","message":"validate create","ver":"1.0.1-bcb74688","name":"elasticsearch"}
 77 {"level":"debug","@timestamp":"2020-03-30T16:17:04.876Z","logger":"license-controller","message":"No enterprise license found. Attempting to remove cluster license secret","ver":"1.    0.1-bcb74688",**"namespace":"logs"**,"es_name":"elasticsearch"}
 78 {"level":"debug","@timestamp":"2020-03-30T16:17:04.882Z","logger":"license-controller","message":"Reconcile result","ver":"1.0.1-bcb74688","requeue":false,"requeueAfter":3600}
 79 {"level":"info","@timestamp":"2020-03-30T16:17:04.882Z","logger":"license-controller","message":"Ending reconciliation run","ver":"1.0.1-bcb74688","iteration":1,"namespace":"logs","name":"elasticsearch","took":0.106257647}
```

My operator is running in the `eck-operator` namespace:

```
$ kubectl -n eck-operator get po
NAME                 READY   STATUS    RESTARTS   AGE
elastic-operator-0   1/1     Running   0          71m
```
Note that the secret has been in this namespace for longer than the operator has been running, and existed when the operator printed the `No enterprise license found` line above:

```
kubectl -n eck-operator get secrets | grep eck-license
eck-license                    Opaque                                1      7h25m
```

meanwhile, I more recently applied the operator in the `logs` namespace:
```
kubectl -n logs get secrets | grep eck-license                                                                                                                                
eck-license                                   Opaque                                1      57m
```

which immediately fixed the issue with the license in the operator:
```
265 {"level":"info","@timestamp":"2020-03-30T16:34:35.230Z","logger":"license-controller","message":"Starting reconciliation run","ver":"1.0.1-bcb74688","iteration":4,"namespace":"logs","name":"elasticsearch"}
266 {"level":"debug","@timestamp":"2020-03-30T16:34:35.231Z","logger":"license-controller","message":"Found license for cluster","ver":"1.0.1-bcb74688","eck_license":"[redacted]","es_license":"[redacted]","license_type":"enterprise","namespace":"logs","es_name":"elasticsearch"}
267 {"level":"info","@timestamp":"2020-03-30T16:34:35.231Z","logger":"generic-reconciler","message":"Creating resource","ver":"1.0.1-bcb74688","kind":"Secret","namespace":"logs",    "name":"elasticsearch-es-license"}
268 {"level":"info","@timestamp":"2020-03-30T16:34:35.240Z","logger":"elasticsearch-controller","message":"Starting reconciliation run","ver":"1.0.1-bcb74688","iteration":4,"namespace":    "logs","name":"elasticsearch"}
269 {"level":"debug","@timestamp":"2020-03-30T16:34:35.240Z","logger":"es-validation","message":"validate create","ver":"1.0.1-bcb74688","name":"elasticsearch"}
270 {"level":"debug","@timestamp":"2020-03-30T16:34:35.240Z","logger":"license-controller","message":"Reconcile result","ver":"1.0.1-bcb74688","requeue":false,"requeueAfter":36000}
271 {"level":"info","@timestamp":"2020-03-30T16:34:35.240Z","logger":"license-controller","message":"Ending reconciliation run","ver":"1.0.1-bcb74688","iteration":4,"namespace":"logs","name":"elasticsearch","took":0.010745226}
```

@anyasabo my `OPERATOR_NAMESPACE` seems to be set to `(v1:metadata.namespace)` in the StatefulSet config. Not very familiar with the moving parts here, so let me know if there's anything more useful I can run to get you the information you need.

**Comment by pebrc** [comment]
@ferozsalam the log line you quoted here
>
```
77 {"level":"debug","@timestamp":"2020-03-30T16:17:04.876Z","logger":"license-controller","message":"No enterprise license found. Attempting to remove cluster license secret","ver":"1.    0.1-bcb74688","namespace":"logs","es_name":"elasticsearch"}
```

does indeed reference the `log` namespace but this is not because it is *looking* for  license in that namespace but because it trying to find a valid license for the Elasticsearch cluster called `elasticsearch` in the `log` namespace.

Can you check that the license secrets you created have the right metadata?

Something like (requires `jq` to be installed on your system): 
```
kubectl get secret eck-license -n elastic-system -o json | jq '.metadata'
```


What would also be interesting is to double check your operator has the right RBAC permissions to read the license secret in its own namespace: 

```
kubectl auth can-i --list --namespace elastic-operator --as system:serviceaccount:elastic-system:elastic-operator
``` 

should give you an overview of the effective permissions we would expects a line with 
```
secrets                                                                 []                       []               [get list watch create update patch delete]
```
 in there.

**Comment by ferozsalam** [comment]
Hi @pebrc - thanks for looking into this!

I have run the commands you mentioned and here's the output - note that I had to recreate the license  because I had deleted it from the operator's namespace. However it was created in exactly the same manner so the same metadata should apply:

```
$ kubectl get secret eck-license -n eck-operator -o json | jq '.metadata'                                   
{
  "creationTimestamp": "2020-04-02T14:20:36Z",
  "labels": {
    "license.k8s.elastic.co/scope": "operator"
  },
  "name": "eck-license",
  "namespace": "eck-operator",
  "resourceVersion": "2941671",
  "selfLink": "/api/v1/namespaces/eck-operator/secrets/eck-license",
  "uid": "1ed0280f-74ed-11ea-b605-062ed548c216"
}
```

Running your `can-i` command gives me the error `Error: unknown flag: --list`, but a variant of the command does work:

```
$ kubectl auth can-i list secrets --namespace eck-operator --as=system:serviceaccount:eck-operator:elastic-operator                                                                    1 ↵
yes
```

and

```
$ kubectl auth can-i get secrets --namespace eck-operator --as=system:serviceaccount:eck-operator:elastic-operator                                                                     
yes
```

does any of this look wrong to you?

It also might be worth mentioning that I deleted the license from the operator's namespace yesterday, which doesn't appear to have affected the licensing status of the cluster, although I don't know if there's a daemon watching for the removal of the license once it has been applied:

````
sh-4.2# curl -k https://localhost:9200/_license                                                                            
{                           
  "license" : {                   
    "status" : "active",                                                               
    "uid" : "[redacted]",                                        
    "type" : "platinum",                                                                                                               
...
    "start_date_in_millis" : 1585094400000
  }
}
```

**Comment by pebrc** [comment]
@ferozsalam This looks good. You seem to have the necessary RBAC in place (which should be the case when you use the YAML manifests we release). The license secret metadata looks OK too. 

So I am not sure what happened here. Can we be sure that the contents of the secret in the `elastic-system` namespace was OK and identical to the one you created later in the `log` namespace? Do you have any additional logs from the loggers `license-controller` or `license` you could share?

> It also might be worth mentioning that I deleted the license from the operator's namespace yesterday, which doesn't appear to have affected the licensing status of the cluster, although I don't know if there's a daemon watching for the removal of the license once it has been 

So do you still have a license secret somewhere in a namespace the operator can access? If so the your clusters will stay on platinum/enterprise. Once you remove the license secret they will go back to a Basic license.

**Comment by ferozsalam** [comment]
Yes, the original license secret that seemed to trigger the change in cluster state (and my suspicion that the docs were incorrect) was placed in the `logs` namespace, and I haven't touched it.

I am trying to replicate this in minikube - I'll post here if I'm successful, hopefully with extensive logs.

**Comment by ferozsalam** [comment]
After some investigation, I have been unable to replicate this locally - so either there was some other issue with my configuration that resolved itself, or I was entirely mistaken. Sorry for the bother, and thanks for your help!
