### ISSUE TITLE
Setup an always up-to-date QA/staging environment

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#279]
We should probably have an always-on k8s cluster on GCP, with an always up-to-date operator (latest master).
I guess we can pre-create the cluster, and Jenkins would be responsible to deploy the operator. Meaning it needs the cluster credentials. We should probably check with infra team how we can set this up.

**Comment by pebrc** [comment]
I wonder if we can close this in favour of https://github.com/elastic/cloud-on-k8s/issues/2270
