### ISSUE TITLE
Updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by scarby** [elastic/cloud-on-k8s#2804]
## Bug Report
**What did you do?**

After updating my elasticsearch resource in order to add an init container for plugins and secureSettings  then using kubectl apply to update the resource,  no changes were propagated to the statefulSet - the statefulSet remained unchanged, no init containers were added and nothing happened

**What did you expect to see?**

after changing elasticsearch repo i expected the statefulSet to update, containing new initContainers to perform the plugin installation and secure setting addition

**What did you see instead? Under which circumstances?**

My original elasticsearch YAML was:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    common.k8s.elastic.co/controller-version: 1.0.0
    elasticsearch.k8s.elastic.co/cluster-uuid: 1gZHNvZSSwK_0jP7QrFJpg
  creationTimestamp: "2020-01-30T04:21:35Z"
  generation: 8
  name: logs
  namespace: logs
  resourceVersion: "33560353"
  selfLink: /apis/elasticsearch.k8s.elastic.co/v1/namespaces/logs/elasticsearches/logs
  uid: d346d27a-1717-4627-b34a-2aaf86de020f
spec:
  http:
    service:
      metadata:
        creationTimestamp: null
      spec:
        type: LoadBalancer
    tls:
      certificate:
        secretName:es-tls
  nodeSets:
  - config:
      node.data: true
      node.ingest: true
      node.master: true
      node.store.allow_mmap: true
    count: 3
    name: logs
    podTemplate:
      spec:
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            requests:
              memory: 8Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: gce-ssd
  updateStrategy:
    changeBudget: {}
  version: 7.5.0
```

Moving to:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
spec:
  http:
    service:
      metadata:
        creationTimestamp: null
      spec:
        type: LoadBalancer
    tls:
      certificate:
        secretName:tls
  nodeSets:
  - config:
      node.data: true
      node.ingest: true
      node.master: true
      node.store.allow_mmap: true
    count: 3
    name: logs
    podTemplate:
      spec:
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            requests:
              memory: 8Gi
        initContainers:
        - command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
          name: install-plugins
    volumeClaimTemplates:
    - metadata:
        name: logs
        namespace: logs
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: gce-ssd
  secureSettings:
  - secretName: gcs-credentials
  updateStrategy:
    changeBudget: {}
  version: 7.5.0
```

despite getting no errors when running kubectl apply i receive the following error from the pod:

{"level":"error","@timestamp":"2020-04-02T01:49:23.311Z","logger":"controller-runtime.controller","message":"Reconciler error","ver":"1.0.0-6881438d","controller":"elasticsearch-controller","request":"logs/logs","error":"StatefulSet.apps \"logs-es-logs\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"StatefulSet.apps \"logs-es-logs\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}]

**Environment**
GKE
* ECK version:
1.0.0

* Kubernetes information:

	* Cloud: GKE 1.15+
	
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sebgl** [comment]
```
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

This usually happens if you modify the `volumeClaimTemplates` section of the manifest. It is [immutable](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-orchestration-limitations).
Can you can inspect the existing volume claims templates in existing StatefulSets resources, and see if there's a difference there? (in doubt, please post the StatefulSet yaml here)

You'll first have to revert that change in order to apply modifications to the podTemplate.

**Comment by anyasabo** [comment]
The volume claim template in your second example needs to be `name: elasticsearch-data` for it to be used for ES data. It is set correctly in the first example, but is `name: logs` in the second.

As @sebgl mentioned it is immutable, but if you need to change it you can create a new nodeSet (just changing the name) with the new volume claim info and it will migrate over (also described in the linked doc).

**Comment by chrono2002** [comment]
Kubernetes now supports PVC enlarge.
Could you please reopen this issue?

**Comment by sebgl** [comment]
> Kubernetes now supports PVC enlarge.
Could you please reopen this issue?

ECK supports it as well now, see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html#k8s_updating_the_volume_claim_settings.
