### ISSUE TITLE
Improve docs for namespace isolation

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#2809]
Currently we do not have great documentation on how to limit ECK to listen only on specific namespaces. We support it but receive questions somewhat regularly on how to do it.

Related to the tooling issue to make this easier: https://github.com/elastic/cloud-on-k8s/issues/2406

Example difficulty topic here:
https://discuss.elastic.co/t/difficulty-installing-eck-in-a-single-namespace/225891/4

**Comment by anyasabo** [comment]
Currently the namespace generator described here:
https://github.com/elastic/cloud-on-k8s/tree/master/config/operator

Can generate a manifest for an operator that only listens on specific namespaces. It still uses non-namespaced resources with cluster roles though. This is necessary for users who want to have ECK manage only a select set of multiple namespaces, but will be a problem for users who do not have access to create cluster-wide resources and only have access to their own namespace. I wonder if we should create a third separate make target for this use case? It should be both easy to set up, and helpful for users in this situation until we have a more full fledged generator as described in https://github.com/elastic/cloud-on-k8s/issues/2406

What do yall think?

**Comment by charith-elastic** [comment]
#2406 is pretty much ready. Just need a couple of PRs approved and a decision on whether we want to use it for 1.1.0 (not much time for wider testing and publishing before the release).

**Comment by anyasabo** [comment]
This will be covered by https://github.com/elastic/cloud-on-k8s/issues/2406 so closing this
