### ISSUE TITLE
Follow coding conventions in deployer

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2815]
Looks like we are have a ton of inconsistent capitalization issues in the deployer code base. 

We should follow https://github.com/golang/go/wiki/CodeReviewComments#initialisms and change things like `Ocp` to `OCP`, `Gke` to `GKE` etc.

**Comment by townsymush** [comment]
I can take a look at this

**Comment by anyasabo** [comment]
I'd have thought the linter would catch this, it looks like we have other warnings disabled right now:
https://github.com/elastic/cloud-on-k8s/blob/master/.golangci.yml#L46

Though I see it maintains a set of common initialisms so maybe it doesn't catch these less common ones, which would make sense:
https://github.com/golang/lint/blob/master/lint.go#L767

**Comment by townsymush** [comment]
Thanks Anyasabo.

As this is my first contribution, can you check my couple of commits to see if I'm on the right understanding, before I proceed with any more please?

https://github.com/townsymush/cloud-on-k8s/commits/2815-refactor-deployer

**Comment by pebrc** [comment]
Closing as this is caused by a shortcoming of https://github.com/imdario/mergo which has since been highlighted through a code comment.
