### ISSUE TITLE
Modification to the prepare-fs script does not lead to a rolling upgrade

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2828]
The prepare-fs init container executes the script that exists in a configmap.
Any update to the content of that configmap does not trigger a rolling upgrade of the cluster.

I think it's not exactly expected.
But also not exactly sure whether that's a bug or a feature :| (it could be useful to not upgrade existing clusters for minor modification in the script?).

**Comment by pebrc** [comment]
Fixed in https://github.com/elastic/cloud-on-k8s/commit/0a19d7da0b56bd748a5b0c7bcdd074c8d636d3ca
