### ISSUE TITLE
Kibana UI is not showing users for elastic and kibana 

### ISSUE THREAD

**Issue by liza-mae** [elastic/cloud-on-k8s#2866]
I am running ECK for Kibana 7.7 BC5 I noticed users for elastic and kibana are not showing in the UI, see elastic/kibana#63276, is this a misconfiguration or a bug?

**Comment by sebgl** [comment]
ECK populates users using the file realm. I think, by design, file realm users are not reported by the Elasticsearch API, so not visible in Kibana UI.

I don't think this is a misconfiguration or a bug.

**Comment by pebrc** [comment]
I think some of the confusions stems from the fact that `[bin/elasticsearch-setup-passwords](https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html#set-built-in-user-passwords)` sets the passwords for the built-in users via the native realm and they show up in the UI if a user users this tool.

**Comment by liza-mae** [comment]
Thanks @pebrc and @sebgl we will update our test to reflect this.
