### ISSUE TITLE
Move github.com/elastic/cloud-on-k8s/hack/licence-detector to a separate repository

### ISSUE THREAD

**Issue by kvch** [elastic/cloud-on-k8s#2870]
## Proposal

Please move `github.com/elastic/cloud-on-k8s/hack/licence-detector` to a separate repository.

**Use case. Why is this important?**

We would like to use the `license-detector` to generate `NOTICE.txt` files in other repositories of Elastic. For example `github.com/elastic/go-ucfg` and `github.com/elastic/beats`.

The module is usable as is, but it would be nice to split it from `cloud-on-k8s`. Thus, the issues, PRs and possible releases would not interfere with the development of the original repository.

**Comment by pebrc** [comment]
I think I am OK with  that proposal. cc @charith-elastic any technical reason we need to have it in the hack (other than convenience and not having to release/maintain it separately from ECK)?

**Comment by charith-elastic** [comment]
I don't think it would be a problem. It was on my list of things to do anyway. I will create a new repository for it shortly.

**Comment by charith-elastic** [comment]
This is now publicly available at https://github.com/elastic/go-licence-detector
