### ISSUE TITLE
Delete es does not delete belonging secret

### ISSUE THREAD

**Issue by FingerLiu** [elastic/cloud-on-k8s#2947]
<!--

** Please read the guidelines below. **
I deleted es, but it did not delete belonging secret.
Is this on purpose or something missing?
 
## Bug Report
**What did you do?**
1. create es （assume it is test-secret)
2. delete es by `kubectl delete es test-secret`
3. check secret `kubectl get secret|grep test-secret`

**What did you expect to see?**
Secret test-secret-xxx should be deleted.

**What did you see instead? Under which circumstances?**
![image](https://user-images.githubusercontent.com/3981064/80170721-346cb580-861b-11ea-91f3-5ecec3b2f52d.png)

**Environment**

* ECK version:

	docker.elastic.co/eck/eck-operator:1.0.1

* Kubernetes information:

no cloud, barel metal.
1.14

```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by sebgl** [comment]
Duplicates https://github.com/elastic/cloud-on-k8s/issues/2948.
