### ISSUE TITLE
Consider moving hack/diagnostics/eck-dump.sh to separate directory

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#2949]
We could promote the diagnostics directory to top level or move it into existing directory for better discoverability. It will also allow avoiding pointing users to `hack` folder which is aimed more towards developers.

**Comment by jstrassb** [comment]
We are having more and more customers that use ECK and many new ECK subscriptions onboarding constantly.

Could we please get a more professional looking folder path? :)

**Comment by idanmo** [comment]
As discussed, it would make most sense to rename the `hack` folder to either `support` or `utils` as we may want to reference other utilities/scripts from that folder.

I'm +1 for `utils`.

**Comment by charith-elastic** [comment]
I don't think we should rename the entire `hack` directory. Just move the public tools like `diagnostics` and `pv-reattach` to a `support` directory at the top-level (`utils` feels a bit too vague).

**Comment by pebrc** [comment]
I also prefer `support` over `utils`

**Comment by idanmo** [comment]
@charith-elastic Sorry I missed that this was actually our conclusion when we synced about this. My bad.
I'll go with `support` and your proposal. ty!

**Comment by idanmo** [comment]
A `support` directory was created at the top-level directory containing the `diagnostics` and `reattache-pv` directories from `hack`.
