### ISSUE TITLE
1.1.0 Release availability?

### ISSUE THREAD

**Issue by gabel** [elastic/cloud-on-k8s#2976]
## Bug Report
**What did you do?**

The documentation promotes version 1.1.0 as the way to go but (https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-deploy-eck.html) but the release is not available yet and `kubectl apply -f https://download.elastic.co/downloads/eck/1.1.0/all-in-one.yaml` will fail with a 404. 

**What did you expect to see?**

Succesful CRD installation.

Is this a temporary issue that will be solved within next hours or is a in between hint in documentation required to use  `1.0.1` as long as `1.1.0` is not released?

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	1.1.0 (official docs version)

**Comment by rabberbock** [comment]
@gabel From the releases it looks like that 1.1.0 is still a release candidate. You can get the yaml for the latest release candidate at https://download.elastic.co/downloads/eck/1.1.0-rc9/all-in-one.yaml.

**Comment by david-kow** [comment]
Hi @gabel, thanks for your question. @rabberbock is correct, we were very close to the release.

`1.1.0` is available now 🙂

**Comment by gabel** [comment]
Thanks for the Feedback!
