### ISSUE TITLE
APM users should not use the built-in "superuser" role

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2977]
I think there has been a regression regarding the role of the user used in the APM/ES association. The `superuser` built-in role is used while we should use one of the roles introduced in https://github.com/elastic/cloud-on-k8s/pull/2777

https://github.com/elastic/cloud-on-k8s/blob/2465556ff521499516dbced091477e22c43a9f60/pkg/controller/association/controller/apm_es.go#L37-L39

**Comment by sebgl** [comment]
:o my bad it probably happened concurrently with the recent refactoring!

**Comment by barkbay** [comment]
I guess we have to replace `ESUserRole` with a something like:

```golang
type AssociationInfo struct {
   ...
   ESUserRole func(commonv1.Associated) (string, error)
}
```

And then try to convert the interface to its implementation in the APM association controller: 

```golang
// getRoles returns for a given version of the APM Server the set of required roles.
func getRoles(associated commonv1.Associated) (string, error) {
	apmServer, ok := associated.(*apmv1.ApmServer)
	if !ok {
		return "", errors.New(".....")
	}

	v, err := version.Parse(apmServer.Spec.Version)
	if err != nil {
		return "", err
	}
...
```

I will try to work on a fix.
