### ISSUE TITLE
Cleanup created resources leftover on errors

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#298]
When creating resources with a non-deterministic name (eg. pod), we sometimes end-up creating multiple resources, that stay there forever if we return on error later on.

Common situation in the code (pseudo-code):

```go
podName := randomlyGenerated()

err := createSecretFor(podName)
if err != nil {
    return err
}

err := createPVCFor(podName)
if err != nil {
    // leftover secret created above
    return err
}

err := createPod(podName)
if err != nil {
    // leftover secret created above
    // leftover PVC created above
    return err
}
```

See how both the secret and PVC can end-up being created, but not the pod.

Potential solutions for cleanup:

1) defer a delete just after the resource was created, based on a bool saying whether we should cleanup or not. 
Example of this:
```go
cleanup := false
podName := randomlyGenerated()

err := createSecretFor(podName)
if err != nil {
    return err
}
defer func() {
    if cleanup {
        err := deleteSecret(podName)
        if err != nil {
            // what should we do here?
        }
    }
}

err := createPod(podName)
if err != nil {
    cleanup = true
    return err
}
```

Benefits: deletion closer to creation in the code.
Concerns: need not to forget about setting `cleanup=true` and `defer func()`, what should we do if the cleanup delete fails?

2) Reconcile leftovers item as part of the reconciliation loop
List all secrets, PVC, etc. If some exist that are not bound to any other resource (ie. podName in PVC labels does not map any existing pod), perform the garbage collection.
Benefits: no need to think about it in other parts of the reconciliation loop, will retry forever in case of error.
Concerns: need to deal with cache inconsistencies and expectations (pod not appearing in our cache does not mean it's not there), useless resources might stay there longer.

3) Other options?

IMHO option 2) (a dedicated package for resources garbage collection in our code base) seems to be cleaner?

**Comment by pebrc** [comment]
Is this really still an issue since we moved to StatefulSets? PVC and Pods have ownerReferences or are managed explicitly. Secrets we either GC manually or set ownerReferences. Any other cases we would need to think of? Otherwise I think we could close this one?

**Comment by naemono** [comment]
Closing this because cleanup of resources with said options should be sufficient at this time.  Open again if issue persists.
