### ISSUE TITLE
Remove links to current

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#2988]
Related https://github.com/elastic/cloud-on-k8s/pull/2984

To prevent future issues with docs changes, we should not link to the `current` branch of the docs directly anywhere. We currently do this in CRD descriptions in a few places, but they're very brittle. If we change the current branch (say 1.0 to 1.1) and the anchor tag no longer exists on that page (or any other reason for the link not working), it will break the docs build. This is because we use the CRD field comments to generate the reference docs, and the reference docs are part of the docs build, which detects the now-invalid link and fails.

I think we have a few options

- Don't link to the docs from CRD descriptions
- Use asciidoc `<<ID, name>>` style links in the CRD descriptions
- Link to a specific version in the docs. Either manual labor to update them between releases or some kind of automation
- Do something clever with the reference docs generator such that we can have a human usable link in the CRD descriptions, and have it translated into an asciidoc link in the reference doc output.

I personally lean towards the first option because it seems odd to have unresolved asciidoc links when reading the source code.

We need to do this for all branches that are currently being built, which is
>branches:   [ master, 1.1, 1.0, 1.0-beta, 0.9, 0.8 ]
as seen [here](https://github.com/elastic/docs/blob/master/conf.yaml#L813)

**Comment by nrichers** [comment]
@anyasabo thank you for opening this issue! I agree the first option is the safest — can't break a link you don't add. In practice, we often use "Link to a specific version in the docs, " because the link will likely remain static, but it does require some additional upkeep over time. Hard-coded links would still be a problem that only a full doc build could catch. 

The "Do something clever" option could include a variable we define for links, e.g. you could use `{some-docs-link}` in the CRD that is meaningful to you and define `:some-docs-link: See <<ID, text>>.` in the index.asciidoc fille for the docs. The benefit of this option is that it is relatively fail-safe: 

* an incorrect link to a section ID in the variable definition will cause a local build error for the ECK docs without requiring a full doc build; and
* a missing variable definition will cause the link to be omitted. It'll just be missing from the output but won't break anything.

Happy to chat further and thank you again for your help fixing the ECK 1.1 links yesterday!

**Comment by thbkrkr** [comment]
0.8, 0.9, 1.0-beta are OK.

```md
0.8 * > ag -A1 -B1 cloud-on-k8s/current
README.md
21-
22:Check the [Quickstart](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html) if you want to deploy you first cluster with ECK.
23-
```

```md
0.9 * > ag -A1 -B1 cloud-on-k8s/current  
README.md
24-
25:Check the [Quickstart](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html) if you want to deploy you first cluster with ECK.
26-
```

```md
1.0-beta * > ag -A1 -B1 cloud-on-k8s/current  
docs/upgrading-eck.asciidoc
34-. link:https://www.elastic.co/guide/en/cloud-on-k8s/0.9/k8s-uninstall.html[Uninstall ECK].
35:. link:https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html[Install new version of ECK].
36-. Re-create the resources by applying the manifests converted in the first step.

README.md
24-
25:Check the [Quickstart](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html) if you want to deploy you first cluster with ECK.
26-
```

In 1.0, we added 3 links in elasticsearch_types.go:

```md
1.0 * > ag -A1 -B1 cloud-on-k8s/current  pkg 
pkg/apis/elasticsearch/v1beta1/elasticsearch_types.go
28-     // NodeSets allow specifying groups of Elasticsearch nodes sharing the same configuration and Pod templates.
29:     // See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html
30-     // +kubebuilder:validation:MinItems=1
--
43-     // SecureSettings is a list of references to Kubernetes secrets containing sensitive configuration options for Elasticsearch.
44:     // See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html
45-     // +kubebuilder:validation:Optional
--
78-     // Items defined here take precedence over any default claims added by the operator with the same name.
79:     // See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html
80-     // +kubebuilder:validation:Optional

pkg/apis/elasticsearch/v1/elasticsearch_types.go
29-     // NodeSets allow specifying groups of Elasticsearch nodes sharing the same configuration and Pod templates.
30:     // See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html
31-     // +kubebuilder:validation:MinItems=1
--
44-     // SecureSettings is a list of references to Kubernetes secrets containing sensitive configuration options for Elasticsearch.
45:     // See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html
46-     // +kubebuilder:validation:Optional
--
79-     // Items defined here take precedence over any default claims added by the operator with the same name.
80:     // See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html
81-     // +kubebuilder:validation:Optional
```

Which generates links in:
- docs/api-docs.asciidoc
- config/crds/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml
- config/crds/all-crds.yaml

In 1.1, we kept 2 links in elasticsearch_types.go. The link in the SecureSettings description has been removed (#2984).
But we had added some links in some README in config/recipes:

```md
1.1 * > ag -A1 -B1 cloud-on-k8s/current config/recipes 
config/recipes/istio-gateway/README.asciidoc
26-----
27:- Install ECK with the Istio sidecar. See: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html
28-- Enforce mTLS

config/recipes/README.asciidoc
6-
7:CAUTION: Some of these recipes use the `node.store.allow_mmap: false` configuration value to avoid configuring memory mapping settings on the underlying host. This could have a significant performance impact on your Elasticsearch clusters and should not be used in production without careful consideration. 
See https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html for more information.
8-
```

In 1.2, it is identical to 1.1 with 2 additional links in the beats README and in the beats doc:

```md
config/recipes/beats/README.asciidoc
6-
7:CAUTION: Some of these examples use the `node.store.allow_mmap: false` configuration value to avoid configuring
 memory mapping settings on the underlying host. This could have a significant performance impact on your Elasticsearch
 clusters and should not be used in production without careful consideration. 
See https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html for more information.8-

docs/orchestrating-elastic-stack-applications/beat.asciidoc
376-
377:CAUTION: Some of these examples use the `node.store.allow_mmap: false` configuration value to avoid configuring
memory mapping settings on the underlying host. This could have a significant performance impact on your Elasticsearch
clusters and should not be used in production without careful consideration. 
See https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html for more information.
378-
```

--

I'm also in favour to remove the links from the CRD (elasticsearch_types.go), that will clean up: docs/api-docs.asciidoc (and config/crds/**.yaml) and will prevent to break the docs build.

Then we need to choose what to do for the 2 links:
- https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
  - config/recipes/README.asciidoc
  - config/recipes/beats/README.asciidoc
  - docs/orchestrating-elastic-stack-applications/beat.asciidoc
- https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html
  - config/recipes/istio-gateway/README.asciidoc

Note that the README.asciidoc are not a part of the documentation and therefore cannot break the docs build but remains a small potential problem as it might become invalid. We can't use anchors or other docs generator power for those.

I find it hard to see more options than:
- Do nothing and preserve the 2 links
- Link to a specific version in the docs
