### ISSUE TITLE
Invalid value error when trying to define custom auth roles

### ISSUE THREAD

**Issue by mtparet** [elastic/cloud-on-k8s#3024]
## Bug Report
**What did you do?**
Following https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s_creating_custom_roles

Define custom roles within a secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-prometheus
stringData:
  roles.yml: |-
    prometheus:
      run_as: [ 'prometheus' ]
      cluster: [ 'monitor' ]
      indices:
      - names: [ '*' ]
        privileges: [ 'indices:monitor/stats' ]
```

Reference it in the elasticsearch crd
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 6.8.5
  auth:
    roles:
    - secretName: elasticsearch-prometheus
[...]
```

**What did you expect to see?**
Successfuly apply.

**What did you see instead? Under which circumstances?**
Error:
```
Error from server (Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch" is invalid: auth: Invalid value: "auth": auth field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown): error when applying patch:

```

**Environment**

* ECK version:

	1.1.0

* Kubernetes information:

AKS, 1.15.10
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by sebgl** [comment]
@mtparet can you retry with setting `apiVersion: elasticsearch.k8s.elastic.co/v1` (`v1` instead of `v1beta1`) in your Elasticsearch resource?

**Comment by mtparet** [comment]
Nice catch @sebgl, I totally forgot to update version of the resources indeed.. thank you and sorry for this mistake. 

Now there is no more errors but the role does not appears, I do not see logs about this in the operator, should I increase the verbosity of the logs ?

**Comment by sebgl** [comment]
What do you mean by `the role does not appears`? Note that you cannot [view file-based roles](https://www.elastic.co/guide/en/elasticsearch/reference/current/defining-roles.html#roles-management-file) with the API and UI.

**Comment by mtparet** [comment]
> What do you mean by the role does not appears

I mean in Kibana, in the `roles` tab but as you just said it is expected. I didn't know this. When using the role, I can confirm it seems working correctly, thanks again!

The fact that we cannot view it, makes the experience a little bit weird, for example we can see the user anonymous linked to the role but if we click on it we got an error:
![2020-05-04_15-58](https://user-images.githubusercontent.com/754770/80974049-7cac8480-8e20-11ea-8b7d-68e2fd23b222.png)
![2020-05-04_15-58_1](https://user-images.githubusercontent.com/754770/80974038-7ae2c100-8e20-11ea-912b-08e4c856cf00.png)
```
Request URL: http://127.0.0.1:5601/api/security/v1/users/anonymous_user
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:5601
Referrer Policy: no-referrer-when-downgrade
```
```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```
