### ISSUE TITLE
Consider raising default memory limit for the operator

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3025]
ECK memory usage scales not only with the number of resources it manages, but also with the size of resources in the K8s cluster in general. This is because we are not able to filter watched resources by labels - client caches include all Pods, Secrets and any other resources of the same type that ECK watches. In https://github.com/elastic/cloud-on-k8s/issues/2981 we can see that caused the operator pod to be OOMKilled. 

As the memory limit is fairly low right now (150Mi) and seems insignificant in comparison with memory requirements of most ES clusters, we should consider raising it to allow larger clusters to work out of the box.

**Comment by sebgl** [comment]
It's a bit arbitrary, but based on [users feedback](https://github.com/elastic/cloud-on-k8s/issues/2981) 512Mi seems to be a fair memory limit.

**Comment by barkbay** [comment]
> It's a bit arbitrary, but based on [users feedback](https://github.com/elastic/cloud-on-k8s/issues/2981) 512Mi seems to be a fair memory limit.

👍 Also in order to be consistent maybe increase the request ? Half of the limit looks reasonable I guess.

**Comment by sebgl** [comment]
> 👍 Also in order to be consistent maybe increase the request ? Half of the limit looks reasonable I guess.

We could do 150Mi for the memory requests?
