### ISSUE TITLE
Transport certs public secret name is not expected

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3034]
Looks like I accidentally changed the name of the transport certs public certificates in https://github.com/elastic/cloud-on-k8s/commit/608642b3e35dc00fa394ae50df732ce486c50848.

It is now (as of `1.1.0`) named `<cluster>-es-ca-certs-public` whereas it used to be `<cluster-name>-es-transport-certs-public` before this commit (in `1.0.0`).

The docs for `1.1.0` mention the (now incorrect) `<cluster>-es-transport-certs-public` naming scheme.

I see 2 options here:
1. We change it back to `<cluster-name>-es-transport-certs-public` in a `1.1.1` version.
2. We change the docs to use `<cluster>-es-ca-certs-public` starting 1.1.0.

Considering we also have `<cluster-name>-es-http-certs-public`, I think the first option makes more sense.

**Comment by barkbay** [comment]
I think I would be in favour of a rename to `<cluster-name>-es-transport-certs-public`
I don't think it is widely used yet and it would make more sense re. http certs.
