### ISSUE TITLE
Homogenize logs

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#305]
Things are in a rather strange state currently:

* we use `log.Info()` most of the times (log level: 0)
* sometimes, we use `log.V(3)` or `log.V(4)`
* we don't have any flag parsing on `-vvvv` to adapt the level of log getting printed out
* the controller-runtime log package pre-configures a [zap logger](https://github.com/uber-go/zap) compatible with the [loggr interface](https://github.com/go-logr/zapr), which only accepts 2 options: development or not
* if development mode is true, we use the debug level (`V(1)`) and logs encoded for a better output on the terminal
* if development is false, we use the info level (`V(0)`) and logs encoded as JSON
* using `V(3)` or `V(4)` has no effect.

Recommendations from the controller-runtime team seems to be: stick to INFO for production and `V(1).Info` (debug) for development. See [this doc](https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md) and [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/167).

I  think we should either:
1) comply with what controller-runtime is doing: keep current settings and use only info and debug levels
2) configure our own logger (zap or something else), with log levels parsed from flags (`-vvv`)

I would personally vote for option 1 (simpler).

**Comment by jonsabo** [comment]
>We want the ability to switch format between JSON and non-structured independently from DEBUG level (V(1))

Do we still think this is necessary? It looks like doing this through kubebuilder is a little bit more involved and I'm not sure what the use case is. I think we would end up mostly re-implementing this function but exposing the knobs we want:
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.12/pkg/runtime/log/log.go#L43

If not I think we can close this issue as the other bullets are checked off now
