### ISSUE TITLE
Kibana readiness probe must be overridden to work with ingresses

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#3054]
We switched the Kibana readiness probe to an `exec` action in #2528. This would affect [users who want to expose Kibana through an ingress](https://discuss.elastic.co/t/kibana-ingress-not-working-after-upgrading-to-eck-1-1-0/232316/2) as some ingress controllers reuse the readiness probe in their own health checks. 

We should document this requirement in the docs and mark it as a breaking change in the 1.1 release notes.

Given that most typical users won't have such strict network controls in place, perhaps we should apply the principle of least astonishment and default to the old behaviour instead?

**Comment by sebgl** [comment]
Fixed in 1.1.1, which reverted to using the same readiness probe (httpGet) as 1.0.x.
