### ISSUE TITLE
E2E flaky test: TestPodTemplateValidation/Phase_should_eventually_be_"invalid"

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3055]
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-gke-k8s-versions/80/testReport/

=== RUN   TestPodTemplateValidation/Phase_should_eventually_be_"invalid"
Retries (5m0s timeout): ....................................................................................................
    TestPodTemplateValidation/Phase_should_eventually_be_"invalid": utils.go:84: 
        	Error Trace:	utils.go:84
        	Error:      	Received unexpected error:
        	            	phase is Ready
        	Test:       	TestPodTemplateValidation/Phase_should_eventually_be_"invalid"

**Comment by barkbay** [comment]
This test is failing because it has been running against a release build canddiate (`cloud-on-k8s-release-build/1.1.1-rc0`) which does not have the validation feature.

**Comment by barkbay** [comment]
Should be fixed by #3066
