### ISSUE TITLE
E2E Tests are always run from the master branch

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3066]
When running e2e tests against a branch we should use the e2e tests from this specific branch.

Otherwise some E2E tests in master may fail because they require some features which are not available in the tested branch.

This is the root cause of #3055

**Comment by thbkrkr** [comment]
We can make a branch specifier (git commit/branch/tag) parameter at the job level to use it for the git checkout in the e2e tests jobs.
And we propagate the git commit in the build pipeline that triggers these jobs.

**Comment by sebgl** [comment]
+1, it's nice since it means we can also manually run those job and specify the git commit we want to use.

**Comment by thbkrkr** [comment]
Quick-update: the previous diff I wrote is wrong as it only concerns the sha1 to checkout the Jenkinsfile. We need to work at the pipeline level (the Jenkinsfile) and to override the default checkout, thing we already did to have a retry. In short, this is not so easy.

**Comment by thbkrkr** [comment]
Actually it can work but only if we switch `lightweight-checkout` to `false`. With `lightweight-checkout` set to `true`, the `Jenkinsfile` is retrieved using the API while `false` implies a `git clone`.
So the downside of this is that  we add a `git clone`.

An alternative to avoid the extra `git clone` is to explicitly call the `checkout` directive to pass it the parametrized branch specifier: 

```groovy
checkout([$class: 'GitSCM', 
    branches: [[name: params.branch_specifier ]],
    extensions: [[$class: 'WipeWorkspace']],
    userRemoteConfigs: [[
        credentialsId: 'f6c7695a-671e-4f4f-a331-acdce44ff9ba',
        url: 'https://github.com/elastic/cloud-on-k8s',
        refspec: params.branch_specifier
    ]]
])
```

Whatever the solution chosen, we can reduce the number of checkouts. We can use [`stash`](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#stash-stash-some-files-to-be-used-later-in-the-build)/[`unstash`](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#unstash-restore-files-previously-stashed) in the jobs where we run stages in parallel with one `checkout scm` by stage (the kind, stack-versions, snapshots and gke jobs). Moreover I think we have some extra unecessary checkout in the ocp, eks and aks jobs as there is already a default checkout.

**Comment by thbkrkr** [comment]
Let's start with the simpler solution despite the extra `git clone`.
I will remove the extra unnecessary checkout and reduce the number of checkouts in separate pull requests.
