### ISSUE TITLE
Some Way To Specify A nodeSelector

### ISSUE THREAD

**Issue by duckman** [elastic/cloud-on-k8s#3094]
## Proposal

Would be useful for some way to specify a nodeSelector for the managed pods. My use case is I have a multi arch setup so I need a way to tell them to start on my amd64 nodes and not the arm64 nodes where they aren't supported. There are other reasons people might want to specify a nodeSelector like keeping things on nodes with SSDs or some network segment or what ever.

I was able to add the nodeSelector to the elastic-operator, but my understanding is that is what actually creates the pods and I don't see a way to configure what nodeSelector it uses to create the requested resources.

**Comment by anyasabo** [comment]
This is described in the docs here: https://www.elastic.co/guide/en/cloud-on-k8s/1.1/k8s-advanced-node-scheduling.html#k8s_node_affinity
