### ISSUE TITLE
Invalid value: "max_initial_line_length"

### ISSUE THREAD

**Issue by chhaosh** [elastic/cloud-on-k8s#3112]
## Bug Report
**What did you do?**
Create elasticsearch resource using yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.7.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    max_initial_line_length: 100kb
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

**What did you expect to see?**
max_initial_line_length takes effect

**What did you see instead? Under which circumstances?**
Error from server (Elasticsearch.elasticsearch.k8s.elastic.co "quickstart" is invalid: max_initial_line_length: Invalid value: "max_initial_line_length": max_initial_line_length field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"elasticsearch.k8s.elastic.co/v1\",\"kind\":\"Elasticsearch\",\"metadata\":{\"annotations\":{},\"name\":\"quickstart\",\"namespace\":\"default\"},\"spec\":{\"http\":{\"max_initial_line_length\":\"100kb\",\"tls\":{\"selfSignedCertificate\":{\"disabled\":true}}},\"nodeSets\":[{\"config\":{\"node.data\":true,\"node.ingest\":true,\"node.master\":true,\"node.store.allow_mmap\":false},\"count\":3,\"name\":\"default\"}],\"version\":\"7.7.0\"}}\n"}},"spec":{"http":{"max_initial_line_length":"100kb"},"nodeSets":[{"config":{"node.data":true,"node.ingest":true,"node.master":true,"node.store.allow_mmap":false},"count":3,"name":"default"}]}}
to:
Resource: "elasticsearch.k8s.elastic.co/v1, Resource=elasticsearches", GroupVersionKind: "elasticsearch.k8s.elastic.co/v1, Kind=Elasticsearch"
Name: "quickstart", Namespace: "default"
Object: &{map["apiVersion":"elasticsearch.k8s.elastic.co/v1" "kind":"Elasticsearch" "metadata":map["annotations":map["common.k8s.elastic.co/controller-version":"1.1.1" "elasticsearch.k8s.elastic.co/cluster-uuid":"V7ObOYF9TBu_U96yuKlmmg" "elasticsearch.k8s.elastic.co/managed-remote-clusters":"" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"elasticsearch.k8s.elastic.co/v1\",\"kind\":\"Elasticsearch\",\"metadata\":{\"annotations\":{},\"name\":\"quickstart\",\"namespace\":\"default\"},\"spec\":{\"http\":{\"tls\":{\"selfSignedCertificate\":{\"disabled\":true}}},\"nodeSets\":[{\"config\":{\"node.data\":true,\"node.ingest\":true,\"node.master\":true,\"node.store.allow_mmap\":false},\"count\":3,\"name\":\"default\"}],\"version\":\"7.7.0\"}}\n"] "creationTimestamp":"2020-05-19T06:35:46Z" "generation":'\b' "name":"quickstart" "namespace":"default" "resourceVersion":"20889570" "selfLink":"/apis/elasticsearch.k8s.elastic.co/v1/namespaces/default/elasticsearches/quickstart" "uid":"f8b46ae2-999a-11ea-817d-0a580aed6ccc"] "spec":map["auth":map[] "http":map["service":map["metadata":map["creationTimestamp":<nil>] "spec":map[]] "tls":map["certificate":map[] "selfSignedCertificate":map["disabled":%!q(bool=true)]]] "nodeSets":[map["config":map["node.data":%!q(bool=true) "node.ingest":%!q(bool=true) "node.master":%!q(bool=true) "node.store.allow_mmap":%!q(bool=false)] "count":'\x03' "name":"default" "podTemplate":map["metadata":map["creationTimestamp":<nil>] "spec":map["containers":<nil>]]]] "transport":map["service":map["metadata":map["creationTimestamp":<nil>] "spec":map[]]] "updateStrategy":map["changeBudget":map[]] "version":"7.7.0"] "status":map["availableNodes":'\x03' "health":"green" "phase":"Ready"]]}
for: "/Users/chenghaoshi/Documents/workspace/shrsearch-deployment/elastic/upgrade-simple-one-node-cluster.yaml": admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "quickstart" is invalid: max_initial_line_length: Invalid value: "max_initial_line_length": max_initial_line_length field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown
**Environment**

* ECK version:

   1.1.1
* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? NO
	* Cloud: GKE / EKS / AKS ? OKE
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by pebrc** [comment]
Settings for Elasticsearch go into the `spec.nodeSets[?].config` section. See here https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html
