### ISSUE TITLE
Optimize cluster mutations by reusing PVCs when replacing nodes

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#312]
Reuse volumes on topology changes.

**Comment by sebgl** [comment]
High-level draft of an initial implementation:

* When computing changes, we end up with pods to create and pods to delete.
* If the user set `updateStrategy.changeBudget.MaxUnavailable` > 0, it means we are allowed to delete a pod and set the cluster below the budget.
* Try to match pods to create with pods to delete for PVC reuse:
   * We don't care about the pod spec: pod to create may have different resource limits, labels,  environment variables, etc. We want to reuse PVCs for eg. a 2GB->4GB heap size bump.
   * We don't care about most pod configuration items. We want to reuse PVCs for eg. a new xpack notifications settings.
   * We do care about PVCs: PVC of the pod to delete must be compatible with expected PVC of the pod to create.
   * We do care about the node role: we want to reuse data volumes for data nodes, not reuse data volumes for master nodes, and the other way around. We probably need to label PVCs with the corresponding node role.
* If we have a match, it means we can normally delete the pod, but we should not delete its PVC. The PVC should be picked up for pod creation whenever the corresponding compatible pod is created, using the existing [orphaned PVC process](https://github.com/elastic/cloud-on-k8s/blob/ffe6ea51302e79352f917a88828e86d2afe5afcd/operators/pkg/controller/elasticsearch/driver/pods.go#L148).
* When deleting the pod, we should go through the normal pod deletion process that makes sure all shards are migrated away from that node. Instead, we should follow recommendations of the [rolling upgrade doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html): disable replicas allocations, do a sync flush, then delete the pod.

Some problems and open questions:

* If 2 consecutive spec changes occur (eg. change one setting, apply the spec, then revert), we may end up with orphaned PVCs that stay there forever. We deleted a pod while keeping its PVC, but no new pod will reuse it. Should we garbage collect PVCs?
* We need to re-enable shard allocations once the pod has been replaced. When can we consider it's safe to re-enable shard allocations? Probably when there are no more pods with PVCs to reuse?
* Hot-warm attributes are probably important here: reusing a warm volume for a hot node is a bit useless, even though the 2 nodes are data nodes. The problem is: this attribute can have any name. If we tag the PVC with nodes attributes, then we can't reuse PVCs for config attribute changes that are unrelated to hot-warm.
* Is there an order in which actions should be performed? Should we prioritize the deletion of pods for PVC reuse over the "pure" pod deletion?
* Do we have to deal with PVCs restricted to a particular region/zone?

**Comment by pebrc** [comment]
> High-level draft of an initial implementation

Do we need a safety check that all shards on the node about to be decomissioned have at least one copy on another node?



> If 2 consecutive spec changes occur (eg. change one setting, apply the spec, then revert), we may end up with orphaned PVCs that stay there forever. We deleted a pod while keeping its PVC, but no new pod will reuse it. Should we garbage collect PVCs?

Not sure I follow your argument here, would the reversion of the settings change not lead to the creation of a pod (the third incarnation of the pod in your example) which would reuse the PVC again (maybe I am misunderstanding your example)

> Hot-warm attributes are probably important here:

Would it make sense to take the storage class of the PVC into consideration for reuse? We use the `node.attr` only to represent different hardware on the application level but on the k8s operator level we could just look directly at the storage class and one would probably not want to reuse PVCs on pods that templated a PVC with a different storage class

**Comment by sebgl** [comment]
> Do we need a safety check that all shards on the node about to be decomissioned have at least one copy on another node?

I think that makes sense. A simpler check would be to simply look at the cluster health: if it's green we can shut down a node. If it's yellow (or red) we do nothing. The downside is PVC reuse would only work for perfectly healthy clusters. Maybe I can start with that, then optimize in a second step with shards assignments checks.

> Not sure I follow your argument here

Yes, sorry, wrong example. A better example would be: we have 3 nodes, request a spec change on one node (memory resource limit ++), which makes the operator remove a node but keep the pvc, then apply a new spec which actually specifies only 2 nodes, while the operator has not yet created the new pod to reuse the PVC. The operator has nothing else to do (no new pod to created, we already have 2).  That PVC remains there, undeleted.

> Would it make sense to take the storage class of the PVC into consideration for reuse

Definitely, that's what we already do when comparing PVCs.

> We use the node.attr only to represent different hardware on the application level but on the k8s operator level we could just look directly at the storage class

That would probably work fine if warm and hot nodes use different storage classes 👍 (which I guess is the most logical thing to do anyway).
If they use the same storage class, we still might assign hot volumes to warm nodes and warm volumes to hot nodes, which makes volume reuse pointless since hot indices would probably then be migrated away from warm nodes and vice-versa. But as you pointed out, that's probably a corner case: in most situations people would use at least a different storage capacity (more capacity in warm than hot), and probably also a different storage class. I guess it's OK not to optimize for that corner case right now?

**Comment by pebrc** [comment]
>  A simpler check would be to simply look at the cluster health

As long as we are aware of the differences in behaviour. You could have a 'yellow' or even 'red' cluster where it is perfectly safe to replace a pod and attempt volume reuse. Because cluster health is a cluster global state but we are only interested in one node. So while e.g. yellow indicates that a replica is missing somewhere, as long as all the shards on the node we are about to retire have still a copy we are OK to move forward. 

I agree though that for practical reasons cluster health (which is readily available in the observer state) might be an OK substitute for the initial implementation. 

> That PVC remains there, undeleted.

Do we need some form of garbage collection for PVCs then?

>  I guess it's OK not to optimize for that corner case right now?

I would say so. Hot/warm with the same storage class for both hot and warm sounds very unusual to me.

**Comment by DaveCTurner** [comment]
I arrived here from #1138 and have a couple of comments:

> For those cases where we need to recreate (e.g. major version upgrade)

Elasticsearch does the Right Thing™ if upgraded in-place across a major version. I recognise that there may be other reasons to create a brand-new pod in this case, apart from Elasticsearch, but just wanted to clarify this point.

> As long as we are aware of the differences in behaviour. You could have a 'yellow' or even 'red' cluster where it is perfectly safe to replace a pod and attempt volume reuse.

Conversely, you could have a `green` cluster in which it's still not safe to replace one of the pods, because there's an index in the cluster with `number_of_replicas: 0` having a primary on that pod. I also wanted to point out that there's a race between checking that it's safe to shut a node down and then actually shutting it down, for which I don't know of a good solution today. Being unavailable until the new node starts should be ok, but dropping the volume without performing some further post-shutdown checks is risky.

**Comment by sebgl** [comment]
Superseded by #1173. We agreed on relying on StatefulSets in the long-term, which makes manual PVC reuse obsolete.
I'm closing this issue in favor of keeping #1773 open.
