### ISSUE TITLE
validatingwebhook not respected when deploying an elasticsearch stack via helm

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [elastic/cloud-on-k8s#3171]
## Bug Report
**What did you do?**
Used helm to change the volumesize in a nodeset

**What did you expect to see?**
Since this is not allowed by kubernetes, nor by the validating webhook, I would expect to see an error at apply time, like I do when using "kubectl edit" to make the same change.

**What did you see instead? Under which circumstances?**
The change is allowed, and I get a reconciller error reporting that I cannot update volumeclaimtemplates.

**Environment**

* ECK version:

	1.0.1

* Kubernetes information:

Amazon EKS
	
```
EKS: Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

* Logs:
```
{"level":"error","@timestamp":"2020-06-01T15:28:39.729Z","logger":"controller-runtime.controller","message":"Reconciler error","ver":"1.0.1-bcb74688","controller":"elasticsearch-controller","request":"common-logging/elastic-common","error":"StatefulSet.apps \"elastic-common-es-data3\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"StatefulSet.apps \"elastic-common-es-data3\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}],"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:88"}
```

**Comment by barkbay** [comment]
Could you change the `failurePolicy` to `Fail` to see if any error gets swallowed when the resource is applied. ([Also see this documentation page about possible issues re. the validation webhook](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-webhook-troubleshooting.html))

**Comment by AlexMichaelJonesNC** [comment]
When I make that change, I get an error in helm:

```
Error: UPGRADE FAILED: cannot patch "elastic-common" with kind Elasticsearch: Internal error occurred: failed calling webhook "elastic-es-validation-v1.k8s.elastic.co": Post https://elastic-webhook-server.elastic-system.svc:443/validate-elasticsearch-k8s-elastic-co-v1-elasticsearch?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "elastic-webhook-ca")
```
Do you have any idea why the certs might be considered invalid?

**Comment by barkbay** [comment]
Could you check that you have only one instance of the operator started with `manage-webhook-certs` ?

**Comment by AlexMichaelJonesNC** [comment]
I can confirm we only have one instance running, and the secret elastic-webhook-server-cert exists. 

We aren't setting the manage-webhook-certs flag, and according to documentation, it defaults true: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-operator-config.html

I don't think this is an rbac error, as our helm service user is a cluster admin.

**Comment by barkbay** [comment]
`manage-webhook-certs` is evaluated only if `enable-webhook` is explicitly set to `true`
Could you check that it is the case ?

**Comment by AlexMichaelJonesNC** [comment]
that appears to be disabled. I'll enable it and see if it helps with the problem.

**Comment by AlexMichaelJonesNC** [comment]
Enabling the webhook did the trick, thank you. Do you know why this is disabled by default? It was not apparent to me at all that this webhook wasn't enabled, and needed to be manaually enabled.

**Comment by anyasabo** [comment]
The flag [is enabled](https://github.com/elastic/cloud-on-k8s/blob/master/config/operator/all-in-one/operator.template.yaml#L26) in the `all-in-one.yaml` we distribute already, so it seems it was removed manually.

**Comment by barkbay** [comment]
One of the reason I guess is that only one ECK instance must have the webhook "role" on a K8S cluster (i.e. reconcile the certs and respond to the K8S API Server). That's why it should be explicitly set to avoid conflicts.

**Comment by AlexMichaelJonesNC** [comment]
that makes a lot of sense, thank you very much for the help. I'll go ahead and close this issue as resolved.

**Comment by AlexMichaelJonesNC** [comment]
> The flag [is enabled](https://github.com/elastic/cloud-on-k8s/blob/master/config/operator/all-in-one/operator.template.yaml#L26) in the `all-in-one.yaml` we distribute already, so it seems it was removed manually.

This doesn't appear to be the case in 1.0.1, The flag was added in this commit tagged 1.1.2: https://github.com/elastic/cloud-on-k8s/commit/3819530fd62f700a9f56a0a71e4ef13d61ef3d5f


either way, this appears to be resolved, and we'll take action on our side to get things configured correctly.

**Comment by anyasabo** [comment]
Correct, the webhook configuration was altered from 1.0 to 1.1 and was flagged as a breaking change:
https://www.elastic.co/guide/en/cloud-on-k8s/1.1/release-highlights-1.1.0.html#k8s-110-breaking-roles

Not trying to be pedantic here just making sure that we did cover all of our bases documentation and defaults wise.

**Comment by AlexMichaelJonesNC** [comment]
Now I understand, thank you very much for ensuring everything is correct, I really appreciate the hard work.
