### ISSUE TITLE
XPACK features are available in basic eck

### ISSUE THREAD

**Issue by AvinashAnchula** [elastic/cloud-on-k8s#3175]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by AvinashAnchula** [comment]
I'm working on elastic operator to create elastic cluster in our kubernetes environment and have question whether xpack features available in basic free eck?

**Comment by pebrc** [comment]
Please use Github issues only for actual bug reports and feature requests. 

You can find an overview which features are included in the Basic license here https://www.elastic.co/subscriptions

For questions around ECK please use our discuss forum at https://discuss.elastic.co/c/eck
