### ISSUE TITLE
Disable default volumes in podTemplate overrides

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3187]
Forked from the Beat CRD PR (https://github.com/elastic/cloud-on-k8s/pull/3041#discussion_r435359920).
I don't think we have a way for the user to override a volume so it isn't appended by default. Which may be useful for metricbeat or filebeat, if you don't want to mount `/proc` or `/var/log/containers` for example.

**Comment by david-kow** [comment]
As user podTemplate is applied first and not overwritten I think the below should work (not tested though):

```yaml
volumes:
- name: proc
  emptyDir: {}
```

Seems hacky, so some alternatives:
1. flag to prevent adding default volumes
2. list field of default volume names to exclude
3. don't use default volumes if the user provides a config

**Comment by david-kow** [comment]
As we decided to go with no defaults approach, this is no longer an issue. Closing.
