### ISSUE TITLE
Make the cluster.local suffix configurable

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#319]
We hardcode it in several places.

**Comment by selmison** [comment]
Are there any plans to implement this feature?

**Comment by pebrc** [comment]
Is the right approach here not use the FQDN but instead to rely on `my-service.my-namespace` and `my-podname.my-namespace` respectively? This would make us immune to custom cluster suffix configurations and avoid the need to configure this explicitly in the operator?

**Comment by selmison** [comment]
> Is the right approach here not use the FQDN but instead to rely on `my-service.my-namespace` and `my-podname.my-namespace` respectively? This would make us immune to custom cluster suffix configurations and avoid the need to configure this explicitly in the operator?


Exactly, @pebrc!

The right would omit the FQDN (cluster.local) leaving only the relative path.

**Comment by nkvoll** [comment]
Closed by https://github.com/elastic/cloud-on-k8s/pull/990
