### ISSUE TITLE
Auto-create dashboards in the default metricbeat/filebeat config

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3192]
Depends on https://github.com/elastic/cloud-on-k8s/issues/3191.

If the users specified a `kibanaRef` in metricbeat & filebeat spec, I think we should consider setting `setup.dashboards.enabled: true`, which gives the best quickstart experience.

**Comment by david-kow** [comment]
This was implemented in #3211, hence closing.
