### ISSUE TITLE
Priavate GKE : Reconciler error [After Firewall Rules]

### ISSUE THREAD

**Issue by sentatr** [elastic/cloud-on-k8s#3202]
We have private GKE & enabled the firewall rules, but again we are facing the reconciler error.

{"log.level":"error","@timestamp":"2020-06-08T17:59:42.359Z","log.logger":"controller-runtime.controller","message":"Reconciler error","service.version":"1.1.1-b6f69fc4","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","request":"default/elasticsearch-sample","error":"Timeout: request did not complete within requested timeout 30s","error.stack_trace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88"}

**Comment by anyasabo** [comment]
Please fill out [the issue template](https://github.com/elastic/cloud-on-k8s/issues/new) in full when opening requests, this is not really actionable as is. Please feel free to re-open when more detail is provided.
