### ISSUE TITLE
Check broken links

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#3227]
As mentioned in https://github.com/elastic/cloud-on-k8s/pull/3222 we should check for broken links in our docs automatically, either as part of every build or nightly.

I started poking around at some tools and I think we have at least a few requirements that any tool we use would need to meet:

- support asciidoc. right now the docs are not built locally so we cannot check the html
- exclude based on regex or something similar, otherwise it checks some of our docs that show how to use port forwarding (e.g. `[ERROR] https://elasticsearch.example.com:9200 (Get "https://elasticsearch.example.com:9200": dial tcp: lookup elasticsearch.example.com: no such host)`)
- have rate limit controls. we have a lot of github links, and github has pretty strict rate limits for anonymous users we hit very quickly. If it could support oauth that would be cool
  - also i hit local limits in some tools: `[ERROR] https://github.com/mitchellh/cli (Get "https://github.com/mitchellh/cli": dial tcp 192.30.255.113:443: socket: too many open files)`

I looked at [liche](https://github.com/raviqqe/liche/) and [link-verifier](https://github.com/bmuschko/link-verifier) and both had some of these issues. Might be worth checking to see what other elastic products are doing.

**Comment by anyasabo** [comment]
I was advised we don't do automated link checking today, so we will be Pioneers.

For point #1, I also realized we could build the docs as part of this check, and then check the resulting HTML. But that'll be a lot heavier weight since we will have to pull down our docs builder image and actually run it.

**Comment by alaudazzi** [comment]
@gtback is this issue still applicable?

**Comment by gtback** [comment]
This seems to be talking about checking links from our docs to external sites that aren't under control. We have an issue for it (elastic/docs#630) but it hasn't been prioritized.

**Comment by alaudazzi** [comment]
Closing.
