### ISSUE TITLE
Elasticsearch CA cert rotation seems broken

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3244]
I need to spend time double-checking this, it happened to me twice today.

After 1 hour (default CA cert rotation when running `make run`), requests from ECK to Elasticsearch started failing consistently with:

```
 x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying t
o verify candidate authority certificate \"quickstart-http\")"
```

Requests from Kibana to Elasticsearch as well, leading to a non-ready Kibana Pod:

```
Unable to revive connection: https://quickstart-es-http.default.svc:9200/
```

**Comment by sebgl** [comment]
After investigation I realised the http-certs-internal secret has been correctly updated with new certs, but the content of that secret did not get propagated to the Elasticsearch Pods.
Which is very strange. Killing the Pod (for recreation) led to the correct content on disk.
I'm suspecting a kubelet/kubernetes bug, as I also observed some weird things happening on that 1.14 gke cluster (I just lost a PV, and owner ref GC for statefulset is extremely slow to kick-in).

**Comment by sebgl** [comment]
Cannot reproduce on a fresh clean gke cluster. Will reopen if it happens again.

**Comment by amanjain97** [comment]
Hi @sebgl, it is happening with me. I am deploying two clusters with same configuration. One of them is working fine, another is having the following issue. 
```
{"log.level":"debug","@timestamp":"2020-10-21T13:34:55.792Z","log.logger":"observer","message":"Unable to retrieve cluster health","service.version":"1.2.1-b5316231","service.type":"eck","ecs.version":"1.4.0","error":"Get \"https://elasticsearch-multi-zone-es-http.elastic-system.svc:9200/_cluster/health\": x509: certificate signed by unknown authority","namespace":"elastic-system","es_name":"elasticsearch-multi-zone"}
```
Although, all of the nodes are running and `GET /_cluster/heath` shows `status: green`

**Comment by anyasabo** [comment]
@amanjain97 does the content of the `http-certs-internal` secret match what is in the filesystem on the pods? From @sebgl's last comment it appears it may be that the secret is getting updated, but the kubelet not refreshing the secret as expected. Killing the pod in his case also forced it to pull fresh secret data and so it worked fine after that. I'd also be curious what version of k8s / platform you are running on as well. If you have the same symptoms it appears to be a k8s bug.

**Comment by amanjain97** [comment]
When I create the elasticsearch cluster, it shows `Unknown` status for elasticsearch as it cannot fetch status from http endpoint and then certificate issue starts to appear after some time.

**Comment by anyasabo** [comment]
Someone else might have a better idea, but at that point I would contact GCP support as it seems to be a cluster issue if the secrets are updated but the filesystem is not getting them. As a mitigation you can increase the rotation period so the certs do not have to refresh as often (1h I think is just the default when running for development).
