### ISSUE TITLE
elasticsearch cluster can't Ready,discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured

### ISSUE THREAD

**Issue by saiyoofan** [elastic/cloud-on-k8s#3269]
elasticsearch cluster can't Ready, The error log “[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured”

How can I solve it？

**Comment by sebgl** [comment]
@saiyoofan this looks like a misusage or misconfiguration more than a bug or feature request.
Can you please open a thread in https://discuss.elastic.co/c/orchestration/eck/79, post your question there, and include your Elasticsearch yaml manifest?
