### ISSUE TITLE
Enable Slack notifications for all E2E tests failures

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3278]
Let's maybe wait for the job to get green, then enable Slack notifications so we don't miss important errors such as [this one](https://github.com/elastic/cloud-on-k8s/issues/3274).

**Comment by thbkrkr** [comment]
Same for the [aks](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-aks/) and [eks](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-eks/) jobs.

I think we were waiting for these jobs to be "_really stable_". They were fairly stable at one time, then we forgot about that and recently they are no longer. But as soon we make them blue again, let's turn on the notifications.
