### ISSUE TITLE
E2E Tests on GKE are flaky

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3287]
Several e2e tests have failed with the following error:

* [cloud-on-k8s-e2e-tests-stack-versions/118 x 2](https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-stack-versions/detail/cloud-on-k8s-e2e-tests-stack-versions/118/pipeline)
* [cloud-on-k8s-e2e-tests-gke-k8s-versions/115](https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-gke-k8s-versions/detail/cloud-on-k8s-e2e-tests-gke-k8s-versions/115/pipeline)

```
statusMessage: u"Google Compute Engine: Invalid value for field 'resource.ipCidrRange': '10.1.160.0/20'. Invalid IPCidrRange: 10.1.160.0/20 conflicts with existing subnetwork 'gke-eck-74-118-e2e-subnet-503d31ad' in region 'europe-west2'."
```

**Comment by anyasabo** [comment]
This is weird because it _should_ just pull from the free space in the vpc automatically. Maybe there's a race condition if we spin up a bunch of GKE clusters at once?

[GKE docs](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create)
>--create-subnetwork=[KEY=VALUE,…]
    Create a new subnetwork for the cluster. The name and range of the subnetwork can be customized via optional 'name' and 'range' key-value pairs.

>    'name' specifies the name of the subnetwork to be created.

>    'range' specifies the IP range for the new subnetwork. This can either be a netmask size (e.g. '/20') or a CIDR range (e.g. '10.0.0.0/20'). If a netmask size is specified, the IP is automatically taken from the free space in the cluster's network. 


And we only specify the subnet size (`/20) not the actual subnet. You can also verify this because the ranges are different in both runs:

>[2020-06-18T00:22:50.128Z]  zone: u'europe-west2'>] finished with error: Google Compute Engine: Invalid value for field 'resource.ipCidrRange': '10.1.160.0/20'. Invalid IPCidrRange: 10.1.160.0/20 conflicts with existing subnetwork 'gke-eck-74-118-e2e-subnet-503d31ad' in region 'europe-west2'.

>[2020-06-18T00:21:24.615Z]  statusMessage: u"Google Compute Engine: Invalid IPCidrRange: 10.1.0.0/20 conflicts with existing subnetwork 'gke-eck-gke14-115-e2e-subnet-0c4bdd01' in region 'europe-west2'."

That actually seems likely? For instance, run 115 failed building the k8s 1.15 cluster, and it conflicted with the 1.14 cluster from the same run. I wonder if we need to sleep between create calls or something and/or open a GKE bug report.

**Comment by anyasabo** [comment]
Opened GCP support case 23965986

**Comment by thbkrkr** [comment]
Google Cloud Support confirmed there is a race condition issue with creation of multiple clusters simultaneously. A fix will be applied for mitigating the issue but there is no ETA for its release.

> The fix plan for race condition issue:
>  When multiple clusters are created simultaneously within the same project where GKE is picking IP ranges, there is a race condition where two GKE clusters pick overlapping IP ranges. With the earlier change, we would halt the retry logic and return early. Removing this check will rerun the IP allocation logic which will end up picking new ranges for the second cluster.

**Comment by thbkrkr** [comment]
We could implement the retry on our side (maybe directly in the deployer) or/?/and add a small random delay before the creation of a cluster to increase the chance to not create two clusters simultaneously when the creation is done from two different jobs or stages started simultaneously.

**Comment by anyasabo** [comment]
Link to the upstream bug issue: https://issuetracker.google.com/159768616

**Comment by anyasabo** [comment]
Option 1 makes more sense to me I think Thibault, since it only affects GKE I think we could limit the change to that specific provider (and maybe that specific error too).

**Comment by anyasabo** [comment]
update in issue, and this has not recurred in our tests. we can reopen if it does

>This was a temporary issue during cluster creation that was fixed in the end of June.

>If the issue still persists after trying again do not hesitate to get back and post your comment here or you can create a new issue.
