### ISSUE TITLE
Autoscaler Elasticsearch and Kibana

### ISSUE THREAD

**Issue by longlnk** [elastic/cloud-on-k8s#3299]
I can't see guide
Please help me.

**Comment by longlnk** [comment]
I don't see guide Horizontal pod autoscaling and Vertical pod autoscaling

**Comment by barkbay** [comment]
There is currently no support for autoscaling in ECK.
You can refer to this [discussion](https://discuss.elastic.co/t/autoscaling-using-hpa/232588) for more informations about why it can be hard to use HPA with Elasticsearch. Also please use [this forum ](https://discuss.elastic.co/c/orchestration/eck/79)for any questions.
