### ISSUE TITLE
Kibana 8.0 gets OOMKilled during initialization with default (1Gi) memory limit 

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3344]
With 2Gi it runs fine. We should consider changing the default only for 8.0+ to avoid recreating Kibana pods without user specified resources.

**Comment by anyasabo** [comment]
This appears to not be intended behavior, so I opened https://github.com/elastic/kibana/issues/72987

**Comment by sebgl** [comment]
This doesn't seem to be a problem anymore.
See https://github.com/elastic/kibana/issues/72987#issuecomment-682445267.

I think we ran some weird tests setup with a combined Elasticsearch 7.8.0 + Kibana 8.0.0 (which ECK refuses now, and Kibana as well).
Running ES 8.0.0-SNAPSHOT + Kibana 8.0.0-SNAPSHOT seems to work as expected, I don't observe any OOM on Kibana.
