### ISSUE TITLE
Release manifest generator

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#3372]
We recently added the manifest generator (https://github.com/elastic/cloud-on-k8s/issues/2406, https://github.com/elastic/cloud-on-k8s/pull/3124), though work remains to make it usable externally. Not an exhaustive list:

- add public documentation on how to use
- Revisit profile names (discussion in PR [here](https://github.com/elastic/cloud-on-k8s/pull/3124#discussion_r431616191))

**Comment by alaudazzi** [comment]
Testing the gmail labeller

**Comment by pebrc** [comment]
Can we close this given that we are going ahead with publishing our internal Helm chart https://github.com/elastic/cloud-on-k8s/issues/938 @anyasabo @charith-elastic ?
