### ISSUE TITLE
E2E tests log streaming may end before the tests complete

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3386]
Forked from https://github.com/elastic/cloud-on-k8s/issues/3130.

Our OCP E2E test job fails because we did not manage to get the entire list of logs for the E2E test job:

```
04:02:15  {"log.level":"info","@timestamp":"2020-07-02T02:02:05.175Z","log.logger":"e2e-ih34m","message":"Log stream ended","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0"}
07:11:51  {"log.level":"info","@timestamp":"2020-07-02T05:11:47.261Z","log.logger":"e2e-ih34m","message":"Test Job succeeded, waiting for log stream to be over","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","name":"eck-e2e-ih34m-v8bh7"}
```

When running it myself locally I also get the log streaming to end with no error way before (eg. after 1 hour) the Pod terminates.

I see 2 solutions to that problem:

1. Retry the log stream request when it ends. I found this [code snippet](https://gitlab.com/gitlab-org/gitlab-runner/-/blob/1ea8d059a297c0c33025a2f56cabf4fc0807b3c6/executors/kubernetes/log_processor.go#L184-198) which seems to cache the timestamp of the last received log line. It says `it's impossible to get two log lines with the same timestamp`, which does not seem to match what I'm observing. In doubt I guess we could also cache the log lines themselves for comparison purposes.
2. Grab the logs file differently. It could be stored in eg. a PersistentVolume or an S3 bucket at the end of the E2E tests, and retrieved by the test runner.

2nd solution feels more robust but also more complicated to implement. If it relies on an external system (eg. S3) then it makes local runs a bit more complicated. I think I'd like to give a try to option 1 first.

**Comment by david-kow** [comment]
+1 on trying 1. first. Streaming logs plays nicely with running E2E locally.
