### ISSUE TITLE
master not discovered or elected yet, an election requires a node with id [...]

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/cloud-on-k8s#3399]
ES: 7.8.0
ECK: 1.1.1-f13b6d26

I have an ECK cluster of 2 nodes that won't form a cluster.  The error seems contradictory:

```
master not discovered or elected yet, an election requires a node with id [JaGjvuwdSIWYmFlRFLJnMQ], have discovered [{quickstart-es-default-0}{JaGjvuwdSIWYmFlRFLJnMQ}{IyrNA9uzRXewhGGGlwAtvA}{10.12.1.10}{10.12.1.10:9300}{dilmrt}{ml.machine_memory=2147483648, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}, {quickstart-es-default-1}{2Qguuf0fRDq3BZRAyI2kuQ}{44pBgl3YT1mTvEwOSasrxg}{10.12.2.3}{10.12.2.3:9300}{dilmrt}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}] which is a quorum; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, 10.12.2.3:9300] from hosts providers and [{quickstart-es-default-1}{2Qguuf0fRDq3BZRAyI2kuQ}{44pBgl3YT1mTvEwOSasrxg}{10.12.2.3}{10.12.2.3:9300}{dilmrt}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true, transform.node=true}, {quickstart-es-default-0}{JaGjvuwdSIWYmFlRFLJnMQ}{IyrNA9uzRXewhGGGlwAtvA}{10.12.1.10}{10.12.1.10:9300}{dilmrt}{ml.machine_memory=2147483648, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}] from last-known cluster state; node term 2, last-accepted version 390 in term 2
```

Meanwhile, the operator seems to be deadlocked on removing a voting exclusion which can't be performed due to the downed cluster:

```
"log.level":"error","@timestamp":"2020-07-06T16:16:21.711Z","log.logger":"controller-runtime.controller","message":"Reconciler error","service.version":"1.1.1-f13b6d26","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","request":"default/quickstart","error":"[failed to revert to basic: 503 Service Unavailable: unknown, unable to delete /_cluster/voting_config_exclusions: 503 Service Unavailable: ]","errorCauses":[{"error":"failed to revert to basic: 503 Service Unavailable: unknown","errorVerbose":"503 Service Unavailable: unknown\nfailed to revert to basic\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.startBasic\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/apply.go:78\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.applyLinkedLicense\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/apply.go
...
```

**Comment by anyasabo** [comment]
Can you share logs from both nodes and your ES manifest? As you said it's confusing because it seems to have found the other node and previously formed a cluster, and thinks it has a quorum, but is not electing a master.

**Comment by PhaedrusTheGreek** [comment]
Yes, here's an `eck-dump` :  [eck-dump-with-election-issue.tar.gz](https://github.com/elastic/cloud-on-k8s/files/4881127/eck-dump-with-election-issue.tar.gz)

The strange thing is that this cluster was working mid-last week, then all of a sudden on Friday it was in this state.  The pods have been running for 17d.

**Comment by anyasabo** [comment]
Is there enough disk space? In the -0 logs:

>{"type": "server", "timestamp": "2020-07-06T15:44:54,447Z", "level": "WARN", "component": "o.e.i.s.RetentionLeaseSyncAction", "cluster.name": "quickstart", "node.name": "quickstart-es-default-0", "message": "[.apm-agent-configuration][0] retention lease background sync failed", "cluster.uuid": "Yjgb9pFTQuetEWEgCZOt_A", "node.id": "JaGjvuwdSIWYmFlRFLJnMQ" , 
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [quickstart-es-default-0][10.12.1.10:9300][indices:admin/seq_no/retention_lease_background_sync[p]]",
"Caused by: org.elasticsearch.gateway.WriteStateException: failed to write state to the first location tmp file /usr/share/elasticsearch/data/nodes/0/indices/_A2qqZHzQFuNEXLjzOHRjQ/0/retention-leases-39.st.tmp",
...
"\tSuppressed: java.io.IOException: No space left on device",

and similar errors on -1

**Comment by PhaedrusTheGreek** [comment]
Thanks @anyasabo , that's likely the problem - apologies!

**Comment by Haoke98** [comment]
I also has this problem!!!
I have a elasticsearch cluster and it was work well before. But yesterday I accidentally deleted the Master node that has been elected. After this, the another master node cannot be elected by other nodes, at the same time, I got the error(below) on it's logging file:
```
master not discovered or elected yet, an election requires a node with id [F-Tn-Q6vQuKE0Fgi5qtUMg], have only discovered non-quorum [{OPT__Master2}{ezEK9jukQTGtVW2DP3cSjA}{tHNwll8bTlmlmNes1HJPJg}{OPT__Master2}{192.168.1.30}{192.168.1.30:9801}{m}];
```
but  when I wanted fix this by using the /_cluster/voting_config_exclusions API , but I got the another erro like below:
```
503 master not discovered exception
```
How can i do ?

**Comment by Haoke98** [comment]
> I also have this problem!!! I have a elasticsearch cluster and it was work well before. But yesterday I accidentally deleted the Master node that has been elected. After this, the another master node cannot be elected by other nodes, at the same time, I got the error(below) on it's logging file:
> 
> ```
> master not discovered or elected yet, an election requires a node with id [F-Tn-Q6vQuKE0Fgi5qtUMg], have only discovered non-quorum [{OPT__Master2}{ezEK9jukQTGtVW2DP3cSjA}{tHNwll8bTlmlmNes1HJPJg}{OPT__Master2}{192.168.1.30}{192.168.1.30:9801}{m}];
> ```
> 
> but when I wanted fix this by using the /_cluster/voting_config_exclusions API , but I got the another erro like below:
> 
> ```
> 503 master not discovered exception
> ```
> 
> How can i do ?

@PhaedrusTheGreek  can you help fix this , it's very important to me , please🙏🙏🙏
