### ISSUE TITLE
Rely on a configMap for operator-level settings

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3401]
Forked from https://github.com/elastic/cloud-on-k8s/issues/2791.

The number of flags that can be passed to the operator binary is becoming quite large. It may feel more natural for users to tweak them through a configMap rather than modifying the operator StatefulSet spec. Providing a default config with comments explaining each setting would also make the possible options easier to understand.

Should we setup a mechanism to auto-reload the config, or auto-kill/restart the operator when the configuration changes, or should we let users deal with it?

**Comment by pebrc** [comment]
Another aspect here is that when ECK is installed via [Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager) users typically do not have the ability to tweak startup flags but a auto-reloaded configuration file would be a way to work around that restriction.
