### ISSUE TITLE
TestEnterpriseSearchConfigUpdate seems to be failing on OCP

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#3407]
Probably related to #3130 

Since July 1st, the [OCP test pipeline](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/) is in a yellow state with `TestEnterpriseSearchConfigUpdate` listed as the failing test.

**Comment by sebgl** [comment]
I think that's https://github.com/elastic/cloud-on-k8s/issues/3386

**Comment by charith-elastic** [comment]
I think it is interesting that that the log stream always ends by the time it reaches that test. Indeed, looking at the time elapsed between logging `Streaming pod logs` to `Log stream ended`  is _always_  1h &plusmn; 1m. I wonder whether it is a timeout in OCP that is configured differently from other Kubernetes distributions.

**Comment by sebgl** [comment]
@charith-elastic agreed, I looked around but could not see such timeout anywhere. I did not spend too long investigating though, considering this problem may also occasionally happen with other distributions due to network blips.

**Comment by charith-elastic** [comment]
Yes, random network failures are certainly something to contend with. It's just very interesting that there's a pattern to these particular failures though. It would be good to understand why the streaming log call seems to reliably terminate after 1 hour on OCP. If it is a configuration difference, it could have an effect on other API calls as well.

**Comment by sebgl** [comment]
Looks better now :). Let's reopen if needed.
