### ISSUE TITLE
 WebhookConfigurationName is hardcoded and not configurable

### ISSUE THREAD

**Issue by wmellouli** [elastic/cloud-on-k8s#3424]
## Proposal

Actually, we have many environments in the same kubernetes cluster, so we need to create multiple instances of eck operator in the same k8s cluster (test, dev, ...). 

To do that, we are using kustomize with `nameSuffix` feature to add a suffix on all k8s name ressources, e.g. : `nameSuffix: -dev`
so with kustomize we create a `ValidatingWebhookConfiguration` with name: `elastic-webhook.k8s.elastic.co-dev`

When we install eck operator, we get this error` validatingwebhookconfigurations.admissionregistration.k8s.io elastic-webhook.k8s.elastic.co not found`

The cause of this error is that `WebhookConfigurationName` is hardcoded as a constant and there is no way to override this value: https://github.com/elastic/cloud-on-k8s/blob/4c359ad33c32d801d26c6283209713e337f98162/cmd/manager/main.go#L65

I suggest to create a new optional flag: `WebhookConfigurationNameFlag` (with a default value `elastic-webhook.k8s.elastic.co`).
The new flag will allow users using `kustomize` with `nameSuffix` or `namePrefix` to be able to patch the `WebhookConfigurationName` using manager env variables. For example with a `patchesStrategicMerge`:

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WEBHOOK_CONFIGURATION_NAME
              value: elastic-webhook.k8s.elastic.co-dev
```

**Comment by wmellouli** [comment]
I created this pull request: https://github.com/elastic/cloud-on-k8s/pull/3425

**Comment by wmellouli** [comment]
FYI: related issue https://github.com/elastic/cloud-on-k8s/issues/2581

**Comment by anyasabo** [comment]
This is related to https://github.com/elastic/cloud-on-k8s/issues/3431

Currently we really only support one webhook/k8s cluster. I think this makes sense as a stepping stone to supporting this use case.

**Comment by wmellouli** [comment]
Related PR was merged https://github.com/elastic/cloud-on-k8s/pull/3425. I close this issue.
