### ISSUE TITLE
 Invalid value: "kibanaRef" when applying APM sample

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/cloud-on-k8s#3438]
## Bug Report
**What did you do?**
Tried adding APM server to Quickstart.

The Quickstart points to the sample configs, and I tried using the APM samples.  The [apmserver.yaml](https://github.com/elastic/cloud-on-k8s/blob/master/config/samples/apm/apmserver.yaml) is missing an `elasticsearchRef`, and the [apm_es_kibana.yaml](https://github.com/elastic/cloud-on-k8s/blob/master/config/samples/apm/apm_es_kibana.yaml) has a `kibanaRef` which seems to be an unsupported config (logs at bottom).

**What did you see instead? Under which circumstances?**
 Invalid value: "kibanaRef"

**Environment**

* ECK version:

	1.1.2

* Kubernetes information:

GKE, I tried 1.16.10-gke.8 and 1.14.10-gke.36

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
I took this from the sample configs and modified the references to point to the Quickstart Elasticsearch and Kibana:
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-apm-sample
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: "quickstart"
  kibanaRef:
    name: "quickstart"
```

* Logs:
STDOUT when I apply the above YAML:
```
kubectl apply -f apm-ex.yml 
Error from server (ApmServer.apm.k8s.elastic.co "apm-apm-sample" is invalid: 
kibanaRef: Invalid value: "kibanaRef": kibanaRef field found in the 
kubectl.kubernetes.io/last-applied-configuration annotation is unknown): error when 
creating "apm-ex.yml": admission webhook "elastic-apm-validation-v1.k8s.elastic.co" 
denied the request: ApmServer.apm.k8s.elastic.co "apm-apm-sample" is invalid: 
kibanaRef: Invalid value: "kibanaRef": kibanaRef field found in the 
kubectl.kubernetes.io/last-applied-configuration annotation is unknown
```

Removing the `kibanaRef` seems to work fine, I am sending in APM data.

**Comment by anyasabo** [comment]
The docs you mentioned are the `master` docs, but the version you are running is `1.1`. If you are looking at the docs in github you will want to switch to the 1.1 branch, or using the version drop down on the elastic.co docs site. This is a yet to be released feature.

**Comment by DanRoscigno** [comment]
Thanks, I will ping @alaudazzi and see if we can change the URL in the docs.

**Comment by DanRoscigno** [comment]
@alaudazzi , is there a way to have the asciidoc insert the current release version into the GitHub link?  Here is the page I am looking at:

https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-check-samples.html

and it is pointing to:

https://github.com/elastic/cloud-on-k8s/tree/master/config/samples

but it should point to:

https://github.com/elastic/cloud-on-k8s/tree/1.1/config/samples

**Comment by charith-elastic** [comment]
This is indeed a problem. I'll raise a PR to fix it.
