### ISSUE TITLE
ElasticSearch Operator - Helm Chart

### ISSUE THREAD

**Issue by vishnugs** [elastic/cloud-on-k8s#3442]
Hi,

I have seen the elasticsearch operator which can be deployed in self managed k8s. The deployment of the same is not straightforward.

Helm Chart - Elasticsearch Cluster
https://github.com/elastic/helm-charts/tree/master/elasticsearch

Im looking similar elasticsearch operator which can manage the cluster, backup etc 
https://github.com/elastic/cloud-on-k8s

**Comment by sebgl** [comment]
https://github.com/elastic/cloud-on-k8s is the Github repo for ECK - the Elastic stack operator. There is no Helm chart for this operator [at the moment](https://github.com/elastic/cloud-on-k8s/issues/938) - see the [quickstart guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html.

https://github.com/elastic/helm-charts/tree/master/elasticsearch is a Helm chart to deploy Elasticsearch - it has a limited feature set compared to what ECK provides (eg. no assistance with upscale, rolling upgrades or version upgrades).
