### ISSUE TITLE
Expand Stack Monitoring example to contain Filebeat

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3475]
From my [comment](https://github.com/elastic/cloud-on-k8s/pull/3465/files#r457098184) in Stack Monitoring PR, as it was already merged:

- we say it's stack monitoring, but even the Stack Monitoring UI is incomplete without it:
<img width="471" alt="Screenshot 2020-07-20 at 07 33 55" src="https://user-images.githubusercontent.com/50632861/87905246-677ae580-ca60-11ea-8f94-212ed45faa02.png">

- I applied the example and then I thought I'm combining it with a Filebeat examples, by applying one too. Took me a while to figure out ES that's being monitored has different labels than in other examples, so Stack Monitoring yaml has to be applied last

- when doing the above I also hit what seems like a [bug](https://github.com/elastic/cloud-on-k8s/issues/3470)

- we already duplicate parts of the config between three Filebeat examples, I think that's ok

It's not that many lines and brings full Stack Monitoring experience, I'd do it :)

**Comment by anyasabo** [comment]
>I applied the example and then I thought I'm combining it with a Filebeat examples, by applying one too. Took me a while to figure out ES that's being monitored has different labels than in other examples, so Stack Monitoring yaml has to be applied last

Ah I was anticipating that people would comment out the ES and Kibana resources from the Filebeat example, but I can see how that's not clear
