### ISSUE TITLE
curator crd

### ISSUE THREAD

**Issue by kfox1111** [elastic/cloud-on-k8s#3491]
A CRD for Curator to make it easy to clean out old indexes would be great.

**Comment by pebrc** [comment]
Any reason not to use the built-in [Index Lifecycle Management](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html) for that?

**Comment by kfox1111** [comment]
Just that I wasn't aware of it. :)

Thanks for the pointer. I'll give that a shot.
