### ISSUE TITLE
Short-circuit reconciliation if ES is down 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#3496]
If Elasticsearch is not responding in time to API requests we keep trying to make requests to it from the Elasticsearch controller effectively blocking reconciliation of other clusters in that go routine for 90 seconds. 

![Screenshot 2020-07-21 at 09 12 35](https://user-images.githubusercontent.com/697790/88025479-9ebac680-cb34-11ea-974f-f75798f9a1b4.png)

I believe @anyasabo also observed the same thing. We could short-circuit the reconciliation loop in these cases instead of continuing. So instead or 90 seconds we would give up after 30 seconds.

**Comment by anyasabo** [comment]
++ that was the big thing I noticed in https://github.com/elastic/cloud-on-k8s/issues/2939. Unfortunately it will take a bit of refactoring as we mix in calls to the k8s API that we want to make even if the ES cluster is not responding. I think we will want to move all of the k8s API operations we can do first and then do the ES operations later. I think doing this will also resolve (or at least improve) the slow cluster health status update issue.

**Comment by anyasabo** [comment]
Thinking about this more, I also wonder if we want to make this timeout configurable. In cloud today we have it set to 60s I believe. It's definitely not urgent because it hasn't come up yet, but might be helpful for getting fubared clusters slightly less fubared

**Comment by sebgl** [comment]
@anyasabo yes, all timeouts should be configurable: https://github.com/elastic/cloud-on-k8s/issues/684
