### ISSUE TITLE
Custom plugin and bundles support.

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#35]
We don't want to store binary data in K8s apis, so perhaps the ECE way of declaring URLs are acceptable? Does tie the availability of nodes to the availability of the URLs.

Perhaps a new CRD for these would make sense as well? They are potentially something we'd like shared between clusters, and they need to be inherently versioned. (Plugins more-so than bundles, so perhaps we split this into a subtask for each?)

**Comment by nkvoll** [comment]
Bundles can be done through `podTemplate` now, but that is in need of some documentation.

Plugins would be easily doable through an init container if https://github.com/elastic/cloud-on-k8s/pull/1022 gets merged.

**Comment by pebrc** [comment]
Closed via #1022
