### ISSUE TITLE
Deploying Filebeat results in serviceaccount error

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/cloud-on-k8s#3500]
## Bug Report
**What did you do?**
 - Deployed ECK CRDs 1.2.0
 - Copied [the sample](https://github.com/elastic/cloud-on-k8s/blob/1.2/config/samples/beat/filebeat_es_kibana_apm.yaml) and edited with my `elasticsearchRef`
 - Deployed
 - Saw only APM indices
 - Looked at the logs

**What did you expect to see?**
Filebeat index and logs

**What did you see instead? Under which circumstances?**
```
E0721 15:10:34.248188       1 reflector.go:125] github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:146: 
Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in 
API group "" at the cluster scope
```
**Environment**
GKE, ECK 1.2.0

* ECK version:

1.2.0

* Kubernetes information:

GKE
	
	for each of them please give us the version you are using
```
$ kubectl version

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.10-gke.8", GitCommit:"fd29f95f189cb16dd8fe0bd5dc8b485dfd049d2c", GitTreeState:"clean", BuildDate:"2020-06-23T23:44:30Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Other info:

Looking at the [default Filebeat Kubernetes](https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat-kubernetes.yaml) manifest I see the following, maybe this helps:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
```

**Comment by DanRoscigno** [comment]
My manifest:

[eck120.yaml.txt](https://github.com/elastic/cloud-on-k8s/files/4954522/eck120.yaml.txt)

**Comment by DanRoscigno** [comment]
Note: The recipe includes the service account, I will look into what the diffs are:
https://github.com/elastic/cloud-on-k8s/blob/1.2/config/recipes/beats/filebeat_autodiscover.yaml

**Comment by david-kow** [comment]
Hi @DanRoscigno, it's a known [issue](https://github.com/elastic/cloud-on-k8s/issues/3338) - that sample will soon be removed as, as you can see, doesn't work ootb which was not the intention. You take a look at our [Configuration Examples](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-beat-configuration-examples.html) or [recipes](https://github.com/elastic/cloud-on-k8s/tree/master/config/recipes/beats) to find self-contained example manifests.

**Comment by DanRoscigno** [comment]
Thanks @david-kow , I just found the recipes.  Working fine now!

**Comment by david-kow** [comment]
That's good to hear!
