### ISSUE TITLE
30min timeout reached on AKS es mutation e2e tests

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3529]
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-aks/435/testReport/

**Comment by pebrc** [comment]
Since moving to local volumes the AKS tests seem to run ~ 30% faster ~ 4:30h instead of ~6:30h so I wonder if we will see this timeout again.

**Comment by sebgl** [comment]
Let's close and reopen if needed.
