### ISSUE TITLE
Misleading log statements in association controller

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3535]
The controller handling both Kibana and ES associations has logging statements that are confusing. E.g.:

https://github.com/elastic/cloud-on-k8s/blob/0d31c4ae18ac652d237c451d8b73758ce4c94002/pkg/controller/association/reconciler.go#L315

https://github.com/elastic/cloud-on-k8s/blob/0d31c4ae18ac652d237c451d8b73758ce4c94002/pkg/controller/association/reconciler.go#L320

This leads to logs similar to the below. Notice Kibana assoc logging about ES config.
`{"log.level":"info","@timestamp":"2020-07-23T19:27:17.235Z","log.logger":"association.beat-kibana-association-controller","message":"Updating spec with Elasticsearch association configuration","service.version":"1.2.0-51ae5fd4","service.type":"eck","ecs.version":"1.4
.0","namespace":"monitoring","beat_name":"log"}`

**Comment by sebgl** [comment]
Will be fixed as part of https://github.com/elastic/cloud-on-k8s/pull/3537.
