### ISSUE TITLE
Support UBI based stack images 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#3552]
We want to support UBI based stack images in ECK. This affects mainly the defaulting mechanism which takes effect if a user does not explicitly specify a Docker image inside the `podTemplate` section of the manifest. 

The following options come to mind: 
- an additional operator flag (flag inflation!) to control the image default (suffix) e.g. `docker.elastic.co/elasticsearch/elasticsearch-ubi7:7.6.0` instead of `docker.elastic.co/elasticsearch/elasticsearch:7.6.0`
   * adds a bit of complexity around what the effective docker image is that ECK will pull given that we already allow an override of the registry.
   * probably the most pragmatic solution
- a configuration file mounted which has a value for each of the applications we support 
   * would add additional value for users that want to override the default images with their own custom images without the need to specify them fully in every manifst
   * more generic solution more work

**Comment by anyasabo** [comment]
I'm +1 to adding a `ubi` bool flag or something similar that changes the default image. Users can still override it. I'm not particularly worried about the additional complexity of knowing the effective docker image. I thiiiink the flag would just modify the name of the image and would work in tandem with the custom repository to easily allow air gapped UBI only configurations.

I also think even if we did want to support a more generic version of this functionality, we would still want the UBI flag to make the (presumably) most common use case easy.

**Comment by pebrc** [comment]
I think we want something slightly more generic than a `ubi` flag. I am thinking a configurable suffix to the operator image might be a good compromise. Something like `--container-suffix=ubi`. This would be in line with the `--container-registry` flag we already have.

This would have the advantage that we don't have to hard-code a UBI suffix and others uses are possible too. 

The configuration file method while most generic has the disadvantage that to my knowledge OLM does not support additional manifests as part of the operator spec, so we could not ship the file with the OLM version of ECK. 

There is finally a bit of uncertainty which naming convention we will have to support: 

* an image suffix as suggested above e.g.  `docker.elastic.co/elasticsearch/elasticsearch-ubi:7.9.0`
* a different tag e.g. `docker.elastic.co/elasticsearch/elasticsearch:7.9.0-ubi`
* a custom namespace `docker.elastic.co/elasticsearch-ubi/elasticsearch:7.9.0`

**Comment by pebrc** [comment]
>     * an image suffix as suggested above e.g.  `docker.elastic.co/elasticsearch/elasticsearch-ubi:7.9.0`

We are going with an image suffix.
