### ISSUE TITLE
QOS is not set for initContainer (elastic-internal-init-keystore)

### ISSUE THREAD

**Issue by smahalingam** [elastic/cloud-on-k8s#3567]
initContainer which is used to setup keystore, doesn't have the QOS/resources. 

**What did you do?**
I tried attaching secrets into pod,
```  
  secureSettings:
    - secretName: gcs-bucket-credentials
```
and then operator creates Statefulset with initContainer (`elastic-internal-init-keystore`). QOS/resources is not set for initContainer. 

**What did you expect to see?**
Operator should set QOS for `elastic-internal-init-keystore`, like it does for `elastic-internal-init-filesystem`

**What did you see instead? Under which circumstances?**
QOS not set on `elastic-internal-init-keystore` 

**Environment**
GKE `v1.14.10-gke.36` 

* ECK version:
	1.1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* GKE
	* v1.14.10-gke.36
	
	for each of them please give us the version you are using
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thbkrkr** [comment]
Duplicates of #2660 resolved by #3193.

This has been landed in the new version [1.2.0](https://www.elastic.co/guide/en/cloud-on-k8s/1.2/release-notes-1.2.0.html).
