### ISSUE TITLE
Log level change requires full restart

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#3593]
Follow-up from #3570 

Once the log level is set, it cannot be changed again without completely stopping the operator and restarting it. This is due to the use of the global `Log` variable in the controller-runtime log package. Even though it can be replaced with a new logger, existing loggers created from the previous logger will not be updated -- which makes it difficult to effect a global log level change in code.

**Comment by pebrc** [comment]
Known issue we won't fix.
