### ISSUE TITLE
Quickstart guide on beats with ECK does not work

### ISSUE THREAD

**Issue by thepotatocannon** [elastic/cloud-on-k8s#3594]
## Bug Report

I used quickstart deployments to test Filebeat on ECK. All the yaml files were taken from documentation. While Kibana and Elasticsearch both work fine, Filebeats cannot connect to elasticsearch.  
Operator version is 1.2.0, ECK stack uses 7.8.1, `kubectl version` results:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T14:00:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
I don't use any specific cloud provider.

Logs from beats:
```
2020-08-06T14:02:14.400Z	WARN	[transport]	transport/tcp.go:52	DNS lookup failure "quickstart-es-http.elastic-system.svc": lookup quickstart-es-http.elastic-system.svc on 10.96.0.10:53: read udp 10.10.1.50:54114->10.96.0.10:53: i/o timeout
2020-08-06T14:02:16.333Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:155	Failed to connect to backoff(elasticsearch(https://quickstart-es-http.elastic-system.svc:9200)): Get https://quickstart-es-http.elastic-system.svc:9200: lookup quickstart-es-http.elastic-system.svc on 10.96.0.10:53: read udp 10.10.1.50:54114->10.96.0.10:53: i/o timeout
2020-08-06T14:02:16.333Z	INFO	[publisher_pipeline_output]	pipeline/output.go:146	Attempting to reconnect to backoff(elasticsearch(https://quickstart-es-http.elastic-system.svc:9200)) with 1 reconnect attempt(s)
2020-08-06T14:02:16.333Z	INFO	[publisher]	pipeline/retry.go:221	retryer: send unwait signal to consumer
2020-08-06T14:02:16.333Z	INFO	[publisher]	pipeline/retry.go:225	  done
```

Any ideas what could go wrong?

**Comment by barkbay** [comment]
```DNS lookup failure "quickstart-es-http.elastic-system.svc": lookup quickstart-es-http.elastic-system.svc on 10.96.0.10:53: read udp 10.10.1.50:54114->10.96.0.10:53: i/o timeout```

Looks like a DNS failure, could you confirm that the Service `quickstart-es-http` exists in the namespace `elastic-system` and check that you can resolve `quickstart-es-http.elastic-system.svc` to the cluster IP from a Pod in your cluster ?

**Comment by thepotatocannon** [comment]
> `DNS lookup failure "quickstart-es-http.elastic-system.svc": lookup quickstart-es-http.elastic-system.svc on 10.96.0.10:53: read udp 10.10.1.50:54114->10.96.0.10:53: i/o timeout`
> 
> Looks like a DNS failure, could you confirm that the Service `quickstart-es-http` exists in the namespace `elastic-system` and check that you can resolve `quickstart-es-http.elastic-system.svc` to the cluster IP from a Pod in your cluster ?

Sorry for the delay. The service exists in the given namespace, what's more, I created a busybox pod, issued `nslookup` command with that service and addresses where successfully resolved.
Is there any possibility that this is connected with current beats image/setup?

**Comment by barkbay** [comment]
I'm wondering if it might come from the `dnsPolicy: ClusterFirstWithHostNet` from the quickstart.
Could you deploy the busybox Pod again with the `dnsPolicy` set to `ClusterFirstWithHostNet` and see if you get the same error ?

**Comment by thepotatocannon** [comment]
Update: 
It was definitely because of the parameter `hostNetwork` (changing `dnsPolicy` didn't make any difference in behavior). The problem was, when I commented `hostNetwork: true`, no data could be collected from nodes.
I ended up switching to a different cluster and deployed whole stack without changes, the DNS failure is gone, but I don't see any logs in kibana, nor the index created in elasticsearch.
Any ideas on how to investigate it further?

**Comment by barkbay** [comment]
> I ended up switching to a different cluster and deployed whole stack without changes, the DNS failure is gone, but I don't see any logs in kibana, nor the index created in elasticsearch.

We are trying to keep Github issues only for actual bug reports and feature requests. It seems that your issue is related to your environment. We would be happy to help but can you create a topic in our discuss forum at https://discuss.elastic.co/c/eck. Also please provide more details about your environment (on prem., EKS, GKE, OCP ?), the operator logs, the health of the cluster...

Thank you.

**Comment by meiry** [comment]
@thepotatocannon  
I'm having the same issue when deploying in Kubernetes 
did you managed to fix it ?

**Comment by thepotatocannon** [comment]
When it comes to the first issue we whad the problem connected to DNS settings. Speaking of authorization, for the purpose of tests, we simply turned off https. Finally, the problem related to no logs in elastic/kibana, it turned out that container logs in our environment were saved in a different directory, so mounting the right one from workers was enough.

**Comment by meiry** [comment]
@thepotatocannon 
how did you turend off https ?
How did you find the error about the mounting? the kibana and filebeats logs don't show anything related to any thing ...

**Comment by thepotatocannon** [comment]
I don't remember how but I am pretty sure it is somewhere in the documentation.
As it comes to logs, I first checked files in filebeat containter and there were symbolic links to files containing logs but the container itself didn't have the access to the actual files, that's why mounting it was enough.

**Comment by meiry** [comment]
@thepotatocannon 
Ok did the checking log thing and they indid there and i can access them and see them with no problem about the http you mean to turn off in the elasticsearch cluster level right? 
so i could access it like this :
curl -u "elastic:xxxxxxxx" -k "http://my-cluster-es-http:9200"

**Comment by thepotatocannon** [comment]
probably yes, this is what we did, but honestly I cannot remember exactly now.
