### ISSUE TITLE
Migration from helm chart to Elastic Cloud on k8s

### ISSUE THREAD

**Issue by Born2Bake** [elastic/cloud-on-k8s#3611]
## Documentation of how to migrate from helm charts to Elastic Cloud on K8s.

Hello,

We have EFK (7.6.2) stack deployed on Kubernetes via official helm charts. However, we would like to migrate to Elastic operatour and have Elastic cloud on k8s. Thus, I am wondering if any kind of documentation related to "How to migrate to Elastic Cloud from Helm charts" would be really nice to have cause we do not want to lose any data we currently have in our efk stack.

Thank you

**Comment by thbkrkr** [comment]
There is nothing really specific to Kubernetes or Helm to [migrate your Elastisearch data](https://www.elastic.co/guide/en/cloud/current/ec-migrate-data.html) into a new infrastructure.

If you choose [snapshot and restore](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html) to create backups. There is an [example](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-snapshots.html) in ECK documentation using GCS. You can configure the [S3 repository plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3.html) in a similar way.

Please use Github issues only for actual bug reports and feature requests.
For questions around ECK please use our discuss forum at https://discuss.elastic.co/c/eck.
