### ISSUE TITLE
ML support

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#363]
ML nodes in small JVMs need different settings to provide acceptable performance. 
For large ML nodes we don't want to grow the Elasticsearch JVM in lock-step with the node but we want to have an upper limit to the JVM size. 

- [ ] Rule of thumb for ML specific settings: 
`xpack.ml.max_machine_memory_percent`: min(90, round((container_size - JVM_heap_size - 200MB) / container_size * 100))
`xpack.ml.max_model_memory_limit`: container_size - JVM_heap_size - 300MB

- [ ] for JVM size:
    * <2GB container => 512MB JVM
    * \>=2GB && <= 8GB container => 25% of container size JVM
    * \>8GB container => 2GB JVM
- [ ] Finally during snapshot restore persistent tasks need to be suspended in order to ensure the ML processes have a consistent view of the data at all times.

**Comment by nkvoll** [comment]
This is now all user-configurable
