### ISSUE TITLE
Improve Webhook server documentation

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3638]
The [current documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-webhook.html) does not clearly describe the different ways to setup and configure the webhook server:

* Let's make it clear that by default ECK automatically manages the certificates
* [Using the cert manager](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-webhook-cert-manager.html) is only an option
* Let's also add a sample to show how to manually manage the certs:
  * add the CA to the `ValidatingWebhookConfig`
  * put the key and the certificate signed by the CA in the secret that the operator mounts

**Comment by alaudazzi** [comment]
@barkbay and @shubhaat this issue covers the use case described in #3616. Maybe we can combine the two issues?

**Comment by shubhaat** [comment]
Yes, I Think we can keep this one and I can close the other one.
