### ISSUE TITLE
Kibana / Alerts and Actions do not work due to TLS misconfiguration

### ISSUE THREAD

**Issue by dobegor** [elastic/cloud-on-k8s#3644]
## Bug Report
**What did you do?**
Set up Elasticsearch and Kibana using Quickstart guide. Opened Stack Management -> Alerts and actions.
**What did you expect to see?**
Alerts and actions ready to be configured.
**What did you see instead? Under which circumstances?**
"You must enable Transport Layer Security

Alerting relies on API keys, which require TLS between Elasticsearch and Kibana. Learn how to enable TLS."
* ECK version: 1.2

* Kubernetes information:
GKE, v1.15.12-gke.2
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

I do believe that the root of this issue is that configuration that is being passed to kibana looks like this (note the *http* instead of *https*):
```
$ cat kibana.yml
elasticsearch:
  hosts:
  - http://search-es-http.default.svc:9200
  password: censored
  ssl:
    certificateAuthorities: /usr/share/kibana/config/elasticsearch-certs/ca.crt
    verificationMode: certificate
  username: default-search-kibana-user
```

**Comment by dobegor** [comment]
![image](https://user-images.githubusercontent.com/14029650/90772796-b6d16180-e2fd-11ea-9b39-8d2f7c9a4a80.png)

**Comment by charith-elastic** [comment]
Have you disabled TLS on Elasticsearch by setting `http.tls.selfSignedCertificate.disabled: true` in the manifest? That would disable the API keys service because it requires TLS.

**Comment by dobegor** [comment]
@charith-elastic thanks, that's exactly what I did. I actually thought that it would only affect a client-facing k8s service.
