### ISSUE TITLE
Implement CCR/CCS/remote cluster concept

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#369]
We already have the "trust relationship" concept, in which our operator will update trusted URLs for a given cluster, as a pre-requisite for cross-cluster search/replication.

We should build on top of that, as part of the global operator, to handle CCS/CCR.

**Comment by pebrc** [comment]
I am reopening this one as we want to revisit some of the design choices made.

**Comment by pebrc** [comment]
We have decided to support the remote cluster concept via 
#962 for now and remove the current CRDs for remote clusters in #963

**Comment by pebrc** [comment]
Closing this as #2203 implements a version of the feature described in this issue.
