### ISSUE TITLE
APM Server Pods are not annotated with co.elastic.logs/module

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3721]
We annotate ES/KB Pods with `co.elastic.logs/module` annotation set to `elasticsearch` and `kibana`, but we don't do that for APM Server. The module that [should be enabled](https://www.elastic.co/guide/en/apm/server/current/monitoring-metricbeat-collection.html) is `beat`.

**Comment by barkbay** [comment]
Is it something that we can do right now ? My understanding is that `co.elastic.logs/module` is used to parse the logs from the containers, but according to https://github.com/elastic/beats/issues/15054 there is no module available yet for the APM Server ?

**Comment by naemono** [comment]
Closing this, as there's no filebeat module for apm server https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-modules.html, and the referenced issue was closed with no resolution, noting that Elastic Agent has support for apm server integration.
