### ISSUE TITLE
Add docs for set-default-security-context flag

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3730]
Document why the flag exist, when it can be ignored and when the default should be overriden.

**Comment by alaudazzi** [comment]
@david-kow as discussed over slack, this is the page that should be updated:
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-operator-config.html
If you can provide the input, I'm happy to push a PR. Or if you prefer, make the change yourself and I'll review it?
