### ISSUE TITLE
Stopping on waiting for the transport certificates when deply elasticsearch on k8s with eck 1.1.2

### ISSUE THREAD

**Issue by Michael-Guo** [elastic/cloud-on-k8s#3731]
Install elasticsearch 7.9.0 on k8s with eck 1.1.2, I stopped on waiting for the transport certificates (/mnt/elastic-internal/transport-certificates/es-cluster-es-master-nodes-0.tls.key) in the process of init container ( elastic-internal-init-filesystem).

k8s: native k8s cluster built from source code, not in cloud

eck version: 1.1.2

kubectl version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

logs: 
Starting init script
Linking /mnt/elastic-internal/xpack-file-realm/users to /usr/share/elasticsearch/config/users
Linking /mnt/elastic-internal/xpack-file-realm/roles.yml to /usr/share/elasticsearch/config/roles.yml
Linking /mnt/elastic-internal/xpack-file-realm/users_roles to /usr/share/elasticsearch/config/users_roles
Linking /mnt/elastic-internal/elasticsearch-config/elasticsearch.yml to /usr/share/elasticsearch/config/elasticsearch.yml
Linking /mnt/elastic-internal/unicast-hosts/unicast_hosts.txt to /usr/share/elasticsearch/config/unicast_hosts.txt
File linking duration: 0 sec.
Copying /usr/share/elasticsearch/config/* to /mnt/elastic-internal/elasticsearch-config-local/
'/usr/share/elasticsearch/config/elasticsearch.yml' -> '/mnt/elastic-internal/elasticsearch-config-local/elasticsearch.yml'
'/usr/share/elasticsearch/config/http-certs' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs'
'/usr/share/elasticsearch/config/http-certs/..data' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..data'
'/usr/share/elasticsearch/config/http-certs/tls.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/tls.crt'
'/usr/share/elasticsearch/config/http-certs/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/ca.crt'
'/usr/share/elasticsearch/config/http-certs/tls.key' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/tls.key'
'/usr/share/elasticsearch/config/http-certs/..2020_09_08_11_20_34.878611724' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_08_11_20_34.878611724'
'/usr/share/elasticsearch/config/http-certs/..2020_09_08_11_20_34.878611724/tls.key' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_08_11_20_34.878611724/tls.key'
'/usr/share/elasticsearch/config/http-certs/..2020_09_08_11_20_34.878611724/tls.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_08_11_20_34.878611724/tls.crt'
'/usr/share/elasticsearch/config/http-certs/..2020_09_08_11_20_34.878611724/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_08_11_20_34.878611724/ca.crt'
'/usr/share/elasticsearch/config/jvm.options' -> '/mnt/elastic-internal/elasticsearch-config-local/jvm.options'
'/usr/share/elasticsearch/config/jvm.options.d' -> '/mnt/elastic-internal/elasticsearch-config-local/jvm.options.d'
'/usr/share/elasticsearch/config/log4j2.properties' -> '/mnt/elastic-internal/elasticsearch-config-local/log4j2.properties'
'/usr/share/elasticsearch/config/role_mapping.yml' -> '/mnt/elastic-internal/elasticsearch-config-local/role_mapping.yml'
'/usr/share/elasticsearch/config/roles.yml' -> '/mnt/elastic-internal/elasticsearch-config-local/roles.yml'
'/usr/share/elasticsearch/config/transport-remote-certs' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs'
'/usr/share/elasticsearch/config/transport-remote-certs/..data' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/..data'
'/usr/share/elasticsearch/config/transport-remote-certs/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/ca.crt'
'/usr/share/elasticsearch/config/transport-remote-certs/..2020_09_08_11_20_34.160459864' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/..2020_09_08_11_20_34.160459864'
'/usr/share/elasticsearch/config/transport-remote-certs/..2020_09_08_11_20_34.160459864/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/..2020_09_08_11_20_34.160459864/ca.crt'
'/usr/share/elasticsearch/config/unicast_hosts.txt' -> '/mnt/elastic-internal/elasticsearch-config-local/unicast_hosts.txt'
'/usr/share/elasticsearch/config/users' -> '/mnt/elastic-internal/elasticsearch-config-local/users'
'/usr/share/elasticsearch/config/users_roles' -> '/mnt/elastic-internal/elasticsearch-config-local/users_roles'
Empty dir /usr/share/elasticsearch/plugins
Copying /usr/share/elasticsearch/bin/* to /mnt/elastic-internal/elasticsearch-bin-local/
'/usr/share/elasticsearch/bin/elasticsearch' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch'
'/usr/share/elasticsearch/bin/elasticsearch-certgen' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-certgen'
'/usr/share/elasticsearch/bin/elasticsearch-certutil' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-certutil'
'/usr/share/elasticsearch/bin/elasticsearch-cli' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-cli'
'/usr/share/elasticsearch/bin/elasticsearch-croneval' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-croneval'
'/usr/share/elasticsearch/bin/elasticsearch-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-env'
'/usr/share/elasticsearch/bin/elasticsearch-env-from-file' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-env-from-file'
'/usr/share/elasticsearch/bin/elasticsearch-keystore' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-keystore'
'/usr/share/elasticsearch/bin/elasticsearch-migrate' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-migrate'
'/usr/share/elasticsearch/bin/elasticsearch-node' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-node'
'/usr/share/elasticsearch/bin/elasticsearch-plugin' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-plugin'
'/usr/share/elasticsearch/bin/elasticsearch-saml-metadata' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-saml-metadata'
'/usr/share/elasticsearch/bin/elasticsearch-setup-passwords' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-setup-passwords'
'/usr/share/elasticsearch/bin/elasticsearch-shard' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-shard'
'/usr/share/elasticsearch/bin/elasticsearch-sql-cli' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-sql-cli'
'/usr/share/elasticsearch/bin/elasticsearch-sql-cli-7.9.0.jar' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-sql-cli-7.9.0.jar'
'/usr/share/elasticsearch/bin/elasticsearch-syskeygen' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-syskeygen'
'/usr/share/elasticsearch/bin/elasticsearch-users' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-users'
'/usr/share/elasticsearch/bin/x-pack-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/x-pack-env'
'/usr/share/elasticsearch/bin/x-pack-security-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/x-pack-security-env'
'/usr/share/elasticsearch/bin/x-pack-watcher-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/x-pack-watcher-env'
Files copy duration: 0 sec.
chowning /usr/share/elasticsearch/data to elasticsearch:elasticsearch
changed ownership of '/usr/share/elasticsearch/data' from root:root to elasticsearch:elasticsearch
chowning /usr/share/elasticsearch/logs to elasticsearch:elasticsearch
changed ownership of '/usr/share/elasticsearch/logs' from root:root to elasticsearch:elasticsearch
chown duration: 0 sec.
waiting for the transport certificates (/mnt/elastic-internal/transport-certificates/es-cluster-es-master-nodes-0.tls.key)

**Comment by pebrc** [comment]
So I guess the question is why are the transport certificates not there. 
* Can you check the operator logs https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting-methods.html * Then it would also interesting to see if the corresponding secret which holds the transport certificates exists: I am assuming based on your log snippet it should be called `es-cluster-es-transport-certificates`

**Comment by Michael-Guo** [comment]
> So I guess the question is why are the transport certificates not there.
> 
> * Is this the first Elasticsearch cluster you have deployed and it never worked or has it worked for others?
> * Can you check the operator logs https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting-methods.html
> * Then it would also interesting to see if the corresponding secret which holds the transport certificates exists: I am assuming based on your log snippet it should be called `es-cluster-es-transport-certificates`
> * Finally: any reason not use the latest version of the operator?

Thank you, it is great to hear reply from you.
It is my first time to deploy an Elasticsearch cluster, it never woked. 
I try to update eck version to 1.2.1, but it still not works.
Eck v1.2. is installed in namespce: elastic-system, es cluster is deployed in namespace: elasticsearch.

**here are the operator's logs.**
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.506Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":57,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000122013}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.623Z","log.logger":"certificates","message":"Issuing new HTTP certificate","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","secret_name":"es-cluster-es-http-certs-internal","owner_namespace":"elasticsearch","owner_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.628Z","log.logger":"certificates","message":"Creating HTTP internal certificate secret","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","secret_name":"es-cluster-es-http-certs-internal"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.634Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":58,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.634Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":58,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000126379}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.635Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-http-certs-public"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.641Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":59,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.641Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":59,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000146058}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.641Z","log.logger":"certificates","message":"No internal CA certificate Secret found, creating a new one","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","owner_namespace":"elasticsearch","owner_name":"es-cluster","ca_type":"transport"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.810Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-transport-ca-internal"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.815Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":60,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.816Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":60,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000111486}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.816Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-transport-certs-public"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.821Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":61,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.821Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":61,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000132118}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.821Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-transport-certificates"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.826Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":62,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.826Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":62,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000119754}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.831Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":63,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.831Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":63,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000175244}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.931Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-elastic-user"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.936Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":64,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:03.936Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":64,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000152896}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.109Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-internal-users"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.114Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":65,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.114Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":65,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000153326}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.115Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-xpack-file-realm"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.122Z","log.logger":"observer","message":"Creating observer for cluster","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.122Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"ConfigMap","namespace":"elasticsearch","name":"es-cluster-es-unicast-hosts"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.122Z","log.logger":"settings","message":"Creating seed hosts","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","es_name":"es-cluster","hosts":[]}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.124Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":66,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.124Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":66,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000158706}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.134Z","log.logger":"driver","message":"Creating master node","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","statefulset_name":"es-cluster-es-master-nodes","actualReplicas":0,"targetReplicas":1}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.134Z","log.logger":"zen2","message":"Setting `cluster.initial_master_nodes`","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","es_name":"es-cluster","cluster.initial_master_nodes":"es-cluster-es-master-nodes-0"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.145Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"elasticsearch","name":"es-cluster-es-master-nodes-es-config"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.146Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":67,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.146Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":67,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000245956}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.146Z","log.logger":"license-controller","message":"Starting reconciliationrun","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":12,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.150Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":68,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.151Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":68,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000273516}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.151Z","log.logger":"license-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":12,"namespace":"elasticsearch","es_name":"es-cluster","took":0.004524806}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.151Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"Service","namespace":"elasticsearch","name":"es-cluster-es-master-nodes"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.156Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","kind":"StatefulSet","namespace":"elasticsearch","name":"es-cluster-es-master-nodes"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.180Z","log.logger":"driver","message":"ES cannot be reached yet, re-queuing","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.186Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":52,"namespace":"elasticsearch","es_name":"es-cluster","took":0.859560017}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.186Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":53,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.186Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.186Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":53,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000120822}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.191Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":54,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.191Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.191Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":54,"namespace":"elasticsearch","es_name":"es-cluster","took":0.00022882}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.213Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":55,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.214Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.214Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":55,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000131671}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.220Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":56,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.220Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.220Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":56,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000156409}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.222Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":57,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.222Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:55:04.222Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":57,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000121444}
{"log.level":"info","@timestamp":"2020-09-09T07:57:03.972Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":58,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:57:03.972Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:57:03.972Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":58,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000216317}
{"log.level":"info","@timestamp":"2020-09-09T07:57:03.991Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":59,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:57:03.992Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:57:03.992Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":59,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000168463}
{"log.level":"info","@timestamp":"2020-09-09T07:58:02.381Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":60,"namespace":"elasticsearch","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:58:02.382Z","log.logger":"annotation","message":"Resource was created with olderversion of operator, will not take action","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","controller_version":"0.0.0","resource_controller_version":"0.0.0","namespace":"elasticsearch","name":"es-cluster"}
{"log.level":"info","@timestamp":"2020-09-09T07:58:02.382Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","iteration":60,"namespace":"elasticsearch","es_name":"es-cluster","took":0.000228695}

In addition, the  secret, es-cluster-es-transport-certificates,  which holds the transport certificates exists
<img width="656" alt="批注 2020-09-09 161326" src="https://user-images.githubusercontent.com/12717447/92572755-6bd0bb80-f2b7-11ea-822a-2af309aff5ed.png">


But I didn't find es-cluster-es-master-nodes-0.tls.key. Where does the key should be.
Any suggestion for me?
Waiting for your apply, thanks again.

**Comment by Michael-Guo** [comment]
I solve my problem by downloading the eck image from docker.elastic.co. Previously I built the image from source code.  It should be the same whether the image is downloaded or built from source code.
Thanks again. 
Please close this issue.
