### ISSUE TITLE
Port is interpreted as a part of the address in kind IPv6 E2E test

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3737]
In the [test failure](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-kind-k8s-versions/207/testReport/github/com_elastic_cloud-on-k8s_test_e2e_beat/Run_tests_on_different_versions_of_vanilla_K8s___1_17_5_IPv6___TestMetricbeatStackMonitoringRecipe_ES_data_should_pass_validations/) we can see:

```
won't start runner: 1 error: host parsing failed for kibana-stats: error parsing URL: address fd00:10:244:0:3::51:5601: too many colons in address"}
```

Which is caused by appending the port (5601) to the IPv6 address of the host. The port is interpreted as the last group, making the group count 7. The `::` can't be used to omit a single group, hence the error.

This adress is constructed from Metricbeat config:

https://github.com/elastic/cloud-on-k8s/blob/15a5fd79d4b96dadfa45bbc6cf1d116b7da97e03/config/recipes/beats/stack_monitoring.yaml#L52

It works for IPv4, but for IPv6, the proper format would be `hosts: "https://[${data.host}]:${data.port}"`. This would require switching somewhere between IPv4 and IPv6, so I'm wondering if there is a better solution.

**Comment by sebgl** [comment]
This looks like a bug in Beats to me: Beats should be able to detect that `data.host` resolves to an ipv6 address to do what's necessary?

**Comment by david-kow** [comment]
> This looks like a bug in Beats to me: Beats should be able to detect that `data.host` resolves to an ipv6 address to do what's necessary?

I don't think it's a bug. As the port is optional in the URL, last group being (or not being) the port determines what's the address. Ie.:

`fd00:10:244::51:5601` could be:
`[fd00:0010:0244:0000:0000:0000:0000:0051]:5601`
`[fd00:0010:0244:0000:0000:0000:0051:5601]`

The only "fix" I can see is introducing something like `data.hostSafe` which will return the regular ipv4 or bracketed ipv6.
