### ISSUE TITLE
Global vs. namespace vs. configurable operators

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#374]
One concept we discussed a few times is to have the global operator responsible for managing namespace operators.

It would need to:

* Watch Stack, Elasticsearchcluster, Kibana resources
* Spawn a namespace operator in a given namespace dynamically
    * And create its RBAC resources (service account, roles, role bindings) - we can probably use a single ClusterRole here, that we map to individual namespaced service accounts in a non cluster-wide RoleBinding.
* Remove namespace operators from namespaces when not needed anymore

Some questions we need to tackle:

* The global operator service account needs permissions to create ServiceAccount, ClusterRole, RoleBindings, ReplicaSet, etc. in any namespace. Is that OK to have such a high-level of privileges on all namespaces? Do we want an option to restrict it to a list of namespaces only?
* Versioning: should the global operator auto-update running namespace operators to the latest version (ie. the version of the global operator itself, since we use the same Docker image)?
* If we already have a global operator running with high privileges, is there really a benefit in deploying individual namespace operators in each namespace? Maybe having everything already handled by the global operator itself is good enough.
* Deploy the namespace operator from the global operator code: reuse our yaml file, or handle everything as code?

**Comment by roldancer** [comment]
Hi All, In our Openshift production environment we manage more than 6K namespaces in a multitenant way, from our security point of view it is critical to have operator's with support for per namespace deployment ( with Role and RoleBindings on that namespace).

**Comment by agup006** [comment]
Hey @roldancer , ECK supports two modes of deployment - at a Global level watching all namespaces as well as on a per namespace level. Does this satisfy your requirement for deploying in OpenShift?

**Comment by sebgl** [comment]
We discussed offline how our initial "global" and "namespace" operators concept are a bit irrelevant and confusing in practice, and decided to remove the existing pre-built manifests via https://github.com/elastic/cloud-on-k8s/issues/2254 to only keep the all-in-one version.

The same global vs. namespace configuration can still be achieved by customizing the operator manifests. The operator can:

- enable or disable webhook support
- be deployed in namespace X
- manage resources in 1 namespace, N namespaces, or all namespaces
- live alongside other operator instances that manage resources in different namespaces

This goes into the direction of the above discussion. https://github.com/elastic/cloud-on-k8s/blob/master/docs/design/0005-configurable-operator.md discusses the need for an easier way to configure the operator yaml manifests.

I'm closing this issue now.

**Comment by rogerschlachter** [comment]
Hi, I landed here searching for how to deploy the operator and CRDs inside a single namespace. It seems like this discussion is more about how to provide the option of global vs namespace and implies both are possible currently?  

So does that mean it is currently possible to deploy the CRDs and the operator to a single namespace (requiring nothing outside the namespace) with some tweaks to the all-in-one as an interim solution for those of us limited to a single namespace on a multi-tenant cluster? 

If it is possible, is there an example? I imagine the ClusterRoles and ClusterRoleBindings need to become Roles and RoleBindings and I imagine there are a few more tweaks?

**Comment by sebgl** [comment]
Copy-paste of my answer from https://discuss.elastic.co/t/deploy-eck-to-a-single-namespace/211495/8:

I think (not tested in a while) this is possible but requires some tweaking.
Basically you can change the ClusterRole and ClusterRoleBinding from the all-in-one manifests to their corresponding Role and RoleBinding translations, with your desired namespace.
Then, you can patch the operator StatefulSet manifest to be deployed in the desired namespace. Also make sure the --namespaces flag of the operator cmd matches the namespace you want the operator to work with (probably the same it's deployed in).

However, you can only deploy the CRDs cluster-wide, AFAIK it is not possible to limit a CustomResourceDefinition resource to a particular namespace. And it looks it's not going to be supported anytime soon.

I understand this feels a bit hacky. I'm opening an issue to track this so we can come up with an easier way to generate your own flavor of the manifests: https://github.com/elastic/cloud-on-k8s/issues/2406
