### ISSUE TITLE
renovate ignores test/e2e/Dockerfile

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3746]
As mentioned in https://github.com/elastic/cloud-on-k8s/pull/3740#issuecomment-690301512 renovate seems to ignore the `Dockerfile` in the test/ directory.

I think we could fix that by adding explicitly that directory in `includepaths`

**Comment by thbkrkr** [comment]
Proposal: instead of relying on the default `ignorePaths` and adding another layer with `includepaths`, we could instead choose to override and therefore control `ignorePaths` which would then just be:
```json
  "ignorePaths": [
  	"**/vendor/**"
  ]
```
It seems slightly simpler and more predictable.

**Comment by thbkrkr** [comment]
It worked for #5018 :-) thanks to a recent fix in renovate (https://github.com/renovatebot/renovate/pull/12193).

**Comment by barkbay** [comment]
> It worked for #5018 :-) thanks to a recent fix in renovate ([renovatebot/renovate#12193](https://github.com/renovatebot/renovate/pull/12193)).

🎉  😄
