### ISSUE TITLE
Restart Elasticseach error "no kind "ElasticsearchList" is registered "

### ISSUE THREAD

**Issue by mchudinov** [elastic/cloud-on-k8s#3761]
I restart Elasticsearch pods in K8S cluster.
Elasticsearch is driven by the ECK opertor.
`kubectl rollout restart elasticsearch -n mynamespace`

This command did work well until version 1.1 of the operator.
It does not work with version 1.2.1 of the operator.

**What did you expect to see?**
It is expected that all Elasticsearch pods will be restarted.

**What did you see instead? Under which circumstances?**
Elasticsearch pods are not restarted.
The following error is shown:
`no kind "ElasticsearchList" is registered for version "elasticsearch.k8s.elastic.co/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

**Environment**
Kubernetes cluster version 1.17 in Azure with Linux nodes.

* ECK version:

	1.2.1

* Kubernetes information:
	* Cloud: AKS
	
	for each of them please give us the version you are using
```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"f862ce9a809b9832be36717bfc4efae470f59fbf", GitTreeState:"clean", BuildDate:"2020-08-24T18:41:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by barkbay** [comment]
> It is expected that all Elasticsearch pods will be restarted.

I'm not sure to understand if it is supposed to work on custom resources. Looking at the [`kubectl` source code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go#L117) it seems that only a few kind of resources are supported.

This is also what seems [to be stated by the documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#rollout):

>Valid resource types include:
> * deployments
> * daemonsets
> * statefulsets

Do you have any indication that this command should be supported by custom resources ?

Also note that restarting an Elasticsearch node requires some API call to avoid shards to be replicated while the Pod is down. I don't know how we could plug that logic within this command.

**Comment by barkbay** [comment]
> This command did work well until version 1.1 of the operator.

I forgot to mention that I tried with both ECK 1.0.0 and 1.1.0, got the same result:

```
$ kubectl rollout restart elasticsearch/elasticsearch-sample 
error: no kind "Elasticsearch" is registered for version "elasticsearch.k8s.elastic.co/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

**Comment by mchudinov** [comment]
Hm.. I might be wrong about version 1.1. I was quite sure that I was able to restart Elasticsearch by this command...
How to restart Elasticsearch deployed with 1.2.1 operator then?

**Comment by anyasabo** [comment]
You shouldn't need to as the operator does rolling restarts as necessary for configuration changes. If you do for some reason though you can `kubectl delete` the pods as necessary.

**Comment by mchudinov** [comment]
Thank you for the answer.
I will test the (auto-)restarts by operator after changes.
