### ISSUE TITLE
Grab data from the Elasticsearch API to better troubleshoot E2E tests

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3766]
Troubleshooting https://github.com/elastic/cloud-on-k8s/issues/3764 is pretty hard, since we are lacking details about:
- the entire cluster state (truncated in the Elasticsearch logs)
- the output from _cluster/allocation/explain

It would probably be also useful to grab:
- _cat/shards
- _cluster/settings

We could perform these calls as part of our existing `eck-dump.sh` tool, which already runs on failed E2E tests.
It would also make sense to rely on the [official Elasticsearch support diagnostics tool](https://github.com/elastic/support-diagnostics), but it probably involves more plumbing.

These calls also make sense beyond the context of E2E tests, for any troubleshooting purposes.

**Comment by sebgl** [comment]
The output of `_cat/nodes` would have been helpful for https://github.com/elastic/cloud-on-k8s/issues/3917.

**Comment by pebrc** [comment]
I think I would be in favour of running the official diagnostics tool over starting to build our own mini-version of it.   It means a bit more work to set up and maybe even build a Docker container for it, initially but it has the advantage that any improvements will feed back into the official tool and we will be using the same tooling we recommend to our users.
