### ISSUE TITLE
Check if the storage class allows volume expansion

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3767]
https://github.com/elastic/cloud-on-k8s/pull/3752 allows resizing pvcs, as long as their storage class supports volume expansion.

We initially [checked the storage class supports volume expansion](https://github.com/elastic/cloud-on-k8s/pull/3752/commits/20e51e1cfd217b5586708fe7f73ba83fe2ec9a47#diff-0c3501d6b47f9a324e6f4ed5b85d2275R60) but there's a concern some users may not be able to give RBAC privilege to ECK so it can list storage classes, which are cluster-wide non-namespaced resources.

 We could have that feature behind an operator flag, which also impacts the manifest generation: storage class rbac should not be included in the operator manifest if the operator is not supposed to check storage classes.

For reference, these commits already have most of the work done for the operator side (just the flag & manifest switchs are missing):
- check when resizing pvcs: https://github.com/elastic/cloud-on-k8s/pull/3752/commits/20e51e1cfd217b5586708fe7f73ba83fe2ec9a47
- check when deleting ssets: https://github.com/elastic/cloud-on-k8s/pull/3752/commits/9b24749d59b0c20cf9abb764269bf1246b61adc6
- validation webhook that checks the storage class: https://github.com/sebgl/cloud-on-k8s/commit/277ed3ebe5688df3f8fc9d86c95c62e1011e52b5

**Comment by sebgl** [comment]
My current thinking is to have the storage class check behind an operator setting (eg. `--validate-storage-class`), enabled by default, which requires a ClusterRole to read storage classes. Users who cannot give that rbac access to the operator can disable that setting.

However the curent `restricted` operator profile does not set any cluster-wide rbac permissions so far. I tend to see the `restricted` profile as a way to have ECK manage a subset of namespaces, more than a way to run ECK with non cluster-wide rbac permissions, but that's debatable. As such I think I would have that setting set to true by default in the restricted profile. Any thoughts on this @charith-elastic @pebrc?

**Comment by charith-elastic** [comment]
I don't think there's a problem with enabling storage class validation by default.  Our default mode of installation assumes that the user has full access to the cluster anyway. Another global RBAC rule added to the list shouldn't be a problem. 

> I tend to see the restricted profile as a way to have ECK manage a subset of namespaces, more than a way to run ECK with non cluster-wide rbac permissions

I think I see it the other way around. The restricted profile is a demonstration of how to run ECK without installing global resources (barring the CRDs, of course). If a feature is optional and requires cluster-scoped resources, it should not be present in that profile. Managing just a handful of namespaces is trivial (`--set=managedNamespaces={a,b,c}`): so there's no specific profile to demonstrate just that. (The `soft-multi-tenancy` profile comes quite close though.)
