### ISSUE TITLE
elasticsearchRef to support ESS and standalone clusters

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/cloud-on-k8s#3770]
## Proposal
At the moment, elasticsearchRef in the deployment manifest can only reference Elasticsearch clusters created and managed by ECK. I have a use case where I want to deploy metricbeat and filebeat using the ECK operator but specify the destination for the monitoring data to be sent to a cluster outside of the k8s cluster, for example, a standalone stack, or a cloud cluster.

**Use case. Why is this important?**
Often, the users want the monitoring clusters to reside outside of the k8s cluster that they are monitoring for the monitoring infrastructure to survive the outage of the system they are monitoring. It makes sense for the ECK operator to support the use case where we only deploy beats and APM server with the cluster being remote (standalone or cloud).

* ECK version:

1.2.1

**Comment by pebrc** [comment]
You can configure a reference to an Elasticsearch cluster not managed by ECK already today. You just do not use `elasticsearchRef` but instead configure the output as you would with a regular self-managed Elasticsearch cluster e.g. by setting [`cloud.id` and `cloud.auth` for Elasticsearch Service](https://www.elastic.co/guide/en/beats/metricbeat/current/configure-cloud-id.html). 

It is documented [in the ECK docs as well](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-beat-configuration.html#k8s-beat-set-beat-output).

**Comment by michaelhyatt** [comment]
Makes sense, thank you.
