### ISSUE TITLE
golangci-lint failures should prevent builds from succeeding

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3815]
Currently build succeeds even if linter catches issues, like [below](https://devops-ci.elastic.co/job/cloud-on-k8s-pr/4726/consoleText):

```
[2020-10-07T14:45:11.709Z] golangci-lint run
[2020-10-07T14:47:48.302Z] [1mhack/deployer/runner/ocp3.go:39[0m:2: [31mcomment on exported var `SharedVolumeName` should be of the form `SharedVolumeName ...`[0m (golint)
[2020-10-07T14:47:48.302Z] 	// Volume name shared by CI container and Ansible container
[2020-10-07T14:47:48.302Z] 	[33m^[0m
[2020-10-07T14:47:48.302Z] [1mhack/deployer/runner/ocp3.go:155[0m:12: [31mG306: Expect WriteFile permissions to be 0600 or less[0m (gosec)
[2020-10-07T14:47:48.302Z] 	if err := ioutil.WriteFile(varsFile, varsBytes, 0644); err != nil {
[2020-10-07T14:47:48.302Z] 	          [33m^[0m
[2020-10-07T14:47:48.302Z] make: *** [Makefile:146: lint] Error 1
[2020-10-07T14:47:48.302Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/cloud-on-k8s-pr/.ci'
[2020-10-07T14:47:48.302Z] make: Leaving directory '/var/lib/jenkins/workspace/cloud-on-k8s-pr/.ci'
[2020-10-07T14:47:48.313Z] [Pipeline] }
[2020-10-07T14:47:48.364Z] [Pipeline] // stage
[2020-10-07T14:47:48.414Z] [Pipeline] stage
[2020-10-07T14:47:48.417Z] [Pipeline] { (Run tests in parallel)
...
[2020-10-07T15:13:44.482Z] Finished: SUCCESS
```

**Comment by anyasabo** [comment]
From what I can see in the [docs](https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#sh-shell-script), if the command returns an error it should fail the step (which is why we use `returnStatus` in later steps since we want to do some stuff with the failed test output):
>returnStatus (optional)
>Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example. 

And made sure it is indeed returning an error:
```
15:57 $ /Users/sabo/go/bin/golangci-lint version
golangci-lint has version 1.27.0 built from fb74c2e on 2020-05-13T18:45:55Z
15:59 $ git revert 1fe23a45837ed41509e51c55c94b18119295d899
[jenkinsfail 5fc22a8d] Revert "Fix duplicate import of commonv1 package (#3857)"
 1 file changed, 2 insertions(+), 1 deletion(-)
✔ ~/dev/go/src/github.com/elastic/cloud-on-k8s [jenkinsfail L|✔]
15:59 $ /Users/sabo/go/bin/golangci-lint run
pkg/controller/elasticsearch/certificates/reconcile.go:12:2: ST1019: package "github.com/elastic/cloud-on-k8s/pkg/apis/common/v1" is being imported more than once (stylecheck)
	commonv1 "github.com/elastic/cloud-on-k8s/pkg/apis/common/v1"
	^
✘-1 ~/dev/go/src/github.com/elastic/cloud-on-k8s [jenkinsfail L|✔]
15:59 $ echo $?
1
```

It doesn't look like we changed the job or pipeline defs any time recently. We did update devops-ci jenkins on September 23 and the first time we noticed a failure was October 7. I'm a little bit confused why it's not failing. I also didn't have a good way to test that specific job, the exact same way jenkins runs it, I need to do some fiddling with my local jenkins setup.

**Comment by anyasabo** [comment]
Well it's consistent at least. This PR https://github.com/elastic/cloud-on-k8s/pull/3862 should be failing but is not:
https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-pr/detail/cloud-on-k8s-pr/4802/pipeline/29

**Comment by thbkrkr** [comment]
Blame on me! For E2E testing on OCP3, I introduced a named Docker volume `ECK_CI_VOLUME` which should always be deleted even if the `DOCKER_CMD` fails (`golangci-lint run` can be the command).

https://github.com/elastic/cloud-on-k8s/blob/1fe23a45837ed41509e51c55c94b18119295d899/.ci/Makefile#L47-L58

The delete volume command (L58) eats the actual exit status of the previous command executed in Docker.

A _slightly ugly_ workaround might be to capture the exit status of the command executed in Docker and use it to exit after the delete command:
```sh
diff --git a/.ci/Makefile b/.ci/Makefile
index 4107ebd9..13475fd0 100644
--- a/.ci/Makefile
+++ b/.ci/Makefile
@@ -54,8 +54,8 @@ ci-internal: ci-build-image
                -w $(GO_MOUNT_PATH) \
                --network="host" \
                $(CI_IMAGE) \
-               bash -c "$(DOCKER_CMD)" ; \
-       docker volume rm $(ECK_CI_VOLUME) > /dev/null
+               bash -c "$(DOCKER_CMD)" ; EXIT=$$? ; \
+       docker volume rm $(ECK_CI_VOLUME) > /dev/null ; exit $$EXIT

```

**Comment by anyasabo** [comment]
That seems reasonable to me @thbkrkr and is essentially what we do in the jenkins pipeline for other steps too
