### ISSUE TITLE
Investigate CNI integration options

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#383]
It would be great if we could integrate with CNIs (Calico et.al) to provide a higher degree of network isolation / control.

This issue is about determining the feasibility of such an effort as the first step towards implementation.

**Comment by pebrc** [comment]
I don't see at this point how we would need to explicitly support CNIs in ECK itself. But I could be missing something important. So please reopen if I do.

What we have done wrt CNIs:
* added specific setup instructions for people using CNIs https://github.com/elastic/cloud-on-k8s/pull/1380
* investigated integration with service meshes some of which use CNI to avoid privileged init-containers/sidecars (e.g. istio-cni). We created documentation to capture the results of these investigations https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-service-meshes.html
