### ISSUE TITLE
ES_data_should_pass_validations in Beat E2E tests is flaky

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3884]
It failed regularly in the past few weeks: https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-kind-k8s-versions/251/testReport/

```
=== RUN   TestPacketbeatDnsHttpRecipe/ES_data_should_pass_validations
Retries (10m0s timeout): ......................................................................................................................................................................................................
    utils.go:84: 
        	Error Trace:	utils.go:84
        	Error:      	Received unexpected error:
        	            	hit count should be more than 0 for /*beat*/_search?q=event.dataset:http
        	Test:       	TestPacketbeatDnsHttpRecipe/ES_data_should_pass_validations
```

**Comment by sebgl** [comment]
Also TestMetricbeatHostsRecipe, with a very similar error: https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-aks/518/testReport/

**Comment by sebgl** [comment]
https://github.com/elastic/cloud-on-k8s/pull/3888 temporarily disables the 2 flaky tests. Let's make sure we re-enable them once this issue is fixed.

**Comment by sebgl** [comment]
So there seems to be a problem with PacketBeat HTTP dataset on Kind 1.17.5 with IPV6:

![image](https://user-images.githubusercontent.com/1050393/98346411-3544c200-2016-11eb-8761-1b1a90d7493f.png)

The 1.16.9 failure in the screenshot above is unrelated. All 1.17.5 IPV6 tests fail because packetbeat does not report any dataset:http event. It happens for TestPacketbeatDnsHttpRecipe and TestPacketbeatConfig.
Interestingly the test sometimes passes though. There would be some flakiness involved in packetbeat reporting http events when using IPV6 on Kind?

Looking at a recent failure diagnostic bundle, Beats Pods are running and I don't see anything suspicious in the logs.

**Comment by sebgl** [comment]
I'll see if I can reproduce locally with Kind 1.17.5 configured with IPV6.

**Comment by sebgl** [comment]
Testing on Kind 0.9.1, k8s 1.17.5, IPV6 enabled on an Ubuntu VM (cannot run Docker with IPV6 on mac): so far I always end up with the http dataset events in Elasticsearch.

**Current working theory**:
However, with Beats sometimes restarting multiple times at startup before it can finally connect to Kibana & ES, it can take some time to have the events available in Elasticsearch. On worst cases Beats quickly reaches a 5min restart back-off timeout.
When combined with https://github.com/elastic/cloud-on-k8s/issues/3909 it's easy to miss the http events because beats has not been running for a long time (or not at all).
I think https://github.com/elastic/cloud-on-k8s/pull/3910 will already mitigate this issue (and maybe actually remove the flakiness).

If not, I think we could look into raising timeouts for Beats tests (considering the 5min restart backoff is normal).
Why is this test failing with Kind IPV6 more than on other version? I don't know. I guess it's possible that IPV6 impacts the overall performance which leads to that situation sooner.

I'll re-enable the temporarily disabled E2E test to check if https://github.com/elastic/cloud-on-k8s/pull/3910 fixes the problem.

**On a side note:**
Kind 0.9.0 has been released (we still use 0.8.1). The changelog mentions `Fixed issues with ipv6 network overlap`. It'd probably be worth upgrading but the new version does not support k8s 1.12 anymore.

**Comment by sebgl** [comment]
Both tests have been re-enabled now. Also we are running CI tests with Kind 0.9, and we've changes the set of tests we run.
I do not see any failures on recent tests involving IPv6.

Let's close for now, and reopen if needed.

**Comment by thbkrkr** [comment]
`TestPacketbeatDnsHttpRecipe` failed again with Kind 1.22.0 with IPV6 enabled ([cloud-on-k8s-e2e-tests-kind-k8s-versions/607](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-kind-k8s-versions/607/)).
