### ISSUE TITLE
Unable to configure Cross Cluster Search - `node_disconnected_exception`s

### ISSUE THREAD

**Issue by robertgates55** [elastic/cloud-on-k8s#3918]
## Bug Report
**What did you do?**
I've used eck to configure two clusters, established mutual trust, and got the UI to show a green tick. The proxy IP specified is one of the AWS Loadbalancer IPs in front of my ingress controller, and nginx-ingress is then configured to route :9300 to the elasticsearch-transport svc.

![image](https://user-images.githubusercontent.com/7437497/98372713-1a824580-2036-11eb-9233-0c9663f075c3.png)

I then run a query using dev-tools to confirm permissions/etc, and get:

![image](https://user-images.githubusercontent.com/7437497/98373209-d2175780-2036-11eb-8aa2-3e57a7817a4d.png)

However, I don't get this _every_ time - approx 50%?

**What did you expect to see?**
Expected reliably to get a search result. Really, I also expected some results.

**What did you see instead? Under which circumstances?**
`node_disconnected_exception` - as per screenshot. This happens most of the time, and then sometimes it seems to actually connect.

I'm raising here because I specifically wonder about the TCP routing required here, and where there's any recommendations for setting up cross-cluster search between two ES clusters in two different K8S clusters?

**Environment**

* ECK version:
1.2.1, elastic 7.9.3

* Kubernetes information:
1.16 EKS

**Comment by barkbay** [comment]
> I'm raising here because I specifically wonder about the TCP routing required here, and where there's any recommendations for setting up cross-cluster search between two ES clusters in two different K8S clusters?

Assuming you are using the [proxy](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html#proxy-mode) mode  (see the operator documentation [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-remote-clusters.html#k8s-remote-clusters-connect-external)) I'm not aware of any specific routing requirement at the TCP level.
If you still have this issue I would open a [new topic on discuss](https://discuss.elastic.co/) with the Elasticsearch nodes logs as they might provide additional information about the underlying error.
