### ISSUE TITLE
[docs] Add troubleshooting section on pod changes not being applied

### ISSUE THREAD

**Issue by a03nikki** [elastic/cloud-on-k8s#3948]
### Overview

Add a section on pod changes not being applied to troubleshooting documentation.

### Details

One of [the limitations of ECK](https://www.elastic.co/guide/en/cloud-on-k8s/1.3/k8s-orchestration.html#k8s-orchestration-limitations) is 

> Rolling upgrades can only make progress if the Elasticsearch cluster health is green. 

However, this is not highlighted well in the documentation.  

It would be helpful if a paragraph or two was added to [Elastic Cloud on Kubernetes [1.3] » Operating ECK » Troubleshoot ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting.html) to include a brief section on why pods are not being replaced after a configuration update.  For example, `kubectl apply -f elasticsearch.yml` replies `... configured` but none of the pods are replaced per the `kubectl get pods` output.   I do not know if it is considered [Common problems](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-common-problems.html) or more advanced to belong on [Troubleshooting methods](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting-methods.html).

**Comment by alaudazzi** [comment]
Draft content discussed with @a03nikki. To be reviewed. This could go into the [Common problems](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-common-problems.html) section.

## Pods are not being replaced after the pod configuration

when / why / background / context
An existing ES cluster is already deployed and needs to be updated. 
The operator is unable to make the changes required for replacing the existing pod.
This can happen in the following cases:
a. Your ES cluster is not healthy. 

<put here a code example> 
Action: Check and fix your shard allocations.
<more API details can be added here>

For more information, see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/cluster-health.html
and https://www.elastic.co/guide/en/cloud-on-k8s/1.3/k8s-deploy-elasticsearch.html#k8s_monitor_cluster_health_and_creation_progress.

b. There are no enough resources in your k8s cluster.
kubectl get events
^ historically tells if unable to assign pods
<code example>
Action: in the worst case delete the pod and ECK operator should recreate it.

**Comment by a03nikki** [comment]
@alaudazzi : I started to add some of the code examples to #3964

**Comment by alaudazzi** [comment]
Thank you for starting this draft, @a03nikki. I added a few editing suggestions, I'll have another pass as soon as the page is complete.
