### ISSUE TITLE
Proposals for Elasticsearch Secure Settings document

### ISSUE THREAD

**Issue by eedugon** [elastic/cloud-on-k8s#3987]
Referenced document (1.3 release): https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html

I would suggest to do a few small changes in that document to be easier to understand and map it clearly with the concept of "elasticsearch keystore" (which now we call "secure settings").

There's a lot of people who asks me how to manage the keystore in ECK, and even after pointing to that document they don't clearly understand how to do that.

The changes I propose:
- Include in the introduction that the `secure settings` are the ones included in Elasticsearch Keystore, pointing also to [this link](https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-keystore.html).

- The referenced example at the bottom of the page is a bit complex and the keystore added there is a `file-based` keystore which is not that typical. Also someone interested on adding a keystore setting might get lost or not even understand the entire snapshots example (which is awesome by the way). So, my proposal here is to add first an `easy example` and at the end of the document we can keep the reference to the snapshots example.

For the easy example we can pick any secure setting we want, like the `secure_bind_password` from an LDAP realm and provide an example of:
- how to create the secret with the setting and the value (i know this is not ECK stuff but it's always useful).
- how to map the secret into the `Elasticsearch` manifest.

- For the example of `You can export a subset of secret keys and also project keys to specific paths...` I would recommend to show it with a more realistic example (easy example of a secret with multiple keys where we only want one or a few of them), and of course using real keys so they will be clearer.

And this is the last change I propose (not totally sure if this is really useful or not):
- Include an `area of application` section in the doc where we can include where this document might be needed, for example:
  - Configuring security realms (LDAP / SAML / etc)
  - Configuring accounts for notifications in watchers (email, pagerduty, etc.)
  - Configuring plugins for snapshots (not installing, configuring :) )
  - Configuring security in watchers
  - etc (there's no need to cover everything)

**Comment by alaudazzi** [comment]
@eedugon I'm working on this issue. It might be good to meet and quickly chat about the changes you propose. I'll set up some time for us this week.

**Comment by alaudazzi** [comment]
@eedugon 
For the first change you propose:

> Include in the introduction that the secure settings are the ones included in Elasticsearch Keystore, pointing also to this link.

There is already a link to the [elasticsearch-keystore](https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-keystore.html) tool.

For the other changes you propose on the page [Secure settings](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html):
- easier examples
- area of application

I'll chat with @idanmo to get feedback and input.

**Comment by alaudazzi** [comment]
Closing in favour of #4324 and #4325.
