### ISSUE TITLE
Autoscaling specification

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4006]
This issue is to discuss the content of the autoscaling specification _(at least in its first version)_.

### Global autoscaling settings (All optional - sane defaults would be provided)
The user should be able to:
- [x] Set the Elasticsearch autoscaling API poll frequency 
- [ ] ~Define a stabilization window: used to restrict the flapping of resources or replicas when the values from the Elasticsearch autoscaling API keep fluctuating _(see below)_~

### Tier/autoscaling policy specific settings

At the tier level, the user should be able to:
- [x] Create N-to-1 associations between nodeSets and an autoscaling policy (already discussed in https://github.com/elastic/cloud-on-k8s/issues/3955)
- [x] Tweak deciders settings (Optional)
- [x] Describe resource constraints (min. / max. values) applied on the associated `nodeSets`
- [x] Specify a `request`/`limit` ([Requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits)) ratio to convert a resource `request` into a `limit` _(Optional: default would be 1 for memory, limit == request, and 0 for CPU, not CPU limit)_
 
 ## Proposal

_Updated on January 5th, 2021 with @sebgl proposal_
 
 ```json
{
	"policies": [{
		"name": "di",
		"roles": ["data", "ingest"],
		"deciders": {
			"fixed": {
				"nodes": "4",
				"storage": "10g",
				"memory": "5g"
			}
		},
		"resources": {
			"nodeCount": {
				"min": 3,
				"max": 8
			},
			"cpu": {
				"min": 2,
				"max": 6,
				"requestsToLimitsRatio": 0
			},
			"memory": {
				"min": "6Gi",
				"max": "10Gi",
				"requestsToLimitsRatio": 1
			},
			"storage": {
				"min": "1Gi",
				"max": "4Gi"
			}
		}
	}],
	"syncPeriod": "60s"
}
```

`requestsToLimitsRatio` and `syncPeriod` are optional.

#### resources

`resources` allows the user to set a range of resources (min and max) which would be applied to each `nodeSet` targeted by the policy.

#### requestsToLimitsRatio

`requestsToLimitsRatio` is a float, either set to 0 or greater than 1, it would be used to convert a `request` value into a `limit`, for example:
* `1`: `limit` value is the same as the `request`
* `0`: no limit 
* `1.5`: `limit` is one and a half the value of the computed `request`
* `2`: `limit` is twice the value of the computed `request`
 
#### behavior

~Even if each autoscaling decider comes with its own [cool down policy](https://github.com/elastic/elasticsearch/blob/68358df07b064b86c7967e4bc9758abd5f6f5617/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlAutoscalingDeciderService.java#L69) I think it makes sense to be able to configure the behaviour of the autoscaling algorithm at the cluster level.  I don't think that a per decider mechanism would prevent some flapping situations at the cluster level.
We can add some additional settings (for example the number of Pods updated per minute), but I'm not sure it's worth it in a first implementation.~

**Comment by pebrc** [comment]
> Set the Elasticsearch autoscaling API poll frequency

Would it suffice to have this as an operator level setting (flag)?

**Comment by barkbay** [comment]
> Would it suffice to have this as an operator level setting (flag)?

My only concern about introducing a new flag is that it would be hard to remove if we change our mind later.

**Comment by sebgl** [comment]
A few comments and questions:

---

* API schema:

I feel a bit concerned about merging Elasticsearch API constructs with our own ECK constructs into the same JSON thing.

```
"policies": [{

         // --- name is in the ES request endpoint
   	"name": "master_data_ingest", 

         // --- roles + deciders are in the ES request payload (snake_case)
   	"roles": ["master", "data", "ingest"],
   	"deciders": [{
   		"storage": {
   			"settings": [{
   				"name": "forecast_window",
   				"value": "60s"
   			}]
   		}
   	}],

         // --- resources is our own construct (upperCamelCase)
   	"resources:": {
   		"minAllowed": {
   			"count": 2,
   			"cpu": 16,
   			"memory": "8Gi",
   			"storage": "10G"
   		},
   		"maxAllowed": {
   			"count": 6,
   			"cpu": 16,
   			"memory": "8Gi",
   			"storage": "100G"
   		},
   		"limitRatio": {
   			"memory": 1,
   			"cpu": 0
   		}
   	}
   }],
```

do we plan the `deciders` part to be raw JSON content that we can pass to Elasticsearch, or do we plan to model it ourselves?

I don't really see a better way to represent things and be a bit more explicit in splitting ES policies vs. ECK resources.

---

* Naming:

- I'm not sure about `minAllowed / maxAllowed`. The k8s vertical pod autoscaler recommendations uses `lowerBound / upperBound`. The k8s horizontal pod autoscaling uses `minReplicas / maxReplicas`... I don't really have a preference.
- `limitRatio` is not immediately obvious to me. `requestsToLimitsRatio` would be more explicit, at the cost of also being more verbose... 

---

* Limit ratios

Do we default to `0` (no limits) or `1` (requests == limits)? For memory I feel like we should default to 1. For CPU I feel like we should default to 0. 

---

* Min / Max

While looking at the spec I had the wrong intuition that, storage + cpu + memory are scaled at the same time. Whereas they are actually scaled independently. I'm wondering if that's just my own bias , or whether reversing things in the API would better express how those are individually scaled:

```json
{
    "resources": {
        "cpu": {
          "min": "1",
          "max": "10",
          "requestsToLimitsRatio": 0  
        },
        "memory": {
          "min": "1GB",
          "max": "10GB",
          "requestsToLimitsRatio": 1
        },
        "nodeCount": {
            "min": 3,
            "max": 30
        },
        "storage": {
            "min": "10G",
            "max": "100G"
        }
}
``` 

I'm also thinking about future use cases where, for example, we are using local volumes and we know we have 100GB, 1TB and 10TB volumes available. In which case we may to express storage as:

```
"storage": {
            // "min": "10G",
            // "max": "100G"
               "discreteSizes": ["10Gi", "1Ti", "10Ti"]
        }
```

 The discrete size things could go further and embed (cpu + ram + storage) discrete requirements.
 I think we should not care much about this discrete sizing thing, I just want to make sure there's room for it in the API if need be.

---

* Behaviour

IIUC this would allow some cool down on downscales, whatever decider is involved? For example, don't scale down hot nodes if you just scaled down warm nodes 10 sec ago?
It feels to me like something that could be implemented by Elasticsearch directly.
Do you think this `behaviour` section is strongly required? Or is it something we could ignore for now and maybe implement in the future if we realize it's needed.

**Comment by barkbay** [comment]
Thanks a lot for you comments @sebgl 🙇, please find my comments inline:

## API schema

> do we plan the deciders part to be raw JSON content that we can pass to Elasticsearch, or do we plan to model it ourselves?

Yes, my first idea was to be able to pass the json content directly to Elasticsearch.
I'm not sure it is an argument but I would not expect this section to be used in nominal operating conditions. It requires advanced knowledge about the deciders and would only be used by advanced users. In that context it might be fine to tolerate some "snake_case" in the manifest ?

> I don't really see a better way to represent things and be a bit more explicit in splitting ES policies vs. ECK resources.

The `roles` are used by both the Elasticsearch API and the operator, so I'm not sure there is a good way to make a clear separation between the two.

## Naming

I'm really bad at naming, so always open to proposals :smile:

* `minAllowed / maxAllowed`: I think your next comments about Min / max makes sense.

* `requestsToLimitsRatio`: Assuming we provide some good defaults it should not be used too often. So I think I would be :+1 to have something more verbose.

## Limit ratios

> For memory I think we should default to 1. For CPU I think we should default to 0.

👍 Yes, that's the idea

## Min / Max

```
{
    "resources": {
        "cpu": {
          "min": "1",
          "max": "10",
          "requestsToLimitsRatio": 0  
        },
        "memory": {
          "min": "1GB",
          "max": "10GB",
          "requestsToLimitsRatio": 1
        },
        "nodeCount": {
            "min": 3,
            "max": 30
        },
        "storage": {
            "min": "10G",
            "max": "100G"
        }
}
```

I would be curious to know if anyone else has an opinion but I think I like your proposal 👍 

## Behaviour

> Do you think this behaviour section is strongly required?

No, I think it requires more discussion. We can ignore it for now and open a dedicated issue to discuss it in a second time.

**Comment by barkbay** [comment]
```json
"nodeCount": {
            "min": 3,
            "max": 30
},
```

It makes me realize that it is not clear if that `nodeCount` limit is per `nodeSet` (as for the resources) or across all the `nodeSets` managed by the policy. I initially thought that it was across all the nodeSets but on a second thought it does not feel that obvious.

**Comment by pebrc** [comment]
> It makes me realize that it is not clear if that nodeCount limit is per nodeSet (as for the resources) or across all the nodeSets managed by the policy.

Now I am confused :-) Isn't memory, storage and CPU limit per node (ofc within the node sets that match the policy) and node count the sum of all nodes within sets that match the policy?

**Comment by barkbay** [comment]
>  Isn't memory, storage and CPU limit per node (ofc within the node sets that match the policy) and node count the sum of all nodes within sets that match the policy?

* memory, storage and CPU are per node ✔️ 
* imho re. node count it can be interpreted in 2 different ways:
1. min and max for `count` are set in the context of a policy, so those are the min and max number of nodes managed in the context of that policy. In that case it is possible to set a max number of 2 nodes event if 3 `nodeSets` match the policy. It would be odd because it means that the third nodeSet would never be used (with the current algorithm at least).
2. min and max for `count` are applied to nodeSets individually.  For example in that case if the user sets a max of 2 nodes and there are 3 `nodeSets` that match the policy then the operator would be able to scale up to 6 nodes.

I think I would go for the first choice, because as a user I'm specifying the behavior of the whole tier/policy. But while I was working on unit tests it didn't appear that obvious 🙃

**Comment by pebrc** [comment]
Yes option 1. seems more intuitive. Would that mean we need to allow 0-sized node sets if a user specs the min `nodeCount` < `len(nodeSets)`? Or are we just going to add a validation on the policy that says: your policy is invalid if you have not at least one node per set when running at minimum `nodeCount`?

**Comment by barkbay** [comment]
> Would that mean we need to allow 0-sized node sets if a user specs the min nodeCount < len(nodeSets)?

I did the test and our current code base is not compatible with 0-sized node sets. In that situation it seems that some objects (at least the headless `Service` associated to the `StatefulSet`) are endlessly created then immediately deleted, this in turn triggers a new reconcile loop. It results in an ∞ of reconciliations.

I will add a validation for now and open an issue to discuss if we should allow 0-sized node sets.

**Comment by barkbay** [comment]
@elastic/cloud-k8s I updated the first comment to match the current state of the discussion, let me know if there are other feedbacks. Thanks !

**Comment by barkbay** [comment]
Implemented in https://github.com/elastic/cloud-on-k8s/pull/4148, https://github.com/elastic/cloud-on-k8s/pull/4239 and https://github.com/elastic/cloud-on-k8s/pull/4264.

Let's create a new issue to revisit this specification when needed.
