### ISSUE TITLE
Refactor the resources association code with more explicit names

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#4062]
We use confusing terminology in the codebase when dealing with associations:
* `Association` represents the general concept of associating 2 resources together
* `Association` also sometimes represent the target resource
* `Associated` represents the resource holding a reference to other resources (it references `association` resources)

We sometimes mismatch one with the other in the codebase, which makes things confusing.

I'd like to propose the following terminology:

* `Association` represents the general concept of association 2 resources together
* `Source` represents the resource holding a reference to an other resource (e.g. Kibana)
* `Target` represents the referenced resource (e.g. Elasticsearch, referenced in the Kibana resource)

While associations in general are technically bi-directional (ES-Kibana requires configuration changes in ES and Kibana), I think it makes sense to consider them conceptually directional: Kibana is the source, Elasticsearch is the target in that association.

**Comment by david-kow** [comment]
https://github.com/elastic/cloud-on-k8s/issues/3511 seems similar 🙂 I think we should close one of these.

**Comment by naemono** [comment]
Going to close this in favor of #3511, as it seems to have some agreement with given proposal, and this can be reviewed as it still will be linked from the other issue.
