### ISSUE TITLE
Autoscaling: dynamic scaling of memory requests with storage deciders

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4076]
Storage deciders only return a storage capacity requirement, without additional information about the required memory.

I think we need to scale the memory similarly to [what is proposed for CPU](https://github.com/elastic/cloud-on-k8s/issues/4021): scale the memory linearly in its allowed range according to the required storage capacity.

**Comment by pebrc** [comment]
Again I am in favour of this idea, similar to the linear CPU scaling. A few questions: 
* turning this behaviour off would require users to remove autoscaling limits for memory completely from the configuration? Something like this?
```json
{
    "resources": {
        "storage": {
            "min": "10G",
            "max": "100G"
        }
}
```

* The storage to memory ratio would be implicitly defined by the min-max range of memory in relation to min-max of storage? E.g. a 1:10 ratio:
```json
{
    "resources": {
        "memory": {
          "min": "1GB",
          "max": "10GB",
          "requestsToLimitsRatio": 1
       },
        "storage": {
            "min": "10G",
            "max": "100G"
        }
}
```
* if memory capacity information becomes available in the autoscaling response for storage deciders in the future we would honor it?

**Comment by barkbay** [comment]
> turning this behaviour off would require users to remove autoscaling limits for memory completely from the configuration? Something like this?

Yes, if there is no autoscaling limits for memory then the autoscaler controller would not compute a memory request. The one set in the `podTemplate` would then be used.
It would also be possible to set a same value for the min and the max, it can be useful if the user still want to manage the memory settings in the autoscaling spec.

> The storage to memory ratio would be implicitly defined by the min-max range of memory in relation to min-max of storage?

Yes

 > if memory capacity information becomes available in the autoscaling response for storage deciders in the future we would honor it?

Yes

**Comment by barkbay** [comment]
Implemented in https://github.com/elastic/cloud-on-k8s/pull/4173
