### ISSUE TITLE
Replace occurrences of "coordinator node" with "coordinating node"

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#4093]
We refer to "coordinator nodes" in a few places in our docs and in our yaml recipes, whereas they are called "coordinating nodes" in [Elasticsearch terminology](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html).

**Comment by alaudazzi** [comment]
@pebrc I am not sure we can replace this type of occurrences:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/46651782/108178548-d9a1ce80-7104-11eb-9505-9345173cdb74.png">

**Comment by pebrc** [comment]
>  I am not sure we can replace this type of occurrences

Why not, what is your concern?

**Comment by alaudazzi** [comment]
@pebrc It's not just text. The occurrences to be replaced are also doc IDs, metadata referenced in the code, etc.
These are just a few examples. There are many more in the ECK doc pages.
Replacing systematically all the occurrences might have undesired side-effects on doc links and code examples.

**Comment by thbkrkr** [comment]
In the example you pointed, the name of the service `hulk-es-coordinator-nodes` is derived from the Elastisearch resource name (`hulk`) and the nodeSet name (`coordinator`). So it's ok to rename both.

I don't see a lot of occurences in the doc pages and just one anchor, which isn't reused in somewhere else:

```
docs/orchestrating-elastic-stack-applications/elasticsearch/node-configuration.asciidoc:  - name: coordinator
docs/advanced-topics/traffic-splitting.asciidoc:  # Dedicated coordinator nodes
docs/advanced-topics/traffic-splitting.asciidoc:  - name: coordinator
docs/advanced-topics/traffic-splitting.asciidoc:.Coordinator nodes
docs/advanced-topics/traffic-splitting.asciidoc:[[{p}-traffic-splitting-coordinator-nodes]]
docs/advanced-topics/traffic-splitting.asciidoc:  name: hulk-es-coordinator-nodes
```

I took a look and think it's okay to replace all occurences by excluding only the occurence in `test/e2e/beat/recipes_test.go` (`beat.HasMonitoringEvent("type:enrich_coordinator_stats")`).

```
# may not work on mac where grep is different
> grep oordinator -rl | grep -v test/e2e/beat/recipes_test.go | xargs -n1 sed -i "s/oordinator/oordinating/g"
```

**Comment by alaudazzi** [comment]
Thank you @thbkrkr!
