### ISSUE TITLE
Use new node roles notation in all manifests

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#4130]
Given Elasticsearch is going to [deprecate](https://github.com/elastic/elasticsearch/issues/66409) the old way of specifying node roles we should move our examples to using the roles list.

**Comment by barkbay** [comment]
Current samples which are still setting roles the old way:

* [config/recipes/traefik/02-elastic-stack.yaml](https://github.com/elastic/cloud-on-k8s/blob/master/config/recipes/traefik/02-elastic-stack.yaml)
* [config/recipes/istio-gateway/03-elasticsearch-kibana.yaml](https://github.com/elastic/cloud-on-k8s/blob/7122d8db35382772eb59298a82f7b9f43f470259/config/recipes/istio-gateway/03-elasticsearch-kibana.yaml#L18-L22)
