### ISSUE TITLE
Refactoring: maintain a Set from StatefulSetList

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4147]
As mentioned by @charith-elastic [here](https://github.com/elastic/cloud-on-k8s/pull/4099#pullrequestreview-566173918) `StatefulSetList` is used as a `Set` in [several](https://github.com/elastic/cloud-on-k8s/blob/63064b6450272af43602de31ed2bac08672cb74e/pkg/controller/elasticsearch/certificates/transport/reconcile.go#L52) [places](https://github.com/elastic/cloud-on-k8s/blob/f397915e67d3ecfca70d3d9997b858fc0f8c8813/pkg/controller/elasticsearch/sset/list.go#L52) [in](https://github.com/elastic/cloud-on-k8s/blob/f397915e67d3ecfca70d3d9997b858fc0f8c8813/pkg/controller/elasticsearch/sset/list.go#L43) the code.

We should try to be smarter here and avoid to recreate a new `Set` every time it is needed.

**Comment by mikechengwei** [comment]
I will optimize it.
