### ISSUE TITLE
Switch leader election to use Leases

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#4150]
Since Kubernetes 1.14 a new leader election method based on the `coordination.k8s.io` API is available and it is the default method in controller-runtime since 0.7.0. We can switch to this new default once support for Kubernetes 1.13 is dropped from the operator.

https://github.com/kubernetes-sigs/controller-runtime/pull/1144

**Comment by naemono** [comment]
In #5662 we moved to `configmapleases` as a temporary/interim measure.  We released this in 2.3.0, and stayed on the 0.12.x branch of controller-runtime in 2.4.0.  We should go ahead and moved to `Leases` and away from `ConfigmapLeases` in the next release.
