### ISSUE TITLE
S3 snapshot plugin is not installing with the eck operator 1.3.1/1.3.0

### ISSUE THREAD

**Issue by vangahari** [elastic/cloud-on-k8s#4225]
I have installed eck-operator 1.3.1 using argocd. I am trying to setup elk cluster using operator.
I have been using official elk version to deploy, cluster is working fine, but s3 plugin for snapshots and restore is not installing.
I wanted to setup a backup plan for elasticsearch data using AWS s3 bucket, so for that i need to install the s3 snapshot plugin

ECK version: 1.3.1
My elasticsearch manifest file to deploy ES below:
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.8.0/7.10.2
  nodeSets:
  - name: default
    count: 1
    config:
      discovery.type: single-node
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin remove --batch repository-s3
              bin/elasticsearch-plugin install --batch repository-s3
        - name: add-access-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "{{ .Values.awsS3AccesssKey }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ .Values.awsS3SecretKey }}"
          command:
            - sh
            - -c
            - |
              echo $AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
              echo $AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key

Please suggest me to fix this issue. 
Note: one more issue is when I removed the eck operator from the eks cluster, some of the CRDs are not removing. pls check one as well

**Comment by charith-elastic** [comment]
The manifest is hard to read because it is not properly formatted. Being able to see spacing is important because it is YAML. You also don't say exactly what the issue is either. For example, are you seeing any errors from the S3 plugin?

If I were to guess, I think you have a spacing problem. The `install-plugins` init container seems to be nested inside the `volumeClaimTemplates` section -- which is wrong. Also the line `version: 7.8.0/7.10.2` is incorrect and would be rejected by the operator.

Please use https://discuss.elastic.co/c/orchestration/eck/79 for these types of questions as we use GitHub issues for bug reports only. If you paste your (properly formatted) manifest on https://discuss.elastic.co/c/orchestration/eck/79 someone will help you figure out the problem.

**Comment by vangahari** [comment]
> The manifest is hard to read because it is not properly formatted. Being able to see spacing is important because it is YAML. You also don't say exactly what the issue is either. For example, are you seeing any errors from the S3 plugin?
> 
> If I were to guess, I think you have a spacing problem. The `install-plugins` init container seems to be nested inside the `volumeClaimTemplates` section -- which is wrong. Also the line `version: 7.8.0/7.10.2` is incorrect and would be rejected by the operator.
> 
> Please use https://discuss.elastic.co/c/orchestration/eck/79 for these types of questions as we use GitHub issues for bug reports only. If you paste your (properly formatted) manifest on https://discuss.elastic.co/c/orchestration/eck/79 someone will help you figure out the problem.

Hi, i dont see any errors in the pod logs, only thing is i am unable to install the s3 snapshot plugin using the eck operator on the eks cluster. for deploying the elk cluster i am using argocd.
This is my proper yaml file
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.8.1
  nodeSets:
  - name: default
    count: 1
    config:
      discovery.type: single-node
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin remove --batch repository-s3
              bin/elasticsearch-plugin install --batch repository-s3
        - name: add-access-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "{{ .Values.awsS3AccesssKey }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ .Values.awsS3SecretKey }}"
          command:
            - sh
            - -c
            - |
              echo $AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
              echo $AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard

**Comment by charith-elastic** [comment]
Please post support questions on https://discuss.elastic.co/c/orchestration/eck/79. GitHub issues are for bug reports and feature requests only.

For the benefit of anyone stumbling onto this issue:

`discovery-type: single-node` does not make sense in ECK context and will most likely prevent Elasticsearch from starting up.

You can use `secureSettings` and simplify the manifest quite a bit.

First, create a secret containing AWS credentials.

```
kubectl create secret generic aws-credentials --from-literal=s3.client.default.access_key=YOUR_ACCESS_KEY --from-literal=s3.client.default.secret_key=YOUR_SECRET_KEY
```

Then, refer to the secret in the manifest.

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hulk
spec:
  version: 7.10.2
  secureSettings:
    - secretName: aws-credentials
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          initContainers:
            - name: install-plugins
              command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin install --batch repository-s3
```

Finally, you have to initialize the plugin with a bucket configuration as described here: https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-usage.html
