### ISSUE TITLE
ReconcileCompatibility should not parse the current version

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4233]
[As mentioned by](https://github.com/elastic/cloud-on-k8s/pull/4197#discussion_r573754541) @pebrc It is not clear why we attempt to parse the current controller version at the end of the [ReconcileCompatibility](https://github.com/elastic/cloud-on-k8s/blob/7c89e2c0d81655b2ee40c459c220fc2da932c089/pkg/controller/common/annotation/controller_version.go#L123) function since the result is only used for logging:

```golang
	ctrlVersion, err := version.Parse(controllerVersion) // <--- Here
	if err != nil {
		return false, errors.Wrap(err, "Error parsing controller version")
	}

	// if the current version is gte the minimum version then they are compatible
	if currentVersion.GTE(minVersion) {
		return true, nil
	}

	log.Info("Resource was created with older version of operator, will not take action", "controller_version", ctrlVersion,
		"resource_controller_version", currentVersion, "namespace", namespace, "name", name)
	return false, nil
}
```

I think we should only attempt to parse the controller version before we set it in the resource annotation (in `UpdateControllerVersion`), to ensure that the operator is able to read back this version later.

Also it seems that at least one unit test relies on this part of the code while it should not, see my comment [here](https://github.com/elastic/cloud-on-k8s/pull/4197#discussion_r574305731).

**Comment by Shanduur** [comment]
If it is still open, I would like to work on this issue.
