### ISSUE TITLE
Telemetry disabled functionality

### ISSUE THREAD

**Issue by voima-eetu** [elastic/cloud-on-k8s#4269]
## Bug Report
**What did you do?**

Installed latest 1.4.0 version with Kibana and ElasticSearch with Helm. Tried to disable telemetry with Helm value
```
telemetry:
  disabled: true
```

**What did you expect to see?**

Telemetry disabled.

**What did you see instead? Under which circumstances?**

In Kibana Settings _'app/management/kibana/settings'_ under _'Usage Data'_ **telemetry::enabled** was 'On'.
![image](https://user-images.githubusercontent.com/66011005/108968697-c608e180-7689-11eb-8d05-af5b4ed05445.png)

  

Is this Helm Value `telemetry.disabled: true` for something else?

  

**Environment**

* ECK version:

	1.4.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise

**Comment by idanmo** [comment]
The `telemetry.disabled` operator setting set to true disables ECK's telemetry sent via Kibana's telemetry. It doesn't control Kibana's telemetry.
For configuring Kibana's telemetry please refer to [Telemetry settings in Kibana](https://www.elastic.co/guide/en/kibana/master/telemetry-settings-kbn.html).

**Comment by voima-eetu** [comment]
Thank you for clarification.
