### ISSUE TITLE
[Autoscaling] Add an initial end user documentation

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4277]
We should add an end user documentation about autoscaling.

**Comment by alaudazzi** [comment]
@barkbay It might be worth to refer to the [Autoscalilng terminology](https://docs.google.com/document/d/1ltZw0qPUvUU8-AAKL-Tn0_HBGJb7k5gFxuFty4XuXY8/edit#heading=h.8xqynwi57f9l) doc.
