### ISSUE TITLE
Expose ES metrics from values.yaml

### ISSUE THREAD

**Issue by navneet066** [elastic/cloud-on-k8s#4280]
How can we expose all the Cluster Metrics? <br>
Do we have any variable from where we can enable the metrics or do we need to install the separate ES exporters?

**Use Case**
We have a centralized Prometheus for monitoring, and we want to integrate this with the ES Cluster Metrics.

Any pointers will be useful.

Thanks in advance

**Comment by pebrc** [comment]
Exporting Prometheus metrics for Elasticsearch is currently not supported by ECK. You would have to rely on a third party exporter.

**Comment by navneet066** [comment]
@pebrc Thank you for your response.  I believe we need to go with third-party exporters then.

Regards,
Navneet Nandan
