### ISSUE TITLE
make e2e-local is broken

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4285]
Ever since moving to the generated manifests and the splitting of the OPERATOR_IMAGE variable the `e2e-local` target can not be executed anymore because it expects an `OPERATOR_IMAGE` it does not use.

Related https://github.com/elastic/cloud-on-k8s/issues/4244

**Comment by charith-elastic** [comment]
I see that you have fixed it as part of #4050 so I am not going to raise a separate PR for this.

**Comment by pebrc** [comment]
> I see that you have fixed it as part of #4050 so I am not going to raise a separate PR for this.

That's correct. But I felt adding the operator image was not a proper fix but just a work around. That's why I raised the issue.

**Comment by charith-elastic** [comment]
It's the simplest fix. The operator image value is not used during the local tests so it doesn't matter. The alternative would be to add an extra check before trying to parse the container image tag but I feel that extra logic there would just complicate the code for no real benefit.
