### ISSUE TITLE
Support for pod deletion cost

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#4297]
[Pod deletion cost](https://github.com/kubernetes/enhancements/issues/2255) is a new feature that allows users (or other controllers) to specify the cost of deleting a pod from a replicaset. 

- Should the operator honour the `controller.kubernetes.io/pod-deletion-cost` annotation when scaling down
- Should the operator automatically set/update the annotation on Elasticsearch pods by calculating a cost (number of shards, disk usage etc.)

**Comment by sebgl** [comment]
IIUC this is for ReplicaSets / Deployments only, not StatefulSets, right? So in our case there's not much we can do for Elasticsearch Pods?

**Comment by charith-elastic** [comment]
You're correct. I should have read the KEP more carefully.
