### ISSUE TITLE
Admission webhook error with 1.4.0 operator

### ISSUE THREAD

**Issue by vterdunov** [elastic/cloud-on-k8s#4326]
## Bug Report
**What did you do?**
Apply Elasticsearch manifest by kubectl. It works with ECK operator version 1.3.1. Doesn't work with 1.4.0

**What did you expect to see?**
Elasticsearch is up and running.

**What did you see instead? Under which circumstances?**
```
Error from server (Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch" is invalid: auth: Invalid value: "auth": auth field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown. This is often due to incorrect indentation in the manifest.): error when creating "infrastructure/base/elastic/elasticsearch.yaml": admission webhook "elastic-es-validation-v1beta1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch" is invalid: auth: Invalid value: "auth": auth field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown. This is often due to incorrect indentation in the manifest.
```

**Environment**

* ECK version:

1.4.0

* Kubernetes information:
	* Cloud: Yandex Cloud
	* Kubernetes distribution: kubernetes
	
	for each of them please give us the version you are using
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-20T02:22:41Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:36:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 7.11.1
  auth:
    fileRealm:
    - secretName: realm
  nodeSets:
  - name: deafult
    count: 1
```

* Logs:
<details>
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.388Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.388Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.388Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.388Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.388Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-kibana-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-kibana-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kb-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kb-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"ent-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"ent-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.389Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.390Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.390Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.392Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.392Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"license-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.392Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.392Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"remoteca-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.489Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.490Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.491Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.491Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.492Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.492Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.492Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.493Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.589Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.590Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.591Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.591Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.592Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.593Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.689Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.691Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.691Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:53.691Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.788Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"webhook-certificates-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.788Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.789Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-es-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.789Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"trial-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.790Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.790Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.790Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.790Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.791Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.791Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.791Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.791Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.792Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.792Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","source":"channel source: 0xc00037a1e0"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.792Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.792Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.792Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.792Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.793Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.793Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.793Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.793Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"remoteca-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.793Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"remoteca-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.794Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.794Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.794Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"ent-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.794Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"ent-es-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.794Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.794Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-es-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.795Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.795Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-es-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.795Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kb-es-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.795Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kb-es-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.795Z","log.logger":"controller","message":"Starting EventSource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-kibana-association-controller","source":"kind source: /, Kind="}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.796Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-kibana-association-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.796Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"license-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.888Z","log.logger":"controller","message":"Starting Controller","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"webhook-certificates-controller"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.888Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"webhook-certificates-controller","worker count":1}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.889Z","log.logger":"webhook-certificates-controller","message":"Starting reconciliation run","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","iteration":1,"namespace":"elastic-system","validating_webhook_configuration":"elastic-operator-webhook-cert"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.889Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-es-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.889Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"trial-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.890Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.891Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.891Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apmserver-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.892Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.892Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kibana-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.893Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.894Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"remoteca-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.894Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"ent-es-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.894Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-es-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.895Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.895Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"beat-es-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.895Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"kb-es-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.897Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"license-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.897Z","log.logger":"controller","message":"Starting workers","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"apm-kibana-association-controller","worker count":3}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.900Z","log.logger":"webhook-certificates-controller","message":"Ending reconciliation run","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","iteration":1,"namespace":"elastic-system","validating_webhook_configuration":"elastic-operator-webhook-cert","took":0.011211997}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.900Z","log.logger":"webhook-certificates-controller","message":"Starting reconciliation run","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","iteration":2,"namespace":"","validating_webhook_configuration":"elastic-operator.elastic-system.k8s.elastic.co"}
{"log.level":"info","@timestamp":"2021-03-09T15:34:54.911Z","log.logger":"webhook-certificates-controller","message":"Ending reconciliation run","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","iteration":2,"namespace":"","validating_webhook_configuration":"elastic-operator.elastic-system.k8s.elastic.co","took":0.011471158}
{"log.level":"info","@timestamp":"2021-03-09T15:35:03.489Z","log.logger":"generic-reconciler","message":"Updating resource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","kind":"ConfigMap","namespace":"elastic-system","name":"elastic-licensing"}
I0309 15:35:04.338705       1 request.go:621] Throttling request took 1.04266483s, request: GET:https://10.96.128.1:443/apis/elasticsearch.k8s.elastic.co/v1beta1?timeout=1m0s
{"log.level":"info","@timestamp":"2021-03-09T15:35:05.122Z","log.logger":"manager","message":"Orphan secrets garbage collection complete","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0"}
{"log.level":"info","@timestamp":"2021-03-09T15:37:03.494Z","log.logger":"generic-reconciler","message":"Updating resource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","kind":"ConfigMap","namespace":"elastic-system","name":"elastic-licensing"}
{"log.level":"info","@timestamp":"2021-03-09T15:39:03.494Z","log.logger":"generic-reconciler","message":"Updating resource","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","kind":"ConfigMap","namespace":"elastic-system","name":"elastic-licensing"}
</details>

Also
```
k get ValidatingWebhookConfiguration -A
NAME                                   CREATED AT
cert-manager-webhook                   2021-03-04T16:23:16Z
elastic-webhook.k8s.elastic.co         2021-03-09T15:20:09Z
ingress-nginx-admission                2020-09-21T11:56:43Z
prometheus-stack-kube-prom-admission   2020-10-23T15:51:34Z
validating-webhook-configuration       2020-12-29T14:26:18Z
```

**Comment by charith-elastic** [comment]
Did you install the operator using Helm? If so, this is a known issue and the fix is documented here: https://www.elastic.co/guide/en/cloud-on-k8s/current/release-highlights-1.4.0.html#k8s-140-known-issues

**Comment by charith-elastic** [comment]
I'll close it.
