### ISSUE TITLE
e2e local mode starts cleaning resources before the start of the tests

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#4332]
When running E2E tests with `--local`, the resources cleanup begins before the tests start. Indeed, in normal mode, the last `runTestJob` step is blocking and the program waits for its end before executing the cleanup. In local mode, there is no blocking step and the cleanup is performed in the process. One particular downside is that it removes the newly created SCC.

**Comment by pebrc** [comment]
I ran into this as well on Monday. I think we should run the test script in the as part of the invocation of `make local` Something like 
```golang
func (h *helper) runTestScript() error {
       ctx, cancelFunc := context.WithTimeout(context.Background(), h.commandTimeout)
       defer cancelFunc()

       cmd := command.New("test/e2e/run.sh", "-run", os.Getenv("TESTS_MATCH"), "-args", "-testContextPath", h.testContextOutPath).
               WithEnv(os.Environ()...).
               Build().
               Raw(ctx)

       cmd.Stderr = os.Stderr
       cmd.Stdout = os.Stdout

       return cmd.Run()
}
```
