### ISSUE TITLE
readiness probe not cover left node

### ISSUE THREAD

**Issue by JaydenHan1106** [elastic/cloud-on-k8s#4354]
Hi all,
Readiness probe is "Get 9200 port" now. When es node left cluster(such as network problem), readiness probe still return ok, so request still can arrive left node. It's not our expect.

**Comment by thbkrkr** [comment]
The Elasticsearch readiness probe was designed to:
- allow for reads without a master
- improve availability for some search heavy use cases

History of changes on this probe:
1) `/_cat/master` => `/ `               # increase availiblity and favor search requests   (#617  / PR #626)
2) `/` => `_cat/nodes?local` # don't break change budget                        (#1748 / PR #1777)
2) `_cat/nodes?local` => `/`                # don't fail if a single node is stuck             (#2248 / PR #2272)
