### ISSUE TITLE
ECK license usage is higher than pod limits allocated

### ISSUE THREAD

**Issue by KannappanSomu** [elastic/cloud-on-k8s#4389]
ECK license usage config map shows , higher than RAM allocated to pods 

Below is our resource limits for our dev cluster , and total RAM limit configured is 20 including kibana,

![image](https://user-images.githubusercontent.com/55806176/112863499-3656b880-90b7-11eb-9f25-770d9395fc99.png)

however the license usage config map show as 21.47, any idea how this is possible when the resource limit total is 20 ? 

```
kubectl -n elastic-system get configmap elastic-licensing -o json | jq .data
{
  "eck_license_level": "enterprise",  
  "enterprise_resource_units": "1",   
  "max_enterprise_resource_units": "6",
  "timestamp": "2021-03-29T14:21:15Z",
  "total_managed_memory": "21.47GB"   
}
```

**Comment by charith-elastic** [comment]
This is because Kubernetes resource limits are expressed in IEC units (1 KiB == 1024 bytes). ECK licence usage is calculated in SI units (1 KB == 1000 bytes). 

```
(20 * (1024^3)) / (1000^3) == 21.47
```

**Comment by KannappanSomu** [comment]
thanks for the answer.. i m closing this
