### ISSUE TITLE
ECK - license calculation

### ISSUE THREAD

**Issue by KannappanSomu** [elastic/cloud-on-k8s#4409]
The ECK configmap license query gives 2 different license usage values for dev and prod k8s cluster , however we are applying the same license key on both kubernetes clusters. Is there a global place to check the total enterprise license usage, 

DEV:
```
$ kubectl -n elastic-system get configmap elastic-licensing -o json | jq .data
{
  "eck_license_level": "enterprise",   
  "enterprise_resource_units": "1",    
  "max_enterprise_resource_units": "6",
  "timestamp": "2021-04-06T13:15:15Z",
  "total_managed_memory": "42.95GB"
}
```

PROD : 

```
$ kubectl -n elastic-system get configmap elastic-licensing -o json | jq .data
{
  "eck_license_level": "enterprise",
  "enterprise_resource_units": "5",
  "max_enterprise_resource_units": "6",
  "timestamp": "2021-04-06T13:14:24Z",
  "total_managed_memory": "316.75GB"
}

```

**Comment by pebrc** [comment]
If you have two independent deployments of the ECK operator there is no communication between the the two and therefore also no aggregation of the total license usage.
