### ISSUE TITLE
E2E Tests: improve resources validation

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4411]
When the node topology is validated [CheckESNodesTopology](https://github.com/elastic/cloud-on-k8s/blob/2a781357091e87d3a026d08bb3fa8ead43d67b9b/test/e2e/test/elasticsearch/checks_es.go#L88)  only verifies the memory limit. We should expand this validation to `requests` and other resources (cpu, storage).

Follow up of https://github.com/elastic/cloud-on-k8s/pull/4373#discussion_r602172506

**Comment by thbkrkr** [comment]
@barkbay I'm looking into this and I'm not sure how to check the cpu/mem requests. Did you have something in mind to check them?

**Comment by barkbay** [comment]
We have the expected Elasticsearch resource, and therefore the expected Pods topology and specifications. I think an idea would be to check that actual Pods are running with the expected resources.
