### ISSUE TITLE
Restarting an Elasticsearch instance while a graceful rolling upgrade is in progress can lead to inconsistent configuration

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#4423]
This came up into a discussion about restarting instances - currently achieved in ECK by deleting Pods and letting them be recreated.

If such a manual restart happens while a rolling upgrade is in progress, the recreated Pod can start with an inconsistent configuration. For example, the `elasticsearch.yml` file could be updated with new settings, while the container spec or the keystore aren't (yet). The node starts with an inconsistent configuration. Eventually, assuming the rolling upgrade can make progress, the Pod will be recreated again, and Elasticsearch will start with the desired configuration.

This is mostly due to the fact we don't have any atomicity guarantee in Kubernetes when updating multiple resources (StatefulSet, Secret, ConfigMap, Service, etc.).

I don't know how much this is a problem in practice, how it can be solved, and whether this is something we want to solve at all.

I can imagine hacky (complicated?) solutions where an init container would ensure all pieces of configurations are consistent (same version/hash) before letting the main Elasticsearch container start. There is also an argument in doing nothing: "if you decide to restart a Pod while a rolling upgrade is in progress, that's your responsibility".

**Comment by pebrc** [comment]
I am in the camp of 
>"if you decide to restart a Pod while a rolling upgrade is in progress, that's your responsibility".

It feels like swimming against the stream to try to force some notion of a checksum / atomic updates onto Kubernetes. 
I guess if we wanted such a feature it could also be in Elasticsearch itself. So that if it boots up and sees for example a configuration file that is not tagged or otherwise marked with the right revision it just bootloops until the correct revision appears. But that would make a very rigid system for the on-prem use case I guess.

**Comment by sebgl** [comment]
We discussed this today in a meeting with the team. We could not really point to a case where this would happen and would be dramatic. In this particular timing where the Pod can start with a wrong config, the regular rolling upgrade process will re-start it with the right config anyway.
We decided to not do anything about this problem unless we discover it materializes into something really bad.
