### ISSUE TITLE
Upgrading instructions for ECK is not clear

### ISSUE THREAD

**Issue by rishabh96b** [elastic/cloud-on-k8s#4427]
## Bug Report
**What did you do?**
Upgrade the ECK deployment using helm.
 
**What did you expect to see?**
There should be a separate section to provide upgrade instructions both using `all-in-one.yaml` and helm based deployments. For helm based deployment, it should be something like
```
helm upgrade elastic-operator elastic/eck-operator --version <target-version> -n elastic-system
```

**What did you see instead? Under which circumstances?**
The upgrade [instructions](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html#k8s-beta-to-ga-upgrade) points to [installation document](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html) without explicitly specifying the upgrade commands. In short, the doc says
```
Follow the instructions in Deploy ECK in your Kubernetes cluster to upgrade ECK to the latest version. This will update the ECK installation to the latest binary and update the CRDs and other ECK resources in the cluster...
```

**Comment by pebrc** [comment]
https://github.com/elastic/cloud-on-k8s/pull/4489 introduces more specific instructions

**Comment by pebrc** [comment]
Closing this as we have new upgrade instructions since #4489 now.
