### ISSUE TITLE
Elastic Agent Fleet mode

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#4429]
## Current state

Starting with `1.4.0`, ECK users can deploy Elastic Agent in the [standalone mode](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent.html). This allows them to supply the entire configuration of the Agent in the CRD and doesn't rely on the [Fleet](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html) feature of the Elastic Stack.

This issue will track the introduction of the Fleet mode. Further issue(s) will be created to track the exact design of CRD changes required.

## Fleet mode

Fleet mode is the alternative way of running the Elastic Agent where the configuration is created through Kibana and fed to Agents directly, without changing the configuration on the machines where Agents are running. In Kubernetes world this translates to keeping the Agent custom resource configuration minimal and fairly (more on that below) static.

One of the important components of the Fleet is the Fleet Server. The Fleet Server is a logical component that offloads connecting with Agents from Kibana. Instead of Kibana connecting to (potentially) thousands of Elastic Agents, Fleet Server connects directly to Elasticseach cluster and each Elastic Agent connects to one of the Fleet Servers.

The Fleet Server is not a separate product we ship, but a mode of running Elastic Agent (`set FLEET_SERVER_ENABLE=1`).

The cardinalities of the instances of the components involved are as following:

`ES cluster 1-to-n Fleet Server n-to-N Elastic Agent`

where `n` is small (1-100) and `N` can be large (1-10k+)

Note that Elastic Agent still connects to and sends _data_ to Elasticsearch directly. 

## CRD considerations

We will need to make some changes to our CRDs, given the introduction of the Fleet mode and the Fleet Server. Note that these features are independent from each other as:
1. Users can choose to run the Fleet Server through ECK, but run Elastic Agents elsewhere
2. Users can choose to run the Fleet Server elsewhere, but run Elastic Agents in the ECK-managed Kubernetes cluster

Allowing to support the above separately allows to support multiple setups, where each of Elasticsearch, Kibana, Fleet Server and Elastic Agents can be inside or outside of a given Kubernetes cluster. If outside, it can be another Kubernetes cluster (ECK-managed or not) or non-k8s environment.

### Fleet Server

There is a number of options we can choose from for supporting the Fleet Server. We can:
1. Introduce a new CRD dedicated to the Fleet Server
2. Allow configuring the Fleet Server through the existing Elastic Agent CRD
3. Make the Fleet Server deployment implicit or configurable when using Elastic Agent CRD
4. Make the Fleet Server deployment configurable through Kibana CRD

I feel fairly strongly against 3/4 due to the fact that it couples the Fleet Server deployment with other components and makes deploying the Fleet Server on its own not possible or unnatural. It goes in the opposite direction that we went so far - creating small, reusable building blocks that higher level concepts can build with.

I think 1. is a good option as it clearly separates Elastic Agent and Fleet Server which are separate components. But this is not how Fleet Server is shipped as it's bundled together with Elastic Agent. I think we should follow the same convention and create a CRD based on the product we ship, not on a particular mode it can run in. Note, that this prepares us better for any future that Elastic Agent might have as we model the CRD after the binary it runs.

Another disadvantage of introducing another CRD is that it would be almost the same as Elastic Agent CRD. I think it's better to reuse what we've built so far.

Given all of the above, I propose to go with option 2.

### Fleet mode

As this is just another mode of running the Elastic Agent, I don't see any value in introducing a separate CRD. I'd reuse the same CRD and introduce a configuration option to specify it should run in the Fleet mode:

```yaml
mode: fleet #standalone by default
```

Running in the Fleet mode requires:
1. Enrollment

Elastic Agent is capable of enrolling itself, but requires connection to Kibana to do that. This could be done through specifying a field:

```yaml
kibanaRef:
  name: kibana
```
I believe this is the right trade-off to make considering the alternative would be for the Operator or an init container to make a number of Kibana API calls. Especially, given those APIs might change/evolve in the future, differ between versions, etc.

2. Connecting to the Fleet Server

We can facilitate connecting to the Fleet Server(s) residing in the same Kubernetes cluster just as we do with all other CRDs:

```yaml
fleetServerRef:
  name: fleet-server
```

### Additional changes

Both the Fleet Server and Elastic Agents running in Fleet mode require introduction of a target that can be connected to. Elastic Agent controller should configure a Service that facilitates that. Note that similar request is already [tracked](#3866) for Beats CRD.

## Dynamic changes to Pod template

New configuration sent by Fleet to the Elastic Agent might require file system access or Pod permissions or K8s API permissions that the Elastic Agent Pod doesn't currently have. In such a case, the configuration change in Fleet needs to be paired with a change to Kubernetes resources. While inconvenient, we don't currently have a way to automate that. This is a non-goal of changes described above and, if at all, will be tracked separately.

FYI @blakerouse, @ruflin, @mostlyjason, @ChrsMark

**Comment by mostlyjason** [comment]
@david-kow I'd propose only supporting Elastic Agents with version 7.13 or higher since we have a breaking change in that release, and since its a beta we don't intend to maintain backwards compatibility. It will be simpler to drop the kibana Fleet connection, and only connect to Fleet Server.

Option 2 will match how users add Fleet Servers on bare metal, so it will be familiar to many users. I don't fully understand the tradeoffs though so I'm hoping others will weigh in.

**Comment by david-kow** [comment]
Thanks for the feedback.

> @david-kow I'd propose only supporting Elastic Agents with version 7.13 or higher since we have a breaking change in that release, and since its a beta we don't intend to maintain backwards compatibility. It will be simpler to drop the kibana Fleet connection, and only connect to Fleet Server.

I think we should be ok with support starting whatever will be the latest version of the Agent at the time of the release of the CRD with Fleet capability. We would still support some of the previous versions for the standalone mode.

As to the Kibana connection - I believe connecting to Kibana is still (`7.13.0-SNAPSHOT`) the case for enrolment purposes. Are you saying that the operator itself should connect to Kibana and do the enrolment on behalf of the Agent or the Fleet Server itself will handle the enrolment?

**Comment by mostlyjason** [comment]
@david-kow we just removed code for fleet in kibana so it might be different in the latest version

**Comment by ruflin** [comment]
In the above the connection is described as `Kibana n-to-n Fleet Server n-to-N Elastic Agent`. This is not correct. There is no direct connection between Kibana and Fleet-Server. All communication goes through Elasticsearch. Elastic Agent allows so specify Kibana variables but this is only for "magical" setup and not needed after the setup.

**Comment by david-kow** [comment]
> In the above the connection is described as `Kibana n-to-n Fleet Server n-to-N Elastic Agent`. This is not correct. There is no direct connection between Kibana and Fleet-Server. All communication goes through Elasticsearch. Elastic Agent allows so specify Kibana variables but this is only for "magical" setup and not needed after the setup.

Got it. I think I misunderstood due to the setup part. Thanks for correction.

**Comment by shubhaat** [comment]
Is there a possibility this might move to ECK 1.8? I need to update the marketing team on the collateral [here](https://docs.google.com/document/d/1JH3LP5rGy9qTfuJbyu35Y2pumhNLzJXMHQR7b2bX38I/edit).

**Comment by david-kow** [comment]
#### Summary

Given the feedback on this issue and some of the offline conversations I propose to move forward with the implementation.

We will introduce the following fields to the Agent CRD with non-breaking defaults:

```yaml
mode: fleet # or standalone
fleetServer: true
kibanaRef: 
  name: kibana
fleetServerRef:
  name: fleet-server
```

#### Basic setup 

##### Fleet Server
```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
spec:
  version: 7.13.0
  elasticsearchRefs:
  - name: elasticsearch
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
  # proposed new fields:
  mode: fleet
  fleetServer: true
  kibanaRef:
    name: kibana
```

##### Elastic Agents
```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: elastic-agent
spec:
  version: 7.13.0
  daemonSet: {}
  # proposed new fields:
  mode: fleet
  kibanaRef: 
    name: kibana
  fleetServerRef: 
    name: fleet-server
```

From user perspective, the above manifests should be enough to setup Fleet Server deployment and Elastic Agents daemon set. ECK will take care of user setup, Services, Agents configuration, required Kibana configuration, etc. We will use Elastic Agents native capabilities (`container` command) to enable Fleet and enroll Agents. 

#### Advanced setup

Each of {Elasticsearch, Kibana, Fleet Server, Elastic Agent} can live inside or outside of local, ECK-managed Kubernetes cluster - either in another Kubernetes cluster (ECK-managed or not) or on a different platform. Some examples could be:

- running ES+KB+FS in ECK-managed cluster with Elastic Agents connecting from outside
- running ES+KB in ECK-managed cluster with Fleet Server and Elastic Agents connecting from outside
- running Fleet Server and Elastic Agents in ECK-managed cluster and connecting to external ES+KB
- running Elastic Agents in ECK-managed cluster and connecting to external ES+KB+FS

To allow configuring those setups we will allow users to override env variables that Elastic Agent binary [consumes](https://github.com/elastic/beats/blob/2a56cd7fe026c5b59e76e47e397041f765125700/x-pack/elastic-agent/pkg/agent/cmd/container.go#L68). This approach doesn't overload CRD with potentially very rarely used fields while maintaining full flexibility.


#### CRD maturity

Given the known data path [issue](https://github.com/elastic/beats/issues/24213) and a need for a workaround for Kibana config [issue](https://github.com/elastic/kibana/issues/102794) I think we should keep the CRD at alpha.


#### Different API approaches considered

1. Decide to enable Fleet Server based on `mode: fleet` and absense of `fleetServerRef`. Unfortunately, this is unacceptable as Fleet Server might live outside of ECK and no ref can't be established automatically. We still want to support this scenario, but implicit approach would make it more complicated.

2. Combine `mode` and `fleetServer` to get `mode: standalone | fleet_server | fleet_agent`. I think this is a small optimization in field count, but mixes together two concepts which might be confusing for users.
