### ISSUE TITLE
ent.TestEnterpriseSearchConfigUpdate fails in 8.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#4455]
`ent.TestEnterpriseSearchConfigUpdate/Enterprise_Search_Pods_should_eventually_be_ready` failed in https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-snapshot-versions-8x/149/.

Pod crashes with `CrashLoopBackOff` due to:

```
Invalid config file (/usr/share/enterprise-search/config/enterprise-search.yml):
The setting '#/ent_search/auth/source' was completely deprecated in version '8.0.0'. Please use the new auth config format ent_search.auth.<auth_name>.source.
``` 

This was solved in #3725 where we made a change to use the new auth config format starting EnterpriseSearch 8.x.

But since we use the `semver` package for version parsing (#4174), we broke the version test:

https://github.com/elastic/cloud-on-k8s/blob/a4b7e530d9bb73a349cc11c82d73cc05778c71e4/pkg/controller/enterprisesearch/config.go#L279-L285

According to [semver](https://semver.org/#spec-item-11), `8.0.0-SNAPSHOT < 8.0.0`:

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version:
> Example: 1.0.0-alpha < 1.0.0.

**Comment by thbkrkr** [comment]
Tested: `7.999.0` < `8.0.0-0` < `8.0.0-A` < `8.0.0-SNAPSHOT` < `8.0.0-alpha1` < `8.0.0-bc1` < `8.0.0`

My thoughts on this: 
- compare strictly to 7.999.999 instead of 8.0.0, (1)
- add a prerelease (`0`, `A`, `SNAPSHOT`) to the reference version 8.0.0, (2)
- clean the source version we test to remove the prerelease, (3) (4)

```go
func TestGTWithSnapshot(t *testing.`T) {
	var v1,v2 Version

	v1, _ = Parse("8.0.0-SNAPSHOT")
	v2 = From(8, 0, 0)
	require.False(t, v1.GTE(v2))  // :-( This is what we want to fix.

	// (1) Compare with 7.999.999
	v1, _ = Parse("8.0.0-SNAPSHOT")
	v2 = From(7, 999, 0)
	require.True(t, v1.GT(v2))    // GT instead of GTE

	// (2) Compare 8.0.0-<something> where <something> <= SNAPSHOT
	v1, _ = Parse("8.0.0-SNAPSHOT")
	v2, _ = Parse("8.0.0-0")
	require.True(t, v1.GTE(v2))

	// (3) Call FinalizeVersion to remove pre-release suffix in the source version
	v1s, _ := semver.FinalizeVersion("8.0.0-SNAPSHOT")
	v1, _ = Parse(v1s)
	v2 = From(8, 0, 0)
	require.True(t, v1.GTE(v2))

	// (4) Manually remove the pre-release suffix in the source version
	v1, _ = Parse("8.0.0-SNAPSHOT")
	v1.Pre = nil
	v2 = From(8, 0, 0)
	require.True(t, v1.GTE(v2))
}
```

I think I prefer (1) which seems to me the most correct. What do you think?

**Comment by pebrc** [comment]
Technically what we are after is just the major version we don't care about the minor/patch/pre-release/tag etc bits. 

```golang
if ver.Major >= uint64(8) { 
		cfg = settings.MustCanonicalConfig(map[string]interface{}{
			"ent_search.auth.native1.source": "elasticsearch-native",
			"ent_search.auth.native1.order":  -100,
		})
	}
```

**Comment by thbkrkr** [comment]
@pebrc Your proposal is simple and effective. I take it.

**Comment by thbkrkr** [comment]
The test fails again but this time because of the addition of a check of the Elastisearch version in Enterprise Search:
```
Unsupported Elasticsearch version: 8.0.0-SNAPSHOT.
Enterprise Search requires Elasticsearch >= 8.0 and < 8.
```
There is a feature flag to work around this, which can be activated with the environment variable `ALLOW_PREVIEW_ELASTICSEARCH_8X=true`.
