### ISSUE TITLE
CVE remaining on the latest image's dependencies

### ISSUE THREAD

**Issue by mfouilleul** [elastic/cloud-on-k8s#4488]
Hello, 

FYI, on the latest version 1.5.0, `docker scan` (Snyk) is reporting 3 "High severity vulnerability" for which there is a fix.

```
docker scan docker.elastic.co/eck/eck-operator:1.5.0

Testing docker.elastic.co/eck/eck-operator:1.5.0...

✗ High severity vulnerability found in openssl-libs
  Description: RHSA-2021:1024
  Info: https://snyk.io/vuln/SNYK-RHEL8-OPENSSLLIBS-1089748
  Introduced through: openssl-libs@1:1.1.1g-12.el8_3
  From: openssl-libs@1:1.1.1g-12.el8_3
  Fixed in: 1:1.1.1g-15.el8_3

✗ High severity vulnerability found in nettle
  Description: RHSA-2021:1206
  Info: https://snyk.io/vuln/SNYK-RHEL8-NETTLE-1287634
  Introduced through: nettle@3.4.1-2.el8
  From: nettle@3.4.1-2.el8
  Fixed in: 0:3.4.1-4.el8_3

✗ High severity vulnerability found in gnutls
  Description: RHSA-2021:1206
  Info: https://snyk.io/vuln/SNYK-RHEL8-GNUTLS-1287630
  Introduced through: gnutls@3.6.14-7.el8_3
  From: gnutls@3.6.14-7.el8_3
  Fixed in: 0:3.6.14-8.el8_3

Organization:      undefined
Package manager:   rpm
Project name:      docker-image|docker.elastic.co/eck/eck-operator
Docker image:      docker.elastic.co/eck/eck-operator:1.5.0
Platform:          linux/amd64

Tested 104 dependencies for known vulnerabilities, found 3 vulnerabilities.

For more free scans that keep your images secure, sign up to Snyk at https://dockr.ly/3ePqVcp
```

Is it planned to upgrade these dependencies? 

Thanks,

Max.

**Comment by thbkrkr** [comment]
Hi,

It is planned to upgrade these dependencies in the next ECK version (1.6.0), which will be available pretty soon.

There was a very related discussion recently on the discuss forum: https://discuss.elastic.co/t/eck-operator-1-3-security-vulnerabilities/271456/2 that should interest you. It says that:

> Elastic supports our products running within updated containers but you are welcome to run 'microdnf update' on the images to pull in the latest packages from Red Hat.

And the most important:

> As for the package flaws themselves, I would not expect any of these to affect ECK. The ECK operator is a statically linked Go executable. It does not rely on operating system packages for its operation. None of these package should pose any threat to your infrastructure.

Please contact security@elastic.co, if you have any questions.
