### ISSUE TITLE
Support for taking and getting heap dumps and other analytics

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#45]
- How should initiate and how should we be able to get to it?
  - E.g: store it inside a mounted volume? Upload to a s3/repository bucket? Same as snapshot bucket? Lifecycle then becomes an issue to GC eventually
- Other JVM/debugging tools that would be relevant?

**Comment by pebrc** [comment]
I think this is a task for a higher-level orchestrator than the ECK operator, as we currently don't have any notion of S3/external storage. Closing for now.
