### ISSUE TITLE
Upgrade to controller-runtime 0.9.0

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4554]
Version 0.9.0 has been released. We should upgrade.

https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.9.0

**Comment by pebrc** [comment]
Looks like renovate has opened a PR already https://github.com/elastic/cloud-on-k8s/pull/4553

**Comment by barkbay** [comment]
Fixed by https://github.com/elastic/cloud-on-k8s/pull/4553
