### ISSUE TITLE
Replace UBI with scratch image

### ISSUE THREAD

**Issue by leonz** [elastic/cloud-on-k8s#4561]
## Proposal

Hey folks,

I'd like to propose that the [UBI in the Dockerfile](https://github.com/elastic/cloud-on-k8s/blob/master/Dockerfile#L27) is replaced with a [scratch image](https://hub.docker.com/_/scratch), at least for a non-Openshift distribution.

RedHat unfortunately is not speedy in updating critical vulnerabilities, so when deploying this image we find that we are hit with failing vulnerability scans.

The scratch image, plus maybe a few hand picked utilities, should provide the minimum necessary platform to run ECK and minimize any vulnerability/attack vector.

**Comment by pebrc** [comment]
For context: we originally shipped the ECK operator in a scratch image but we changed the base image in [release 1.3](https://www.elastic.co/guide/en/cloud-on-k8s/current/release-highlights-1.3.0.html) to UBI to be able to offer the operator also via Red Hat certified operator program. 

We could consider shipping two versions of the image which we decided not to do originally due to the added complexity in our build and test pipelines.

**Comment by leonz** [comment]
Peter - the reasoning makes sense.  It’s unfortunate that the Red Hat certified images are so behind in patching vulnerabilities.

This recent announcement of UBI Micro might be interesting - https://www.redhat.com/en/blog/introduction-ubi-micro

I haven’t yet investigated the quality of the image, but it’s likely worse than Scratch but strictly better than the current image, and would allow you to maintain certification with a single build.

**Comment by pebrc** [comment]
Once we are moving back to scratch we should also add a section to our troubleshooting guide how users can attach an ephemeral container for debugging purposes.

**Comment by PraveenBodasingi19** [comment]
1.	What image was scanned?  - eck-operator:2.2.0
2.     What tool was used for scanning? - Aquasec Scanner
3.     What vulnerabilities are being reported? Your image shows versions of software but not specific vulnerabilities ? - curl
glib2
gmp
gnutls
libarchive
libgcrypt
libsolv
libssh
libtasn1
libxml2
pcre2
rpm

These packages are not latest version. Please upgrade to latest version.

**Comment by PraveenBodasingi19** [comment]
When you will release ES Operator Image 2.3.0. Please let me know
