### ISSUE TITLE
Kibana config fix for pre-7.6.0 invalid settings is not always applied

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#4592]
In https://github.com/elastic/cloud-on-k8s/pull/3315 we added a fix to work around a bug in Kibana settings pre 7.6.0:

https://github.com/elastic/cloud-on-k8s/blob/e34820466048ec5866e6f9644575e32847b34d12/pkg/controller/kibana/config_settings.go#L80-L84

Looking at this piece of code again I think the fix only applies to one code path where there is an Elasticsearch association:

https://github.com/elastic/cloud-on-k8s/blob/e34820466048ec5866e6f9644575e32847b34d12/pkg/controller/kibana/config_settings.go#L117-L133

But not to the code path where Kibana is not associated to any Elasticsearch resource:

https://github.com/elastic/cloud-on-k8s/blob/e34820466048ec5866e6f9644575e32847b34d12/pkg/controller/kibana/config_settings.go#L100-L110

Additionally, the Kibana config generation function could benefit from some refactoring to avoid those 2 code paths, and instead just merge empty configs when there's no es config to setup.

**Comment by thbkrkr** [comment]
Pseudo-code of what we are doing:
```go
newConfig := filterConfigSettings(initialConfig)

if x {
  // bug? we didn't use newConfig!
  return initialConfig
}

return newConfig
```

`filterConfigSettings(kb kbv1.Kibana, cfg *settings.CanonicalConfig)` takes a pointer to `settings.CanonicalConfig`.
Even if we don't use the returned modified configuration `newConfig`, the initial `initialConfig` is mutated by the function.
So there is no bug but we can make this less ambiguous.
