### ISSUE TITLE
Unable to scale masternode count: The POST operation against Pod could not be completed at this time, please try again.

### ISSUE THREAD

**Issue by timvol** [elastic/cloud-on-k8s#4594]
## Bug Report
**What did you do?**

I've created a Elasticsearch cluster with 3 data-nodes and 1 master-node. Now I wanted to scale the cluster by adding a new master node.

**What did you expect to see?**

I expected to see that the masternode comes up as usual as fallback for the first masternode.

**What did you see instead? Under which circumstances?**

I changed "count" parameter of the masternodes but the pod is already pending since some hours and when I check the stateful set, it gives me the following error:

> create Pod elasticdb-es-data-nodes-2 in StatefulSet elasticdb-es-data-nodes failed error: The POST operation against Pod could not be completed at this time, please try again.

**Environment**

* ECK version: 1.6.0

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? No
	* Cloud: GKE / EKS / AKS ? Hetzner
	* Kubernetes distribution: Openshift / Rancher / PKS ? Rancher
	
	for each of them please give us the version you are using
```
$ kubectl version: 1.20.6
```

**Comment by sebgl** [comment]
> create Pod elasticdb-es-data-nodes-2 in StatefulSet elasticdb-es-data-nodes failed error: The POST operation against Pod could not be completed at this time, please try again

It looks like the Kubernetes StatefulSet controller has some issues reaching out to the apiserver?
Can you describe both the statefulset resource (`kubectl describe statefulset <name>`) and the Pending Pod resource if it exists (`kubectl describe pod <name>`)? I'm curious about what's reported there.

In any case, this does not look like an ECK problem.
