### ISSUE TITLE
Support for diagnostics bundle / dumping

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#46]
Perhaps not something to directly bundle into our resources, but bake some supporting infra / labels etc into this?

A script or something otherwise runnable could suffice, and what we'd want is a final artifact of a reasonable size that will encapsulate all information (without containing secrets etc) we'd need when remotely debugging weird or unexpected behavior on a system we can't or won't directly access.

This is something we'd like to have working on both a installation-wide basis as well as on a deployment-wide basis.

**Comment by thbkrkr** [comment]
`kubectl cluster-info dump` exists but does not work properly when `--namespaces` flag is specified (https://github.com/kubernetes/kubernetes/issues/72088).

ECE has a similar tool that can provide some inspiration: https://github.com/elastic/ece-support-diagnostics .

Some ideas for the tool:

- easy to download: 1 shell script or 1 binary
- no or few dependencies: curl ok, jq?
- respect privacy: do not dump all the k8s resources of all the namespaces
- diag viewer: nice to have in a second time

#### What information is interesting for debugging and diagnosing problems?

##### Phase 0

Cluster version
- `kubectl version -o json`

Operator info
- Resources (statefulsets, pods and configmaps): `kubectl get -n $ns $resourceName -o json`
- Pods logs: `kubectl logs -n $ns $podName`

Managed Elastic stack component info
- Resources, global overview (elastic,pods,rs,deploy,svc,ep,secrets,configmaps,pv,pvc): `kubectl get -n $ns $resourceName`
- Resources, details overview (elastic,pods): `kubectl get -n $ns $resourceName -o json`
- Pods logs: `kubectl logs -n $ns $podName`

##### Phase 1

- RBAC for the namespaces concerned
- Nodes info: number, hardware (cpu, ram, disk), os, kernel
- K8s cluster limits and capacity

##### Questions

How to retrieve the namespace(s) where the operator(s) is(are) deployed?
How to retrieve the namespace(s) of the elastic ressources(s) managed by the operator(s)?

- Autodiscover?
- Can be a parameter of the diagnostic script?

**Comment by thbkrkr** [comment]
No magic. I propose to allow to specify the namespaces with flags and to use by default:
- "elastic-system" and "elastic-namespace-operators", for the namespaces in which the operators are running in 
- the current namespace, for the namespace in which the resources are managed

**Comment by thbkrkr** [comment]
Closed by #1115.
