### ISSUE TITLE
False negative on cloud-on-k8s-e2e-tests-ocp

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#4610]
Since #4593, the job fails at the end during the cleanup:

```
08:01:56  2021/06/30 06:01:56 Deleting cluster...
08:01:57  level=info msg=Credentials loaded from file "/home/.gcp/osServiceAccount.json"
08:02:43  level=info msg=Stopped instance ocp4-ci-492-92qb7-worker-c-wpnx7
...
08:06:39  level=info msg=Deleted network ocp4-ci-492-92qb7-network
08:06:39  level=info msg=Time elapsed: 4m35s
08:06:39  2021/06/30 06:06:34 Removing context, user and cluster entry from kube config

08:06:39  error: cannot delete context admin, not in /root/.kube/config <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

08:06:39  Error: exit status 1
08:06:39  exit status 1
08:06:39  make: *** [Makefile:525: run-deployer] Error 1
08:06:39  Makefile:46: recipe for target 'ci-internal' failed
08:06:39  make[1]: *** [ci-internal] Error 2
08:06:39  make[1]: Leaving directory '/var/lib/jenkins/workspace/cloud-on-k8s-e2e-tests-ocp/.ci'
08:06:39  Makefile:40: recipe for target 'ci' failed
08:06:39  make: *** [ci] Error 2
08:06:39  make: Leaving directory '/var/lib/jenkins/workspace/cloud-on-k8s-e2e-tests-ocp/.ci'
08:06:39  [Pipeline] }
08:06:39  [Pipeline] // script
08:06:39  Error when executing cleanup post condition:
```

**Comment by pebrc** [comment]
My bad 😞  we should make this conditional maybe?

**Comment by thbkrkr** [comment]
IIUC this happens in CI because the kubeconfig file is in a custom location:
https://github.com/elastic/cloud-on-k8s/blob/cb2f97d35135f7f2f13316d8a22a3ec0181df7f3/hack/deployer/runner/ocp.go#L317

and `KUBECONFIG` is not set for the `kubectl config delete...` commands like for the other `kubectl` commands:

https://github.com/elastic/cloud-on-k8s/blob/cb2f97d35135f7f2f13316d8a22a3ec0181df7f3/hack/deployer/runner/ocp.go#L327

So it uses the default path (`$HOME/.kube/config`) where we didn't add context, user and cluster. 

It is not relevant to cleanup the kube config in CI as we are in a isolated env and only one k8s cluster is created.
We could set `KUBECONFIG` "and|or just" make the cleanup conditional as you proposed. I find it a little weird to only do the second. I would tend to choose to do both.

**Comment by thbkrkr** [comment]
Forget what I said, let's just make the cleanup conditional. We don't want to update/cleanup our working kube config but only the one pointed by the KUBECONFIG env var.

**Comment by pebrc** [comment]
Well we kind of do. If you are running locally at least. The config pointed to by `KUBECONFIG` is merged with the config in your `HOME` directory: 

https://github.com/elastic/cloud-on-k8s/blob/b48b1afd26b54a5891183904bc29a9128a46f5d1/hack/deployer/runner/kubeconfig.go#L15-L36

The purpose of my original change was to undo that merge so that repeated bootstrapping would not create an invalid mix of various OCP configs.
