### ISSUE TITLE
OCP 4.5 e2e pipeline is failing

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4658]
`cloud-on-k8s-e2e-tests-ocp` failed a [couple](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/504/console) of [times](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/509/consolev) today:

```
08:23:04  docker.elastic.co/eck-ci/deployer-ocp:4.5.37-a9abf10a46398833
08:23:04  2021/07/19 06:23:03 Checking if cluster exists...
08:23:04  2021/07/19 06:23:03 Creating cluster...
08:23:05  level=info msg="Credentials loaded from file \"/home/.gcp/osServiceAccount.json\""
08:23:05  level=info msg="Consuming Install Config from target directory"
08:23:15  level=info msg="Creating infrastructure resources..."
08:25:52  level=info msg="Waiting up to 20m0s for the Kubernetes API at https://api.ocp4-ci-509.eck-ocp.elastic.dev:6443..."
08:27:00  level=info msg="API v1.18.3+cdb0358 up"
08:27:00  level=info msg="Waiting up to 40m0s for bootstrapping to complete..."
08:33:36  level=info msg="Destroying the bootstrap resources..."
08:35:28  level=info msg="Waiting up to 30m0s for the cluster at https://api.ocp4-ci-509:6443 to initialize..."
09:05:36  level=info msg="Cluster operator insights Disabled is False with : "
09:05:36  level=fatal msg="failed to initialize the cluster: Working towards 4.5.37: 87% complete, waiting on authentication"
09:05:36  2021/07/19 07:05:28 Uploading cluster state: gsutil rsync -r -d /root/ocp4-ci-509885793437 gs://eck-deployer-ocp-clusters-state/ocp4-ci-509
09:05:36  Error: exit status 1
09:05:36  exit status 1
```

**Comment by barkbay** [comment]
Looks similar to https://bugzilla.redhat.com/show_bug.cgi?id=1846203, no solution or workaround documented however.

**Comment by barkbay** [comment]
I hit this one from my laptop, with the exact same [message](https://github.com/elastic/cloud-on-k8s/issues/4658#issuecomment-886670027), while I wanted to test a dev build of ECK `1.7.1` on OCP `4.5.41` _(the latest available version for OCP 4.5 to date)_

The interesting thing is that it definitely seems to be a timeout problem, the install process seems to take a bit more than 30 minutes.
Here is the cluster status from the OpenShift console right after the failure:

![image](https://user-images.githubusercontent.com/976373/129862076-b5dedceb-994c-4593-ada2-12943159f36c.png)

Same screenshot 2 minutes later:

![image](https://user-images.githubusercontent.com/976373/129862176-e82d1c6a-f2ef-4f34-824a-0a40007b7c86.png)

 All Pods are eventually Running, and all the nodes are Ready:

```
michael-ocp-cluster-cgwwd-master-0          Ready    master   69m   v1.18.3+d8ef5ad
michael-ocp-cluster-cgwwd-master-1          Ready    master   69m   v1.18.3+d8ef5ad
michael-ocp-cluster-cgwwd-master-2          Ready    master   69m   v1.18.3+d8ef5ad
michael-ocp-cluster-cgwwd-worker-a-zckmd    Ready    worker   40m   v1.18.3+d8ef5ad
michael-ocp-cluster-cgwwd-worker-b-d5zzx    Ready    worker   40m   v1.18.3+d8ef5ad
michael-ocp-cluster-cgwwd-worker-c-b4cj7    Ready    worker   40m   v1.18.3+d8ef5ad
```

It is not possible to customize the timeout, attempts to make it a parameter have been [rejected](https://github.com/openshift/installer/pull/1777) and the value of 30m is [hardcoded](https://github.com/openshift/installer/blob/6d778f911e79afad8ba2ff4301eda5b5cf4d8e9e/cmd/openshift-install/create.go#L379).

If we don't want to investigate why the install process takes 31 minutes instead of 30 minute, an option could be to:
1. attempt to catch this specific failure (or not)
2. wait an additional amount of time for the cluster to be ready using the `openshift-install wait-for install-complete` command:

```
> openshift-install wait-for install-complete

INFO Waiting up to 30m0s for the cluster at https://REDACTED:6443 to initialize...
INFO Waiting up to 10m0s for the openshift-console route to be created...
INFO Install complete!
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=REDACTED'
INFO Access the OpenShift web-console here: https://REDACTED
INFO Login to the console with user: "kubeadmin", and password: "REDACTED"
INFO Time elapsed: 1s
```

I agree that it's definitely not a clean solution though, but I'm not sure how we could investigate how to optimize the install process.

**Comment by thbkrkr** [comment]
Note that this prevents us from testing OCP 4.6 and 4.7 via the job [cloud-on-k8s-e2e-tests-ocp-all-but-latest](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/). When luckily we managed to create a 4.3 or 4.4 OCP cluster, it fails for the 4.5.
```
# https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/8/

13:13:21  Starting building: cloud-on-k8s-e2e-tests-ocp #572 4.3.40 FAILURE
	> 13:54:09  error: error validating "/tmp/eck-e2e/e2e-0d3nm/monitoring-operator.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.http.properties.service.properties.spec.properties.selector): unknown field "x-kubernetes-map-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
13:58:21  hudson.remoting.ProxyException: co.elastic.BuildException

# https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/9

15:28:15  Starting building: cloud-on-k8s-e2e-tests-ocp #573 4.3.40 SUCCESS
22:52:55  Starting building: cloud-on-k8s-e2e-tests-ocp #574 4.4.33 SUCCESS
06:04:02  Starting building: cloud-on-k8s-e2e-tests-ocp #575 4.5.41 FAILURE
	> 06:54:33  level=fatal msg="failed to initialize the cluster: Cluster operator console is reporting a failure: RouteHealthDegraded: route not yet available, https://console-openshift-console.apps.ocp4-ci-575.eck-ocp.elastic.dev/health returns '503 Service Unavailable'"
06:57:27  hudson.remoting.ProxyException: co.elastic.BuildException

# https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/15

10:10:23  Starting building: cloud-on-k8s-e2e-tests-ocp #582 4.3.40 FAILURE
	> 13:43:59      --- FAIL: TestAutoscaling/All_expected_Pods_should_eventually_be_ready#02 (1800.00s)
13:48:10  hudson.remoting.ProxyException: co.elastic.BuildException

# https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/21

10:02:08  Starting building: cloud-on-k8s-e2e-tests-ocp #592 4.3.40 SUCCESS
17:28:47  Starting building: cloud-on-k8s-e2e-tests-ocp #593 4.4.33 FAILURE
	> 17:35:44  level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
17:37:46  hudson.remoting.ProxyException: co.elastic.BuildException

# https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/22

17:40:07  Starting building: cloud-on-k8s-e2e-tests-ocp #594 4.3.40 SUCCESS
01:14:51  Starting building: cloud-on-k8s-e2e-tests-ocp #595 4.4.33 SUCCESS
08:43:06  Starting building: cloud-on-k8s-e2e-tests-ocp #596 4.5.41 FAILURE
	> 09:29:56  level=fatal msg="failed to initialize the cluster: Working towards 4.5.41: 87% complete"
09:33:09  hudson.remoting.ProxyException: co.elastic.BuildException

# https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp-all-but-latest/30

10:18:52  Starting building: cloud-on-k8s-e2e-tests-ocp #608 4.3.40 FAILURE
	> 10:24:45  level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
10:26:46  hudson.remoting.ProxyException: co.elastic.BuildException
```

**Comment by thbkrkr** [comment]
Since the last comment, none of the last jobs failed when creating the OpenShift `4.5.41` environment :partying_face:.

We got 1 :heavy_check_mark:  [(630)](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/630/) and 2 :red_circle:  ([640](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/640/), [651](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/651/) because the 4h timeout was reached (https://github.com/elastic/cloud-on-k8s/issues/5030).

**Comment by thbkrkr** [comment]
Closing because the bug did not reproduced in the last 2 months, which tends to suggest that it was transient. We will reopen if it reproduces.

**Comment by thbkrkr** [comment]
Happened again:

| date | build | status |
| --- | --- | --- |
| 27 nov. | `e2e/ocp/4.5.41/686` | :red_circle: |
| 04 dec. | `e2e/ocp/4.5.41/706` | :red_circle: |

**Comment by barkbay** [comment]
`4.5` support ended `July 27, 2021`. It is removed from our pipeline in #5415.
Let's reopen this issue if the problem still occurs for OCP >= 4.6 (according to [footnote here](https://access.redhat.com/support/policy/updates/openshift#footnotes) OpenShift 4.6 EUS end date is Oct 27, 2022)
