### ISSUE TITLE
Make running elasticsearch with non-root user the default way

### ISSUE THREAD

**Issue by mtparet** [elastic/cloud-on-k8s#4662]
## Proposal

**Use case. Why is this important?**

For compliance and security, elasticsearch should not run by default with a root user. 
If this is not possible to make it the default, we should have a clear and easy way to achieve it.

This does not implicate running initContainers as non-root users which are ephemeral and really needs root/privileged access for some actions.

Linked to https://github.com/elastic/cloud-on-k8s/issues/1996

**Comment by barkbay** [comment]
Starting with `8.0` Elasticsearch container will start with a non privileged user by default. For now I would say that the solution  to control security aspects is to rely on PSPs (to be replaced by [PodSecurity admission](https://github.com/kubernetes/kubernetes/pull/103099)). We are providing some [examples](https://github.com/elastic/cloud-on-k8s/tree/master/config/recipes/psp) to show how to ensure that containers are running as non root.

**Comment by mtparet** [comment]
Thanks for your answer, we will add securityContext to the podTemplate for now so.
