### ISSUE TITLE
The latest available eck-operator Docker image is 43.0.0

### ISSUE THREAD

**Issue by maxdanilov** [elastic/cloud-on-k8s#4688]
## Bug Report
**What did you do?**

We have an automation in our repository that creates automatic PRs when there's a new version of ECK Operator available, to not a miss an upgrade.

Unfortunately, there's a (dummy?) image of the operator tagged as `docker.elastic.co/eck/eck-operator:43.0.0` that breaks this automation. Instead of having a PR for the actual latest version (`1.6.0` as of now) we get the non-existing `43.0.0`

![image](https://user-images.githubusercontent.com/6655714/127006289-4e322f57-5b89-4998-9313-5189b2536a5a.png)

**What did you expect to see?**

The latest available Docker image for the operator is `1.6.0`, the image `docker pull docker.elastic.co/eck/eck-operator:43.0.0` should not exist in the registry.

**What did you see instead? Under which circumstances?**

The latest available Docker image is 43.0.0 which is wrong:

```
docker pull docker.elastic.co/eck/eck-operator:43.0.0
43.0.0: Pulling from eck/eck-operator
ab5ef0e58194: Downloading [===>                                               ]  4.819MB/75.78MB
47c2154639cb: Verifying Checksum
d37075b7075a: Downloading [===>                                               ]  1.463MB/19.99MB
```

**Comment by thbkrkr** [comment]
Sorry for the inconvenience, these tags have been pushed by mistake in the past. They will be deleted soon, I keep you posted.

**Comment by thbkrkr** [comment]
Deletion completed :heavy_check_mark: .

```
> docker pull docker.elastic.co/eck/eck-operator:43.0.0
Error response from daemon: manifest for docker.elastic.co/eck/eck-operator:43.0.0 not found: manifest unknown: manifest unknown
```
