### ISSUE TITLE
[FEATURE REQUEST] Ability to easily mount existing volumes to new cluster for investigations

### ISSUE THREAD

**Issue by hartfordfive** [elastic/cloud-on-k8s#4714]
## Proposal

When running clusters with ECK , in some cases I've had incidents were a cluster has becomes unusable (typically due to disk being filed even though the watermarks are there to prevent this).  Unfortunately in critical production use-cases, users don't always have the ability take take time to directly debug the issue.   Using the last-resort approach of creating new volumes and then restoring data from snapshots tends to be faster than spending an unknown amount of time trying to track down the issue.      Keeping the old cluster volumes is relatively easy to do (given the proper policy exists to prevent deleting them), thus having a tool or script that could allow us to easily attach an unbound PV to a new cluster could simply the process of performing a RCA for issues such as a filed disk. 

A solution could be provided as a clear step-by-step guide although for paying customers, especially enterprise ones, MTTR is key.  Consequently, having this feature provided as a helper script would take any guess work out of the equation and reduce the possibility of it being completed incorrectly.

**Comment by pebrc** [comment]
Thanks for the proposal. What is not clear to me is how reattaching a full disk to a new cluster won't help with diagnosing the problem as the new cluster will also not be able to run with a full disk. What could be done instead is to mount to the disk to a non-Elasticsearch Pod for debugging purposes. Given that this would be not an automatic mechanism but rather a set of manual steps as you already mentioned, this could be a section in our troubleshooting guide.

**Comment by shubhaat** [comment]
Closing this for the ER for now.
