### ISSUE TITLE
Elastic Operator not stable

### ISSUE THREAD

**Issue by vaibhavsw** [elastic/cloud-on-k8s#4763]
When deploying elastic on Kubernetes, the below error is coming up because even elastic isn't getting deployed.

```log
E0814 16:22:06.330007       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.ApmServer: request to convert CR from an invalid group/version: apm.k8s.elastic.co/v1
E0814 16:22:06.422435       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.Kibana: request to convert CR from an invalid group/version: kibana.k8s.elastic.co/v1
E0814 16:22:07.236631       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.Elasticsearch: request to convert CR from an invalid group/version: elasticsearch.k8s.elastic.co/v1
```

**Comment by barkbay** [comment]
We would need more details to understand and reproduce your issue. Could you provide:

* The version your are trying to install and the original version if it is an upgrade.
* The steps you followed to install and upgrade the operator.
* Your environment details (k8s client and server version, cloud provider...)
* The output of the following command: `kubectl get crds -o go-template='{{range .items}}{{.metadata.name}}:{{range .spec.versions}} {{.name}}{{end}}{{"\n"}}{{end}}'`

**Comment by david-kow** [comment]
Closing as there was no updates in some time. Reopen as needed.
