### ISSUE TITLE
Document fsGroup setting in securityContext 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4781]
Part of https://github.com/elastic/cloud-on-k8s/issues/2791 but also relevant for custom Elastic Stack Docker images that don't use the root user (e.g. Iron Bank)

If run as root we set up file system permissions in an initContainer and things "just work". We should however document that the data directory has to be made writeable for the `elasticsearch` user when not running the container as root.

**Comment by pugnascotia** [comment]
Particularly relevant for 8.0.0 because starting from that version, the Elasticsearch Docker image will use the `elasticsearch` user by default.
