### ISSUE TITLE
Support IP filtering on a cluster level

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#48]
This might have more involved implications when it comes to accepting connections from remote clusters, possibly accessed through some form of ingress-like proxy (here we'd have to enforce the ip filtering in the proxy and allow the proxy to connect to the ES instances).

Perhaps network policies would make more sense than using the xpack ip filtering support directly in some cases? Or would both make sense still?

**Comment by pebrc** [comment]
https://github.com/elastic/cloud-on-k8s/pull/3634 adds manifests and documentation for NetworkPolicies

**Comment by pebrc** [comment]
Closing this for now, let's reopen if we change our mind about the need for this.
