### ISSUE TITLE
Simplify K8S CRD from elasticsearch and kibana to es and kb

### ISSUE THREAD

**Issue by mapdegree** [elastic/cloud-on-k8s#4921]
## Proposal
Change or add an additional K8S CRD called `es` and `kb` as `elasticsearch` and `kibana` are longer words to type with developers are interactively typing the kubectl commands and making typos.

**Use case. Why is this important?**
Improve speed of executing kubectl commands

**Comment by pebrc** [comment]
You can do that today, we have `es` and `kb` as short names for the Elasticsearch and Kibana CRDs.

We also have `apm` (APM server), `agent` (Elastic Agent) , `beat` (Beats), `ems` (Elastic Maps Server) and `ent` (Enterprise Search).

**Comment by thbkrkr** [comment]
There is also the alias `elastic` which includes them all.

Note that these shortcuts are visible using `kubectl api-resources`:
```
> kubectl api-resources | grep elastic
agents                            agent        agent.k8s.elastic.co              true         Agent
apmservers                        apm          apm.k8s.elastic.co                true         ApmServer
beats                             beat         beat.k8s.elastic.co               true         Beat
elasticsearches                   es           elasticsearch.k8s.elastic.co      true         Elasticsearch
enterprisesearches                ent          enterprisesearch.k8s.elastic.co   true         EnterpriseSearch
kibanas                           kb           kibana.k8s.elastic.co             true         Kibana
elasticmapsservers                ems          maps.k8s.elastic.co               true         ElasticMapsServer
```
