### ISSUE TITLE
FIPS 140-2 enabled in Java process JCE jar's are missing

### ISSUE THREAD

**Issue by vinodhreddyg** [elastic/cloud-on-k8s#4933]
## Bug Report
**What did you do?**
Enable FIPS 140-2 for elasticsearch 7.9.0 version. Followed this blog https://www.elastic.co/guide/en/elasticsearch/reference/7.9/fips-140-compliance.html
**What did you expect to see?**
Java process should contain jar specific to JCE like US_export_policy.jar, jcmFIPS.jar, sslj.jar.  Referring below blog.
https://docs.oracle.com/middleware/1213/wls/SECMG/fips.htm#SECMG770
**What did you see instead? Under which circumstances?**
I don't see any jar in /usr/share/elasticsearch/jdk (except ./lib/jrt-fs.jar). Can you please let me know how we can validate FIPS is enabled at java level?
**Environment**

* ECK version:

	1.3.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ? GKE 1.20.10-gke.1600
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
1.20+
```

* Resource definition:
```
kubectl -n <ns> exec -it elasticsearch-config-es-data-ingest-0 -- bash
```

* Logs:
```
N/A
```

**Comment by thbkrkr** [comment]
> I don't see any jar in /usr/share/elasticsearch/jdk (except ./lib/jrt-fs.jar). 

Yes, if you want to use the bundled JVM with FIPS mode enabled, it is up to you to provide the BCFIPS provider JARs. Maybe this discuss post can help: https://discuss.elastic.co/t/elasticsearch-wont-start-with-fips-mode-enabled/280758/2.

Like for plugin installs our recommendation is to create a [custom Docker image](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-custom-images.html) based on the official image which downloads the JARs and configures the bundled JVM to run with a FIPS 140-2 certified Java Security Provider or uses an external JVM configured for FIPS 140-2.

> Can you please let me know how we can validate FIPS is enabled at java level?

Sorry, I don't know much about FIPS. This seems to be [programmatically verifiable](https://support.azul.com/hc/en-us/articles/360057629072-How-can-one-programmatically-check-if-FIPS-is-enabled-)?
