### ISSUE TITLE
Elasticsearch HTTP client: log requests at debug level

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4935]
As mentioned in this [comment](https://github.com/elastic/cloud-on-k8s/pull/4922#discussion_r722087762) we should log (at the debug level) all the requests to Elasticsearch.
We should take care to not log the body or any header as they may contain some credentials. The debug log should also contain the Elasticsearch cluster namespaced name as for the other logs (`es_name`).

**Comment by koneko096** [comment]
let me try
