### ISSUE TITLE
ECK operator doesn't keep a right count of data nodes which is defined in my elasticsearch yaml after I modify data nodeset statefulset directly 

### ISSUE THREAD

**Issue by bydeath** [elastic/cloud-on-k8s#4936]
## Bug Report
**What did you do?**
I modified data nodeset statefulset directly. I executed kubectl edit  statefulset my-es-data, and replace the value of spec.replicas 4 with 3.

**What did you expect to see?**
 Eck-operaor should modify spec.replicas form 3 to 4 eventually, and there are 4 data nodes running in my elasticsearch cluster.
In fact, I'm not sure whether it is a bug or a feature, I hope get an explaination about the phenomena, Thank you very much.
**What did you see instead? Under which circumstances?**
There  are 3 elasticsearch data nodes running. 

**Environment**

* ECK version:

	1.8.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise kubernetes 1.19

```
$ kubectl version
```
1.19

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```
{..."statefulset_name": "my-es-data", "actualReplicas": 3, "replicasToCreate": 1}

**Comment by david-kow** [comment]
Hey, thanks for your report.

This is actually a feature :) ECK watches our custom resources and configures all other resources as required to fulfil what the custom resource describes. If you want to increase the number of nodes in the particular `nodeSet` (which maps 1:1 to a statefulset), use `count` field. See the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-statefulsets) for more details.

I'm going to close this, but feel free to use our [discuss](https://discuss.elastic.co/c/orchestration/eck/79) forum for further questions.
