### ISSUE TITLE
Change ES version validation

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#4951]
In `validUpgradePath` we validate whether the current version is upgradable to the proposed version. Right now, we specify anything that's greater or equal to `7.4.0` to be upgradable to `8.x`:

https://github.com/elastic/cloud-on-k8s/blob/4aa7e519365a0b7be5080f85da3f30c6c5e0a978/pkg/controller/elasticsearch/version/supported_versions.go#L37-L42

 But based on [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-upgrade.html) it should only be `7.16.x`.

**Comment by thbkrkr** [comment]
Closed in #5075.
