### ISSUE TITLE
Stop using transient settings as of 7.16

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4997]
Transient cluster settings are deprecated as of 7.16. https://github.com/elastic/elasticsearch/pull/78794

We should stop using them starting with certain cut off version and either consider persistent settings or see if we can remove the call to the settings API. I am specifically thinking of the settings calls for allocation filtering during data migrations that we won't need anymore once we implement the Node Shutdown API as proposed in https://github.com/elastic/cloud-on-k8s/pull/4597

There is the question how we are going to migrate from one form to another. E.g. assuming we start using persistent settings with 7.16 and we disabled allocations in 7.15 with the transient version of the setting. In this case we would have to check for both options when removing settings and only set them as persistent settings. 

We should also investigate which steps are necessary before upgrading to 8.0: e.g. do we need to remove all transient settings before an upgrade to 8.0 can succeed? Or will the upgrade work and we will just get warnings?

**Comment by david-kow** [comment]
As per https://github.com/elastic/elasticsearch/issues/80556, depreciation of transient settings is reverted. Given that, we should decide whether we want to:
1. do nothing and close this until transient settings are being deprecated again, or
2. use the `7.16.x`->`8.x` "opportunity" to remove transient settings from ECK-managed clusters as explained in my previous comment.


`2.` is compelling because we are possibly saving ourselves from future trouble, but we can't be sure how depreciation and removal of transient settings feature will work. Maybe they will just disappear and no unsetting/removal will be needed on our side. In such a case the implementation work would be wasted.

Given that I'd be inclined to do nothing at this time. Thoughts?

**Comment by pebrc** [comment]
I think we have two scenarios: new ES clusters and upgraded clusters. 

For new clusters starting with ES `7.15.2` we will not longer set any transient settings thanks to the node shutdown API. 

For clusters upgraded from any version < `7.15.2` or clusters originally orchestrated by an ECK version <`2.0` we will end up with a left-over transient setting in cluster state like this: 

```json
 "transient": {
    "cluster": {
      "routing": {
        "allocation": {
          "exclude": {
            "_name": "none_excluded"
          }
        }
      }
    }
  }
```

Given that we don't know the deprecation route Elasticsearch is going to take to remove transient settings I think there is a lot in favour of your argument @david-kow of doing nothing for now. However it feels like we are not cleaning up after ourselves right now and if the deprecation strategy Elasticsearch choses does involve users doing something to fix the situation then we would need to address the issue eventually anyway in the operator. 

So maybe one approach to address the problem would be to `null` this setting on any cluster that is running `7.16.x`. Why `7.16.x`? Once all nodes are on `7.16.x` we know for sure node shutdown is in use and we know for sure everyone wanting to upgrade to `8.x` has to go through `7.16.x`. This approach would not be without gaps however as an upgrade to `8.0` is also possible from an ECK `1.9` installation in which case we would miss the opportunity. I wonder if this is however an acceptable tradeoff as our recommendation will be to upgrade to ECK `2.0` before upgrading the stack to `8.0` due to `8.0` specific adjustments we will ship in `2.0`.

**Comment by david-kow** [comment]
@pebrc +1 to nulling transient settings on `7.16.x` in ECK `2.x`. Regarding "do nothing" option, I forgot about the deprecation logging that will be polluting ES as soon as depreciation happens.
