### ISSUE TITLE
Release notes should include enhancements made in the documentation

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#5006]
Today, unless someone is looking through PRs or going through the entire documentation once in a while, it's difficult to find about new content added to the docs. This is especially true for any improvements we make other than related to new features. 

We could make it more discoverable by including relevant doc changes in the release notes.

**Comment by alaudazzi** [comment]
@david-kow In ESS / ECE docs, when a PR deserves a mention in the release notes we use the label @Public and add the block **Release Notes** in the root comment of the PR, like in this example:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/46651782/142421476-46357b9a-bf0a-4266-9109-6f2473ab0d82.png">

Could we use a similar approach?
