### ISSUE TITLE
Expose recipes in ECK documentation

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#5012]
As per offline conversation with @naemono, it would be helpful if at least some of [config/recipes](https://github.com/elastic/cloud-on-k8s/tree/master/config/recipes) were discoverable from ECK docs. Right now they are fairly hidden from users that might be interested.

**Comment by nicenemo** [comment]
Mentioning a few working and up to date recipes in the documentation would be so helpful.
For learning and expirementing having a secure cluster that works set up in minutes is so useful.

It is great to have a secured Elasticsearch/Kibana running but as long as you cannot acces it from the outside it is a bit pointless. Portforwarding via kubectl does not count.

You can find countless examples on the internet that instruct to disable security and https. No! no! NO!, I want security features and xpact etc.

A sensible example should be provided by Elastic, linked in the documentation and easy to find via Google. (you know for search ;) ) As Kubernetes Noob I did not get ECK based Elasticsearch or Kibana working working with Traefik out of the box yet. Either I need some guidance or It does not work and I need to open a port directly was my tought. I have ECK running in a recent default K3S environment that includes Traefik out of the box. In 2019 I did manage to run multipe nginx services with letsencrypt etc, so I am not completely stupid, I hope.

Based on 2019-2020 experience with K3S  onnon elasticsearch examples in blogposts:

* Probably my K3S Traefik combination is either too new or to old for the provided recipe and I need to change the recipe or use an upgraded Traefik and disable the one provided out of the box or upgrade the sample recipe to the newest standard for Kubernetes. Now 2021-11-15, It seems the recipe is outdated and it looks quite complex.

A recipe that just opens Elasticsearch on one DNS entry and Kibana on another would be nice.
Is that split up for Elasticsearch in different configurations for POST/DELETE etc really needed for a simple example?
If so explain why that is needed.

**Comment by pebrc** [comment]
The reason we have recipes separate from what we call `samples` is that that they are hard to test in automated fashion but might still be useful to users. 

If we make the recipes more prominent we should only do so for those that we test on a regular basis and can ensure they work. This currently only applies for the Elastic Agent and Beats recipes.

**Comment by alaudazzi** [comment]
Discussed this issue with @david-kow, here are the meeting notes:
- The recipes that are regularly tested were transferred to the docs. This is the case for [Elastic Agent](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-configuration-examples.html) and [Beats](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-beat-configuration-examples.html).
- To publish the other recipes we have two options:
  1. Either we test them on a regular basis, make sure they work with the latest operator, and then we publish them. In which case we suggest to continue in a separate issue and close this one.
  2. Or we publish them with a disclaimer saying something like "_please note these recipes are not regularly tested_".

@pebrc your opinion on this would help

**Comment by pebrc** [comment]
> Either we test them on a regular basis

I think some of the recipes are quite hard to test automatically. At least it would mean considerable effort to get there. I think it would be OK to link to them from our documentation with a disclaimer. We can still work towards testing more of them (separate issue) and remove the disclaimers one by one. 

The downside of this approach is of course that we expose users and customers to examples that might not work and this can lead to frustration. But I would argue we are already doing that by having them in our GitHub repo, we are just changing the visibility with the proposed links.

**Comment by naemono** [comment]
Agreed with @pebrc .  I think the upside of having these more visible outweighs the downside of them potentially not being 100% working at all times.  A disclaimer would help alleviate that, as mentioned by pebrc, and having more visibility means we would likely be notified via GH issue if one of the recipes/examples isn't working as expected.

**Comment by alaudazzi** [comment]
Here is a proposal on how we can expose these recipes from the product doc pages.

1. Create a new section **Recipes** in [Orchestrating Elastic Stack applications](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestrating-elastic-stack-applications.html), similarly to what we do in the [ES guide](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/recipes.html).
2. Add intro + disclaimer
    
   > This section includes recipes that provide configuration examples for some common use cases.
   >     WARNING: The recipes in this section are for illustration purposes only and should not be considered to be production-ready.

3. Link to the recipes that are documented:
    - [gclb](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/gclb)
    - [istio-gateway](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/istio-gateway)
    - [logstash](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/logstash)
    - [maps](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/maps)
    - [psp](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/psp)
    - [traefik](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/traefik)
4. Leave out the recipes for which there is only a YAML file with no docs
   - [apm-server-jaeger](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/apm-server-jaeger)
   - [associations-rbac](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/associations-rbac)
   - [autoscaling](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/autoscaling)

If this makes sense, I’ll go ahead and update the docs.

**Comment by naemono** [comment]
I would be fine with this approach.  From a discussion we had:

1. I think noting, comparing/contrasting these to the actual 'tested' [samples](https://github.com/elastic/cloud-on-k8s/tree/main/config/samples) may make sense as well
2. I agree with the approach of leaving out the 3x linked in bullet point 4.

Overall 👍
