### ISSUE TITLE
Dedicated/On-Demand ARM Jenkins build node

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5015]
## Proposal

https://devops-ci.elastic.co/job/cloud-on-k8s-release-build/view/tags/

Our build times are steadily growing from initially being ~18 minutes, up to ~45 minutes on the most recent build.

https://devops-ci.elastic.co/job/cloud-on-k8s-release-build/view/tags/job/1.9.0-bc2/

Most of our time is being spent in the `Build and push Docker image` step, and further investigation shows that the largest piece of the time is being spent building our binary on arm64 (this is around 15 mins):

```
05:36:51  #17 [linux/arm64 builder 7/7] RUN CGO_ENABLED=0 GOOS=linux 		go build       ...
05:52:29  #17 DONE 943.1s
```

I propose we work with our infra team to get a dedicated/on-demand arm node on which to build our arm images.  In my understanding, some other teams already take this approach to building arm.

Feels like the steps would be
- [ ] Work with Infra team to allow on-demand arm nodes
- [ ] Make CI/jenkins changes to have a build that is labeled properly for ARM.

**Comment by thbkrkr** [comment]
Closing because since we moved to Buildkite we are using a native ARM VM to build the ARM Docker image. The build takes on average just under 4 minutes.
