### ISSUE TITLE
Cannot access ES  when ruuning CURL 

### ISSUE THREAD

**Issue by balla18** [elastic/cloud-on-k8s#5020]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
I deployed ECK using this "https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html", but faced an error when trying to curl not sure why it happened. 
**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ? EKS
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```
Command: curl -u "elastic:$PASSWORD" -k "https://quickstart-es-http:9200"
curl: (6) Could not resolve host: quickstart-es-http

**Comment by balla18** [comment]
Hi i tried to deploy es using the quickstart setup, but when I'm trying to curl I am getting this error,

curl -u "elastic:$PASSWORD" -k "https://quickstart-es-http:9200"
curl: (6) Could not resolve host: quickstart-es-http

**Comment by naemono** [comment]
Hi @balla18.  We'd be more than happy to assist.  If you look at this section of the documentation

https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html#k8s_request_elasticsearch_access

Under Section `2.`, you are attempting the section labeled `From inside the Kubernetes cluster`.  It sounds as though you are attempting to access this from outside of the cluster, and you'll need to `port-forward` to do that successfully.   Check the section right after that labeled `From your local workstation, use the following command in a separate terminal`

Specifically, you'll need to

```bash
kubectl port-forward service/quickstart-es-http 9200
# then
curl -u "elastic:$PASSWORD" -k "https://localhost:9200"
```

If you are interested in accessing from the public internet, you'll need to follow the directions here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-services.html#k8s-allow-public-access

**Comment by balla18** [comment]
Thank you @naemono naemono, it worked, I have created a load balancer to access it over the internet. Now I got my ELB created (using EKS) but when i am trying to access with my load balancer I cannot get the connection, the page is loading and doesn't show anything, tried https://LOADBALANCER_IP and http://LOADBALANCER_IP

**Comment by balla18** [comment]
##### here is the snippet of my code##


apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-eck
  namespace: elastic-system
spec:
  version: 7.15.1
  podDisruptionBudget:
    spec:
      minAvailable: 1
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: elastic-eck
  http:
    service:
      spec:
        # expose this cluster service with a LoadBalancer
        type: LoadBalancer

**Comment by pebrc** [comment]
Can we move this discussion to https://discuss.elastic.co/c/orchestration/eck/79, which is our forum for community support and reserve GitHub for bug reports and feature requests. Thank you!
