### ISSUE TITLE
PriorityClassName not supported

### ISSUE THREAD

**Issue by timbrd** [elastic/cloud-on-k8s#5021]
My k8s cluster is running several elasticsearch clusters - a production and 3 development clusters. 
I would like to define a [priority class](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) to my elasticsearch pods, to prioritise the production cluster when resources are low.

In the [api reference](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-elasticsearch-k8s-elastic-co-v1.html) of the elasticsearch crd I could not find a way to set a priority class, so I guess it is currently unsupported?

**Comment by pebrc** [comment]
Each [node set ](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-elasticsearch-k8s-elastic-co-v1.html#k8s-api-github-com-elastic-cloud-on-k8s-pkg-apis-elasticsearch-v1-nodeset) contains a regular Kubernetes `podTemplateSpec` where you can define the `priorityClassName`.
