### ISSUE TITLE
After the source code is compiled, initContainter appears and has been waiting for the transport certificates ，pod is always in init   --current version：1.4

### ISSUE THREAD

**Issue by haojieupup** [elastic/cloud-on-k8s#5028]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by pebrc** [comment]
I am not sure I am following what seems to be problem. 

> After the source code is compiled

Are you compiling the operator yourself? Why? Please use a release version of the ECK operator. You can find the latest version here https://www.elastic.co/downloads/elastic-cloud-kubernetes or linked from our Github releases page. 

>  --current version：1.4

Again I am not sure I understand. Are you running version 1.4 of the ECK operator? 

Maybe you could explain a bit more what the problem is.

**Comment by haojieupup** [comment]
Sorry, due to environmental issues, we can only use the 1.4 version of the operator. I did not use the official elastic-operator image. I pulled the 1.4 version of the source code on github. After compiling by myself, the pod created by the operator has been In the init state, the log of the container is stuck waiting for the transport certificates

**Comment by thbkrkr** [comment]
So you compile ECK 1.4 and now ES pods are stuck. We lack information (operator logs, pod logs, es manifest, ...) to help debug your problem. (You could use [eck-diagnostics](https://github.com/elastic/eck-diagnostics) to collect this information.)

We try to keep GitHub issues only for actual bug reports and feature requests for the official Elastic operator. Can we please continue in our community discussion forum: https://discuss.elastic.co/c/orchestration/eck?
