### ISSUE TITLE
Increase E2E tests retry timeout

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#503]
It seems like a few E2E tests have failed for not retrying long enough:

- https://cloud-ci.elastic.co/view/k8s-operators/job/k8s-operators-e2e-tests/10/console (pod not yet running)
- https://cloud-ci.elastic.co/view/k8s-operators/job/k8s-operators-e2e-tests/8/console (secrets not there yet)

It's probably safe to increase a little bit the current test timeout to avoid these situations.

**Comment by thbkrkr** [comment]
I close this, given the timeout has been increased and some flaky E2E tests have been fixed.
