### ISSUE TITLE
4h timeout reached on cloud-on-k8s-e2e-tests-ocp

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#5030]
Sometimes the 4h timeout per package is reached on the job [`cloud-on-k8s-e2e-tests-ocp`](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp). So far this has only appeared on OCP 4.4.x and 4.5.x.

[cloud-on-k8s-e2e-tests-ocp/640](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/640/testReport/) OCP `4.5.41` :red_circle:
[cloud-on-k8s-e2e-tests-ocp/650](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/650/testReport/) OCP `4.4.33` :red_circle:
[cloud-on-k8s-e2e-tests-ocp/651](https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-ocp/651/testReport/) OCP `4.5.41` :red_circle:

Why?

I compared the tests execution times between job executions 650 (:red_circle: 4h), 651 (:red_circle: 4h), 652 (:heavy_check_mark: 3h45) and 653 (:heavy_check_mark: 3h36).
![2021-11-09-123820_1115x862_scrot](https://user-images.githubusercontent.com/582883/140918953-3a783a26-aae7-449b-bd64-e9c5fe891967.png)

In execution 650, `TestCustomHTTPCA` took 1256s (+16min) and `TestMutationWithLargerMaxUnavailable` 2300s (+33min).
In execution 651, `TestMutationLessNodes` took 1236s (~+16min) ans `TestMutationResizeMemoryDown` 535s (+1min45).

We see that sometimes just 1 or 2 tests took more time (+100s, +1000s or +2000s), for a reason still unknown and this is enough to reach the 4h timeout. I think we could just increase the timeout to 6h? :man_shrugging: for now while continuing to investigate what the root cause is.

**Comment by pebrc** [comment]
Closed through #5042
