### ISSUE TITLE
Revisit Filebeat default memory requests/limits

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5036]
We are currently defaulting to 200Mi. However the Filebeats ingesting e2e test cluster data into our monitoring were constantly running into OOM. We should reevaluate whether the current default is still enough with recent version of Filebeat/Metricbeat.

**Comment by barkbay** [comment]
It might be a good candidate for the [VPA](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#components-of-vpa) recommender ?
But agreed, we still need to check (with the Beats folks ?) what would be some sane defaults.
