### ISSUE TITLE
E2E: Elasticsearch cluster health should not have been red during mutation process

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5040]
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-snapshot-versions/446//testReport
```
=== RUN   TestMutationResizeMemoryUp/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process
    steps_mutation.go:128: 
        	Error Trace:	steps_mutation.go:128
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 9
        	Test:       	TestMutationResizeMemoryUp/Elasticsearch_cluster_health_should_not_have_been_red_during_mutation_process
    steps_mutation.go:130: Elasticsearch cluster health check failure at 2021-11-10 05:36:06.457907754 +0000 UTC m=+5717.933233476: cluster health red
```

Variations of this error have been observed on recent 7.16 and 8.0 snapshot builds for similar mutation test cases.

The problem is that we start with a rolling upgrade  while Elasticsearch is still in the process of creating internal indices.
#4998 should fix the issue but in the mean time this issue serves to document the problem. 

![allocation-problem](https://user-images.githubusercontent.com/697790/141147066-b9aa0e9b-702d-4bce-8d3e-fd40532aa63e.png)

Sequence of events leading to the error:
1. e2e test runner checks for green cluster health OK
2. e2e test running triggers rolling upgrade
3. we disable replica shard allocation on the cluster
4. first Pod is deleted in K8s and connection draining via pre-stop hook begins ~50 secs
5. Elasticsearch starts allocating an internal index like ILM history that it had not allocated previously
6. It picks the already doomed Pod as the node to allocate to and because replica shard allocation is disabled only a primary is allocated
7. Pod is being terminated and cluster goes RED

Problems are twofold:
* we don't have a notion of Elasticsearch being ready in the sense that all internal indices have been successfully allocated. Cluster goes green even when a few internal indices have not been created yet
* Elasticsearch does not have a notion that we are going to take down a node or in fact already have lit the fuse for the destruction of a Pod (this will be addressed by the Node Shutdown API coming in #4998)

**Comment by pebrc** [comment]
I did a bit more research and I think I understand better why these things happen (with some open questions remaining) 

> why are these two data streams (`logs-deprecation.elasticsearch-default` and something like `"ilm-history-5`) not there initially and only created at this unfortunate point in time? 

They are created lazily on first use through index templates. And there is a chain reaction going on. As soon as the first deprecation warning needs to be written into the deprecation log the deprecation data stream gets created. That data stream has an ILM policy attached to it so this triggers the first write to the ILM history data stream with the same effect. 

> what is the deprecation warning that triggers this first write? 

```
The HTTP status code for a cluster health timeout will be changed from 408 to 200 in a future version. Set the [return_200_for_cluster_health_timeout] query parameter to [true] to suppress this message and opt in to the future behaviour now.
```

As it happens these mutation tests run a bunch of health checks during the mutation to ensure the cluster always stays green. I assume these trigger the deprecation warning. 

This is also where things get a bit unclear because the operator is also running continuous health checks against the cluster in 30 second intervals. Since https://github.com/elastic/cloud-on-k8s/pull/5041 we wait an extra 30 seconds so I would assume that the operator has enough time to hit the Elasticsearch cluster at least once with a health check, but maybe it is just bad timing and actually either of them could be triggering this warning. 

I wonder if one way to fix these tests is to set that `return_200_for_cluster_health_timeout` query parameter on 7.16 to silence the warning.

**Comment by pebrc** [comment]
Another option would be to disable deprecation logging to an index with `cluster.deprecation_indexing.enabled: false`

**Comment by pebrc** [comment]
I think this specific problem might solve itself for 8.0 as the change causing this seems to have been reverted yesterday https://github.com/elastic/elasticsearch/commit/89bbac9216fb7ca2387bdf49a1a59373784ea2da

**Comment by barkbay** [comment]
I spent a fair amount of time trying to understand and to reproduce this one without success 😬 (on `7.16` or `8.0`, using the e2e job, running all the `Mutate*` tests ... it did not happen a single time, I'm pretty sure I'm missing something obvious... 😞 )

I believe we are supposed to be using the node shutdown API since #4597? I would expect it to avoid this situation, unless the shutdown API allows a node to be restarted even if a primary shard is still initializing?

> I wonder if one way to fix these tests is to set that return_200_for_cluster_health_timeout query parameter on 7.16 to silence the warning.

If the failure is related to indices/datastreams not under the control of the e2e job, should we then not ignore them? _(assuming the shutdown API does not prevent this situation)_. We could use either an allowlist or a blocklist to filter on the primary shards (using `/_cat/shards` here should be ok ?)

**Comment by pebrc** [comment]
> I believe we are supposed to be using the node shutdown API since #4597? I would expect it to avoid this situation, unless the shutdown API allows a node to be restarted even if a primary shard is still initializing?

I think even with the node shutdown API we can construct a sequence of events that leads to this failure. If we assume that the node shutdown API will allow are restart of a node even if it holds the only copy of a shard. 

1. we start the rolling upgrade process by disabling replica allocation
2. we call the `_cluster/health` API with a timeout triggering the deprecation warning
3. the primary of the deprecation data stream's backing index is allocated
4. we restart the node on which that primary resides
5. the cluster goes red

> If the failure is related to indices/datastreams not under the control of the e2e job, should we then not ignore them? (assuming the shutdown API does not prevent this situation). We could use either an allowlist or a blocklist to filter on the primary shards (using /_cat/shards here should be ok ?)

Yes probably, we would need to build a custom health check for that. Currently we are just using the the health indicator returned by Elasticsearch which includes all indices/data streams.

**Comment by pebrc** [comment]
Actually I realise that my theory about node shutdown and how we can still see `red` cluster health was build on an incorrect assumption. We do not disable replica allocation anymore during rolling upgrades when using the node shutdown API. That's the whole point of using this new API: to have a less blunt tool to manage the upgrade process. What remains a mystery to me and requires further investigation is why only a primary of the deprecation index is allocated when our e2e test fails.

**Comment by pebrc** [comment]
I am closing this as the issue in Elasticsearch responsible for this has been fixed. In addition the theory about cases where this might still happen with node shutdown API in use was incorrect.
