### ISSUE TITLE
cloud-on-k8s-pr-full uses an unlicensed development build of ECK

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#5065]
Since we switched the `cloud-on-k8s-pr-full` job to use the master GKE pipeline (#5045), something is wrong. Builds failed on `TestElasticMapsServerCrossNSAssociation` (ex: [67](https://devops-ci.elastic.co/job/cloud-on-k8s-pr-full/67/testReport/junit/github/com_elastic_cloud-on-k8s_test_e2e_ems/TestElasticMapsServerCrossNSAssociation_ElasticMapsServer_deployment_should_be_created/) or [73](https://devops-ci.elastic.co/job/cloud-on-k8s-pr-full/73/testReport/junit/github/com_elastic_cloud-on-k8s_test_e2e_ems/TestElasticMapsServerCrossNSAssociation_ElasticMapsServer_deployment_should_be_created/)) due to:
```
{
    "log.level": "info",
    "@timestamp": "2021-11-21T00:40:21.597Z",
    "log.logger": "license",
    "message": "This is an unlicensed development build of ECK. License management and Enterprise features are disabled",
    "service.version": "2.0.0-SNAPSHOT+e2ce6b0a",
    "service.type": "eck",
    "ecs.version": "1.4.0"
}
```

**Comment by pebrc** [comment]
I _think_ this means that the build did not embed the necessary public key into the binary that is required for non-trial license checks.

**Comment by thbkrkr** [comment]
It's still unclear what happened but the last build was successfully, hence closing. One suspicious thing is that the failed builds didn't build a new operator Docker image and instead pulled an already published one. I think this is related to the fact that I did a `git push -f`.
