### ISSUE TITLE
Reuse private key for CA rotation

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#507]
When rotating a cluster CA, we could reuse existing private keys so that the generated cert keeps using the same associated public key.

**Comment by chimeworld** [comment]
I'd like to work on this if it's still an issue.

**Comment by sebgl** [comment]
Go for it @chimeworld!
I think the general idea is that if the CA cert is expired, we want to renew it with a new expiration date, but keep the existing private and public keys so clients can keep using the same CA cert.

**Comment by chimeworld** [comment]
Can you point me where I should be looking to fix this?

**Comment by sebgl** [comment]
This is where CAs are renewed: https://github.com/elastic/cloud-on-k8s/blob/883f45d16f8f5f4f09474fb2ada0cafac33d797c/pkg/controller/common/certificates/ca_reconcile.go#L79
Following function calls from this, we end up creating a new CA with new private and public keys.

**Comment by chimeworld** [comment]
I'll be working on this in the next few days/weeks.
