### ISSUE TITLE
Remove deprecated Stack Monitoring settings 

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#5083]
We should remove `xpack.monitoring.elasticsearch.collection.enabled` and `xpack.monitoring.collection.enabled` from our Stack Monitoring configuration. I believe (to be double checked) that the default behavior is the one we expect. Otherwise `7.16.0-SNAPSHOT` emits the below:

```
[xpack.monitoring.elasticsearch.collection.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
...
[xpack.monitoring.collection.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
```

**Comment by thbkrkr** [comment]
I've had the confirmation that these settings are not needed and that the monitoring documention has been wrong for some time.

https://github.com/elastic/elasticsearch/pull/77409#issuecomment-987311137
