### ISSUE TITLE
Move to `vX.X.X` tags for easier go module imports

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#5095]
Go modules rely on a `vX.X.X` tag naming scheme. Currently we use an `X.X.X` scheme, which does not make it easy to import this project as a dependency in other projects.

Let's move to `vX.X.X` for the next tag.

Additionally, we should probably care about what we do once migrating to `v2.x`, which seems far from trivial: https://donatstudios.com/Go-v2-Modules.

**Comment by pebrc** [comment]
Reading through the article linked I don't see a strong need for us to move everything into a `v2` directory which is one of the approaches outlined. I think one the reasons for doing this are non-module aware versions of Go consuming the ECK operator as a library. There are very few examples of other projects referencing the ECK operator:

https://github.com/search?p=1&q=%22github.com%2Felastic%2Fcloud-on-k8s%22+filename%3Ago.mod&type=Code

But I would say that it is probably OK to just move to the new tagging scheme with `v2.0.0` as we can assume we do not have users that develop in `GOPATH` mode and need the directory structure to match the module version.

**Comment by mrkm4ntr** [comment]
Hi. Non-module aware versions are still used in v2.X.X. Is there any plan to use module aware versions?
