### ISSUE TITLE
ECK dump documentation refers to the wrong script URL

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#5096]
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-take-eck-dump.html#k8s-take-eck-dump links to https://raw.githubusercontent.com/elastic/cloud-on-k8s/master/support/diagnostics/eck-dump.sh, which does not work.

We should update that doc page to refer to the newer diagnostic tool: https://github.com/elastic/eck-diagnostics.

**Comment by naemono** [comment]
#5102 resolved this.  closing
