### ISSUE TITLE
Error: pull image "docker.elastic.co/eck-dev/eck-operator-thb:1.7.0-SNAPSHOT-ff98c86"

### ISSUE THREAD

**Issue by pabloandrei** [elastic/cloud-on-k8s#5151]
Hello.

After applying the sample described at https://github.com/elastic/cloud-on-k8s/blob/1.9.0/config/all-in-one.yaml, I am getting the error below.

Would they know how to inform the workaround?
Sincereley, Pablo

* ECK version: 1.9.0

* Kubernetes information: microk8s (ubuntu)

* kubectl version: Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.7-3+7700880a5c71e2", GitCommit:"7700880a5c71e25c44491ef5c7d7fb30527d8337", GitTreeState:"clean", BuildDate:"2021-11-17T22:07:23Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

* Resource definition: https://github.com/elastic/cloud-on-k8s/blob/1.9.0/config/all-in-one.yaml

* Logs:
```
Failed to pull image "docker.elastic.co/eck-dev/eck-operator-thb:1.7.0-SNAPSHOT-ff98c869": rpc error: code = NotFound desc = failed to pull and unpack image "docker.elastic.co/eck-dev/eck-operator-thb:1.7.0-SNAPSHOT-ff98c869": failed to resolve reference "docker.elastic.co/eck-dev/eck-operator-thb:1.7.0-SNAPSHOT-ff98c869": docker.elastic.co/eck-dev/eck-operator-thb:1.7.0-SNAPSHOT-ff98c869: not found
```

**Comment by naemono** [comment]
Could you please let us know what documentation you were following that was referencing this file?  Recent documentation (since 1.7) indicates using 2 separate files

https://www.elastic.co/guide/en/cloud-on-k8s/1.9/k8s-deploy-eck.html

```bash
kubectl create -f https://download.elastic.co/downloads/eck/1.9.0/crds.yaml
kubectl apply -f https://download.elastic.co/downloads/eck/1.9.0/operator.yaml
```

Let us know if we can go ahead and close this issue, thanks.

**Comment by thbkrkr** [comment]
Sorry for the inconvenience, this file was accidentally committed.

**Comment by pabloandrei** [comment]
> Could you please let us know what documentation you were following that was referencing this file? Recent documentation (since 1.7) indicates using 2 separate files
> 
> https://www.elastic.co/guide/en/cloud-on-k8s/1.9/k8s-deploy-eck.html
> 
> ```shell
> kubectl create -f https://download.elastic.co/downloads/eck/1.9.0/crds.yaml
> kubectl apply -f https://download.elastic.co/downloads/eck/1.9.0/operator.yaml
> ```
> 
> Let us know if we can go ahead and close this issue, thanks.

Exactly this...

**Comment by pabloandrei** [comment]
> ```shell
> kubectl apply -f https://download.elastic.co/downloads/eck/1.9.0/operator.yaml
> ```

Ill try now...

**Comment by pabloandrei** [comment]
After uses of the new merge, I get other problem:

`0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`

![image](https://user-images.githubusercontent.com/16004192/145572815-6a804260-b1e3-45f6-b278-7ba483dfe954.png)

**Comment by pabloandrei** [comment]
> After uses of the new merge, I get other problem:
> 
> `0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`
> 
> Follow below my sequence of commands:
> 
> ```
> > sudo snap install microk8s --classic
> > microk8s enable dns
> > microk8s enable storage
> 
> 
> > microk8s kubectl create -f https://download.elastic.co/downloads/eck/1.9.0/crds.yaml
> > microk8s kubectl apply -f https://download.elastic.co/downloads/eck/1.9.0/operator.yaml
> 
> 
> cat <<EOF | microk8s kubectl apply -f -
> apiVersion: elasticsearch.k8s.elastic.co/v1
> kind: Elasticsearch
> metadata:
>   name: quickstart
> spec:
>   version: 7.16.0
>   nodeSets:
>   - name: default
>     count: 1
>     config:
>       node.store.allow_mmap: false
> EOF
> ```
> 
> ![image](https://user-images.githubusercontent.com/16004192/145572815-6a804260-b1e3-45f6-b278-7ba483dfe954.png)

After reinstall Microk8s, the problem no more occurred.
