### ISSUE TITLE
Document namespace setup 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5170]
The ECK operator runs by default in the `elastic-system` namespace. We do not document the expectation that users should not deploy their workloads into that namespace.  

We could also add a sentence guiding beginners to chose a namespace for their workloads rather then using the `default` namespace (which is fine for experimentation).

**Comment by alaudazzi** [comment]
@pebrc Here is suggestion for the doc update.

On the page https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html, we could slightly reword step 1 with something like this:

Step 1 Install custom resource definitions
[command line]

Step 2 Install the operator with its RBAC rule
[command line]
**The ECK operator runs by default in the `elastic-system` namespace. It is recommended that you choose a dedicated namespace for your workloads, rather then using the default namespace.**

NOTE: If you are running a version of Kubernetes before 1.16 you have to use the legacy version of the manifests:
[command lines]

Step 3 Monitor the operator logs:
[command line]
