### ISSUE TITLE
elasticsearch v1alpha1 loosing configuration after upgrading eck-operator

### ISSUE THREAD

**Issue by Lucaber** [elastic/cloud-on-k8s#5181]
I noticed an issue with the old `v1alpha1` apiVersion of `elasticsearches.elasticsearch.k8s.elastic.co` while upgrading eck-operator.

After upgrading to the new operator, my existing elasticsearches are partially loosing its configuration.
All fields which where previously of `type: object` are now missing after applying the CR.

This propably happened by upgrading the CRD version from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`.

The new apiVersion `v1` of `elasticsearches.elasticsearch.k8s.elastic.co` has all `object` fields correctly marked with `x-kubernetes-preserve-unknown-fields: true`. This is missing on the old `v1alpha1` versions.

I noticed this issue because my `sysctl` initContainer went missing after upgrading the operator.
After simply changing the apiVersion to `v1` (and nothing else needed in my case) my initContainer is back.

**Comment by pebrc** [comment]
The `v1alpha1` API version was use in the alpha version of the operator and there is no direct upgrade path from those early versions to the `v1beta1` or `v1` versions. 

We have however some guidance on how to upgrade here: https://www.elastic.co/guide/en/cloud-on-k8s/1.0-beta/k8s-upgrading-eck.html#k8s-upgrading-eck

**Comment by Lucaber** [comment]
Ups, I didnt upgrade from `v1alpha1` but from `v1beta1`. I was already on a "stable" 1.x.x operator version.

**Comment by pebrc** [comment]
Ah OK, I see you have adjusted your original post accordingly. On which version of the operator did you start and to which version were you upgrading?

**Comment by Lucaber** [comment]
`1.0.0` to `1.9.1`. I found #4489 but everything mentioned there worked flawlessly for me.
Actually, the initial automatic CR "upgrade" from v1beta1 to v1 after applying the new crd worked.
But later reapplying this CR in v1beta1 does not (via a helm upgrade).
The first upgrade probably works because the schema isnt checked on crd upgrade.
