### ISSUE TITLE
ECK >= 1.9.x failing to run with webhooks enabled in Openshift <= 4.6

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5191]
Since enabling webhooks within Openshift within ECK, it was found that Openshift 4.6 and below have issues where they mount the Certificates in a location that doesn't align with the Operator SDK, and as such, the operator goes into a `CrashLoopBackoff`.

Bug fix reference in 4.7 release notes:
https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-bug-fixes

Bugzilla reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1879248

We will need to find a solution for supporting these older versions of openshift and the webhook, either with a code fix, or simply disabling the webhook within openshift.

**Known workarounds as of now:**
- remove `--enable-webhook` flag from the list of args in the `elastic-operator` container via the yaml definition for the operator within the Openshift UI. (Operators -> Installed Operators -> Elasticsearch (ECK) Operator -> Operator details -> YAML)
- Upgrade Openshift to version 4.7

![146973539-f473a8a3-0e13-4b60-9547-e4d0e6ebf144](https://user-images.githubusercontent.com/697790/146982205-1ae3727a-c8bd-41ae-82f3-85e7217d5ecd.png)

**Comment by pebrc** [comment]
Closing this as there are two workarounds and we are not planning any additional fix for this.
