### ISSUE TITLE
APM: e2e: verify that events show up in Elasticsearch

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#520]

**Comment by sebgl** [comment]
@nkvoll can you comment a bit more on what you have in mind with this issue?

**Comment by pebrc** [comment]
The current APM e2e tests only check that the events we sent to the APM server are accepted. This issues is about actually checking in Elasticsearch that APM server is able to forward the event via the configured output to Elasticsearch.

**Comment by pebrc** [comment]
Relevant existing test code: https://github.com/pebrc/cloud-on-k8s/blob/4f8c29176442bdd23a3c06fd439814374410b29b/operators/test/e2e/test/apmserver/checks_apm.go#L84:L108
