### ISSUE TITLE
Rolling upgrade should handle data tiers

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#5228]
Running a mixed version cluster may lead to some issues, for example with searchable snapshot and ILM, see an example here: https://github.com/elastic/elasticsearch/issues/77007#issuecomment-909076823

The [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/rolling-upgrades.html#rolling-upgrades) explicitly states that data nodes should be upgraded in the following order:

1. frozen
2. cold
3. warm
4. hot

For now ECK only ensures that master nodes are upgraded once all the data nodes are up-to-date: https://github.com/elastic/cloud-on-k8s/blob/eb46da9af31fe97348792332ae1afec938181307/pkg/controller/elasticsearch/driver/upgrade_predicates.go#L354-L355
We should introduce a mechanism to upgrade data nodes in the recommended order.

**Comment by barkbay** [comment]
The operator would still allow some new nodes, with a more recent version, to be added/started while nodes in other tiers have not been upgraded yet.
For example it would be the case if the user upgrades the ES version while adding some nodes at the same time. This is because the cluster is first upscaled using the most recent specification: https://github.com/elastic/cloud-on-k8s/blob/721cccfd905f43c345c7957fbfe173ea3ebb6bbf/pkg/controller/elasticsearch/driver/nodes.go#L89-L98

I think we want the user to be able to add some nodes/capacity when requested. It would then mean that, for a given tier, only the `replicas` field in the `StatefulSet` specification can be changed if other tiers with higher priorities are not fully upgraded.

**Comment by pebrc** [comment]
I wonder if it would be acceptable to really interpret this rule as a `should` rule. That means we would pick the Pods to roll respecting this recommended upgrade order in the rolling upgrade part of the code. But if a user would combine a rolling upgrade with a scale up we would accept the suboptimal upgrade order caused by the fact that we scale out first.
