### ISSUE TITLE
Elastic Agent has to trust CA of the Elasticsearch used as output

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#5250]
Today, there is no good mechanism offered by Kibana/Agent that would allow to trust a CA of Elasticsearch that Agents are sending data to. While [ca_sha256 setting](https://www.elastic.co/guide/en/kibana/master/fleet-settings-kb.html#_fleet_settings) exists, it's not useful due to https://github.com/elastic/kibana/issues/105400. The alternative that ECK-managed Agents are using right now, is to trust ES CA by copying it to `/etc/pki/ca-trust/source/anchors/` and running `update-ca-trust` which updates CA store for the entire container.

This worked so far, but in recent days Agent base image was changed in `8.0.0` from CentOS to Ubuntu. The path `/etc/pki/ca-trust/source/anchors/` is no longer correct. We need to update Agent container command to be able to handle this.

**Comment by ruflin** [comment]
@elastic/elastic-agent-control-plane For awareness, a breaking change was introduced with the image change. This should be documented at least.

**Comment by markniemeijer** [comment]
Hi, we still have the issue when we want to upgrade fleet server from 7.16.3 to 7.17.1 while our ECK operator is v2.0.0
Log of looping error pod: 2022-03-07T10:45:13.636948882Z cp: cannot create regular file '/etc/pki/ca-trust/source/anchors/': No such file or directory

Version ECK:
mark_niemeijer_cna_com@cna-g-prod-gke-elm-proxy:/tmp/Prod$ k describe pods -n elastic-system
Name:         elastic-operator-0
Namespace:    elastic-system
Priority:     0
Node:         gke-g-prod-gke-elm-b-g-prd-elm-bridge-ba090952-d176/10.165.47.16
Start Time:   Mon, 07 Mar 2022 08:43:02 +0000
Labels:       control-plane=elastic-operator
              controller-revision-hash=elastic-operator-6b46d74d6b
              statefulset.kubernetes.io/pod-name=elastic-operator-0
Annotations:  checksum/config: 31ccc507ad9eaa3f0a03cd8859ab5dff92a24610dca131e9e5c85d06d7657d99
              co.elastic.logs/raw:
                [{"type":"container","json.keys_under_root":true,"paths":["/var/log/containers/*${data.kubernetes.container.id}.log"],"processors":[{"conv...
Status:       Running
IP:           172.26.128.38
IPs:
  IP:           172.26.128.38
Controlled By:  StatefulSet/elastic-operator
Containers:
  manager:
    Container ID:  docker://1f8a740bd01a2dd7e9ed3ddf4fef63de68ed874d5fc032b37f2498cecbbaf58a
    Image:         docker.elastic.co/eck/eck-operator:2.0.0
    Image ID:      docker-pullable://docker.elastic.co/eck/eck-operator@sha256:97750a726fb4f403dfdc13f94ef85d0746db609ad4d7df1682fbf2526490e96e
    Port:          9443/TCP
    Host Port:     0/TCP
