### ISSUE TITLE
Integrate with Prometheus operator

### ISSUE THREAD

**Issue by Oliver-Sellwood** [elastic/cloud-on-k8s#5299]
It would be good if the various CRD's could also deploy prebuilt Grafana dashboards and prometheus PodMonitors and alerts to help facilitate automatic monitoring and observability of deployed clusters.

This is partially implemented for the operator itself, (at least in the helm chart there is an option to deploy PodMonitors) so I don't feel as though it's too much of a stretch to include for the operator's resources as well.

Maybe it doesn't make sense though if it's expected to use elastic native products for that?

**Comment by barkbay** [comment]
As you mentioned an Helm option already exists, but the aim is to scrape the operator metrics, not the metrics from the stack.

IIUC your proposal it would create a direct dependency on `monitoring.coreos.com` resources in the operator itself (controllers and CRDs). It feels like a big change while we already offer [a simplified way](https://www.elastic.co/blog/a-simplified-stack-monitoring-experience-in-elastic-cloud-on-kubernetes) to setup stack monitoring.

Let me know if I missed something but I'm not sure we want to go down that road given the complexity of the change.

**Comment by barkbay** [comment]
Closing, but feel free to reopen if I missed something or open a new topic [here](https://discuss.elastic.co/c/orchestration/eck/79).
