### ISSUE TITLE
Example of availability zone awareness seems to be incorrect

### ISSUE THREAD

**Issue by akazs** [elastic/cloud-on-k8s#5390]
## Bug Report

I tried out the example in the documentation (https://www.elastic.co/guide/en/cloud-on-k8s/2.0/k8s-advanced-node-scheduling.html#k8s-availability-zone-awareness-example) and it did not work.
It seems that the correct value of `node.attr.zone` should be `${ZONE}` instead of `$ZONE`, in order to make the [substitution](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_environment_variable_substitution) happen.

**Environment**

* ECK version:

	2.0.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* on premise
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2021-12-20T06:57:14Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

please refer to the example here: https://www.elastic.co/guide/en/cloud-on-k8s/2.0/k8s-advanced-node-scheduling.html#k8s-availability-zone-awareness-example

* Logs:

none

**Comment by barkbay** [comment]
Fixed in #5392, thanks !
