### ISSUE TITLE
Update supported versions (README.md)

### ISSUE THREAD

**Issue by Ziphone** [elastic/cloud-on-k8s#5609]
Seems like the README has not been updated after the release of ElasticSearch 8. Would be nice if it reflected the current state of ECK, and supported Elastic stack versions. I guess ElasticSearch 8 is supported, as it is referred in the quickstart guide(?).

**Comment by thbkrkr** [comment]
Good catch! Yes, I confirm that Elasticsearch `8.x` is well supported by ECK.
We will update the documentation. Thank you.
