### ISSUE TITLE
[Docker images] add OCI label org.opencontainers.image.source

### ISSUE THREAD

**Issue by OuesFa** [elastic/cloud-on-k8s#5611]
## Proposal

Add the following OCI label `org.opencontainers.image.source` in the docker image to indicate the source repo URL. 

**Use case. I'm using [Renovate](https://github.com/renovatebot/renovate) to update dependencies. Renovate [supports docker label `org.opencontainers.image.source`](https://github.com/renovatebot/renovate/pull/2907) to point to source and add the release notes in the created PR. I would like to leverage that for ECK/ES/Kibana images**

**Comment by pebrc** [comment]
This was added here https://github.com/elastic/cloud-on-k8s/commit/56d8edca438853d84ba032fe5112c1eb8388c8aa#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R39
