### ISSUE TITLE
'Failed to check available memory' errors

### ISSUE THREAD

**Issue by ajaynair** [elastic/cloud-on-k8s#5636]
## Bug Report
**What did you do?**
Run standard oscap xccdf eval command
 
**What did you expect to see?**
Run successfully without errors

**What did you see instead? Under which circumstances?**
A bunch of errors like the following:

```
Title   All User Files and Directories In The Home Directory Must Have Mode 0750 Or Less Permissive
Rule    xccdf_org.ssgproject.content_rule_accounts_users_home_files_permissions
E: probe_password: Failed to check available memory
E: probe_password: Failed to check available memory
E: probe_password: Failed to check available memory
E: probe_password: Failed to check available memory
E: probe_password: Failed to check available memory
Result  pass
```

**Environment**
arm64 development environment (personal computer)

* ECK version:

	insert version or git commit id here

```
[ajaynai@cav-NCN2036A06605 ~]$ oscap --version
OpenSCAP command line tool (oscap) 1.2.17
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1
```

**Comment by thbkrkr** [comment]
Hi @ajaynair,

I'm not sure to understand how it could related to ECK. I imagine you got the wrong repository?
I see that you created the same issue 6 days later in the `openscap` repository:
- https://github.com/OpenSCAP/openscap/issues/1858

Please reopen if needed.
