### ISSUE TITLE
[Docs][Bug] Upgrading ECK from `2.1.0` to `2.2.0` Causes Rolling Restart

### ISSUE THREAD

**Issue by BenB196** [elastic/cloud-on-k8s#5648]
## Bug Report
**What did you do?**

Upgrade ECK from `2.1.0` to `2.2.0`

**What did you expect to see?**

No Elasticsearch rolling restart as the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html#k8s-beta-to-ga-rolling-restart) don't have `2.2.0` listed.

**What did you see instead? Under which circumstances?**

I see Elasticsearch start a rolling restart after upgrading from `2.1.0` to `2.2.0`

**Environment**

* ECK version:

	`2.1.0` -> `2.2.0` (Helm Install)

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? yes
	* Cloud: GKE / EKS / AKS ? n/a
	* Kubernetes distribution: Openshift / Rancher / PKS ? Rancher v1.22.8+rke2r1

I'm assuming that the docs here just need to be updated to include 2.2.0

**Comment by thbkrkr** [comment]
Thanks for the report and really sorry for the omission.
