### ISSUE TITLE
Investigate root cause of "TestMutationWhileLoadTesting" random failures.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5659]
Historically end-to-end test `TestMutationWhileLoadTesting` randomly fails with a couple of networking errors every couple of weeks.  Multiple folks have taken a bit of time to investigate the failures, but the root cause, and a final resolution have not been found.  This issue is here so we can spend a more significant amount of time to fully understand why we continue to see this failure, and can remove the "hack" we put in place in #5643 .

**Comment by pebrc** [comment]
Theory: only GKE is affected. Somewhat disproven on Sep 8th when the test failed on EKS, but the vast majority of failures happen on GKE 1:60 or something like that within the last year (exact numbers are a bit hard to come by we don't have Jenkins history that far back)

Theory: `kube-proxy` in iptables mode  is responsible. Unclear: while GKE only allows iptables mode the other Cloud providers seem to at least for now also be using it per default (AKS does also not support `ipvs`, in EKS you can plugin different CNIs but `kube-proxy` is the default, overall needs more research) which does not make this the main distinguishing factor.
