### ISSUE TITLE
Unable to upgrade elasticsearch to version 8.0.0

### ISSUE THREAD

**Issue by MohammedHoche1** [elastic/cloud-on-k8s#5664]
## Bug Report
Hey, recently I decided to upgrade the ECK cluster from version 7.17.1 -> 8.0.0. However I have run into a few issues when upgrading.
Before I upgraded from the 7.17.1, I decided to upgrade the operator to version 2.2.0 and the CRD. I then decided to upgrade the elasticsearch to version 8.0.0.

Before version 2.2.0 of the operator, i was on 2.1.0.

**What did you expect to see?**
I expected the elasticsearch to upgrade to version 8.0.0 without any issues.
**What did you see instead? Under which circumstances?**
The elastic search crashed and the logs returned:
`{"@timestamp":"2022-05-11T20:36:19.492Z", "log.level": "INFO", "message":"deprecation component started", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.xpack.deprecation.logging.DeprecationIndexingComponent","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch"}
{"@timestamp":"2022-05-11T20:36:19.668Z", "log.level": "INFO", "message":"publish_address {100.64.86.229:9300}, bound_addresses {0.0.0.0:9300}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.transport.TransportService","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch"}
{"timestamp": "2022-05-11T20:36:21+00:00", "message": "readiness probe failed", "curl_rc": "7"}
uncaught exception in thread [main]
java.lang.IllegalStateException: Failed to parse mappings for index [[elastalert/FYUShuBaTyCgPwgKXAiJsw]]
Likely root cause: java.lang.IllegalArgumentException: Unknown pattern letter: t
	at java.base/java.time.format.DateTimeFormatterBuilder.parsePattern(DateTimeFormatterBuilder.java:1891)
	at java.base/java.time.format.DateTimeFormatterBuilder.appendPattern(DateTimeFormatterBuilder.java:1781)
	at org.elasticsearch.common.time.DateFormatters.forPattern(DateFormatters.java:2126)
	at org.elasticsearch.common.time.DateFormatter.forPattern(DateFormatter.java:116)
	at org.elasticsearch.index.mapper.DateFieldMapper$Builder.buildFormatter(DateFieldMapper.java:278)
	at org.elasticsearch.index.mapper.DateFieldMapper$Builder.build(DateFieldMapper.java:332)
	at org.elasticsearch.index.mapper.DateFieldMapper$Builder.build(DateFieldMapper.java:219)
	at org.elasticsearch.index.mapper.ObjectMapper$Builder.buildMappers(ObjectMapper.java:157)
	at org.elasticsearch.index.mapper.RootObjectMapper$Builder.build(RootObjectMapper.java:109)
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:99)
	at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:94)
	at org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:370)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:347)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:337)
	at org.elasticsearch.cluster.metadata.IndexMetadataVerifier.checkMappingsCompatibility(IndexMetadataVerifier.java:196)
	at org.elasticsearch.cluster.metadata.IndexMetadataVerifier.verifyIndexMetadata(IndexMetadataVerifier.java:92)
	at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:226)
	at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:213)
	at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:127)
	at org.elasticsearch.node.Node.start(Node.java:1172)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:367)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log
{"@timestamp":"2022-05-11T20:36:24.169Z", "log.level":"ERROR", "message":"uncaught exception in thread [main]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch","error.type":"org.elasticsearch.bootstrap.StartupException","error.message":"java.lang.IllegalStateException: Failed to parse mappings for index [[elastalert/FYUShuBaTyCgPwgKXAiJsw]]","error.stack_trace":"java.lang.IllegalStateException: Failed to parse mappings for index [[elastalert/FYUShuBaTyCgPwgKXAiJsw]]\nLikely root cause: java.lang.IllegalArgumentException: Unknown pattern letter: t\n\tat java.base/java.time.format.DateTimeFormatterBuilder.parsePattern(DateTimeFormatterBuilder.java:1891)\n\tat java.base/java.time.format.DateTimeFormatterBuilder.appendPattern(DateTimeFormatterBuilder.java:1781)\n\tat org.elasticsearch.common.time.DateFormatters.forPattern(DateFormatters.java:2126)\n\tat org.elasticsearch.common.time.DateFormatter.forPattern(DateFormatter.java:116)\n\tat org.elasticsearch.index.mapper.DateFieldMapper$Builder.buildFormatter(DateFieldMapper.java:278)\n\tat org.elasticsearch.index.mapper.DateFieldMapper$Builder.build(DateFieldMapper.java:332)\n\tat org.elasticsearch.index.mapper.DateFieldMapper$Builder.build(DateFieldMapper.java:219)\n\tat org.elasticsearch.index.mapper.ObjectMapper$Builder.buildMappers(ObjectMapper.java:157)\n\tat org.elasticsearch.index.mapper.RootObjectMapper$Builder.build(RootObjectMapper.java:109)\n\tat org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:99)\n\tat org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:94)\n\tat org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:370)\n\tat org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:347)\n\tat org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:337)\n\tat org.elasticsearch.cluster.metadata.IndexMetadataVerifier.checkMappingsCompatibility(IndexMetadataVerifier.java:196)\n\tat org.elasticsearch.cluster.metadata.IndexMetadataVerifier.verifyIndexMetadata(IndexMetadataVerifier.java:92)\n\tat org.elasticsearch.gateway.GatewayMetaState.upgradeMetadata(GatewayMetaState.java:226)\n\tat org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:213)\n\tat org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:127)\n\tat org.elasticsearch.node.Node.start(Node.java:1172)\n\tat org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:272)\n\tat org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:367)\n\tat org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)\n\tat org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)\n\tat org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)\n\tat org.elasticsearch.cli.Command.main(Command.java:77)\n\tat org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)\n\tat org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)\nFor complete error details, refer to the log at /usr/share/elasticsearch/logs/elasticsearch.log\n"}
{"@timestamp":"2022-05-11T20:36:24.176Z", "log.level": "INFO", "message":"stopping ...", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-2","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch"}
{"@timestamp":"2022-05-11T20:36:24.233Z", "log.level": "INFO", "message":"stopped", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-2","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch"}
{"@timestamp":"2022-05-11T20:36:24.233Z", "log.level": "INFO", "message":"closing ...", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-2","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch"}
{"@timestamp":"2022-05-11T20:36:24.244Z", "log.level": "INFO", "message":"closed", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-2","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch-es-default-2","elasticsearch.cluster.name":"elasticsearch"}`

I then decided to check the logs of the operator and it seemed that elasticsearch could not be upgraded due to incompatibility reasons.

logs :

`{"log.level":"info","@timestamp":"2022-05-11T20:08:19.389Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","iteration":110,"namespace":"elastic","es_name":"elasticsearch"}
{"log.level":"info","@timestamp":"2022-05-11T20:08:19.390Z","log.logger":"generic-reconciler","message":"Updating resource","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","kind":"Service","namespace":"elastic","name":"elasticsearch-es-transport"}
{"log.level":"info","@timestamp":"2022-05-11T20:08:19.699Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","iteration":110,"namespace":"elastic","es_name":"elasticsearch","took":0.310060162}
{"log.level":"error","@timestamp":"2022-05-11T20:08:19.699Z","log.logger":"manager.eck-operator.controller.elasticsearch-controller","message":"Reconciler error","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","name":"elasticsearch","namespace":"elastic","error":"elasticsearch-es-default-2 has incompatible version: version 8.2.0 is higher than the highest supported version of 7.99.99","errorCauses":[{"error":"elasticsearch-es-default-2 has incompatible version: version 8.2.0 is higher than the highest supported version of 7.99.99","errorVerbose":"version 8.2.0 is higher than the highest supported version of 7.99.99\nelasticsearch-es-default-2 has incompatible version\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).verifySupportsExistingPods\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/version.go:21\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:208\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:298\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:187\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"log.level":"info","@timestamp":"2022-05-11T20:08:45.395Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","iteration":111,"namespace":"elastic","es_name":"elasticsearch"}
{"log.level":"info","@timestamp":"2022-05-11T20:08:45.395Z","log.logger":"generic-reconciler","message":"Updating resource","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","kind":"Service","namespace":"elastic","name":"elasticsearch-es-transport"}
{"log.level":"info","@timestamp":"2022-05-11T20:08:45.700Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.2.0+02f250eb","service.type":"eck","ecs.version":"1.4.0","iteration":111,"namespace":"elastic","es_name":"elasticsearch","took":0.305124203}`

**Environment**

* ECK version:

	ECK version : 2.2.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? N/A
	* Cloud: GKE / EKS / AKS ? EKS 1.20
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version: 1.20.15

Has anyone came across this issue before?

**Comment by thbkrkr** [comment]
`Failed to parse mappings for index [[elastalert/FYUShuBaTyCgPwgKXAiJsw]]`

I believe that you did not run the upgrade assistant. It would probably have tell you that you have deprecated settings/mappings.

Please move this discussion to our [community forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) and use GitHub only for bug reports or feature requests directly related to ECK, thank you!
