### ISSUE TITLE
Feature request - ingress option 

### ISSUE THREAD

**Issue by jmcgrath207** [elastic/cloud-on-k8s#5732]
I would like to see a option to use a ingress instead of a load balancer to public expose a kibana and elastic search.

**Comment by naemono** [comment]
@jmcgrath207 We have some recipes here for exposing using Google Cloud LBs:

https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/gclb

Along with an Nginx ingress example for Maps:

https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/maps/03-ingress.yaml

And a Traefik example here: 

https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/traefik

Unfortunately, supporting Ingress more directly in the CRDs is complicated by the fact that there are so many ingress types, with conflicting options for each.

We also have an [issue](https://github.com/elastic/cloud-on-k8s/issues/5012) tracking making the recipes more clear from the official documentation, which could help this situation.

I'm going to close this, but feel free to open if you feel more needs to be discussed.  Thanks.
