### ISSUE TITLE
No `/v2` suffix for v2 versions

### ISSUE THREAD

**Issue by SVilgelm** [elastic/cloud-on-k8s#5733]
## Bug Report
**What did you do?**

```shell
go get github.com/elastic/cloud-on-k8s/v2@latest
go: downloading github.com/elastic/cloud-on-k8s v0.0.0-20220603135112-a082bb1e1089
go: module github.com/elastic/cloud-on-k8s@latest found (v0.0.0-20220603135112-a082bb1e1089), but does not contain package github.com/elastic/cloud-on-k8s/v2
```

**What did you expect to see?**

the package name in `go.mod` must contain `/v2` suffix for the v2 versions
otherwise the go mod uses the commit number `github.com/elastic/cloud-on-k8s v0.0.0-20220603135112-a082bb1e1089` instead of release

**Comment by SVilgelm** [comment]
hmmm, I realized all tags have no `v` prefix at all, that's why the go.mod uses commit id :(

it would be great it you change the versioning schema to use `v...` versions and add `/v2` or `/v3` suffix to the package name in `go.mod`

**Comment by naemono** [comment]
We are tracking this change in #5095, and it's on the radar.  If you have any additional comments, could you please add them there?  Thanks.
