### ISSUE TITLE
How to become a member

### ISSUE THREAD

**Issue by jiuker** [elastic/cloud-on-k8s#5784]
Whether I have the honor to be your member？
 What is the way? I didn't see the relevant instructions in this repo.
I have pr list:
[#5783](https://github.com/elastic/cloud-on-k8s/pull/5783) fix update bug
[#5755](https://github.com/elastic/cloud-on-k8s/pull/5755) fix leak memory
[#5744](https://github.com/elastic/cloud-on-k8s/pull/5744) refactor long swtich
[#5723](https://github.com/elastic/cloud-on-k8s/pull/5723) copy 
[#5719](https://github.com/elastic/cloud-on-k8s/pull/5719) fix dockfile bug

**Comment by Kushmaro** [comment]
@jiuker Becoming a "member" is for Elastic Employees :slightly_smiling_face: we're always looking for engineers.
You can look here https://www.elastic.co/about/careers/

Meanwhile, we're always happy to get external contributions.
