### ISSUE TITLE
Improve RemoteCluster specification

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#579]
A few things do not feel right in our current RemoteCluster specification:

* the source cluster is designated through a label, whereas the target cluster is designated through the Spec. Technically the label allows us to easily filter on a list of resources, but by using the controller-runtime we already cache all resources locally anyway. The same goes for TrustRelationships.
* should users be allowed to specify a list of remote clusters?
* naming this resource can be confusing: should we move the "remote" section into the Elasticsearch spec?

**Comment by pebrc** [comment]
Closing as we decided to remove RemoteCluster for now #963
