### ISSUE TITLE
ES Operator Image 2.2..0 has vulnerabilities

### ISSUE THREAD

**Issue by PraveenBodasingi19** [elastic/cloud-on-k8s#5797]
We need exact release date for new version of ES Operator Image. This blocking our higher environment deployments.

Vulnerabilities list : 

![image](https://user-images.githubusercontent.com/105217846/174356731-c0cea028-5901-4d23-a312-4305496b3370.png)

**Comment by naemono** [comment]
Please provide details such as

1. What image was scanned?
2. What tool was used for scanning?
3. What vulnerabilities are being reported?  Your image shows versions of software but not specific vulnerabilities.

Please be aware of #4561 which was merged and will reduce our surface for vulnerabilities in the upcoming release

**Comment by naemono** [comment]
@PraveenBodasingi19 you updated a closed issue #4561.  Please update this issue, as it's still open.

> These packages are not latest version. Please upgrade to latest version.

Having a vulnerability, and not being the latest version are 2 separate issues.  Does the scan show that these versions have actual vulnerabilities?

> Is it give solution to use image as : docker.elastic.co/eck/eck-operator:2.2.0-ubi ?

No, the `-ubi` image has a larger surface area for vulnerabilities, but with 2.3.0 version, likely to be released within a week, the default image `docker.elastic.co/eck/eck-opeartor:2.3.0` will be based off of [distroless](https://github.com/GoogleContainerTools/distroless), which has nearly zero dependencies.

**Comment by PraveenBodasingi19** [comment]
Having a vulnerability, and not being the latest version are 2 separate issues. Does the scan show that these versions have actual vulnerabilities? - yes

Thanks please let me know once new version releases.
