### ISSUE TITLE
How to use cert-manager to get certificates to be trusted?

### ISSUE THREAD

**Issue by ejsmith** [elastic/cloud-on-k8s#5798]
I'm trying to get my app reporting APM data using APM server and I have it setup and can get things working locally without https, but in my prod environment the APM server is using HTTPS, but my client can't connect to it because it gets a certificate validation error because the APM server is using a self-signed certificate. Is there some way to maybe use cert-manager that I already have setup to get the APM server to use a trusted certificate or do I have to figure out how to get my pods to trust the self-signed CA?

**Comment by pebrc** [comment]
https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-custom-http-certificate.html#k8s_custom_self_signed_certificate_using_cert_manager
