### ISSUE TITLE
TopologySpreadConstriant with Parallel pod management policy is unreliable

### ISSUE THREAD

**Issue by leonz** [elastic/cloud-on-k8s#5810]
## Bug Report

We are trying to enable AZ spread for our cluster using Topology Spread Constraints, with a maxSkew = 1 and a DoNotSchedule policy.

The problem is that the K8s scheduler only consider live pods when calculating the constraint, which means that when pods are spun up simultaneously, if there is any scheduling delay (such as: waiting for nodes to become available), it's possible for the scheduling to be inconsistent.

It's not clear to me that there is an obvious fix on the Elastic Operator side except to try to resolve the issue automatically when it arises by replacing the node. But I wanted to make you aware that this is an edge case.

**What did you do?**

Added a topology spread that looks like:

```
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              foo: bar
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
```

And then spun up a new node set with 3 pods.

**What did you expect to see?**

3 pods split across 3 AZs, A, B and C.

**What did you see instead? Under which circumstances?**

We saw 3 pods scheduled to AZs A, B, and B with one pod stuck in pending.

```
es-data-0                1/1     Running   0          4h42m
es-data-1               0/1     Pending   0          4h5m
es-data-2                1/1     Running   0          4h7m
```

**Environment**

AWS

* ECK version: 2.1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
[~] $ kubectl -n data-regalia get sts -o yaml | grep topologySpread -A 10^C
[~] $ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.901", GitCommit:"f7859aeae924c59a2384b7b165f0a0766819df4c", GitTreeState:"clean", BuildDate:"2022-02-08T18:35:50Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by leonz** [comment]
Okay, I think I exacerbated this issue by not having a match label per node set, just per cluster.  So it resulted in un-even nodes across node sets.

It's still technically possible to end up in a rough situation but I think that this is largely my own fault.

**Comment by naemono** [comment]
@leonz reading through this more carefully, this seems to be exactly what I would expect from the k8s scheduler.  It sounds as though you have 3x nodes:

` nodes [a,b,c]`

All in different availability zones, from what I'm reading, let's call them

`azs [1,2,3]`

If Node A is in AZ1 and is ready, and Node B is in AZ2 and is ready, and Node C is in AZ3, but the node isn't ready, I'd expect:


* pod1 on node A
* pod2 on node B
* pod 3 in a `pending` state, as it's unable to be scheduled

That seems to be exactly what you're describing above.  If this is not the case, please explain further, and also include the `Events` in the cluster, as I'd expect something like:

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  67s (x3 over 69s)  default-scheduler  2/3 nodes are available: **1 node(s) didn't match pod topology spread constraints**
  ```
  
In addition, I'm unsure what the ECK Operator could do in these scenarios (which you mentioned), as these decisions are made by the k8s scheduler, and not our Operator.
