### ISSUE TITLE
Specify a custom image for Filebeat container.

### ISSUE THREAD

**Issue by aleks-m** [elastic/cloud-on-k8s#5903]
Hi.

We have an ECK cluster with enabled monitoring (configured using this doc - https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html). It automatically creates a filebeat container (using filebeat: `docker.elastic.co/beats/filebeat` image). 
We are also mirror ES/Kibana images to our internal docker repo (to survive external repo outages). In case of ES and Kibana we can specify custom images from our internal repo in a CRD. But in case of that Filebeat container - I can't find how to specify a custom image. Is there any way to do so?

Thanks.

**Comment by pebrc** [comment]
You can override values in the pod template used to create the sidecar containers this includes the image used. This is documented here https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s_override_the_beats_pod_template.html

**Comment by davehouser1** [comment]
Just wanted to add a comment to this. Its not possible to provide custom image paths for the sidecars. They are hard coded based on `eck-operator.containerRepository`. They will prefix the path with that every time. See this go file for details. https://github.com/elastic/cloud-on-k8s/blob/2.16/pkg/controller/elasticsearch/stackmon/sidecar.go
