### ISSUE TITLE
Run as non-root Elasticsearch is outdated and not relevant when running on OpenShift

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#5913]
[Run as non-root Elasticsearch](https://www.elastic.co/guide/en/cloud-on-k8s/2.3/k8s-security-context.html#k8s_run_as_non_root_elasticsearch) is outdated:

> By default, the Elastisearch container is run as root and its entrypoint is responsible to run the Elasticsearch process with the elasticsearch user (defined with ID 1000). In the background, ECK uses an initContainer to make sure that the data volume is writable for the elasticsearch user.

This is not true since `8.0.0`, Elastisearch container is run as user id `1000` by default:

```
docker run --rm docker.elastic.co/elasticsearch/elasticsearch:7.17.5 id
uid=0(root) gid=0(root) groups=0(root)
```

```
docker run --rm docker.elastic.co/elasticsearch/elasticsearch:8.3.3 id
uid=1000(elasticsearch) gid=0(root) groups=0(root)
```

We should also:
* State that this section is not relevant in the context of OpenShift as workloads are supposed to get assigned a [random user id](https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids).
* Document the new default SecurityContext for Elasticsearch containers introduced with https://github.com/elastic/cloud-on-k8s/pull/6703

**Comment by gbschenkel** [comment]
Also when upgrading from 7.x to 8.x the container still use 0, I was needed to run a initContainer to chown the directory to user and group elasticsearch:elasticsearch which is 1000, but I didn't know when this stuck on my Openshift cluster.

**Comment by barkbay** [comment]
We should also document the new default `SecurityContext` for Elasticsearch containers introduced with https://github.com/elastic/cloud-on-k8s/pull/6703
