### ISSUE TITLE
Elastic Agent hostPath volumes must not be used before 7.15

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5933]
Related https://github.com/elastic/cloud-on-k8s/issues/4428#issuecomment-827081534

Work done in https://github.com/elastic/cloud-on-k8s/pull/5890 ignored that Elastic Agent state handling while added in 7.13 was not functional until 7.15 when this PR https://github.com/elastic/beats/pull/27396 was merged.

We need to version gate the functionality for >= 7.15

**Comment by barkbay** [comment]
nit: is it not fixed by https://github.com/elastic/cloud-on-k8s/pull/5934?

**Comment by pebrc** [comment]
Yes sorry forget to add the magic incantation to auto-close the issue in the PR.
