### ISSUE TITLE
Ingest CRD again

### ISSUE THREAD

**Issue by NikitaIvankov1992** [elastic/cloud-on-k8s#5953]
Hey :)

This question has been already asked but since it's more than 2 years left maybe something changed
Is it possible to add CRD for the "[Ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html)" feature?

Currently, we need to parse and split one of the fields of the application's logs and to do so we're using the "KV"  [filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html). So we have to deploy custom "Logstash" to the stack we're using(EFK) and we'd like to get rid of the "Logstash" and use the similar [KV processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/kv-processor.html). But the ways to use it(create the ingest pipeline) - either manually or via some POST request, which is a bit against the IaC paradigm we follow...

The initial request is [available here](https://github.com/elastic/cloud-on-k8s/issues/3127)

Thanks

**Comment by barkbay** [comment]
I'm sorry there is still no plan to introduce such a CRD in the short/mid term planning.
