### ISSUE TITLE
Reschedule pods when a node is tainted / drained.

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#60]
## Drain
![](https://kubernetes.io/images/docs/kubectl_drain.svg)

## Reference links
* https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
* https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by pebrc** [comment]
Closing as we don't control individual pods anymore with the move to `StatefulSets`
