### ISSUE TITLE
Clarify documentation for adjusting metrics port.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#6060]
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-operator-config.html

```
You can edit the elastic-operator ConfigMap to change the operator configuration. Unless the --disable-config-watch flag is set, the operator should restart automatically to apply the new changes. Alternatively, you can edit the elastic-operator StatefulSet and add flags to the args section — which will trigger an automatic restart of the operator pod by the StatefulSet controller.
```

While this is technically true, it doesn't "just work" in some scenarios, specifically `metrics-port`, as the statefulset doesn't expose the port, and there's no `podMonitor` (with the all-in-one) to allow scraping.

If installing via the all-in-one, metrics are disabled, and it would take a bit of tinkering to get it to work correctly, although our documentation states that it's as easy as editing the `configmap`.  It actually would take

(When using all-in-one)
1. Configmap edit
2. Statefulset edit to the `spec.template.spec.containers[].ports` section

(When using Helm, which also includes a `podMonitor`, and a `networkPolicy`, which include the metrics port)
1. `helm upgrade elastic-operator -n elastic-system elastic/eck-operator --set=config.metricsPort=8080 --reuse-values`

I would suggest we update the documentation to be more clear on this point.

**Comment by barkbay** [comment]
> While this is technically true, it doesn't "just work" in some scenarios, specifically metrics-port, as the statefulset doesn't expose the port, and there's no podMonitor (with the all-in-one) to allow scraping.

Sorry, I'm not sure to understand that part. As soon as a Pod listens on its "non localhost" interface ("0.0.0.0") then the port is accessible. AFIAK `containers[].ports` is mostly used in conjunction with `Services`, which is unlikely to be the case for metrics (because I think we want want metrics from all the operator instances).

**Comment by naemono** [comment]
@barkbay I though that without the `pod.spec.containers[0].ports` configuration missing that the iptables rules to allow communication over this port would work, but after testing this morning, I can access it via a pod in the default namespace without issues.  Do you think we should add something here noting that no `podMonitor` is in place to scrape these metrics using the all-in-one yaml?

**Comment by barkbay** [comment]
`iptables` is a way to implement the `Service` object. It is not required to route a packet from a Pod to another one.

If by `podMonitor` you mean the [Prometheus `PodMonitor` resource](https://github.com/prometheus-operator/prometheus-operator/blob/main/example/user-guides/getting-started/example-app-pod-monitor.yaml), my feeling is that the documentation makes it clear that this configuration is not about creating and managing any additional Prometheus or monitoring resources, only setting the metrics endpoint port.

**Comment by naemono** [comment]
> my feeling is that the documentation makes it clear that this configuration is not about creating and managing additional Prometheus or monitoring resources, but only setting the metrics endpoint port.

Ok then, I'll just close this without merging.  thanks for the clarification.
