### ISSUE TITLE
Remove License CRDs

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#607]
Custom resource definition draw too much attention and might confuse users.

Suggested change:

* We should therefore remove the intermediate step of creating cluster license CRs in the namespace of the cluster operator  
* update the ADR accordingly
* use a secret instead of the custom resource

**Comment by pebrc** [comment]
Another suggested change from @bleskes is 
* to remove the EnterpriseLicense CRD as well and use a secret instead 
* move the parsing of the license into the controller to make the CLI tool redundant

**Comment by devdattakulkarni** [comment]
+1 

A CRD for Licenses make senses if there are any declarative actions to be performed by one of the controllers based on the License related CR spec inputs. If there are no such actions then using a Secret or ConfigMap will be a better choice for uploading License information.

**Comment by pebrc** [comment]
closed with #969 and #1018
