### ISSUE TITLE
seccompProfile.type: RuntimeDefault does not work without additional SCC on OpenShift < 4.11

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#6073]
#6047 introduced a securityContext for the operator Pod with the `RuntimeDefault` seccomp profile

However it seems on OpenShift version before 4.11 Pods specifying this will not be allowed to start. 

```
 create Pod elastic-operator-0 in StatefulSet elastic-operator failed error: pods "elastic-operator-0" is forbidden: unable to validate against any security context constraint: [pod.metad │
│ ata.annotations.container.seccomp.security.alpha.kubernetes.io/manager: Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable by user or serviceaccount provider "nonroot": Forbidden: not │
│  usable by user or serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount prov │
│ ider "hostnetwork": Forbidden: not usable by user or serviceaccount provider "hostaccess": Forbidden: not usable by user or serviceaccount provider "node-exporter": Forbidden: not usable by user or serviceac │
│ count provider "privileged": Forbidden: not usable by user or serviceaccount] 
```

I think it is because none of the SCCs allows configuring a seccomp profile. Analogous to this issue https://bugzilla.redhat.com/show_bug.cgi?id=2010564

**Comment by pebrc** [comment]
I think we should remove the 

```
  seccompProfile:
    type: RuntimeDefault
```

section again from the values file/template. If not the operator won't be able to start on OpenShift versions prior to 4.11 without creating a custom SCC (sidetone: I have not been able to make this work with a custom SCC so far that explicitly allows the `runtime/default` seccomp profile, not sure why)

This will cause a warning in 4.11 due to the Pod Security Standard check. However, and this confuses me as well, as of 4.11 there is actually a new default SCC called `restricted-v2`  that with the default seccomp profile and it is applied to every Pod.  So it seems the Pod Security Standard admission controller is not aware of that? 

Wdyt @barkbay ?

**Comment by barkbay** [comment]
> So it seems the Pod Security Standard admission controller is not aware of that?

Good point 🤔 
👍 for removing the `seccompProfile`
