### ISSUE TITLE
Add a second client to allow access to namespace operator control plane

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#611]
controller-runtime is limited to watching one namespace only or every namespace until the next release see #405 

If we want to deploy an operator limited to watching one managed namespace that poses a problem  for example to watch and create secrets for admission control or to watch licenses for controller licensing.

Until then a workaround to allow namespace operators to watch resources in their own control-plane namespace could be to create a second client watching the control plane namespace and passing it as an argument to interested controllers.

**Comment by sebgl** [comment]
I think we decided we'd wait for controller-runtime `0.2` to benefit from multi-namespace watches.
Closing this issue now.
