### ISSUE TITLE
Prefix releases/tags with `v`.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#6134]
See https://github.com/elastic/cloud-on-k8s/pull/5809#issuecomment-1298877962

Even after moving to a `/v2` go module path in `go.mod`, we are still being imported using a legacy format:

```
❯ go get github.com/elastic/cloud-on-k8s/v2@2.4.0
go: added github.com/elastic/cloud-on-k8s/v2 v2.0.0-20220812092235-96282ca98df1
```

We need to adjust our release process to ensure we are prefixing releases/tags with `v`, such as `v2.6.0`.

Things to consider:

- [ ] Redhat release process changes needed.
- [ ] Documentation noting the change, as not to confuse someone wanting to install a previous version, only to find it's not prefixed with `v`.
- [ ] ECK Helm chart changes.
- [ ] Tooling changes needed under `hack` directory? (release-notes, upgrade-test-harness, update-stack-version.sh)
- [ ] CI changes?
- [ ] Public facing documentation changes (kubectl install links; release notes links)

**Comment by thbkrkr** [comment]
For the go module import to work properly, we need to create the git tag with the `v` prefix. Am I correct if I say that we do not need to have this 'v' elsewhere? So, couldn't we just remove the `v` prefix where we use the git tag and continue as before? It would only involve one small change, nothing more, it is only used in one place.


```diff
diff --git a/.ci/setenvconfig b/.ci/setenvconfig
index b986f6eab5..2ef1caef1b 100755
--- a/.ci/setenvconfig
+++ b/.ci/setenvconfig
@@ -686,7 +686,7 @@ GO_TAGS=release
 export LICENSE_PUBKEY=${PROJECT_PATH}/.ci/license.key

 SNAPSHOT=false
-IMG_VERSION=$TAG_NAME
+IMG_VERSION=${TAG_NAME#"v"} # remove v prefix
 ENV
```
