### ISSUE TITLE
ECK 2.4.0 fails on ShutdownResponse json unmarshal with ELS 7.10.0

### ISSUE THREAD

**Issue by kzzalews** [elastic/cloud-on-k8s#6192]
## Bug Report
Recently we've upgraded our ECK operator to version 2.4.0 (from 1.8.0) on cluster with ELS 7.10.0. During upgrade we've observed errors in ECK logs (see "Logs" section). As documentation states that this version of ECK should support this version of ELS (see: `Elasticsearch, Kibana, APM Server: 6.8+, 7.1+, 8+`) we've expected it to work without issues.

We've done our own investigation and realized that:
1. New feature was added some time ago to ECK (see: https://github.com/elastic/cloud-on-k8s/pull/4597) and it uses `/_nodes/*/shutdown` and `/_nodes/shutdown` to manage lifecycle of ELS. Comment to this PR states: `This comes with no escape hatch for users and fully relies on the new API as of version 7.15.2`
2. Documentation for ELS 7.15 shows JSON that should be returned by endpoint `/_nodes/*/shutdown`. See: https://www.elastic.co/guide/en/elasticsearch/reference/7.15/get-shutdown.html. This response is much different from what we're seeing when we're calling this endpoint on ELS 7.10.0. E.g. on older ELS version `nodes` contains map instead of list expected by operator. See: https://github.com/elastic/cloud-on-k8s/blob/2.4.0/pkg/controller/elasticsearch/client/model.go#L497
3. We believe that there is incompatibility between ECK 2.4.0 and ELS 7.10.0.
4. ECK 2.4.0 works fine with ELS 7.17.5.

We assume that it could lead to one of two outcomes:
1. Changing list of supported ELS versions for ECK versions containing mentioned PR and adding info about breaking changes to release notes. See: https://www.elastic.co/guide/en/cloud-on-k8s/2.0/release-notes-2.0.0.html
2. Adding compatibility with older versions to new ECK (most probably, this will be hard and unlikely to happen).

We've decided to don't include info about cloud or K8s version as it seems irrelevant here. If needed, we can provide such information.

What we're expecting here? Confirmation that our understanding of situation is right/flawed. If right, it would be great to reflect outcomes from this investigation in docs (i.e. breaking changes in release notes + info about compatibility with ELS versions).

**Environment**

* ECK version:

	2.4.0

* ELS version:

	7.10.0

* Logs:
```
{"log.level":"error","@timestamp":"2022-11-24T10:44:09.474Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","object":{"name":"elasticsearch","namespace":"our-namespace"}
,"namespace":"our-namespace","name":"elasticsearch","reconcileID":"f0d0893e-bcbb-4d1a-807b-bf25912e5080","error":"while getting node shutdowns: json: cannot unmarshal object into Go struct field ShutdownResponse.nodes of type []client.NodeShutdown","errorCauses":[{"error":"while getting node shutdowns: j
son: cannot unmarshal object into Go struct field ShutdownResponse.nodes of type []client.NodeShutdown"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsig
s.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
```

**Comment by pebrc** [comment]
The odd think here is that for versions prior to 7.15.2 there should be no interactions with the `_node/shutdown` API. The operator should not even try to use this API in 7.10.0. Is your version in the in `Elasticsearch.Spec.Version` attribute set to something else than 7.10?

**Comment by kzzalews** [comment]
@pebrc, thank you very much! Of course, our investigation was flawed exactly by `Elasticsearch.Spec.Version`. I'll confirm, how it behaves for older ELS with proper var in CR, but I'm pretty sure that this is it and as almost always the problem sits between chair and keyboard ;)

Thanks again!

**Comment by kzzalews** [comment]
I can confirm, everything works fine, when `Elasticsearch.Spec.Version` is used properly. Mea culpa! Thank you for support (it was fast and accurate) and I'm closing this ticket.
