### ISSUE TITLE
Remove deprecation note for APM Server standalone

### ISSUE THREAD

**Issue by simitt** [elastic/cloud-on-k8s#6207]
Starting ECK with a standalone APM Server issues a warning that it is deprecated from `8.0.0` onwards. The standalone server has not actually been deprecated yet. We should remove [this deprecation note](https://github.com/elastic/cloud-on-k8s/blob/f7448b650474e1be4e20b5cb6b2abdebcb183eeb/pkg/controller/apmserver/controller.go#L285) to avoid user confusion.

**Comment by ebuildy** [comment]
Well, they call it "legacy" since v7:

https://www.elastic.co/guide/en/apm/guide/current/legacy-apm-overview.html

**Comment by simitt** [comment]
The focus shifted towards the Elastic Agent managed APM Server, but the standalone server has not been deprecated, therefore the deprecation warning should be removed. We are aware that the usage of the term "legacy" is not ideal here.
