### ISSUE TITLE
[deploy/eck-elasticsearch] Expose volumeClaimDeletePolicy

### ISSUE THREAD

**Issue by tbnguyen1407** [elastic/cloud-on-k8s#6249]
## Proposal

Expose `volumeClaimDeletePolicy` to allow configuring retention of PVCs. Currently this field is not configurable in values.yaml.

**Comment by urechi** [comment]
Is there a way to set the `volumeClaimDeletePolicy`  to `DeleteOnScaleDownOnly` in the eck-elasticsearch helm chart or any other charts? I need to be able to retain the PVC on cluster deletion so if this could be added that would be much appreciated.

**Comment by thbkrkr** [comment]
> Is there a way to set the volumeClaimDeletePolicy to DeleteOnScaleDownOnly in the eck-elasticsearch helm chart or any other charts?

@urechi Not yet but https://github.com/elastic/cloud-on-k8s/pull/6409 should be available in the next ECK release.
