### ISSUE TITLE
Unable to deploy ECK stack due to license.

### ISSUE THREAD

**Issue by andrelsyoo** [elastic/cloud-on-k8s#6261]
## Bug Report
**What did you do?**

Trying to deploy `eck-stack` based on [Elastic ECK Repo](https://github.com/elastic/cloud-on-k8s/tree/main/deploy)

**What did you expect to see?**

According to Elastic documentations, eck suppose to work with basic-tier and enterprise-tier customers.

So I expect to have Elastic stack resources running on my cluster w/ basic license (Free). Currently I'm able to deploy only `elastic-operator`.

<img width="1616" alt="Screen Shot 2022-12-28 at 23 12 32" src="https://user-images.githubusercontent.com/41391870/209895641-199f9b05-1083-4146-8952-100aaf1a0470.png">

<img width="1723" alt="Screen Shot 2022-12-28 at 23 13 08" src="https://user-images.githubusercontent.com/41391870/209895651-ed46a1ef-035e-49ac-8acb-fe7e2cf118be.png">

<img width="1723" alt="Screen Shot 2022-12-28 at 23 15 37" src="https://user-images.githubusercontent.com/41391870/209895658-27b55fc9-394e-45c5-90c5-a8a11c3d406f.png">

**What did you see instead? Under which circumstances?**

I'm able to deploy elastic-operator but when I try to deploy eck-stack or any of eck chart got webhook denied due to license.

**Environment**

* ECK version:

	0.1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* EKS 
	
```
$ kubectl version  v1.21.14
```

* Logs 1:
```
helm install es-kb-quickstart elastic/eck-stack -n elastic-stack 
Error: INSTALLATION FAILED: admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch" is invalid: metadata.annotations.eck.k8s.elastic.co/license: Invalid value: "enterprise": Enterprise license required but ECK operator is running on a Basic license
```

* Logs 2:
```
helm install elasticsearch elastic/eck-elasticsearch -n elastic-system
Error: INSTALLATION FAILED: admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-eck-elasticsearch" is invalid: metadata.annotations.eck.k8s.elastic.co/license: Invalid value: "enterprise": Enterprise license required but ECK operator is running on a Basic license

**Comment by pratheekrebala** [comment]
This configuration is set using the annotations. This is currently hardcoded in the chart but you can override this.

Try updating the values.yaml for the chart to override the `eck.k8s.elastic.co/license` annotation.

```
eck-elasticsearch:
    enabled: true
    annotations:
        eck.k8s.elastic.co/license: basic

eck-kibana:
    enabled: true
    annotations:
        eck.k8s.elastic.co/license: basic
```

**Comment by thbkrkr** [comment]
> According to Elastic documentations, eck suppose to work with basic-tier and enterprise-tier customers.
> So I expect to have Elastic stack resources running on my cluster w/ basic license (Free).

The ECK Helm Charts are licensed under the [Elastic License 2.0](https://www.elastic.co/licensing/elastic-license) like the operator, but require different subscription levels.

The ECK Operator Helm Chart can be used with a Basic license for free, while the ECK Stack and Resources Helm Charts require an [Elastic Enterprise License](https://www.elastic.co/subscriptions) for use.

**Comment by rkubik-hostersi** [comment]
Where is it stated? Does it mean that ECK components cannot be used using free license?

**Comment by andrelsyoo** [comment]
Disappointing! moving to **Bitnami** charts! thanks for response anyways!

**Comment by mbochenk** [comment]
@thbkrkr This is still not mentioned in README and should've been made clear.
A disappointing decision, but at least documenting this would save people a lot of trouble.

**Comment by thbkrkr** [comment]
> Does it mean that ECK components cannot be used using free license?

No, you can still use normal k8s YAML manifests or also write your Helm Chart.

>  This is still not mentioned in README and should've been made clear.

This is mentioned in the bottom of the README of the Helm Charts (https://github.com/elastic/cloud-on-k8s/tree/main/deploy#licensing) and the second note of the documentation page 'Elastic Stack Helm Chart' (https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-helm-chart.html).

**Comment by mbochenk** [comment]
@thbkrkr Thanks, missed it at first.

**Comment by vit-zikmund** [comment]
This is really strange. The charts for `eck-elasticsearch` and `eck-kibana` are but a thin wrapper around the operator's CRs.
Sorry to poke, but @thbkrkr can you pls explain what's the purpose of licensing that? This way?

Currently charts are readable, public, everyone can `helm pull` them, learn from them, and bash together their own, or go as short as to remove the license annotations (or even use @pratheekrebala's funny hack off the bat) and go along their way. As a well-behaved person I surely respect the license (which also prohibits license tampering) and will spin my own chart, but still... This makes no sense to me, taming something as open and silly as helm charts, while leaving the operator that does the heavy lifting for the general public. Not that I wouldn't love the last part. I do, but this little cherry on top? Won't get you any new subscribers, I'm sure.

**Comment by konck1** [comment]
Hello, new to using ECK using Helm charts.

We are planning to deploy 
- [ECK Operator](https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-operator)
- [ECK Elasticsearch](https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-elasticsearch)

From the conversation above, I gather that you are free to use the operator, but not ECK-elasticsearch Helm deployment unless you have a license?

What's the point of using ECK-operator in the first place?

**Comment by Kushmaro** [comment]
Hey @vit-zikmund . I'm the current PM for ECK. I'll be very transparent here. 
There's a cost associated with helm-chart maintenance, support, updates, etc. And while you're right about the current ones being a thin wrappers, we hope to improve and refine them over time. In addition, we may opt to change the license model in the future for the eck-helm charts in future releases, to be more widely available. 

Meanwhile, you are very free and welcome to create your own set of charts for eck managed resources as well of course.

We do try our best to provide as much value to our customers *and* the community as we can. And will definitely continue doing so. Hope this sheds a bit more light.

**Comment by vit-zikmund** [comment]
Thank you, @Kushmaro. I understand. Obviously, helm charts are something rather new in your portfolio and in such a phase it's hard to reserve enough funds to support it publicly before it deems feasible. I can only hope it does and wish you (and us, choosing beggars :stuck_out_tongue:) best of luck!

**Comment by simonebenati** [comment]
@pratheekrebala Hello, I tried your method on version 2.8 and instead of changing from enterprise to basic it appends the string under enterprise as such:
```
  annotations:
    eck.k8s.elastic.co/license: enterprise
    eck.k8s.elastic.co/license: basic
```

Do you have any anything on this?
Thank you

**Comment by polak785** [comment]
@simonebenati Same for me on 2.8. This is still working as expected but indeed the annotation should be replaced.
