### ISSUE TITLE
How to --set storage class name?

### ISSUE THREAD

**Issue by rhrytskiv** [elastic/cloud-on-k8s#6273]
Hi, we want to try ECK via helm but how do you tell which storage class to use?

**Comment by barkbay** [comment]
Please refer to this example in the Elasticsearch chart: https://github.com/elastic/cloud-on-k8s/blob/a82fbca490deafe5b01ea01bd4ab57b209dc3c16/deploy/eck-elasticsearch/examples/hot-warm-cold.yaml#L51
