### ISSUE TITLE
ElasticMapsServer Pod does not start on ARM

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#6299]
`TestElasticMapsServerCrossNSAssociation/ElasticMapsServer_Pods_should_eventually_be_ready` failed 2 times in a row on ARM:
* https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-eks-arm/detail/cloud-on-k8s-e2e-tests-eks-arm/586/pipeline/
* https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-eks-arm/detail/cloud-on-k8s-e2e-tests-eks-arm/587/pipeline/

Error in the EMS Pod logs is:

```
==== START logs for e2e-pwsy4-venus/test-cross-ns-ems-es-46m4-ems-6dd454f667-cmp44 ====
exec /bin/sh: exec format error
==== END logs for e2e-pwsy4-venus/test-cross-ns-ems-es-46m4-ems-6dd454f667-cmp44 ====
```

For `587` the image pulled is `docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8@sha256:f8d8eb19d8bf8bbcb4e051a8f3b216339d131b9e7bf51bbf048921b6a7145c69`:

```json
                "containerStatuses": [
                    {
                        "containerID": "docker://9bee63637904d31e9e272d4cd3a31db46c64cdeddf88d9c59e248d0a83545bd1",
                        "image": "docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8:8.5.0",
                        "imageID": "docker-pullable://docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8@sha256:f8d8eb19d8bf8bbcb4e051a8f3b216339d131b9e7bf51bbf048921b6a7145c69",
                        "lastState": {
                            "terminated": {
                                "containerID": "docker://9bee63637904d31e9e272d4cd3a31db46c64cdeddf88d9c59e248d0a83545bd1",
                                "exitCode": 1,
                                "finishedAt": "2023-01-10T01:58:41Z",
                                "reason": "Error",
                                "startedAt": "2023-01-10T01:58:41Z"
                            }

```
Which seems designed for `amd64`:

```
docker inspect docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8@sha256:f8d8eb19d8bf8bbcb4e051a8f3b216339d131b9e7bf51bbf048921b6a7145c69 | grep Architecture
        "Architecture": "amd64",
```

While nodes are `arm64`:

```json
"nodeInfo": {
                    "architecture": "arm64",
                    "containerRuntimeVersion": "docker://20.10.17",
                    "kernelVersion": "5.4.226-129.415.amzn2.aarch64",
                    "kubeProxyVersion": "v1.20.15-eks-fb459a0",
                    "kubeletVersion": "v1.20.15-eks-fb459a0",
                    "operatingSystem": "linux",
                    "osImage": "Amazon Linux 2",
                }
```

**Comment by pebrc** [comment]
The Elastic Maps Server image never had an ARM layer. We always excluded these tests from being run on ARM by not listing the build tag form maps in the ARM build runs. My suspicion is that this mechanism is broken: 

https://github.com/elastic/cloud-on-k8s/blob/e440baef28c3c7d9ace857f5e7d86818161bae0c/.ci/setenvconfig#L488

**Comment by thbkrkr** [comment]
I don't know what's going on. It already happened 27 days ago and my conclusion had stopped at:
- For eks-arm, we set `E2E_TAGS=es kb apm ent beat agent` in `.env`file included by the root Makefile to restrict the e2e-tests to run.
- `TestElasticMapsServerCrossNSAssociation` is defined in a file with `//go:build ems || e2e`.
- I don't know what could have happened that the go tags weren't respected.

Log https://devops-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/cloud-on-k8s-e2e-tests-eks-arm/runs/584/nodes/34/steps/38/log/?start=0 shows that e2e tags seem well propagated when building the e2e-tests docker image:
```
[2023-01-06T01:04:43.712Z] docker buildx build \
[2023-01-06T01:04:43.712Z] 	--progress=plain \
[2023-01-06T01:04:43.712Z] 	--file test/e2e/Dockerfile \
[2023-01-06T01:04:43.712Z] 	--build-arg E2E_JSON=true \
[2023-01-06T01:04:43.712Z] 	--build-arg E2E_TAGS='es kb apm ent beat agent release' \
[2023-01-06T01:04:43.712Z] 	--platform "linux/amd64,linux/arm64" \
[2023-01-06T01:04:43.712Z] 	--push \
[2023-01-06T01:04:43.712Z] 	-t docker.elastic.co/eck-ci/eck-e2e-tests:2.7.0-SNAPSHOT-7c9bb794 .
```

I wonder if the issue could come from the tricky part with the deprecated space commented here:
https://github.com/elastic/cloud-on-k8s/blob/0dfaefb7c4163d3194e4aaa00fced45f270dc851/Makefile#L483-L486

**Comment by thbkrkr** [comment]
#6587 switched to a comma separated list for the Go build tags as spaces separated list is deprecated. There is something still mysterious in this issue but it seemed related to the spaces Go build tag, so I'm closing. Of course, we will reopen if it happens again.
