### ISSUE TITLE
Empty Go Structs lead to invalid JSON Objects once marshalled

### ISSUE THREAD

**Issue by blakeromano** [elastic/cloud-on-k8s#6360]
## Bug Report
**What did you do?**

When trying to write a simple Kibana Object in Go with `github.com/elastic/cloud-on-k8s/v2 v2.6.0-bc5` in go.mod for the version I get the following error from the API Server
```
{"message":"Kibana.kibana.k8s.elastic.co \"elasticsearch\" is invalid: spec.enterpriseSearchRef.name: Required value"}
```
I saw a similar issue https://github.com/elastic/cloud-on-k8s/issues/5544 but I can't tell why this would be happening again on my side or if I am importing an incorrect version or something because on go.dev that is the latest version according to them. 

ECK Version: 2.6.0-bc5 client and 2.6.1 deployed

Kubernetes Version: 
  Can replicate on a kubernetes KIND cluster running 1.24 or 1.25 and a KOPS cluster on 1.24
  
I can replicate trying to apply it with a Kibana Resource defined like so in the spec
```go
return &es.Kibana{
		Spec: es.KibanaSpec{
			Version: ns.Spec.NamespaceServices.Elasticsearch.Version,
			Count: 1,
			ElasticsearchRef: escommon.ObjectSelector{
				Name: "elasticsearch",
				Namespace: "default",
			},
			Config: &escommon.Config{
				Data: configData,
			},
			HTTP: escommon.HTTPConfig{
				TLS: escommon.TLSOptions{
					SelfSignedCertificate: &escommon.SelfSignedCertificate{
						Disabled: true,
					},
				},
			},
		}
```

**Comment by naemono** [comment]
@blakeromano Could we please get a minimally reproducible example with go code, and client/server versions so that we can easily  reproduce this issue?

The following are what we ask from a bug report from the issue template:

**Environment**

* ECK version:

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

Thank you.

**Comment by blakeromano** [comment]
I added those details @naemono this can be supplemented by the details in the other issue I linked also

**Comment by blakeromano** [comment]
I ended up finding the issue. The CRDs that I believe were on the ES website were leading me to having name be a required field. When I found a different CRD from one of my internal company repos I got it to work.
