### ISSUE TITLE
Kibana readiness probe failed using ECK and anonymous authentication

### ISSUE THREAD

**Issue by nvivo** [elastic/cloud-on-k8s#6378]
## Bug Report
Installed elasticsearch and kibana using ECK, with kibana anonymous authentication enabled.

**What did you expect to see?**
The pod should be up and running.

**What did you see instead? Under which circumstances?**

The kibana readiness probe fails trying to get /login.

**Environment**

* ECK version: 2.6.1

* Kubernetes information:

	* Cloud: EKS 1.24

**Workaround**

Once I change the readiness check url to /status or / it works fine.
I suppose that when anonymous auth is enabled, the /login page doesn't exist?

**Comment by ajax-shmyrko-o** [comment]
>  I suppose that when anonymous auth is enabled, the /login page doesn't exist?

Yes, that's true, I've got the same issue. In case anonymous authentication is enabled in Kibana, the login endpoint returns this response:
```
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```
Kibana config with anonymous authentication to reproduce:

    xpack.security.authc.providers:
      anonymous.anonymous1:
        order: 0
        credentials:
          username: "username"
          password: "password"

**Comment by thbkrkr** [comment]
I confirm that you need to override the Kibana readiness probe when anonymous authentication is enabled.
Closing as I created https://github.com/elastic/cloud-on-k8s/issues/6417 to follow up on this.
