### ISSUE TITLE
Not able to expose Kibana using path based routing

### ISSUE THREAD

**Issue by chetan94k** [elastic/cloud-on-k8s#6419]
Have depoyed Kibana using helm chart 8.5.1 and tried to expose it using nginx controller along with ingress resource.

Below is the ingress file:
spec:
  ingressClassName: nginx
  rules:
  - host: [Hostname]
    http:
      paths:
      - backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
        path: /kbn
        pathType: Prefix

Here I am trying to access kibana at "[Hostname]/kbn"  but request is redirecting to **[Hostname]/login** and getting failed.

To mitigate it I tried to add server basepath like below via helm chart:
kibanaConfig:
   kibana.yml: |
     server.basePath: "/kbn"

Now when I browse "[Hostname]/kbn", it redirects to **[Hostname]/kbn/login?next=%2Fkbn%2Fkbn%2Flogin%3Fnext%3D%252Fkbn%252Fkbn%252Flogin%253.......**

and failed with error "Nginx 502 bad gateway"

Any suggestions on how to achieve this?

K8s version is 1.24

**Comment by thbkrkr** [comment]
The recipe '[Expose Elasticsearch and Kibana using a Google Cloud Load Balancer](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/gclb)' and '[Expose Elastic Maps Server and Kibana using a Kubernetes Ingress](https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/maps)' might help.

Please try to keep GitHub issues only for real bug reports and feature requests specific to the ECK operator. For these kinds of questions, you are more likely to get answers on our community [forum](https://discuss.elastic.co/c/orchestration/eck/79).
