### ISSUE TITLE
dev Helm chart released in wrong bucket with wrong parent version

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6568]
After I triggered the release of `v2.7.0-bc3` that should release `eck-operator-crds` and `eck-operator` in `2.7.0` in the dev Helm repo, I noticed 2 issues:

I'm not sure if it is correct that we release in `elastic-helm-charts-dev` and not in `elastic-dev`.
```
> helm search repo dev/eck-operator-crds
NAME                                            CHART VERSION   APP VERSION     DESCRIPTION
elastic-dev/eck-operator-crds                   2.7.0           2.7.0           A Helm chart for installing the ECK operator Cu...
elastic-helm-charts-dev/eck-operator-crds       2.7.0           2.7.0           A Helm chart for installing the ECK operator Cu...
```

The parent Helm chart `eck-operator` is still in `2.6.1`.
```
> helm search repo dev/eck-operator
NAME                                            CHART VERSION   APP VERSION     DESCRIPTION
elastic-dev/eck-operator                        2.6.1           2.6.1           A Helm chart for deploying the Elastic Cloud on...
elastic-dev/eck-operator-crds                   2.7.0           2.7.0           A Helm chart for installing the ECK operator Cu...
elastic-helm-charts-dev/eck-operator            2.6.1           2.6.1           A Helm chart for deploying the Elastic Cloud on...
elastic-helm-charts-dev/eck-operator-crds       2.7.0           2.7.0           A Helm chart for installing the ECK operator Cu...
```

**Comment by naemono** [comment]
@thbkrkr I think the `2.7.0` version of the `crds` Helm chart is the one released before resolution of #6554 . There's a CDN in front of  `elastic-helm-charts-dev` and you're getting a cached version of the `index.yaml` file, which doesn't include the newly uploaded charts.

If I pull the index.yaml file straight from the gs bucket, I see the `eck-operator` helm chart.

**Comment by thbkrkr** [comment]
Well seen! I deleted then added the repositories again and now it looks good.

**Comment by thbkrkr** [comment]
And for the `elastic-helm-charts-dev`, I have the dev helm repo twice with different names, although I have no idea how it got there. 
```sh
> helm repo list | grep dev
NAME                    URL
elastic-dev             https://helm-dev.elastic.co
elastic-helm-charts-dev https://helm-dev.elastic.co
```
So no problem here either.
