### ISSUE TITLE
Tanzu state not persisted

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6576]
When creating a Tanzu cluster, the installer state directory is not persisted in the Azure storage container.

https://github.com/elastic/cloud-on-k8s/blob/a4de99fc6f38da8d5c00ff6a34b5964f5734d324/hack/deployer/runner/tanzu.go#L433-L438

Discovered in #6525.

Once fixed, we can re-enable e2e tests here: https://github.com/elastic/cloud-on-k8s/pull/6525/commits/4d952b661b68c4a9be388670ae9c63ff25db7940.

**Comment by thbkrkr** [comment]
I tested and it requires `--recursive`.
```
> az storage azcopy blob upload -c eck-e2e-tanzu-test-1 --account-name cloudonk8s -s dirstate
failed to perform copy command due to error: cannot start job due to error: cannot scan the path /dirstate, please verify that it is a valid.

> az storage azcopy blob upload -c eck-e2e-tanzu-test-1 --account-name cloudonk8s -s /home/dirstate3a
failed to perform copy command due to error: cannot use directory as source without --recursive or a trailing wildcard (/*)

> az storage azcopy blob upload -c eck-e2e-tanzu-test-1 --account-name cloudonk8s -s /home/dirstate3a --recursive
Job b06c83af-e946-be40-4a84-7c41c27aa62c has started
...
0.0 %, 0 Done, 0 Failed, 2 Pending, 0 Skipped, 2 Total,
...
Total Number of Transfers: 2
```

There is also an issue with the path.

https://github.com/elastic/cloud-on-k8s/blob/a4de99fc6f38da8d5c00ff6a34b5964f5734d324/hack/deployer/runner/tanzu.go#L115-L117

During the cluster setup we run the tanzu cli in a container with `HOME=/root` and create `/root/tempdirstate` (stored in `installerStateDirPath`).

To store the state, we run the az cli in a container with `HOME=/home` and use the `installerStateDirPath`.

We should use ` installerStateDirBasename` instead or run the container with `HOME=/root`.

**Comment by thbkrkr** [comment]
I've not completely tested but I think there will be another issue because one config file contains the absolute path to another config file and we use a generated temporary directory for the `installerStateDirPath` that is different when we upload the state after the cluster creation and when we download the state to get the kubeconfig. 

The minimal steps to retrieve the kubeconfig of the workload cluster is to:

- have these 2 files:

```sh
> tree dirstate -a
dirstate/
├── .config
│   └── tanzu
│       └── config.yaml
└── .kube-tkg
    └── config
```

```
> cat dirstate/.config/tanzu/config.yaml
apiVersion: config.tanzu.vmware.com/v1alpha1
current: tkg-mgmt-azure-20230323194145
kind: ClientConfig
servers:
- managementClusterOpts:
    context: tkg-mgmt-azure-20230323194145-admin@tkg-mgmt-azure-20230323194145
    path: /root/dirstate/.kube-tkg/config # <---- THIS
  name: tkg-mgmt-azure-20230323194145
  type: managementcluster
```


- run:
```
tanzu plugin install cluster
tanzu cluster kubeconfig get eck-e2e-tanzu-test-1 --admin --export-file /root/.kube/config
```

**Comment by pebrc** [comment]
Excellent analysis! Could we work around the absolute path being part of the config by using a predictable name for the temp directory that stays the same between build steps? I think a fixed work dir can already be configured.
