### ISSUE TITLE
Multiple operatorhub/quay.io releases are seen as "latest".

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#6665]
related #6511 

After resolving the issue where we were not tagging the `latest` release in operatorhub environment, and after the release of `2.7.0`, we are seeing that multiple versions are now tagged as `latest`. This seems contradictory as to how most container registries work where only one can be tagged as `latest`. We need to investigate why this is happening during release, and ensure only the latest release is tagged as `latest`.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/4429174/230251874-5357919f-7dcb-4039-ac74-2207dea622cd.png">

**Comment by thbkrkr** [comment]
Syncing tags for version `2.4.0` removed the `latest` tag from version `2.4.0`. I'm not sure there's more to do here other than checking the "latest" tag on the next release.

<img width="1529" alt="Capture d’écran 2023-04-06 à 13 59 08" src="https://user-images.githubusercontent.com/582883/230373155-56eb91b2-bfaf-49da-8a68-87d9ff7469a9.png">

**Comment by naemono** [comment]
@thbkrkr See #6670. I think this is what we're needing to do according to https://catalog.redhat.com/api/containers/docs/objects/CertProjectImageRequest.html?highlight=sync&tab=Fields
