### ISSUE TITLE
Remove `is_default` and `is_default_fleet_server` flag from ECK recipes

### ISSUE THREAD

**Issue by juliaElastic** [elastic/cloud-on-k8s#6678]
Flags `is_default` and `is_default_fleet_server` are deprecated since 8.1.

Remove these from ECK recipes:
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-kubernetes-integration.yaml#L30

The change should be tested, so that Fleet on Kubernetes still works after removing these flags.

_Originally posted by @jen-huang in https://github.com/elastic/ingest-docs/issues/76#issuecomment-1499426546_

**Comment by barkbay** [comment]
> We could find another way to detect defaults (I have some ideas but not familiar enough with the Fleet API...)

My idea was to automatically detect a "Default Fleet Server policy" and a "Default Agent Policy" as long as the following conditions were met:
* There are only 2 policies.
* One of these 2 policies can clearly be detected as a "Fleet Server policy". That policy would have been the "Default Fleet Server Policy" Consequently the other one would have been the "Default Agent Policy".

Unfortunately, without `is_default` and `is_default_fleet_server`, I don't think we can select a default policy from the Fleet API answer:

```json
{
	"items": [{
		"id": "eck-agent",
		"namespace": "default",
		"monitoring_enabled": ["logs", "metrics"],
		"name": "Elastic Agent on ECK policy",
		"unenroll_timeout": 900,
		"inactivity_timeout": 1209600,
		"is_preconfigured": true,
		"status": "active",
		"is_managed": false,
		"revision": 3,
		"updated_at": "2023-04-24T14:44:26.541Z",
		"updated_by": "system",
		"schema_version": "1.0.0",
		"agents": 0
	}, {
		"id": "eck-fleet-server",
		"namespace": "default",
		"monitoring_enabled": ["logs", "metrics"],
		"name": "Fleet Server on ECK policy",
		"unenroll_timeout": 900,
		"inactivity_timeout": 1209600,
		"is_preconfigured": true,
		"status": "active",
		"is_managed": false,
		"revision": 2,
		"updated_at": "2023-04-24T14:44:20.503Z",
		"updated_by": "system",
		"schema_version": "1.0.0",
		"agents": 0
	}],
	"total": 2,
	"page": 1,
	"perPage": 20
}
```

While poking around with the Fleet API, by using the `full` parameter in the query (`agent_policies?perPage=20&full=true`),  I noticed that the Fleet Server policy holds a package named `fleet_server`. But it seems a bit "hacky" or "brittle" do detect the default Fleet Server policy that way? 😕 By "brittle" I mean that I have the feeling that we would rely on something (a specific policy name), which should be out of the scope of ECK.

```json
		"package_policies": [{
			"id": "fleet_server-1",
			"version": "WzY5MSwxXQ==",
			"name": "fleet_server-1",
			"namespace": "default",
			"package": {
				"name": "fleet_server", ## Here
				"title": "Fleet Server",
				"version": "1.2.0"
			},
```

@juliaElastic please let me know if my reasoning is correct 🙏 

Unless someone else has an idea, I think I'll create a PR to make `policyID` a required field and flag this as a breaking change.

**Comment by juliaElastic** [comment]
@barkbay Yes, the policy with the `fleet_server` integration is the fleet server policy.

Would it be possible to remove the `is_default` flags from the recipes and pass the `policyID` instead, but also keep the default detection logic in place to avoid the breaking change?
