### ISSUE TITLE
Provide an example for S3 snapshots

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#669]
Our current snapshot docs demonstrate how to perform snapshots in a GCS repository.
We should complete it with another example using S3, once https://github.com/elastic/k8s-operators/pull/661 is merged.

**Comment by pebrc** [comment]
We decided not to enumerate all vendor variants for storage plugins. Elasticsearch docs should suffice https://github.com/elastic/cloud-on-k8s/issues/398#issuecomment-505035618
