### ISSUE TITLE
base path setting on stackconfigpolicy snapshot repository

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6692]
For cloud repositories (azure, gcs, s3), ECK sets `base_path` to `snapshots/<namespace>-<esName>` and it's not possible to override it. This is problematic for example to configure a read-only repository where a user wants full control of the `base_path`.

https://github.com/elastic/cloud-on-k8s/blob/ae88fe1662ed9f04fabc063edfdaaa4984ddb6d1/pkg/controller/elasticsearch/filesettings/file_settings.go#L148

I missed the original intent that was to only add `<namespace>-<esName>` to the user provided `base_path` like it's done for `location` for `fs` repository and `path` for `hdfs` repository. But this is also a problem if the need is to fully control the `base_path`.

I could see 3 cases, but I'm not sure we need to deal with the third one, which makes everything more complex because we need to be able to distinguish it from the second one.

| | user provided `base_path` | configured `base_path` |
|---|---|---|
| 1) no base_path |  | `snapshots/ns1-es1`|
| 2) full base_path | `some/thing` | `some/thing` |
| 3) partial base_path | `some/thing` | `some/thing/ns1-es1` |

**Comment by pebrc** [comment]
What would be the use case for the 3 case?

**Comment by thbkrkr** [comment]
A use-case where you want something else than `snapshots` as the location to write the snapshots in the bucket.

Imagine you have two environments but you are restricted to one bucket (ok, it's bizarre, but) and you want to configure a different `base_path` per env so you can have the same name for the clusters: `snapshots-qa/ns1-es1` & `snapshots-prod/ns1-es1`.

Use-case 2 makes sense only for read-only repositories. For write/read repositories, you need 1 or 3.

**Comment by thbkrkr** [comment]
I think so too and this is the option I finally opted into https://github.com/elastic/cloud-on-k8s/pull/6689.
