### ISSUE TITLE
Buildkite job annotation must not be larger than 1MB

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#6697]
```
Failed to annotate build: POST https://agent.buildkite.com/v3/jobs/.../annotations: 400 The annotation body must be less than 1 MB
```

I assume the size results from the test runner output being part of the collapsible test failure sections. I am not sure how we can trim those.

**Comment by thbkrkr** [comment]
I chose `3000 bytes` in #6699, thinking that when the stack trace is longer, it is very rarely useful. And anyway, it will always be possible to go and see the raw stack trace because we upload the tests result json file.
