### ISSUE TITLE
Decouple Elasticsearch config bits from the process management bits

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#671]
Currently the process manager serves the checksum of the Elasticsearch configuration file into the process status. These two things are not related. It would be cleaner to decouple the ES configuration file bits from the process management bits.

Following of #561.

**Comment by sebgl** [comment]
Closing as we got rid of the process manager with https://github.com/elastic/cloud-on-k8s/pull/1249.
