### ISSUE TITLE
Use `with` syntax in Helm Charts

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6716]
Follow-up of https://github.com/elastic/cloud-on-k8s/pull/6711#discussion_r1172811833.

`with` is [syntaxic sugar](https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with) that we could use it the ECK Helm charts in many places where we do `"if A; then A"`:

`if` syntax:
```yaml
{{- if .Values.config.something }}
something: {{ .Values.config.something }}
{{- end }}
```

`with` syntax:
```yaml
{{- with .Values.config.something }}
something: {{ . }}
{{- end }}
```

**Comment by Unknovvn** [comment]
Hey. I would like to handle this issue. Could you assign it to me?
