### ISSUE TITLE
a Dedicate Kubernetes service for indexing data

### ISSUE THREAD

**Issue by itayB** [elastic/cloud-on-k8s#6759]
## Bug Report
We are running a 8.7.0 Elasticsearch with elastic operator 2.7.0.
We have a dedicated data nodes (let's call them `data-wrk`) where we bake our indices (which later on becomes read-only and relocated to a dedicated data nodes for searching).
We are using Python and bulk API to index to multiple indices concurrently.
While creating a different node "groups" (which are different by their name, roles and awareness attributes) we see that a dedicated service was created by the operator to each one of the groups - as opposed to the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-traffic-splitting.html) that says that we should create it manually.
Now we got that:
```
Name:              elasticsearch-aud-es-data-wrk
Namespace:         elasticsearch-cdp
Labels:            common.k8s.elastic.co/type=elasticsearch
                   elasticsearch.k8s.elastic.co/cluster-name=elasticsearch-aud
                   elasticsearch.k8s.elastic.co/statefulset-name=elasticsearch-aud-es-data-wrk
Annotations:       <none>
Selector:          common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=elasticsearch-aud,elasticsearch.k8s.elastic.co/statefulset-name=elasticsearch-aud-es-data
-wrk
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              http  9200/TCP
TargetPort:        9200/TCP
Endpoints:         10.2.12.233:9200,10.2.16.47:9200,10.2.17.142:9200 + 5 more...
Session Affinity:  None
Events:            <none>
```
In addition to the default one:
```
Name:              elasticsearch-aud-es-http
Namespace:         elasticsearch-cdp
Labels:            common.k8s.elastic.co/type=elasticsearch
                   elasticsearch.k8s.elastic.co/cluster-name=elasticsearch-aud
Annotations:       <none>
Selector:          common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=elasticsearch-aud
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                x.y.z.56
IPs:               x.y.z.56
Port:              http  9200/TCP
TargetPort:        9200/TCP
Endpoints:         10.2.12.233:9200,10.2.16.47:9200,10.2.17.72:9200 + 12 more...
Session Affinity:  None
```

**Questions:**
* Are those documentations up to date? we didn't expect to see this service.
* The `elasticsearch-aud-es-http` service has `IP`/`IPs` while `elasticsearch-aud-es-data-wrk` doesn't (although it has `Endpoints` and it seems to work) - does it mean that it misconfigured?
* Should I use a single host (the service url) in Python's elasticsearch client? Am I losing something by doing that instead of giving a list of hosts (data-nodes) to the client? (for HA) I ask it [here](https://discuss.elastic.co/t/bulk-via-python-to-kubernetes-cluster/329065) as well.
* When one node (from the `Endpoints` list) goes down - my Python code returns 
```
elastic_transport.ConnectionError: Connection error caused by: ClientConnectorError(Cannot connect to host elasticsearch-aud-es-http.elasticsearch-cdp.svc.cluster.local:9200 ssl:default [Temporary failure in name resolution])
Node <AiohttpHttpNode(http://elasticsearch-aud-es-http.elasticsearch-cdp.svc.cluster.local:9200/)> has been marked alive after a successful request [_node_pool.py:266]
``` 
does this service knows to route me to a different data-node if the connection is open and node goes down? (round-robin per request of something like that?

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:
	2.7.0

* Kubernetes information:
	* Cloud: EKS 1.22

**Comment by jmp601** [comment]
We do this with node.roles spec as shown here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html

A dedicated ingest node would be:

node.roles: "[ingest]"

**Comment by thbkrkr** [comment]
> Are those documentations up to date? we didn't expect to see this service.
> The elasticsearch-aud-es-http service has IP/IPs while elasticsearch-aud-es-data-wrk doesn't (although it has Endpoints and it seems to work) - does it mean that it misconfigured?

Yes. What you see are [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) deployed per ECK per nodeSet to interact directly with the Pods instead of a proxy since the beginning. These services are internal to the operator, so we have chosen not to mention them in the documentation.


> Should I use a single host (the service url) in Python's elasticsearch client? Am I losing something by doing that instead of giving a list of hosts (data-nodes) to the client? (for HA) I ask it here as well.
> does this service knows to route me to a different data-node if the connection is open and node goes down? (round-robin per request of something like that?

Yes, you should use the service URL. From https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation: "Clients can connect using that virtual IP address, and Kubernetes then load-balances traffic to that Service across the different backing Pods.".

> When one node (from the Endpoints list) goes down - my Python code returns
> elastic_transport.ConnectionError: Connection error caused by: ClientConnectorError(Cannot connect to host elasticsearch-aud-es-http.elasticsearch-cdp.svc.cluster.local:9200 ssl:default [Temporary failure in name resolution])
> Node <AiohttpHttpNode(http://elasticsearch-aud-es-http.elasticsearch-cdp.svc.cluster.local:9200/)> has been marked alive after a successful request [_node_pool.py:266]

`Temporary failure in name resolution` looks like a DNS issue.
