### ISSUE TITLE
ECK Fleet APM Node.JS agent logs "APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200"

### ISSUE THREAD

**Issue by khteh** [elastic/cloud-on-k8s#6762]
## Bug Report
**What did you do?**
I have installed and run ECK 8.7.1 with fleet:
```
$ k get agent
NAME            HEALTH   AVAILABLE   EXPECTED   VERSION   AGE
elastic-agent   green    6           6          8.7.1     84m
fleet-server    green    3           3          8.7.1     84m
```
**Kibana version**: 8.7.1

**Elasticsearch version**: 8.7.1

**APM Server version**: 8.7.1

**APM Agent language and version**: Node.JS `"elastic-apm-node": "^3.45.0",`
My application config:
```
var apm = require('elastic-apm-node').start({
  // Override service name from package.json
  // Allowed characters: a-z, A-Z, 0-9, -, _, and space
  serviceName: 'myapplication-apm',
  // Use if APM Server requires a token
  secretToken: '',
  // Use if APM Server uses API keys for authentication
  apiKey: '',
  // Set custom APM Server URL (default: http://127.0.0.1:8200)
  serverUrl: '',
  // Only activate the agent if it's running in production
  active: process.env.NODE_ENV === 'production'
})
```
My application log:
```
{"log.level":"error","@timestamp":"2023-05-05T07:42:34.295Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200"}
```

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version: 8.7.1

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? No
	* Cloud: GKE / EKS / AKS ? EKS
	* Kubernetes distribution: Openshift / Rancher / PKS ? EKS
	
	for each of them please give us the version you are using
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-25T19:00:00Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.2-eks-a59e1f0", GitCommit:"8b68f4b95d7121d039ceebd30870e48acc7772e4", GitTreeState:"clean", BuildDate:"2023-03-09T19:59:45Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```
Whenever I click "Launch APM" button in Kibana, the following screen appears for a slit second and then disappears.
![Screenshot from 2023-05-05 15-17-15](https://user-images.githubusercontent.com/3871483/236405328-1860f904-9405-4aaa-a9a6-fc0dc8a0a714.png)

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by naemono** [comment]
@khteh could you please share a bit more information?

`ECK 8.7.1`: The most recent ECK version is 2.10, which was released today. Are you perhaps running ECK 2.7?

Could you share complete Yaml manifests so we could properly replicate the issue and identify the core problem?

Thanks much for the issue.
