### ISSUE TITLE
ApmServer secret token config is invalid for APM Server 8.0+

### ISSUE THREAD

**Issue by axw** [elastic/cloud-on-k8s#6768]
https://github.com/elastic/cloud-on-k8s/blob/f82671958ae2f529b1cc626112d0bddaf8b41205/pkg/controller/apmserver/config.go#L30

ECK is setting outdated configuration for the APM secret token, that was removed in APM Server 8.0 (https://www.elastic.co/guide/en/apm/guide/current/release-notes-8.0.html#_breaking_changes_7). This should be updated to `apm-server.auth.secret_token` for 8.0+

The outcome of this bug is that, by default, APM Server has no secret token auth configured.

**Comment by pebrc** [comment]
@barkbay I think we should try to fix this for the upcoming 2.8 release wdyt?

**Comment by barkbay** [comment]
> @barkbay I think we should try to fix this for the upcoming 2.8 release wdyt?

Yes 👀
