### ISSUE TITLE
Document how users can access Elasticsearch

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#677]
We need something more in-depth than the quickstart tutorial to explain:

- the es service we create
- how the es service can be exposed (ClusterIP, NodePort, LoadBalancer)
- how to build the Elasticsearch URL (https://<service>:9200)
- users we create
- certificates we create
- how to request the ES endpoint using basic auth + certificate validation with the CA
- mention the ingress doc?

**Comment by thbkrkr** [comment]
Closed by #983.
