### ISSUE TITLE
Filebeat/autodiscover ES_data_should_pass_validations fails in 8.9.0-SNAPSHOT

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6946]
[cloud-on-k8s-operator-nightly/builds/217@stack-8.9.0-SNAPSHOT](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/217#0188dfec-e18a-4ab9-b938-04ce543b4953)

- TestFilebeatDefaultConfig/ES_data_should_pass_validations
- TestBeatSecureSettings/ES_data_should_pass_validations 
- TestBeatConfigRef/ES_data_should_pass_validations

```go
--- FAIL: TestFilebeatDefaultConfig (1887.47s)
    --- FAIL: TestFilebeatDefaultConfig/ES_data_should_pass_validations (1800.00s)
                Error Trace:    /go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
                Error:          Received unexpected error:
                                hit count should be more than 0 for /*beat*/_search?q=agent.type:filebeat

--- FAIL: TestBeatSecureSettings (1888.35s)
    --- FAIL: TestBeatSecureSettings/ES_data_should_pass_validations (1800.00s)
                Error Trace:    /go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
                Error:          Received unexpected error:
                                hit count should be more than 0 for /*beat*/_search?q=agent.type:filebeat

--- FAIL: TestBeatConfigRef (1896.88s)
    --- FAIL: TestBeatConfigRef/ES_data_should_pass_validations (1800.00s)
                Error Trace:    /go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
                Error:          Received unexpected error:
                                hit count should be more than 0 for /*beat*/_search?q=agent.type:filebeat
```

**Comment by thbkrkr** [comment]
Running `TestFilebeatDefaultConfig` locally I see missing RBAC permissions to use Filebeat with autodiscover, not sure if this is the root cause:

```
E0627 12:15:14.396909       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: 
  Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: replicasets.apps is forbidden: 
  User "system:serviceaccount:e2e-mercury:test-fb-default-cfg-d26k-sa" cannot list resource "replicasets" in
  API group "apps" at the cluster scope
```

**Comment by thbkrkr** [comment]
I asked the Beats team to confirm if this change is normal.

**Comment by thbkrkr** [comment]
I got confirmed that the change is normal. These permissions are required since a very long time.

However, a recent change makes that when the permissions are not set, the errors are propagated and that is why we only see them now.
- https://github.com/elastic/elastic-agent-autodiscover/pull/44
- https://github.com/elastic/beats/pull/35483
- https://github.com/elastic/elastic-agent-autodiscover/issues/31

Going back in time and following the movement of the source code, I think these permissions are required since: 
- `7.12` for ReplicaSets: https://github.com/elastic/beats/pull/23610 
- `8.2` for Jobs: https://github.com/elastic/beats/pull/30637

We need to update our manifests with Filebeat using autodiscover in `config/recipes/beats`.

**Comment by barkbay** [comment]
I'm closing this one as I think this particular issue is fixed (feel free to reopen if I'm wrong)
New failures are tracked in https://github.com/elastic/cloud-on-k8s/issues/7172
