### ISSUE TITLE
Reload TLS certificate in the process manager

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#702]
TLS certificate are mounted into Elasticsearch pods through a secret volumes, and used by the process-manager.
When a certificate is close to expire, the operator signs a new one, propagated through the secret volume. Elasticsearch reloads it automatically when a change is detected on disk.

Since we don't do the same in the process-manager, we keep on using an old outdated certificate. The operator detects an expired certificate when issuing requests to the process-manager and returns an error, preventing restarts to happen correctly.

**Comment by thbkrkr** [comment]
Closing as we decided to retire the process manager see #1199.
