### ISSUE TITLE
Write a user-facing doc about upgrades and debugging

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#703]
We should have a user facing doc explaining how to:

* change Elasticsearch configuration
* change cluster topology
* upgrade ES version
* quick overview of what happens behind the scene (new pod vs. pod reuse vs. pvc reuse), without entering into too many technical details
* debug failing scenarios (get ES nodes logs, delete a pod, change the config, kubectl exec, rollback, etc.)

**Comment by alaudazzi** [comment]
Closed in favour of #1143, #1144, #1145.
