### ISSUE TITLE
(Release) Build creates invalid install manifest

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#7032]
Build for rc5 as an example https://buildkite.com/elastic/cloud-on-k8s-operator/builds/4899#01894938-f453-4a20-85fc-e117253284a4

Evidence https://download.elastic.co/downloads/eck/2.9.0-bc5/operator.yaml

```
 serviceAccountName: eck-operator-root
 - image: "docker.elastic.co/eck-dev/eck-operator-root:2.9.0-3e40d5b9"
 ```

when it should be: 

```
 serviceAccountName: eck-operator
 - image: "docker.elastic.co/eck/eck-operator:2.9.0-bc5"
```

So it looks like the `OPERATOR_NAME`, `REGISTRY_NAMESPACE` and `IMAGE_TAG` environment variables are not set correctly when generating the manifest. `OPERATOR_NAME` takes `IMAGE_SUFFIX` as an input which needs to be setup https://github.com/elastic/cloud-on-k8s/blob/dc79edd0b2f1ef64742ea8269164773c864bd605/Makefile#L44

cc @thbkrkr

**Comment by thbkrkr** [comment]
Closed by https://github.com/elastic/cloud-on-k8s/pull/7034.
