### ISSUE TITLE
Helm dev release from main instead of release branch

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#7033]
Build for rc5 released `helm/eck-operator/eck-operator-2.10.0-SNAPSHOT.tgz` from main instead of `helm/eck-operator/eck-operator-2.9.0-bc5.tgz` from 2.9

I think we need to pass on the branch information when calling the other pipeline wdyt? @thbkrkr

**Comment by thbkrkr** [comment]
I thought the build context (at least branch, commit, message) was propagated when another pipeline was triggered.
But it is not, by default the branch is the triggered pipeline's default branch, commit is HEAD and the message is the label of the trigger step.

So yes, you are right, we need to pass the branch on the trigger step.
