### ISSUE TITLE
Write an ADR about cluster changes

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#704]
Describe what happens behind the scene when we perform:

* configuration change
* version upgrade
* "topology" change

This should cover:

* pods creation and deletion (grow-and-shrink approach)
* pods reuse and rolling restart with config propagation and process manager interaction
* pvc reuse
* how the user can configure those

**Comment by pebrc** [comment]
This somehow overlaps with https://github.com/elastic/cloud-on-k8s/issues/1144 
Maybe public facing docs is as good as an ADR and we can close this one?
