### ISSUE TITLE
Stack monitoring for beats missing

### ISSUE THREAD

**Issue by padzikm** [elastic/cloud-on-k8s#7051]
Hi, I configured stack monitoring for elasticsearch, kibana and beats in eck 2.8.0 (cluster is monitoring itself). I can see elasticsearch and kibana in kibana ui, but beats are missing. I don't have elasticsearch ref in beats definition and I don't have elasticsearch in beats output, as I send logs to logstash (and having elasticsearch ref in beats caused error with two outputs in beats). How can I see beats monitoring in kibana ui?

**Comment by TimBosman** [comment]
Hey, did you take a look at [this documentation page](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-stack-monitoring.html)? It explains how to set up monitoring for Elasticsearch, Kibana, Logstash and Beats.

**Comment by barkbay** [comment]
Closing this one as stack monitoring is supported for Elasticsearch, Kibana, Beats and Logstash.
