### ISSUE TITLE
[Bug] Cannot install Elastic operator with k8s namespace level permissions only

### ISSUE THREAD

**Issue by Kavish1407** [elastic/cloud-on-k8s#7063]
I am trying to Deploy eck-elasticsearch, eck-operator with restricted-profile using helm charts,
I only have namespace-level permissions in my k8s cluster,
But the operator requires Daemonset permissions which is cluster level, and is thowing error because of it

-->

## Proposal
The elasticsearch operator should work with namespace level permissions as well

Tried installing eck-operator without daemonset permissions as it is cluster level 

**What did you expect to see?**
ECK operator should be installed with namespace level permissions as well

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version: 2.7.0

* Kubernetes information:
	* On premise - v1.22

```
$ kubectl version- v1.22
```

* Logs:
1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "" cannot list resource "daemonsets" in API group "apps" in the namespace ""
```

cc: @mohitevishal

**Comment by pebrc** [comment]
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-eck-permissions.html#k8s-eck-permissions-running

RBAC access to DaemonSets is one of the listed requirements for ECK. Also I am not sure what you mean by cluster-level here. DaemonSets are namespaced resources. I am closing this issue as I don't see an ECK bug here.
