### ISSUE TITLE
Kibana: Provide possibility for having a Pod Disruption Budget (PDB)

### ISSUE THREAD

**Issue by OmarHawk** [elastic/cloud-on-k8s#7065]
## Proposal
Hi,

we'd like to have a possibility to configure a Pod Disruption Budget / and or at least a standard PDB that avoid any downtime when a version update of Kibana is happening through the operator.

**Use case. Why is this important?**
We use automation in order to provide a default set of Dashboards and index patterns in all our stages. For that, we use the import objects API of Kibana while applying corresponding resources. While a version upgrade is running, the Kibana deployment is completely restarted at once, leaving also the Kibanan API unavailable for the time being, forcing us to wait for it to be up and running again, before we can POST some data again to the API.

Unfortunately, Kibana configured through the operator currently doesn't support something like a Pod Disruption Budget and also does not provide a default one, so without anything manually extra (which I don't really like), it is not possible to avoid downtimes during a version update (afaik).

https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-api-kibana-k8s-elastic-co-v1.html

**Comment by ebuildy** [comment]
I believe this is by design, you can only have 1 instance of Kibana running, because index migration stuff.

**Comment by OmarHawk** [comment]
Well, you can define the replica amount, so why would that be possible if there can only be 1 instance

**Comment by barkbay** [comment]
> While a version upgrade is running, the Kibana deployment is completely restarted at once

This is indeed by [design](https://github.com/elastic/cloud-on-k8s/blob/07d3efef731798333c0c54934b0890d2e71e5412/pkg/controller/kibana/driver.go#L193-L214), refer to the Kibana documentation [here](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-kibana.html) regarding version upgrade:

> 1. Shut down all Kibana instances. Kibana does not support rolling upgrades. Upgrading while older Kibana instances are running can cause data loss or upgrade failures.

**Comment by OmarHawk** [comment]
> > While a version upgrade is running, the Kibana deployment is completely restarted at once
> 
> This is indeed by [design](https://github.com/elastic/cloud-on-k8s/blob/07d3efef731798333c0c54934b0890d2e71e5412/pkg/controller/kibana/driver.go#L193-L214), refer to the Kibana documentation [here](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-kibana.html) regarding version upgrade:
> 
> > 1. Shut down all Kibana instances. Kibana does not support rolling upgrades. Upgrading while older Kibana instances are running can cause data loss or upgrade failures.

Well, that is indeed a bit disappointing. Sorry for not consulting the documentation first, but to be honest, I did not even expect this to be the reason...
