### ISSUE TITLE
Helm install failed with the error failed when downloading eck-operator

### ISSUE THREAD

**Issue by just-NPT** [elastic/cloud-on-k8s#7075]
## Proposal

Helm install failed with the error failed when downloading eck-operator

## Bug Report
**What did you do?**
I just follow the tutorial in here [https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-stack](url) 
and I just finish first step is `helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace`
**What did you expect to see?**
I expect elastic-operator pod run healthily to install ECK Stack 
**What did you see instead? Under which circumstances?**
The pod keeps restart and this is it's log 
`{"log.level":"error","@timestamp":"2023-08-03T09:04:20.707Z","log.logger":"manager","message":"Error setting GOMAXPROCS","service.version":"2.9.0+f24ccc37","service.type":"eck","ecs.version":"1.4.0","error":"path \"/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c\" is not a descendant of mount point root \"/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c/kubelet\" and cannot be exposed from \"/sys/fs/cgroup/misc/kubelet\"","error.stack_trace":"github.com/elastic/cloud-on-k8s/v2/cmd/manager.startOperator\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:427\ngithub.com/elastic/cloud-on-k8s/v2/cmd/manager.doRun.func2\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:394"}
{"log.level":"error","@timestamp":"2023-08-03T09:04:20.709Z","log.logger":"manager","message":"Operator stopped with error","service.version":"2.9.0+f24ccc37","service.type":"eck","ecs.version":"1.4.0","error":"path \"/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c\" is not a descendant of mount point root \"/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c/kubelet\" and cannot be exposed from \"/sys/fs/cgroup/misc/kubelet\"","error.stack_trace":"github.com/elastic/cloud-on-k8s/v2/cmd/manager.doRun.func2\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:396"}
{"log.level":"error","@timestamp":"2023-08-03T09:04:20.709Z","log.logger":"manager","message":"Shutting down due to error","service.version":"2.9.0+f24ccc37","service.type":"eck","ecs.version":"1.4.0","error":"path \"/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c\" is not a descendant of mount point root \"/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c/kubelet\" and cannot be exposed from \"/sys/fs/cgroup/misc/kubelet\"","error.stack_trace":"github.com/elastic/cloud-on-k8s/v2/cmd/manager.doRun\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:405\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
Error: path "/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c" is not a descendant of mount point root "/docker/73fc5ee2ec11d0425d0d9b3d5dd62590b4902ecf389f5b63732eeec250e8318c/kubelet" and cannot be exposed from "/sys/fs/cgroup/misc/kubelet"`
**Environment**

- Minikube version:

![image](https://github.com/elastic/cloud-on-k8s/assets/59968811/355f301a-9447-426c-8320-c9e580648792)

- kubectl version:

![image](https://github.com/elastic/cloud-on-k8s/assets/59968811/32384278-c1a3-4de9-adda-4acf2848f1c4)

- helm version:

![image](https://github.com/elastic/cloud-on-k8s/assets/59968811/61215e04-c839-4722-84a5-643ac53710ff)
* ECK version:
I think it's latest version

* Logs:
![image](https://github.com/elastic/cloud-on-k8s/assets/59968811/b426c323-b752-4173-9dd7-91647b8a20f2)

**Comment by thbkrkr** [comment]
Although you're using a fairly recent version of minikube, it looks like:
- https://github.com/elastic/cloud-on-k8s/issues/5325

Could you please try again with minikube [v1.31.0](https://github.com/kubernetes/minikube/releases/tag/v1.31.0) that contains https://github.com/kubernetes/minikube/pull/14152?

**Comment by thbkrkr** [comment]
#7077 confirmed that `v1.30.1` suffers from this bug and `v1.31.0` fixes it.
