### ISSUE TITLE
Allow users to provide their own CA and certificates

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#714]
Several things to consider:

- users provide their own CA, and we need a way to sign certificates with this CA
and/or:
- users provide their own node certificates

**Comment by pebrc** [comment]
* #776

**Comment by pebrc** [comment]
https://github.com/elastic/cloud-on-k8s/pull/1013 adds support for custom HTTP certificates. We won't add any facilities to customize the certificates for the internal TLS between nodes for now.
