### ISSUE TITLE
Include an example of how to use the CA cert within the cluster in the docs

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#715]
Improve the documentation in https://github.com/elastic/cloud-on-k8s/pull/983 to add more details about:

* the CA cert can be mounted into pods
* explain how a Python program running in the cluster can use it

**Comment by sebgl** [comment]
Related: https://github.com/elastic/cloud-on-k8s/issues/798

**Comment by pebrc** [comment]
Closing this as we have an example for in-cluster access in https://www.elastic.co/guide/en/cloud-on-k8s/0.9/k8s-accessing-elastic-services.html#k8s-request-elasticsearch-endpoint (even though it is not using the python client but `curl`)
