### ISSUE TITLE
Remove trailing whitespaces from operator's values.yaml file

### ISSUE THREAD

**Issue by bpankowski** [elastic/cloud-on-k8s#7178]
## Bug Report
**Remove trailing whitespaces from operator's values.yaml file**

**What did you expect to see?**
No trailing whitespaces in lines 247(https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml#L247) and 251(https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml#L251) which ones holds comments for `global` section.

**What did you see instead? Under which circumstances?**
Trailing whitespaces in `values.yaml`

**Environment**

* ECK version:

	- 2.9

**Comment by notpeter** [comment]
This can be closed.  It was fixed by:
- #7179
