### ISSUE TITLE
Clarify how to reset the password of the default user

### ISSUE THREAD

**Issue by rodrigc** [elastic/cloud-on-k8s#7182]
## Proposal

This blog post has some good details on how to reset the default user's password by deleting the Kubernetes secret:

https://www.gooksu.com/2022/03/elasticsearch-on-k8s-eck-all-about-passwords/

It would be good to incorporate this tip into the official operator documentation.

**Comment by barkbay** [comment]
I think it is already explained here: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-rotate-credentials.html#k8s-rotate-credentials I would only add a link instead.
