### ISSUE TITLE
Document filebeat/metricbeat integration with ECK clusters

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/cloud-on-k8s#719]
Something like:

# Deploy Filebeat and Metricbeat
The steps are:
* Find the service names for Elasticsearch and Kibana
* Determine the fully qualified DNS names for the services
* Create a Kubernetes Secret
* Deploy kube-state-metrics
* Deploy the Beats
* Deploy a sample application

## Find the service names for Elasticsearch and Kibana
```
kubectl get services

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes                ClusterIP   10.96.0.1       <none>        443/TCP    1h
quickstart-es             ClusterIP   10.102.7.12     <none>        9200/TCP   33m
quickstart-es-discovery   ClusterIP   None            <none>        9300/TCP   33m
quickstart-kibana         ClusterIP   10.110.46.130   <none>        5601/TCP   15m
```

The above tells you that Elasticsearch is available in the default
namespace at the name `quickstart-es`, and Kibana is at `quickstart-kibana`

## Determine the fully qualified DNS names for the services
Because the services are in the `default` namespace, the fully qualified names are `quickstart-es.default.svc.cluster.local`
and `quickstart-kibana.default.svc.cluster.local`

## Create a Kubernetes Secret 
Using the service names and FQDNs from above you would perform these steps:

```
echo '["http://quickstart-es.default.svc.cluster.local:9200"]' > ELASTICSEARCH_HOSTS
echo '"http://quickstart-kibana.default.svc.cluster.local:5601"' > KIBANA_HOST
echo elastic > ELASTICSEARCH_USERNAME
echo changeme > ELASTICSEARCH_PASSWORD

kubectl create secret generic dynamic-logging \
   --from-file=./ELASTICSEARCH_HOSTS \
   --from-file=./ELASTICSEARCH_PASSWORD \
   --from-file=./ELASTICSEARCH_USERNAME \
   --from-file=./KIBANA_HOST \
   --namespace=kube-system
```

## Deploy kube-state-metrics if it is not already there
kube-state-metrics provides state and event information that Metricbeat collects.

```
kubectl get pods --namespace=kube-system | grep kube-state
git clone https://github.com/kubernetes/kube-state-metrics.git kube-state-metrics
kubectl create -f kube-state-metrics/kubernetes
kubectl get pods --namespace=kube-system -w | grep kube-state  
```

## Deploy Filebeat and Metricbeat

```
kubectl create -f https://raw.githubusercontent.com/elastic/examples/master/beats-k8s-send-anywhere/filebeat-kubernetes.yaml

kubectl create -f https://raw.githubusercontent.com/elastic/examples/master/beats-k8s-send-anywhere/metricbeat-kubernetes.yaml
```

## Verify
```
kubectl get pods --namespace=kube-system -w 
```

## Deploy a sample app
This is a sample application based on the [tutorial](https://kubernetes.io/docs/tutorials/stateless-application/guestbook/) at kubernetes.io
```
kubectl create -f https://raw.githubusercontent.com/elastic/examples/master/beats-k8s-send-anywhere/guestbook.yaml
```

# Verify
```
kubectl get pods -w
```

**Comment by mustafaakin** [comment]
The new clusters have SSL enabled as well, we need to mount ca.crt as well, I hoped this repo would have CRDs for *beat as well.

**Comment by DanRoscigno** [comment]
@mustafaakin yes, needs the cert also.  Here is how I do that:

## Get the CA cert

The Elasticsearch cluster that has been deployed is configured with TLS enabled, so we need to provide 
the cert to the Beats in order to connect.  The cert is added to a secret, let's grab that:

### List the secrets

```bash
kubectl get secrets| grep ca
```

```bash
elasticsearch-sample-ca                     Opaque                                1      5h
elasticsearch-sample-ca-private-key 
```
We need the ca.crt or ca.pem, not the private key

### Find the name of the cert:

```bash
kubectl get secret elasticsearch-sample-ca -o=json
```
This should be ca.pem


### Extract the ca:

Make sure to escape the dot in ca.pem
```bash
kubectl get secret elasticsearch-sample-ca -o=jsonpath='{.data.ca\.pem}' | base64 --decode
```

### Create a Kubernetes ConfigMap with the cert

Edit the manifest `vi kubecon2019/cert.yaml` and replace the sample with the decoded ca.pem.
Note: Indent the cert like it is in the sample.

Create the ConfigMap
```bash
kubectl create -f kubecon2019/cert.yaml
```

and then mount the configmap in the Beats.  I will document this.  In the meantime, if you need a hand let me know.

**Comment by sebgl** [comment]
Related to https://github.com/elastic/cloud-on-k8s/issues/715

**Comment by pebrc** [comment]
Closing this in favour of #2143
