### ISSUE TITLE
[Docs] Provide example of NetworkPolicy of Hot-Warm architecture

### ISSUE THREAD

**Issue by azhurbilo** [elastic/cloud-on-k8s#7201]
## Proposal

**Use case. Why is this important?**

this example doesn't cover Hot-Warm architecture https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s_prerequisites.html

as I understand es nodes of different layers (hot,warm,cold) communicates via 9200 port too or all data goes via 9300 but features like stack monitoring use 9200?

**Comment by ebuildy** [comment]
there is no difference, all elasticsearch nodes communicate with each others on port 9300.

Port 9200 is for HTTP API only, if you have a good cluster with master / client / data nodes, only client and data nodes should be accessible under port 9200.

**Comment by azhurbilo** [comment]
@ebuildy thnx for explanation!
