### ISSUE TITLE
how really add user and role in es?

### ISSUE THREAD

**Issue by aufkm** [elastic/cloud-on-k8s#7268]
**What did you expect to see?**
I`d expect to see a my own index in es

**What did you see instead? Under which circumstances?**
I see a bunch of errors from my logstash that say diffrent patterns about, with 1 main part:
```
error=>{
 "type"=>"security_exception",
 "reason"=>"action [indices:data/write/bulk[s]] is unauthorized for user 
    [elastic-stack-eck-stack-eck-logstash-elastic-stack-quickstart-logstash-user] with effective roles 
    [eck_logstash_user_role] on indices [hey], this action is granted by the index privileges 
    [create_doc,create,delete,index,write,all]
"}} 
```

**Environment**
kind v0.20.0 go1.20.4 windows/amd64
Server: Docker Desktop 4.24.2

* ECK version:
i'am use latest version of this github repo in my private repo for deploing it via agrocd

* Kubernetes information:
	* On premise ? 
yes, i use localhost, i'am just training
	
	
```
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

firs of all i should say that my stack is working. I can't see any troubles in my lens 
![image](https://github.com/elastic/cloud-on-k8s/assets/148851399/1cb36d04-6bd5-4b29-b287-86f7b0dce9c4)
I'll se some staf on the internet and fing simular cases, but i think my situation another. 
So i make a username that i have from 
![image](https://github.com/elastic/cloud-on-k8s/assets/148851399/f5335255-6876-4d9c-93d2-b6d8054ba31f)
and create it in es via kibana interface
![image](https://github.com/elastic/cloud-on-k8s/assets/148851399/6ac6dfad-b9a8-464f-92b3-d5592a449592)
after that i'am tried attach some permissions that requed in role 
![image](https://github.com/elastic/cloud-on-k8s/assets/148851399/f6a7f537-33e4-4f49-94f6-ac8ac84981d4)
i make a index 
![image](https://github.com/elastic/cloud-on-k8s/assets/148851399/29faf29e-85c8-4046-8f4e-e0b307584e31) 
i see confirming logs in my es 
![image](https://github.com/elastic/cloud-on-k8s/assets/148851399/fd1a014f-f4ab-444b-8400-735acb674f7b)

but i can not be able to make my data view. I can`t catch where am make mistake/// there is my logstash pipeline  

```
pipelines:
  - pipeline.id: main
    config.string: |
      input {
        beats {
          port => 5044
        }
      }
      
      filter {
        grok {
          match => { "message" => "%{WORD:numbers} %{WORD:classic} %{WORD:beer} %{GREEDYDATA:party} %{GREEDYDATA:real}" }
        }
        mutate {
          convert => {
            "numbers" => "string"
            "classic" => "string"
            "beer" => "string"
            "party" => "string"
            "real" => "string"
          }
        }
      }

      output {
        elasticsearch {
          hosts => ["${QUICKSTART_ES_HOSTS}"]
          index => "hey"
          ssl => true
          ssl_certificate_verification => false
          user => ["${QUICKSTART_ES_USER}"]
          password => ["${QUICKSTART_ES_PASSWORD}"]        
        }
      }
```
 can someone help?

**Comment by thbkrkr** [comment]
> how really add user and role in es?

Here is the documentation for creating users and roles declaratively: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html. It is still also valid to create them using the Kibana UI or the Elasticsearch API.

I am closing this I don't see a bug in the ECK operator in this issue. Please reserve GitHub issues exclusively for bug reports and feature requests directly related to the ECK operator and let's move any discussion on how to use Elastic Stack to https://discuss.elastic.co/c/orchestration/eck/79. Thank you.

**Comment by dpkirchner** [comment]
@aufkm I know this was closed but I'm running in to similar problems -- were you able to figure this one out?
