### ISSUE TITLE
SAML presents error on Kibana login

### ISSUE THREAD

**Issue by charliek17** [elastic/cloud-on-k8s#7309]
## Bug Report
**What did you do?**
On Kibana Login I was presented: security_exception: Cannot find any matching realm for [SamlPrepareAuthenticationRequest]
However it was configured on the ES master nodes.

On the test environment the same config worked.
The only difference was that I had to manually delete the master nodes on the prod environment one at a time forcing recreation, once all master nodes were recreated SAML worked as expected.

It seems the operator didn't enforce a rebuild on an helm upgrade but worked on blank build.

* ECK version:

	2.8

* Kubernetes information:

	* Cloud: AKS

	* Stack 8.9.2

**Comment by barkbay** [comment]
> It seems the operator didn't enforce a rebuild on an helm upgrade but worked on blank build.

The operator only restarts the ES nodes if it is safe to do so. Was there any message in the logs about a failing predicate: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-advanced-upgrade-control

**Comment by charliek17** [comment]
This wasn't an issue, I thought masters were the only authenticating nodes but it turns out all the nodes need the idp metadata.
