### ISSUE TITLE
Verify client cert in the process manager server

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#731]
The process manager server must require and verify client certificates.

To do this right, we need to have a dedicated CA for this scenario (internal <-> internal comms). This would be the 3rd CA related to an ES cluster. A suggested approach would be to create a new CA, issue unique certificates (and private keys) that are mounted as secrets to the process manager container, and make the process manager require a client certificate signed by the same CA, with `operator` in the `.Subject.OrganizationalUnit` part of the certificate.

May be handled at the same time as #702.

**Comment by nkvoll** [comment]
Updated the issue description to include mention of a dedicated CA.

**Comment by pebrc** [comment]
Closing as we decided to retire the process manager
