### ISSUE TITLE
recipe link for fleet-kubernetes-integration-nonroot returns a 404 not found

### ISSUE THREAD

**Issue by dbalijapalli0264** [elastic/cloud-on-k8s#7312]
## Bug Report
**What did you do?**
* I've opened this link in a new tab:  https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.10/config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml
* From this page:  https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-configuration-examples.html#k8s_system_and_kubernetes_integrations_running_as_non_root
**What did you expect to see?**
*  I've expected a yaml file with contents for the recipe: fleet-kubernetes-integration-nonroot.yaml 
I've clicked on this link for: 
**What did you see instead? Under which circumstances?**
* I got a 404 page not found.
* Code line: https://github.com/elastic/cloud-on-k8s/blob/2.10/docs/orchestrating-elastic-stack-applications/agent-fleet.asciidoc?plain=1#L677
Please investigate,  I am working on setting up Fleet-managed _Elastic Agent Synthetics_ on ECK, and would like to know if you have any sample recipes to set up elastic-agent as non-root user.

**Comment by thbkrkr** [comment]
Hello, thank you for the feedback, there is indeed a mismatch between the doc (`fleet-kubernetes-integration-nonroot.yaml`) and the name of the recipe in the repository ([fleet-kubernetes-integration-noroot.yaml](https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-kubernetes-integration-noroot.yaml)) .

I will update the name of the recipe. In the meantime you can use: https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.10/config/recipes/elastic-agent/fleet-kubernetes-integration-noroot.yaml

**Comment by dbalijapalli0264** [comment]
thank you @thbkrkr for the quick response.

**Comment by thbkrkr** [comment]
https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.10/config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml is now available.

**Comment by dbalijapalli0264** [comment]
Hello @thbkrkr 

I still get a 404 page not found for the link you provided, could you kindly verify, could be a copy paste issue:
https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.10/config/recipes/elastic-agent/fleet-kubernetes-integration-noroot.yaml

**Comment by dbalijapalli0264** [comment]
Confirming that this loads without errors. Appreciate your help.

https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.10/config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml 


On a different note, can we use this recipe for configuring elastic-agent synthetics managed by Fleet on EKS?
