### ISSUE TITLE
Unable to run elastic-agent synthetics as non-root user

### ISSUE THREAD

**Issue by dbalijapalli0264** [elastic/cloud-on-k8s#7316]
## Bug Report
**What did you do?**
Create Yaml files to run elastic-agent synthetics as non-root user (PS: Root user run fine) - to run on-prem.
Document used: https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.10/config/recipes/elastic-agent/fleet-kubernetes-integration-nonroot.yaml
From: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-configuration.html

(As elastic-agent-synthetics are supposed to be run s non-root for the checks to work)

**What did you expect to see?**
The agent running healthy, and accepting the checks. 

**What did you see instead? Under which circumstances?**
cp: cannot create regular file '/usr/local/share/ca-certificates/ca.crt': Permission denied
Just want to know if there is any corrections to the documentation coming as I see few other tickets with similar comments. 

* ECK version:

	2.8

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? yes
	* Cloud: GKE / EKS / AKS ? EKS

**Comment by barkbay** [comment]
> ECK version:
> 2.8

Fix is available in `2.10`: https://github.com/elastic/cloud-on-k8s/pull/6700

Note that you may still experience some permission issues, I just opened https://github.com/elastic/cloud-on-k8s/pull/7317 to fix them.

Closing, reopen if needed.

**Comment by dbalijapalli0264** [comment]
Appreciate your quick response and document updates.
