### ISSUE TITLE
Remove default value of annotation

### ISSUE THREAD

**Issue by orenstartio** [elastic/cloud-on-k8s#7338]
https://github.com/elastic/cloud-on-k8s/blob/59c1e727bcc3282c34f80e67f274f8e2e5ad86cc/deploy/eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml#L9

I'm installing eck-elasticsearch using FluxV2, [0.41.0](https://github.com/fluxcd/flux2/releases/tag/v0.41.1), with helm controller version [0.31.1](https://github.com/fluxcd/helm-controller/blob/v0.31.1/CHANGELOG.md).

I need to use the basic license elasticsearch, so I followed this [issue](https://github.com/elastic/cloud-on-k8s/issues/6261#issuecomment-1373945748), and added the annotation to my `HelmRelease` values. But, the FluxCD is throwing errors of `DuplicateKeys`: `line 15: mapping key "eck.k8s.elastic.co/license" already defined at line 14`.

The solution would be to remove the default enterprise from the default helm templates annotation.

**Comment by barkbay** [comment]
Thanks for your interest in the Stack Helm Charts.
As [mentioned](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-helm-chart.html) in our documentation the Stack Helm Charts requires an Enterprise licence.
