### ISSUE TITLE
Expose Kibana configuration

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#740]
It should be possible to configure custom Kibana settings

**Comment by djschny** [comment]
Excuse my ignorance, but why not just mirror the way this is handled in the Kibana docker image today where `env` is provided in the pod template?

For example:

```

**Comment by nkvoll** [comment]
@djschny We'll be supporting that as well (we already do in master), but we also want to provide people with the flexibility of specifying the contents of their `kibana.yml` file as well. Some would also argue that it's a bit more of a convenient format than having to translate settings to the environment-equivalent.
