### ISSUE TITLE
es add custom user and role failed

### ISSUE THREAD

**Issue by woodliu** [elastic/cloud-on-k8s#7467]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
Add custom user and role as described in https://www.elastic.co/guide/en/cloud-on-k8s/2.10/k8s-users-and-roles.html#k8s-users-and-roles
**What did you expect to see?**
I can see the user and role in kibana UI or get the user and role with [api](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html)
**What did you see instead? Under which circumstances?**
After add the user and role, the cluster is green and Ready, but i can't find the added user and role
**Environment**
Kubernetes 1.26 
* ECK version:
2.10.0
	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: AKS
	
	for each of them please give us the version you are using
```
$ kubectl version
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.6
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1
* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
It says can't find secret `exporter-role` in  `dragon-eck` namespace 
{"log.level":"info","@timestamp":"2024-01-16T09:51:51.656Z","log.logger":"elasticsearch-controller","message":"referenced secret not found","service.version":"2.10.0+59c1e727","service.type":"eck","ecs.version":"1.4.0","iteration":"1123","namespace":"dragon-eck","es_name":"elasticsearch","namespace":"dragon-eck","es_name":"elasticsearch","secret_name":"exporter-role"}

But it is there...
![image](https://github.com/elastic/cloud-on-k8s/assets/9976943/c2b51645-e96d-4ec0-9e0a-a6fd3f6e6d97)

And about the added user ,the operator pod show nothing about it..

**Comment by barkbay** [comment]
> I can see the user and role in kibana UI or get the user and role with [api](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-user.html)

This API returns users in the native realm, not the ones in the file realm.

> And about the added user ,the operator pod show nothing about it..

I don't think the operator logs individual information about the users in the provided `Secret`.

Did you try to use that user in a curl request?

> It says can't find secret exporter-role in dragon-eck namespace

Could you check if this was a temporary error?

**Comment by woodliu** [comment]
@barkbay 
I don't think the operator logs individual information about the users in the provided Secret.
> That make sense!
Did you try to use that user in a curl request?
> Yes, i found the user is workable, and i can see it in file `/usr/share/elasticsearch/config/users` in es container
Could you check if this was a temporary error?
> That is my mistake, i use the role secret `matadata.name` as the role name, so the operator log shows it can't found the role

Thank you for your answer, that very helpful!
