### ISSUE TITLE
Upgrade Harness test is broken

### ISSUE THREAD

**Issue by kvalliyurnatt** [elastic/cloud-on-k8s#7527]
Currently the Upgrade Harness test is broken because the test expects the Logstash CR to have a health field in the status, but the Logstash does not have a health field in the status.
```
type LogstashStatus struct {
	// Version of the stack resource currently running. During version upgrades, multiple versions may run
	// in parallel: this value specifies the lowest version currently running.
	Version string `json:"version,omitempty"`

	// +kubebuilder:validation:Optional
	ExpectedNodes int32 `json:"expectedNodes,omitempty"`
	// +kubebuilder:validation:Optional
	AvailableNodes int32 `json:"availableNodes,omitempty"`

	// ObservedGeneration is the most recent generation observed for this Logstash instance.
	// It corresponds to the metadata generation, which is updated on mutation by the API Server.
	// If the generation observed in status diverges from the generation in metadata, the Logstash
	// controller has not yet processed the changes contained in the Logstash specification.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// ElasticsearchAssociationStatus is the status of any auto-linking to Elasticsearch clusters.
	ElasticsearchAssociationsStatus commonv1.AssociationStatusMap `json:"elasticsearchAssociationsStatus,omitempty"`

	// MonitoringAssociationStatus is the status of any auto-linking to monitoring Elasticsearch clusters.
	MonitoringAssociationStatus commonv1.AssociationStatusMap `json:"monitoringAssociationStatus,omitempty"`

	Selector string `json:"selector"`
}
```

@robbavey @kaisecheng  is this field something that the Logstash team could add ? else we will have to look at modifying the test specifically for Logstash.

**Comment by kaisecheng** [comment]
@kvalliyurnatt Could you link the red CI here or provide the command to reproduce the test? On top of my head, we recently added a restriction to the minimum version of Logstash, 8.12.0, running in ECK

**Comment by robbavey** [comment]
@kvalliyurnatt Was this a new requirement for the test harness? 

I've added a PR, which I think should add what we need - #7528

**Comment by kvalliyurnatt** [comment]
Thanks @robbavey . This is not a new requirement but I think we were excluding Logstash from the upgrade tests, but at some point it was added to the upgrade test harness and it started failing.
