### ISSUE TITLE
OpenSSL is missing in Logstash UBI image 8.12.1

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#7544]
## 8.12.0 ✅ 

```
➜  docker run --rm --entrypoint openssl  docker.elastic.co/logstash/logstash-ubi:8.12.0 version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

## 8.12.1 ❌
```
➜  docker run --rm --entrypoint openssl  docker.elastic.co/logstash/logstash-ubi:8.12.1 version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon:
 failed to create task for container: failed to create shim task:
   OCI runtime create failed: runc create failed:
     unable to start container process: exec: "openssl": executable file not found in $PATH: unknown.
```

CC @robbavey @kaisecheng

**Comment by kaisecheng** [comment]
logstsh 8.12.0 docker image builds on top of `docker.elastic.co/ubi8/ubi-minimal`, which depends on `redhat/ubi8-minimal`. [microdnf update -y](https://github.com/elastic/logstash/blob/main/docker/templates/Dockerfile.j2#L79) brings `openssl` command to the image. However, in 8.12.1, the update command didn't bring the same thing. 

logstash docker need to do `microdnf install -y openssl` to ensure the availability of the command

**Comment by kaisecheng** [comment]
@barkbay I have added the command to Logstash docker image. From Logstash 8.12.2, it will have `openssl`. 
```
docker run --rm --entrypoint openssl docker.elastic.co/logstash/logstash:8.12.2-ae316674-SNAPSHOT-arm64 version
OpenSSL 1.1.1f  31 Mar 2020
```
For the next ECK release note, I think the note needs to tell users not to use Logstash 8.12.1 image.  Can we close this issue?

**Comment by barkbay** [comment]
> For the next ECK release note, I think the note needs to tell users not to use Logstash 8.12.1 image. Can we close this issue?

SGTM
