### ISSUE TITLE
Expose the Kibana keystore

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#755]
It would be great if users could configure secure settings for Kibana through its keystore feature (similar to how we do it via Secret for the ES keystore): https://www.elastic.co/guide/en/kibana/current/secure-settings.html

**Comment by sebgl** [comment]
Things I've learned while looking into this:

* Kibana loads the keystore when starting.
* There is not hot-reload keystore feature like Elasticsearch has.
* Key/values are strings, there is no "file" type as in Elasticsearch keystore.
* `kibana-keystore` CLI and underlying file format is not the same as `elasticsearch-keystore`.
* Any setting from `kibana.yml` can be set in the keystore, using a reference in `kibana.yml`: `elasticsearch.password: ${elasticsearch.password}`

I think there is no good reason to reuse our Elasticsearch keystore client implementation for Kibana.
Also it's probably fine to recreate a Kibana instance automatically on Keystore update.

What I have in mind for the implementation.

* Keystore key-values can be provided by the user in a secret, referenced from the `SecureSettings` field of Kibana CRD, similar to Elasticsearch CRD.
* Values are reconciled into an internal secret, in which we also inject our own secrets (Elasticsearch password is a good example).
* This secret is mounted into Kibana pod.
* We create the keystore on pod startup (`./bin/kinana-keystore create`), and add all secrets present in the secure settings mounted volume (`cat my.secret | ./bin/kibana-keystore add my.secret --stdin`)
* This can be done either through an init container where we mount Kibana `data` volume as an EmptyDir, or through overriding Kibana container command.
* We store a hash of the secure settings secret into the Kibana Deployment labels: if anything changes in this secret, this will lead to the deployment being recreated, hence keystores to be recreated for all Kibana instances.

**Comment by thbkrkr** [comment]
Note: a secret for the Kibana config `${name}-kb-config` is already in place and its checksum is already used as a pod label.

I'm in favor of the init container that looks cleaner.

**Comment by sebgl** [comment]
> Note: a secret for the Kibana config ${name}-kb-config is already in place and its checksum is already used as a pod label.

Do you think we should reuse it?
It currently contains a single `kibana.yml` entry. We could reconcile all secure settings entries in there and ignore the `kibana.yml` one.
It seems a bit cleaner to have a dedicated secret imo (even more since we can mount the user-provided secret directly without reconciling into our own secret first)?

**Comment by pebrc** [comment]
I am in favour of two separate secrets (config + secure settings) + using an init container
