### ISSUE TITLE
Quickstart Guide for Logstash not working

### ISSUE THREAD

**Issue by lost-carrier** [elastic/cloud-on-k8s#7572]
## Bug Report
**What did you do?**
Tried to setup Logstash according to Quickstart guide.

**What did you expect to see?**
Logstash up and running

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	2.11.1

* Kubernetes information:

	* K0S On premise

```
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1+k0s
```

On https://www.elastic.co/guide/en/cloud-on-k8s/2.11/k8s-logstash-quickstart.html I copy-pasted the given example at the top...
```
cat <<EOF | kubectl apply -f -
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
[...]
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
  services:
[...]
```
...and found the `${...}` variables not getting filled once on Kubernetes.

When passed via shell (`cat <<EOF | kubectl apply -f -...`) instead of a file, those will need to be escaped!

```
            hosts => [ "\${QS_ES_HOSTS}" ]
            user => "\${QS_ES_USER}"
            password => "\${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "\${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
```

Not a huge issue, but keeps beginners (main quickstart audience, I guess) struggling...

**Comment by thbkrkr** [comment]
Thanks for reporting this.
