### ISSUE TITLE
Makefile targets don't exist

### ISSUE THREAD

**Issue by ryanhockstad** [elastic/cloud-on-k8s#7606]
## Proposal

Fix Makefile to allow `make deploy` to build and deploy dev ECK operator.

## Bug Report
**What did you do?**
Run `make deploy` to deploy operator in dev cluster.

**What did you expect to see?**
I expected the `elastic-operator` statefulset to be deployed to my cluster.

**What did you see instead? Under which circumstances?**
The `make` command fails under all circumstances because the make target `publish-operator-image` does not exist.

This can be fixed if `publish-operator-image` is changed to `docker-push-operator` on line 232 of the Makefile.

There are a few other Makefile targets that are missing if certain `make` commands are run, and the documentation in the [Contributing Guide](https://github.com/elastic/cloud-on-k8s/blob/main/CONTRIBUTING.md#tests) is out of date regarding these commands (ie: make docker-push).

**Comment by barkbay** [comment]
Closed by https://github.com/elastic/cloud-on-k8s/pull/7607
