### ISSUE TITLE
Failed to deploy operator on GKE due to permission issue

### ISSUE THREAD

**Issue by bindiego** [elastic/cloud-on-k8s#7643]
## Bug Report
**What did you do?**

Simply deployed ECK 2.11.1 on GKE 1.29.1-gke.1589017

**What did you expect to see?**

Operator works as intended

**What did you see instead? Under which circumstances?**

Operator failed to deploy due to a permission issue. 

**Environment**

* ECK version: 2.11.1

* Kubernetes information:

	* Cloud: GKE 1.29.1-gke.1589017

* deployment script: https://github.com/elasticsearch-cn/elastic-on-gke/blob/develop/bin/demo.sh

Usually, this script should quickly get everything set up in about 10min.

### Grant the configmap `get` permission to the prohibited user

kubectl apply -f [$pwd/conf/elastic-operator-get-configmaps.yaml](https://github.com/elasticsearch-cn/elastic-on-gke/blob/develop/conf/elastic-operator-get-configmaps.yaml)

**Comment by barkbay** [comment]
I'm not sure to understand how you deployed ECK but it works as expected using `https://download.elastic.co/downloads/eck/2.11.1/operator.yaml` 

```
> k apply -f https://download.elastic.co/downloads/eck/2.11.1/operator.yaml
namespace/elastic-system created
serviceaccount/elastic-operator created
secret/elastic-webhook-server-cert created
configmap/elastic-operator created
clusterrole.rbac.authorization.k8s.io/elastic-operator created
clusterrole.rbac.authorization.k8s.io/elastic-operator-view created
clusterrole.rbac.authorization.k8s.io/elastic-operator-edit created
clusterrolebinding.rbac.authorization.k8s.io/elastic-operator created
service/elastic-webhook-server created
statefulset.apps/elastic-operator created
validatingwebhookconfiguration.admissionregistration.k8s.io/elastic-webhook.k8s.elastic.co created
```

```
>  k get pods -n elastic-system
NAME                 READY   STATUS    RESTARTS   AGE
elastic-operator-0   1/1     Running   0          10s
```

**Comment by bindiego** [comment]
Confirmed, it works now.

I have reverted my [temp fix](https://github.com/elasticsearch-cn/elastic-on-gke/commit/f21ad0ee67cbd0687f84764cd219f3f94609b24d)

This is still an unknow issue for me. But it does work now.

Thanks for your quick reply.
