### ISSUE TITLE
Propagate more podTemplate fields into the final pods

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#765]
So far, users are allowed to use `podTemplate` to propagate:
* labels
* affinity
* resources limits

We should extend that behaviour to more fields of the provided pod template.

**Comment by nkvoll** [comment]
Our intention now is to not copy a few whitelisted fields, but start out with the pod template from the spec when constructing the pods we need.

**Comment by nkvoll** [comment]
Closed in #943

**Comment by pebrc** [comment]
#952 fixes the Kibana side of this
