### ISSUE TITLE
Consider calling the desired balance API on cluster changes

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#7677]
We should consider calling the (reset) [desired balance API](https://www.elastic.co/guide/en/elasticsearch/reference/current/delete-desired-balance.html) to speed up rolling upgrades in certain scenarios. 

> After making changes that could significantly impact cluster balance and potentially move shards from their current desired nodes, it is recommended to reset the current desired balance to help it speed up. 

@ywangd could you help us specify in what kind of scenarios it is recommended to call this API and maybe enumerate scenarios which impact cluster balance.

**Comment by ywangd** [comment]
AIUI, from ES's perspective, we would like to reach a state where calling this API externally become largely unecessary, i.e. we'd like to automate either this API or achieve similar effect via other means internally without manualy intervention. There is no roadmap for it though. Also ping @idegtiarenko @DaveCTurner for their expert opinions on this topic.

**Comment by DaveCTurner** [comment]
Yeah we shouldn't need to call this API and _definitely_ shouldn't build any such calls into ECK. It's an ES bug if ever it's needed. See https://github.com/elastic/elasticsearch/pull/106921 for incoming docs changes to that effect.

**Comment by pebrc** [comment]
Thanks for the input from both of you. I'am closing this issue.
