### ISSUE TITLE
Beats autodiscover error in 8.14.0-SNAPOSHOT

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#7718]
`TestBeatKibanaRef` and `TestMetricbeatDefaultConfig` failed for Stack `8.14.0-SNAPSHOT` twice in a row..

- https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/515
- https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/514
- build/513 didn't run because of a k8s cluster creation error
- build/512 is the last success build, started Thu 11th Apr 2024 at 21:42 UTC

Beats pods are in `CrashLoopBackOff` state:
```
Exiting: error in autodiscover provider settings: error setting up kubernetes autodiscover provider: 
         unknown autodiscover builder hints
```

### How to reproduce?

The same error can be reproduced deploying [`config/recipes/beats/metricbeat_hosts.yaml`](https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/metricbeat_hosts.yaml) and replacing the stack version in the `default` namespace.

```sh
> sed "s|8.13.0|8.14.0-SNAPSHOT|g" config/recipes/beats/metricbeat_hosts.yaml | k apply -f-
```

```sh
NAME                                                       HEALTH   NODES   VERSION           PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/elasticsearch   green    3       8.14.0-SNAPSHOT   Ready   19m

NAME                                  HEALTH   NODES   VERSION           AGE
kibana.kibana.k8s.elastic.co/kibana   green    1       8.14.0-SNAPSHOT   19m

NAME                                  HEALTH   AVAILABLE   EXPECTED   TYPE         VERSION           AGE
beat.beat.k8s.elastic.co/metricbeat   red                  3          metricbeat   8.14.0-SNAPSHOT   19m

NAME                                   READY   STATUS             RESTARTS        AGE
pod/elasticsearch-es-default-0         1/1     Running            0               19m
pod/elasticsearch-es-default-1         1/1     Running            0               19m
pod/elasticsearch-es-default-2         1/1     Running            0               19m
pod/kibana-kb-f8d655f5-wpbls           1/1     Running            0               19m
pod/metricbeat-beat-metricbeat-f6hgn   0/1     CrashLoopBackOff   8 (3m6s ago)    19m
```

```go
> k logs metricbeat-beat-metricbeat-f6hgn | grep error | tail -2
{
    "log.level": "error",
    "@timestamp": "2024-04-15T09:44:25.227Z",
    "log.origin": {
        "function": "github.com/elastic/beats/v7/libbeat/cmd/instance.handleError",
        "file.name": "instance/beat.go",
        "file.line": 1345
    },
    "message": "Exiting: error in autodiscover provider settings: error setting up kubernetes autodiscover provider: unknown autodiscover builder hints",
    "service.name": "metricbeat",
    "ecs.version": "1.6.0"
}
Exiting: error in autodiscover provider settings: error setting up kubernetes autodiscover provider: unknown autodiscover builder hints
```

**Comment by pkoutsovasilis** [comment]
I think this is affected by this commit https://github.com/elastic/beats/commit/930410642ebaf67a18c2a4e77256ac128b45bb21 and the sequence order needs to be checked as the error you posted @thbkrkr suggests that the "hints" builder [is not found in the registry](https://github.com/pkoutsovasilis/beats/blob/main/libbeat/autodiscover/builder.go#L89)

**Comment by blakerouse** [comment]
The issue is the order at which the `InitializeModule` is being called. It needs to be performed either before `NewAutodiscover` or adjust `NewAutodiscover` to not be called so early. I think the later is the proper solution because at the moment its being created when the RootCmd is being created, when its not even being used as a runner.

Working on a proper fix now.

**Comment by thbkrkr** [comment]
Thank you @blakerouse for the quick resolution!
