### ISSUE TITLE
elastic-internal-diagnostics may not allow to detect all stack versions

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#7776]
I think the new diagnostic user introduced in #7723 does not always allow https://github.com/elastic/eck-diagnostics to run ES or Kibana diagnostic tools.

Also refer to my comment here: https://github.com/elastic/cloud-on-k8s/commit/8420c9c03764305e2fb3e10273832f774a7cc292#r141719077

**Comment by naemono** [comment]
Investigating now.

**Comment by naemono** [comment]
> Investigating now.

Testing Fix on versions < 8.5, and 7.x.
