### ISSUE TITLE
Custom Logs with operator eck dosen't works

### ISSUE THREAD

**Issue by aalagia90** [elastic/cloud-on-k8s#7781]
Hi,
i have tried to install this solution https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-custom-logs-integration.yaml but the package custom logs is not present in the elk policy. When the kibana start i have seen this error

 
![immagine](https://github.com/elastic/cloud-on-k8s/assets/169151112/2986753c-5cae-453a-8d75-f8bc91f4aa0f)

The version that i use of components are

kibana,elastic,fleet,elastic-agent : 8.13.2
eck operator: 2.12
log: 2.3.1

This is my yaml file

package_policies:
      - name: system-1
        id: system-1
        package:
          name: system
      - package:
          name: log
        name: log-1
        inputs:
        - type: logfile
          enabled: true
          streams:
          - data_stream:
              dataset: log.log
            enabled: true
            vars:
            - name: paths
              value:
              - '/var/log/containers/*${kubernetes.container.id}.log'
            - name: custom
              value: |
                symlinks: true
                condition: ${kubernetes.namespace} == 'default'

Thank you very much

**Comment by pebrc** [comment]
Please post your question in our community support forum https://discuss.elastic.co/c/orchestration/eck/79 
We use Github exclusively for bug reports and feature requests. Thank you.
