### ISSUE TITLE
How many Elasticsearch clusters can I deploy with ECK

### ISSUE THREAD

**Issue by Rookie-Zmy** [elastic/cloud-on-k8s#7786]
When deploying an Elasticsearch cluster through ECK, are there any recommendations for the number of clusters managed by a single elastic-operator?

If there are many clusters, do they need to be deployed in multiple namespaces and managed using different elastic-operators?

**Comment by thbkrkr** [comment]
> When deploying an Elasticsearch cluster through ECK, are there any recommendations for the number of clusters managed by a single elastic-operator?

One operator instance can manage several hundred of clusters. Its capacity is mostly bound by the resources allocated to it and the limitations of the underlying Kubernetes installation. Check https://github.com/elastic/cloud-on-k8s/issues/357#issuecomment-561069362.

If you need to manage a large number of clusters, monitor memory usage and adjust the container resources as necessary. You should also increase `max-concurrent-reconciles` to handle multiple resources at the same time.

> If there are many clusters, do they need to be deployed in multiple namespaces and managed using different elastic-operators?

Not necessarily, it's up to you how you want to organize your Elastic deployments based on your use case. Just make sure you don't have 2 operators managing the same namespace.
