### ISSUE TITLE
Reconciler error on upgrade from 8.13.3 to 8.13.4

### ISSUE THREAD

**Issue by TheRockyOng** [elastic/cloud-on-k8s#7861]
## Bug Report
**What did you do?**
Upgrade Elasticsearch version from 8.13.3 to 8.13.4

**What did you expect to see?**
eck-operator upgrades the cluster successfully

**What did you see instead? Under which circumstances?**
Operator failed to upgrade and errored out on `node_version` being not present. See detailed logs below. 
Worth noting: upgrade from 8.11.x -> 8.13.3 prior was successful

**Environment**

* ECK version: 2.12.1

* Kubernetes information: EKS 1.28

* ES Version: 8.13.4

* Logs:
```
400 Bad Request: {Status:400 Error:{CausedBy:{Reason: Type:} Reason:[node_version] field is required and must have a valid value Type:x_content_parse_exception StackTrace: RootCause:[{Reason:[node_version] field is required and must have a valid value Type:x_content_parse_exception}]}}

```

**Comment by rhr323** [comment]
Hey @TheRockyOng,

Thanks for reporting this issue. The `node_version` field was deprecated starting with Elasticsearch 8.13.0 (ECK does not set it anymore since 2.13). Can you double-check the versions you’re using?

**Comment by TheRockyOng** [comment]
Hey @rhr323. Thanks for the response. I did notice the deprecation as well hence I think this might be a bug. Not sure exactly if it's a bug on the ES side or Operator at this point though

Current ES version is 8.13.3 and I am trying to upgrade to 8.13.4.

**Comment by rhr323** [comment]
It looks like this might actually be a bug in Elasticsearch. To confirm, you can check whether all nodes in cluster state have the "desired_node.version_deprecated" feature. For any nodes that don't, restart them (one-by-one) via deleting the corresponding pod.

Getting the cluster state: `GET _cluster/state`

Getting the relevant info from cluster state: `cat cluster_state.json| jq '.nodes_features[]' -cMr`

Let us know how it went.

**Comment by TheRockyOng** [comment]
you are right. all of the data nodes don't seem to have `desired_node.version_deprecated` feature for whatever reasons. Rebooting them fixed it though. Good to know! Thanks for the quick response here. I will close out this issue then

**Comment by thbkrkr** [comment]
Thank you very much @TheRockyOng for the report.

As it looks like an Elasticsearch bug, it is now tracked in:
- https://github.com/elastic/elasticsearch/issues/109254
