### ISSUE TITLE
Breakdown usage by managed application

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#7866]
Currently the usage data reporting is summary only https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-licensing.html#k8s-get-usage-data

We should create a breakdown by managed application, as different license agreements per user can influence whether or not e.g. Logstash memory should be included in the ERU summary. The intent behind this change is to make it transparent to users which applications are being included in the calculatation and allow users that are on older license terms to subtract e.g. Logstash from the total displayed.

**Comment by thbkrkr** [comment]
Have you started to think more deeply about how we can implement this?

Where should we add these information? 
```sh
> kubectl -n elastic-system get configmap elastic-licensing -o json | jq .data
{
  "eck_license_level": "enterprise",
  "eck_license_expiry_date": "2022-01-01T00:59:59+01:00",
  "enterprise_resource_units": "1",
  "max_enterprise_resource_units": "10",
  "timestamp": "2020-01-03T23:38:20Z",
  "total_managed_memory": "64GiB",
  "total_managed_memory_bytes": "68719476736"
  
  "details" {
  	...
  }

}
```

Format / level of details?
```json
 "details" {
	"elasticsearch": "32GB",
	"kibana": "8GB",
	"apm-server": "8GB"
	"enterprise-search": "8GB"
	"logstash": "8GB"
}
```
Should we go further into detail?
```json
 "details" {
	"elasticsearch": [{"ns1/name1": "16GB"}, {"ns2/name2": "16GB"}],
	"kibana": [{"ns1/name1": "4GB"}, {"ns2/name2": "2GB"}, {"ns2/name3": "2GB"}],
	"apm-server": [{"ns1/name1": "4GB"}, {"ns2/name2": "4GB"}],
	"enterprise-search": [{"ns1/name1": "4GB"}, {"ns/2name2": "4GB"}],
	"logstash": [{"ns1/name1": "8GB"}],
}
```

**Comment by pebrc** [comment]
I was thinking: 
1. just add the sum for each application (that's what's relevant for licensing) 
2. add it to the same config map. I am not sure about the nested structure

```
{
  "eck_license_level": "enterprise",
  "eck_license_expiry_date": "2022-01-01T00:59:59+01:00",
  "enterprise_resource_units": "1",
  "max_enterprise_resource_units": "10",
  "managed_elasticsearch_memory": "32GB",
  "managed_kibana_memory": "8GB",
  "managed_apm_server_memory": "8GB",
  "managed_enterprise_search_memory": "8GB",
  "managed_logstash_memory": "8GB",
  "timestamp": "2020-01-03T23:38:20Z",
  "total_managed_memory": "64GiB",
  "total_managed_memory_bytes": "68719476736",
}
```

For consistency we should probably report both `GiB` and bytes, wdyt?

**Comment by thbkrkr** [comment]
I like your proposal, without nested structure. About `GiB` and bytes, I would only add bytes. Finally, the only field in `GiB` would be `total_managed_memory`.

**Comment by barkbay** [comment]
> About GiB and bytes, I would only add bytes. Finally, the only field in GiB would be total_managed_memory.

Isn't #5465 also relevant to this "per application" use case? I wonder if, beyond the consistency aspect, having the 2 values ​​could not be useful.
