### ISSUE TITLE
When scaling down StatefulSets, will PVCs be deleted together? Is this implemented in the operator?

### ISSUE THREAD

**Issue by dxygit1** [elastic/cloud-on-k8s#7891]
operator version：eck-operator:2.9.0
When reducing the replicas of a StatefulSet from three to one, I noticed that the corresponding PVCs were also deleted.

**Comment by pebrc** [comment]
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html#k8s_controlling_volume_claim_deletion

Please reserve Github issues for bug reports and feature requests. We have a community discussion forum for more general questions here https://discuss.elastic.co/c/orchestration/eck/79
