### ISSUE TITLE
logstash: statefulset not restarting on pipeline changes

### ISSUE THREAD

**Issue by Tajjar** [elastic/cloud-on-k8s#7936]
## Bug Report
**What did you do?**
tried to modify pipeline config.string 

**What did you expect to see?**
expected to see my modifications present by having old pod terminated and new one with latest config created.

**What did you see instead? Under which circumstances?**
same old config was still there.

* ECK version:
2.13

* Kubernetes information:

	* Cloud: EKS:1.29

**Comment by pebrc** [comment]
Logstash automatically reloads the pipeline config without the need to recreate the pods. See https://github.com/pebrc/cloud-on-k8s/blob/4ab7f3a923399030c3ed0d6da95b619bd8d4c42c/pkg/controller/logstash/driver.go#L135-L138
