### ISSUE TITLE
[E2E] Flaky TestLogstash* tests on 8.[15|16].0-SNAPSHOT

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#7993]
We had several failures for these tests, including on ECK 2.4.0:

### TestLogstashEsOutput/Logstash_should_respond_to_default_pipeline_requests ~ stack-8-15-0-sna

```
=== RUN   TestLogstashEsOutput/Logstash_should_respond_to_default_pipeline_requests
    step.go:51: 
        	Error Trace:	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
        	Error:      	Received unexpected error:
        	            	fail to request /_node/pipelines/main, status is 404)
        	Test:       	TestLogstashEsOutput/Logstash_should_respond_to_default_pipeline_requests
```

### TestLogstashKeystoreWithPassword/Logstash_should_respond_to_default_pipeline_requests ~ stack-8-15-0-sna

```
=== RUN   TestLogstashKeystoreWithPassword/Logstash_should_respond_to_default_pipeline_requests
    step.go:51: 
        	Error Trace:	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
        	Error:      	Received unexpected error:
        	            	fail to request /_node/pipelines/main, status is 404)
        	Test:       	TestLogstashKeystoreWithPassword/Logstash_should_respond_to_default_pipeline_requests
```

### TestLogstashEsOutput/Logstash_should_respond_to_default_pipeline_requests ~ stack-8-16-0-sna

```
TestLogstashKeystoreWithoutPassword/Logstash_should_respond_to_default_pipeline_requests ~ stack-8-15-0-sna
=== RUN   TestLogstashKeystoreWithoutPassword/Logstash_should_respond_to_default_pipeline_requests
    step.go:51: 
        	Error Trace:	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
        	Error:      	Received unexpected error:
        	            	fail to request /_node/pipelines/main, status is 404)
```

**Comment by barkbay** [comment]
The following error appears to be logged indefinitely:

```
[2024-08-09T04:16:47,812][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [A-Za-z0-9_-], [ \\t\\r\\n], \"#\", \"{\", [A-Za-z0-9_], \",\", \"]\" at line 5, column 18 (byte 100) after output { \n  elasticsearch {\n\thosts => [ https", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:239:in `initialize'", "org/logstash/execution/AbstractPipelineExt.java:173:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:48:in `initialize'", "org/jruby/RubyClass.java:949:in `new'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:49:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:386:in `block in converge_state'"]}
```

@robbavey @kaisecheng 👋 , sorry for the direct ping here, do you know is something has changed (very) recently in `2.15.0`? We are observing these errors since yesterday.

**Comment by robbavey** [comment]
@barkbay Thanks for pointing this out - there have been changes made recently with ENV substitution, which look like they may be the cause. I've filed an [upstream issue](https://github.com/elastic/logstash/issues/16383)

**Comment by robbavey** [comment]
I believe this should be [fixed](https://github.com/elastic/logstash/pull/16375)

**Comment by pebrc** [comment]
Do we need to skip the tests for the stack versions that have not received the patch?

**Comment by barkbay** [comment]
I'm not sure to understand if this bug:
* Is affecting `8.15.0` (not sure because tests on `8.15.0` are ✅ [here](https://buildkite.com/elastic/cloud-on-k8s-operator/builds/9000))
or
* Has been introduced between `8.15.0` and `8.15.1` (in this case it should resolve itself?)

**Comment by pebrc** [comment]
> I'm not sure to understand if this bug:
> 
>     * Is affecting `8.15.0` (not sure because tests on `8.15.0` are ✅ [here](https://buildkite.com/elastic/cloud-on-k8s-operator/builds/9000))
>       or
> 
>     * Has been introduced between `8.15.0` and `8.15.1` (in this case it should resolve itself?)

Same. The fix references https://github.com/elastic/logstash/pull/16365 which is in 8.15.0 but the failures seem to be restricted to snapshot versions which would support your second hypothesis.

**Comment by robbavey** [comment]
The bug was introduced between `8.15.0` and `8.15.1` - the `8.15.0` tag in https://github.com/elastic/logstash/pull/16365 is incorrect. I believe the bug was backported to the `8.15` branch between the final BC and the version bump, which caused this incorrect tag on the commit.

[Commits](https://github.com/elastic/logstash/commits/v8.15.0/) for the 8.15.0 tag do not show the offending commit
