### ISSUE TITLE
Tanzu e2e tests cleanup is failing due to Azure CLI Warning.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#8004]
See https://buildkite.com/elastic/cloud-on-k8s-operator-e2e-clusters-cleanup/builds/379#01914d54-eddf-4fa7-bfc3-117043352801 and discussion in https://elastic.slack.com/archives/C8RU9J1C2/p1723579539801359.

The Tanzu cleanup is failing because the Azure CLI is now displaying a warning:

```
WARNING: Azure CLI 2.63.0 is the last version available on Alpine and will not receive updates. Consider migrating to the Azure Linux based image for Azure CLI. For more information: https://go.microsoft.com/fwlink/?linkid=2282203
```

Which seems to have been interpreted as part of the output of "show clusters", as you can see the actual cluster being displayed shortly afterwards:

```
eck-e2e-tanzu-jadk-4081
```

I believe we've seen something in the past similar and I believe https://github.com/elastic/cloud-on-k8s/pull/5585 was the fix for this, which included only showing the stdout, not stderr. Also, verify that this isn't affecting Azure e2e cleanup.

We need to verify, and fix or remove Tanzu support, and we don't support it any longer anyways.

**Comment by pebrc** [comment]
I vote for removing the Tanzu code.

**Comment by naemono** [comment]
> I vote for removing the Tanzu code.

Agreed.

**Comment by naemono** [comment]
`eck-e2e-tanzu-jadk-4081` resource group manually removed in azure.
