### ISSUE TITLE
Update Elastic Maps Server image

### ISSUE THREAD

**Issue by jsanz** [elastic/cloud-on-k8s#8034]
EMS started to publish additional docker images based on the hardened `chainguard-base` docker image in 8.14. We don't plan to deprecate the `-ubi` images, but upgrade to `-ubi9` soon but it would be great for ECK users to migrate to the Chainguard base images by default.

For example, for `8.15.0` we have:

* UBI8 image at `docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8:8.15.0`
* Aliased UBI image at `docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi:8.15.0`
* New chainguard image at `docker.elastic.co/elastic-maps-service/elastic-maps-server:8.15.0-amd64`

**Comment by pebrc** [comment]
> New chainguard image at docker.elastic.co/elastic-maps-service/elastic-maps-server:8.15.0-amd64

@jsanz is there are reason we can't have a [multi-architecture image](https://docs.docker.com/build/building/multi-platform/) with both `arm64` and `amd64` behind a shared tag e.g. `8.16.0` ?

**Comment by pebrc** [comment]
Discussed out of band: we should have a multi-arch image for 8.16.0-SNAPSHOT very soon. That means as part of this task we should also remove the restriction on running the e2e tests for both archictures which is currently done via build tags: 

https://github.com/elastic/cloud-on-k8s/blob/7323879c77aecede9971cee8a4b4988906725d7b/.buildkite/e2e/release-branch-matrix.yaml#L64

**Comment by jsanz** [comment]
@pebrc I see latest `SNAPSHOT` images for EMS Server `9.0.0` and `8.16.0` on both `elastic-maps-service/elastic-maps-server-ubi` and `elastic-maps-service/elastic-maps-server-wolfi` to be multi-arch. Con you confirm if this is working on your end?

* https://container-library.elastic.co/r/elastic-maps-service/elastic-maps-server-wolfi:8.16.0-SNAPSHOT
* https://container-library.elastic.co/r/elastic-maps-service/elastic-maps-server-wolfi:9.0.0-SNAPSHOT
* https://container-library.elastic.co/r/elastic-maps-service/elastic-maps-server-ubi:8.16.0-SNAPSHOT
* https://container-library.elastic.co/r/elastic-maps-service/elastic-maps-server-ubi:9.0.0-SNAPSHOT

**Comment by pebrc** [comment]
@jsanz our e2e tests succeeded last night 👍

**Comment by jsanz** [comment]
Nice!

![](https://media.giphy.com/media/dat4Tl3EZ3re4lInTN/giphy.gif?cid=ecf05e473oxec0ef7xq87e6yo0bq26kwipzq4qzjxdbf052b&ep=v1_stickers_search&rid=giphy.gif&ct=s)
