### ISSUE TITLE
Elastic Cluster status unknown and phase stuck in "Applyingchanges"

### ISSUE THREAD

**Issue by cheths87** [elastic/cloud-on-k8s#8047]
Hi Team,

I created a 3-node Elasticsearch cluster, but the status in kubectl get elasticsearch is stuck on "applying changes." However, all the pods and stateful sets are showing as green in the Kubernetes dashboard, and the Elasticsearch cluster status is also green when checked from within the pods. 
I'm unsure if this is a bug or if there's a way to determine the cause of this unknown status. Any guidance would be greatly appreciated.

PFB details:
========================
Kubernetes version: v1.29.6

terminal@terminal:~$ kubectl get elasticsearch
NAME     HEALTH    NODES   VERSION   PHASE             AGE
mon  unknown  3       8.15.1    ApplyingChanges   3h30m

terminal@terminal:~$ kubectl get pods  
NAME                            READY   STATUS    RESTARTS   AGE
mon-es-default-0             1/1     Running   0          3h36m
mon-es-default-1             1/1     Running   0          3h36m
mon-es-default-2             1/1     Running   0          3h36m
mon-kb-6cdc8dbb4f-rtrvx   1/1     Running   0          3h5m

terminal@terminal:~$ kubectl get statefulset
NAME                READY   AGE
mon-es-default   3/3     3h37m

**Comment by cheths87** [comment]
This is the yaml config:
=============================
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mon
  namespace: elk-monitor  # Specified namespace
spec:
  version: 8.15.1
  nodeSets:
  - name: default
    count: 3  #  Three Elasticsearch nodes
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data  # Name of the persistent volume claim (PVC)
      spec:
        accessModes: [ "ReadWriteOnce" ]  # Access mode for the storage
        resources:
          requests:
            storage: 60Gi  # Request 60 GB of persistent storage
        storageClassName: standard  # Adjust storage class based on your environment (e.g., gp2 for AWS, standard for GCP)
    config:
      node.store.allow_mmap: false  # Disable mmap for node storage
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi  # Request 4 GiB of memory
              cpu: 2       # Request 2 CPUs
            limits:
              memory: 4Gi  # Limit to 4 GiB of memory
              cpu: 2       # Limit to 2 CPUs
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  nc -zv -w2 127.0.0.1 9200  # Check if port 9200 is open on 127.0.0.1
            initialDelaySeconds: 30  # Delay before readiness probe starts
            timeoutSeconds: 5        # Probe timeout duration
            periodSeconds: 10        # How often to perform the probe
            failureThreshold: 3      # Number of failures before marking the pod as unready

**Comment by pebrc** [comment]
Do not set a readiness probe see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html#k8s_elasticsearch_versions_8_2_0_and_later
