### ISSUE TITLE
[E2E] TestPipelineConfig*Logstash are failing on 8.16.0-SNAPSHOT

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#8102]
We are observing some failures for some Logstash e2e tests since Thursday, October 10th.

Failures seem to be always due to **`expected status to be green but got yellow`** (or `red`) when calling the `/` API:

* `TestPipelineConfigLogstash/Logstash_should_respond_to_metrics_requests`

```
=== RUN   TestPipelineConfigLogstash/Logstash_should_respond_to_metrics_requests
Retries (15m0s timeout):
    step.go:51: 
        	Error Trace:	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
        	Error:      	Received unexpected error:
        	            	expected status to be green but got yellow
        	Test:       	TestPipelineConfigLogstash/Logstash_should_respond_to_metrics_requests
```

* `TestPipelineConfigRefLogstash/Logstash_should_respond_to_metrics_requests`

```
=== RUN   TestPipelineConfigRefLogstash/Logstash_should_respond_to_metrics_requests
Retries (15m0s timeout): .........................................................................................................................................................................................................................................................................................................
    step.go:51: 
        	Error Trace:	/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
        	Error:      	Received unexpected error:
        	            	expected status to be green but got red
        	Test:       	TestPipelineConfigRefLogstash/Logstash_should_respond_to_metrics_requests
```

This is fairly easy to reproduce locally, I can confirm that the Logstash response is:

```json
{
  "host" : "test-split-pipeline-j6pk-ls-0",
  "version" : "8.16.0",
  "http_address" : "0.0.0.0:9600",
  "id" : "02115e04-db10-4c04-8263-0426d5c94a5b",
  "name" : "test-split-pipeline-j6pk-ls-0",
  "ephemeral_id" : "4f94107d-edb7-4fed-86b3-8f14caeeebf2",
  "snapshot" : true,
  "status" : "yellow",
  "pipeline" : {
    "workers" : 2,
    "batch_size" : 125,
    "batch_delay" : 50
  },
  "build_date" : "2024-10-13T02:35:37+00:00",
  "build_sha" : "dc0739bdaf2fbab416aaa5ab91ccab9895cd7c3d",
  "build_snapshot" : true
}
```

I tried to set`"log.level": "debug"` but nothing stands out from the logs 😕 

@yaauie @mashhurs 👋 sorry for the ping here, I noticed that https://github.com/elastic/logstash/pull/16532 was merged a few days ago, I was wondering if it could be related to this `status` reported as `yellow` or `red`? 🙇 

As a side note something confusing is that the custom resource itself is reported as `green`:

```
NAME                                                        HEALTH   AVAILABLE   EXPECTED   AGE     VERSION
logstash.logstash.k8s.elastic.co/test-split-pipeline-4h22   green    1           1          2m47s   8.16.0-SNAPSHOT
```

**Comment by kingttdk** [comment]
{
  "host" : "test-split-pipeline-j6pk-ls-0",
  "version" : "8.16.0",
  "http_address" : "0.0.0.0:9600",
  "id" : "02115e04-db10-4c04-8263-0426d5c94a5b",
  "name" : "test-split-pipeline-j6pk-ls-0",
  "ephemeral_id" : "4f94107d-edb7-4fed-86b3-8f14caeeebf2",
  "snapshot" : true,
  "status" : "yellow",
  "pipeline" : {
    "workers" : 2,
    "batch_size" : 125,
    "batch_delay" : 50
  },
  "build_date" : "2024-10-13T02:35:37+00:00",
  "build_sha" : "dc0739bdaf2fbab416aaa5ab91ccab9895cd7c3d",
  "build_snapshot" : true
}
