### ISSUE TITLE
Elasticsearch does not refresh AWS Web Identity Token file after upgrading version

### ISSUE THREAD

**Issue by jackchi** [elastic/cloud-on-k8s#8142]
I upgraded from ES 8.8.1 to 8.15.0 and we experienced the same issue with token not getting refreshed by ElasticSearch.

POST /_snapshot/my-repo/_verify?pretty=true
```json
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[my-repo] path  is not accessible on master node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[my-repo] path  is not accessible on master node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unable to upload object [tests-u7JQMsD-QrWRscI0Vv0EuA/master.dat] using a single upload",
      "caused_by": {
        "type": "amazon_client_exception",
        "reason": "amazon_client_exception: java.lang.IllegalStateException: Connection pool shut down",
        "caused_by": {
          "type": "illegal_state_exception",
          "reason": "Connection pool shut down"
        }
      }
    }
  },
  "status": 500
}
```

I am following the ECK instructions for IRSA https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#iam-kubernetes-service-accounts

I see the token files are new on the projected volume mounts:

```sh
~/config/repository-s3$ ls -lah                                 
total 4.0K
drwxrwsrwt  3 root elasticsearch  100 Oct 16 14:34 .
drwxrwsrwx 10 root elasticsearch 4.0K Oct 15 19:22 ..
drwxr-sr-x  2 root elasticsearch   60 Oct 16 14:34 ..2024_10_16_14_34_53.3014348955
lrwxrwxrwx  1 root elasticsearch   32 Oct 16 14:34 ..data -> ..2024_10_16_14_34_53.3014348955
lrwxrwxrwx  1 root elasticsearch   34 Oct 15 19:21 aws-web-identity-token-file -> ..data/aws-web-identity-token-file
```

Are there any other reports of this issue?

Similar previous issue:
* https://github.com/elastic/elasticsearch/issues/101828
* https://github.com/elastic/elasticsearch/issues/101828#issuecomment-2417706588

PR fix should be put in 8.13:
* https://github.com/elastic/elasticsearch/issues/101828#issuecomment-2417706588

Solution: A restart of master, data, coordinator nodes will fix this issue. However, could it be that somehow we missed the loading during version upgrades. @arteam 

Thanks.

**Comment by pebrc** [comment]
This is an Elasticsearch issue ([draft PR](https://github.com/elastic/elasticsearch/pull/115304)) not an ECK issue.
