### ISSUE TITLE
Elasticsearch observability Integration

### ISSUE THREAD

**Issue by alita1991** [elastic/cloud-on-k8s#8244]
Hi,

My goal is to identify the recommended approach for exporting telemetry data, such as metrics, from Elasticsearch in a way that can be ingested by an OpenTelemetry Collector. One option, used in some legacy charts, involves utilizing the Elasticsearch Exporter. However, I want to validate if there is a better, more standardized solution provided natively by  Elasticsearch itself that can be configured via CR config.

Thanks

**Comment by barkbay** [comment]
> However, I want to validate if there is a better, more standardized solution provided natively by Elasticsearch itself that can be configured via CR config.

You can only [set an observability cluster in the Elasticsearch resource](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html). I would suggest to open a new topic in [our discuss forum](https://discuss.elastic.co/c/observability/82) to get help from the relevant team.

Closing this as I think it is more a question than an issue.
