### ISSUE TITLE
Beats ingest_pipeline e2e test for stack monitoring seems broken in 8.16.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#8250]
The manifest used in our e2e [test](https://github.com/elastic/cloud-on-k8s/blob/a79db966d6be6e962cb584f0584c90cba05fc2a7/test/e2e/beat/recipes_test.go#L101) for Beats Stack Monitoring: https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/beats/stack_monitoring.yaml is failing in 8.16.x. 

The `.ds-metricbeat-8.16.*` index contains no documents. We see this in the logs:

```
{"took":5,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}
```

And the index shows 0 documents:
```
green open .ds-metricbeat-8.16.0-2024.11.21-000001                            6-n8-dkGTvGzVI_pTOd60Q 1 1      0 0    498b    249b    249b
```

We are investigating what could be causing the underlying issue.

Previous versions of the stack do not exhibit this behavior.

**Comment by pebrc** [comment]
```
{"log.level":"warn","@timestamp":"2024-11-22T17:53:07.731Z","log.logger":"elasticsearch","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/outputs/elasticsearch.(*Client).applyItemStatus","file.name":"elasticsearch/client.go","file.line":517},"message":"Cannot index event '{\"@timestamp\":\"2024-11-22T17:52:45.681Z\",\"host\":{\"name\":\"metricbeat-ghk8-beat-metricbeat-bdf49dd67-mr5zm\"},\"cloud\":{\"region\":\"europe-west1\",\"project\":{\"id\":\"elastic-cloud-dev\"},\"account\":{\"id\":\"elastic-cloud-dev\"},\"provider\":\"gcp\",\"service\":{\"name\":\"GCE\"},\"availability_zone\":\"europe-west1-c\",\"instance\":{\"id\":\"2234889521242930945\",\"name\":\"gke-pebrc-eck-dev-default-pool-9548049e-jnj6\"},\"machine\":{\"type\":\"n1-standard-8\"}},\"error\":{\"message\":\"error making http request: Get \\\"https://10.34.193.8:5601/api/status\\\": dial tcp 10.34.193.8:5601: connect: connection refused\"},\"metricset\":{\"name\":\"cluster_rules\",\"period\":10000},\"service\":{\"address\":\"https://10.34.193.8:5601/api/monitoring_collection/cluster_rules\",\"type\":\"kibana\"},\"kubernetes\":{\"namespace_uid\":\"10677c07-0a0d-49cb-ac8b-3f1694879552\",\"namespace_labels\":{\"test-run\":\"e2e\",\"kubernetes_io/metadata_name\":\"e2e-mercury\",\"name\":\"e2e-mercury\"},\"replicaset\":{\"name\":\"kibana-ghk8-kb-848d9f8ddf\"},\"labels\":{\"common_k8s_elastic_co/type\":\"kibana\",\"kibana_k8s_elastic_co/name\":\"kibana-ghk8\",\"kibana_k8s_elastic_co/version\":\"8.16.0\",\"pod-template-hash\":\"848d9f8ddf\",\"scrape\":\"kb\",\"test-name\":\"beats-stack_monitoring\"},\"node\":{\"name\":\"gke-pebrc-eck-dev-default-pool-cf93aa17-sfcp\",\"uid\":\"d98e3e0e-7a8f-4a9e-9d29-d3a5591183e0\",\"labels\":{\"cloud_google_com/gke-container-runtime\":\"containerd\",\"cloud_google_com/gke-nodepool\":\"default-pool\",\"topology_kubernetes_io/zone\":\"europe-west1-b\",\"node_kubernetes_io/instance-type\":\"n1-standard-8\",\"cloud_google_com/machine-family\":\"n1\",\"cloud_google_com/gke-memory-gb-scaling-level\":\"30\",\"cloud_google_com/gke-boot-disk\":\"pd-ssd\",\"cloud_google_com/gke-os-distribution\":\"cos\",\"beta_kubernetes_io/arch\":\"amd64\",\"cloud_google_com/gke-max-pods-per-node\":\"110\",\"cloud_google_com/gke-provisioning\":\"standard\",\"kubernetes_io/arch\":\"amd64\",\"failure-domain_beta_kubernetes_io/region\":\"europe-west1\",\"kubernetes_io/os\":\"linux\",\"beta_kubernetes_io/os\":\"linux\",\"cloud_google_com/gke-cpu-scaling-level\":\"8\",\"failure-domain_beta_kubernetes_io/zone\":\"europe-west1-b\",\"cloud_google_com/gke-local-ssd\":\"true\",\"cloud_google_com/gke-stack-type\":\"IPV4\",\"kubernetes_io/hostname\":\"gke-pebrc-eck-dev-default-pool-cf93aa17-sfcp\",\"cloud_google_com/gke-logging-variant\":\"DEFAULT\",\"topology_kubernetes_io/region\":\"europe-west1\",\"topology_gke_io/zone\":\"europe-west1-b\",\"beta_kubernetes_io/instance-type\":\"n1-standard-8\",\"cloud_google_com/private-node\":\"false\"}},\"pod\":{\"name\":\"kibana-ghk8-kb-848d9f8ddf-b66jl\",\"uid\":\"e5417171-f691-4257-bda4-b00620863ad2\",\"ip\":\"10.34.193.8\"},\"namespace\":\"e2e-mercury\"},\"ecs\":{\"version\":\"8.0.0\"},\"agent\":{\"id\":\"82edc4a1-4a7b-483b-bc44-c567bffc1188\",\"name\":\"metricbeat-ghk8-beat-metricbeat-bdf49dd67-mr5zm\",\"type\":\"metricbeat\",\"version\":\"8.16.0\",\"ephemeral_id\":\"a196f056-fb56-40ff-8f84-b816914bb4ae\"},\"orchestrator\":{\"cluster\":{\"name\":\"pebrc-eck-dev\",\"url\":\"https://10.34.176.2\"}},\"event\":{\"dataset\":\"kibana.cluster_rules\",\"module\":\"kibana\",\"duration\":652755}}\n' (status=400): {\"type\":\"document_parsing_exception\",\"reason\":\"[1:1519] failed to parse: Limit of total fields [10000] has been exceeded while adding new fields [18]\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Limit of total fields [10000] has been exceeded while adding new fields [18]\"}}, dropping event!","service.name":"metricbeat","log.type":"event","ecs.version":"1.6.0"}
```

**Comment by pebrc** [comment]
In the metricbeat's pod event log which is in `/logs` folder inside the container

**Comment by pebrc** [comment]
If I hack the test to  set `index.mapping.total_fields.ignore_dynamic_beyond_limit` on the beats indices I get a `PASS` 

```diff
diff --git a/pkg/utils/retry/retry.go b/pkg/utils/retry/retry.go
index 4c550f8c8..1b9b3fcad 100644
--- a/pkg/utils/retry/retry.go
+++ b/pkg/utils/retry/retry.go
@@ -48,6 +48,7 @@ func UntilSuccess(f func() error, timeout time.Duration, retryInterval time.Dura
 				return nil
 			}
 			lastErr = err
+			println(lastErr.Error())
 			retryTimer := time.NewTimer(retryInterval)
 			select {
 			case <-retryTimer.C:
diff --git a/test/e2e/beat/recipes_test.go b/test/e2e/beat/recipes_test.go
index 4c67638b4..63304a2fd 100644
--- a/test/e2e/beat/recipes_test.go
+++ b/test/e2e/beat/recipes_test.go
@@ -99,13 +99,13 @@ func TestMetricbeatHostsRecipe(t *testing.T) {
 }
 
 func TestMetricbeatStackMonitoringRecipe(t *testing.T) {
-	v := version.MustParse(test.Ctx().ElasticStackVersion)
+	// v := version.MustParse(test.Ctx().ElasticStackVersion)
 
-	// https://github.com/elastic/cloud-on-k8s/issues/8250
-	// Update when the referenced issue is resolved.
-	if v.GE(version.MinFor(8, 16, 0)) {
-		t.SkipNow()
-	}
+	// // https://github.com/elastic/cloud-on-k8s/issues/8250
+	// // Update when the referenced issue is resolved.
+	// // if v.GE(version.MinFor(8, 16, 0)) {
+	// 	t.SkipNow()
+	// }
 
 	name := "fb-autodiscover"
 	pod, loggedString := loggingTestPod(name)
diff --git a/test/e2e/test/beat/steps.go b/test/e2e/test/beat/steps.go
index 1c931b9e2..e19842886 100644
--- a/test/e2e/test/beat/steps.go
+++ b/test/e2e/test/beat/steps.go
@@ -5,16 +5,21 @@
 package beat
 
 import (
+	"bytes"
 	"context"
 	"fmt"
+	"io"
+	"net/http"
 
 	"github.com/google/go-cmp/cmp"
 	"github.com/pkg/errors"
 	corev1 "k8s.io/api/core/v1"
 	apierrors "k8s.io/apimachinery/pkg/api/errors"
+	utilerrs "k8s.io/apimachinery/pkg/util/errors"
 
 	beatv1beta1 "github.com/elastic/cloud-on-k8s/v2/pkg/apis/beat/v1beta1"
 	esv1 "github.com/elastic/cloud-on-k8s/v2/pkg/apis/elasticsearch/v1"
+	"github.com/elastic/cloud-on-k8s/v2/pkg/controller/elasticsearch/client"
 	"github.com/elastic/cloud-on-k8s/v2/pkg/utils/k8s"
 	"github.com/elastic/cloud-on-k8s/v2/pkg/utils/pointer"
 	"github.com/elastic/cloud-on-k8s/v2/test/e2e/cmd/run"
@@ -178,7 +183,7 @@ func (b Builder) CheckStackTestSteps(k *test.K8sClient) test.StepList {
 
 				for _, validation := range b.Validations {
 					if err := validation(esClient); err != nil {
-						return err
+						return utilerrs.NewAggregate([]error{err, b.ignoreBeyondLimit(esClient)})
 					}
 				}
 
@@ -189,6 +194,25 @@ func (b Builder) CheckStackTestSteps(k *test.K8sClient) test.StepList {
 	}
 }
 
+func (b Builder) ignoreBeyondLimit(esClient client.Client) error {
+	body := `{"index":{"mapping": {"total_fields": {"ignore_dynamic_beyond_limit": true}}}}`
+	req, err := http.NewRequest(http.MethodPut, "/*beat*/_settings", bytes.NewBuffer([]byte(body)))
+	if err != nil {
+		return err
+	}
+	res, err := esClient.Request(context.Background(), req)
+	if err != nil {
+		return err
+	}
+	defer res.Body.Close()
+	resultBytes, err := io.ReadAll(res.Body)
+	if err != nil {
+		return err
+	}
+	println(string(resultBytes))
+	return nil
+}
+
 func (b Builder) UpgradeTestSteps(k *test.K8sClient) test.StepList {
 	return test.StepList{
 		{
```

I think this points to a product issue with too many mappings for all kinds of integrations being configured + dynamic mapping. I saw you are already talking to folks on the stack monitoring team @naemono This issue should be fixed there imo. Maybe they have some guidance how we can work around it in a less hacky way than I did here. But I am sure customers will run into this too.

**Comment by consulthys** [comment]
> From an attempt at local reproduction of the error:
> 
> ```
> Cannot index event '{"@timestamp":"2024-11-22T17:52:45.681Z","host":{"name":"metricbeat-ghk8-beat-metricbeat-bdf49dd67-mr5zm"},"cloud":{"region":"europe-west1","project":{"id":"elastic-cloud-dev"},"account":{"id":"elastic-cloud-dev"},"provider":"gcp","service":{"name":"GCE"},"availability_zone":"europe-west1-c","instance":{"id":"2234889521242930945","name":"gke-pebrc-eck-dev-default-pool-9548049e-jnj6"},"machine":{"type":"n1-standard-8"}},"error":{"message":"error making http request: Get \"https://10.34.193.8:5601/api/status\": dial tcp 10.34.193.8:5601: connect: connection refused"},"metricset":{"name":"cluster_rules","period":10000},"service":{"address":"https://10.34.193.8:5601/api/monitoring_collection/cluster_rules","type":"kibana"},"kubernetes":{"namespace_uid":"10677c07-0a0d-49cb-ac8b-3f1694879552","namespace_labels":{"test-run":"e2e","kubernetes_io/metadata_name":"e2e-mercury","name":"e2e-mercury"},"replicaset":{"name":"kibana-ghk8-kb-848d9f8ddf"},"labels":{"common_k8s_elastic_co/type":"kibana","kibana_k8s_elastic_co/name":"kibana-ghk8","kibana_k8s_elastic_co/version":"8.16.0","pod-template-hash":"848d9f8ddf","scrape":"kb","test-name":"beats-stack_monitoring"},"node":{"name":"gke-pebrc-eck-dev-default-pool-cf93aa17-sfcp","uid":"d98e3e0e-7a8f-4a9e-9d29-d3a5591183e0","labels":{"cloud_google_com/gke-container-runtime":"containerd","cloud_google_com/gke-nodepool":"default-pool","topology_kubernetes_io/zone":"europe-west1-b","node_kubernetes_io/instance-type":"n1-standard-8","cloud_google_com/machine-family":"n1","cloud_google_com/gke-memory-gb-scaling-level":"30","cloud_google_com/gke-boot-disk":"pd-ssd","cloud_google_com/gke-os-distribution":"cos","beta_kubernetes_io/arch":"amd64","cloud_google_com/gke-max-pods-per-node":"110","cloud_google_com/gke-provisioning":"standard","kubernetes_io/arch":"amd64","failure-domain_beta_kubernetes_io/region":"europe-west1","kubernetes_io/os":"linux","beta_kubernetes_io/os":"linux","cloud_google_com/gke-cpu-scaling-level":"8","failure-domain_beta_kubernetes_io/zone":"europe-west1-b","cloud_google_com/gke-local-ssd":"true","cloud_google_com/gke-stack-type":"IPV4","kubernetes_io/hostname":"gke-pebrc-eck-dev-default-pool-cf93aa17-sfcp","cloud_google_com/gke-logging-variant":"DEFAULT","topology_kubernetes_io/region":"europe-west1","topology_gke_io/zone":"europe-west1-b","beta_kubernetes_io/instance-type":"n1-standard-8","cloud_google_com/private-node":"false"}},"pod":{"name":"kibana-ghk8-kb-848d9f8ddf-b66jl","uid":"e5417171-f691-4257-bda4-b00620863ad2","ip":"10.34.193.8"},"namespace":"e2e-mercury"},"ecs":{"version":"8.0.0"},"agent":{"id":"82edc4a1-4a7b-483b-bc44-c567bffc1188","name":"metricbeat-ghk8-beat-metricbeat-bdf49dd67-mr5zm","type":"metricbeat","version":"8.16.0","ephemeral_id":"a196f056-fb56-40ff-8f84-b816914bb4ae"},"orchestrator":{"cluster":{"name":"pebrc-eck-dev","url":"https://10.34.176.2"}},"event":{"dataset":"kibana.cluster_rules","module":"kibana","duration":652755}}
> ' (status=400): {"type":"document_parsing_exception","reason":"[1:1519] failed to parse: Limit of total fields [10000] has been exceeded while adding new fields [18]","caused_by":{"type":"illegal_argument_exception","reason":"Limit of total fields [10000] has been exceeded while adding new fields [18]"}}, dropping event!
> ```

Actually, reaching the field limit has been identified recently in https://github.com/elastic/beats/pull/41614
The solution was to simply update the total fields limit to 12500
