### ISSUE TITLE
Is there any reference where we can find the kubernetes compatibility versions for specific Elastic cloud-on-k8s operator?

### ISSUE THREAD

**Issue by Sandhyaranitp** [elastic/cloud-on-k8s#8290]
I'm looking for information on the Kubernetes version compatibility for Operator version eck-operator:1.9.1. Specifically, I need to know which Kubernetes versions (within the 1.2x to 1.x range) are supported by this operator version. Could anyone provide a reference or documentation that outlines this?

**Comment by pebrc** [comment]
https://www.elastic.co/guide/en/cloud-on-k8s/1.9/k8s_supported_versions.html

**Comment by Sandhyaranitp** [comment]
In the link it is mentioned as Kubernetes 1.18-1.22 but on 1.24 eck-operator:1.9.1 is running fine. Is this the updated link?
