### ISSUE TITLE
StatefulSet currentRevision and currentReplicas mismatch after rolling update with Elasticsearch manifest changes

### ISSUE THREAD

**Issue by abellosovic** [elastic/cloud-on-k8s#8295]
When performing a rolling update to an existing kind: Elasticsearch StatefulSet in Kubernetes, the StatefulSet's status does not reflect the expected values after the rotation is completed.

**Steps to Reproduce:**

- Deploy a running StatefulSet for Elasticsearch in Kubernetes.
- Make a change to the manifest (e.g., updating environment variables or resource requests/limits).
- Observe the rolling update process initiated by the change.
- Once the rotation is complete, check the status of the StatefulSet.

**Observed Behavior:**

- The currentRevision value remains set to the original version, while updateRevision reflects the updated version.
- The currentReplicas field is missing, even though all replicas are successfully updated and running.

**Expected Behavior:**
According to the Kubernetes StatefulSet specification:

- After the rolling update completes, currentRevision should match updateRevision.
- The currentReplicas field should equal the replicas field if all pods are up-to-date and running as expected.

**Environment:**

Kubernetes version: 1.29.9
ECK: 2.8.0

**Additional Notes:**
This behavior seems inconsistent with the Kubernetes StatefulSet specification. It may lead to confusion or potential issues with tooling that relies on the status fields to determine the health and current state of the StatefulSet.

**Comment by pebrc** [comment]
ECK does not have its own StatefulSet implementation. We are using the built-in Kubernetes StatefulSets. What you are observing is just Kubernetes behaviour.
