### ISSUE TITLE
Block upgrade of CRDs to 9.0 if Ent. search nodes exist

### ISSUE THREAD

**Issue by Kushmaro** [elastic/cloud-on-k8s#8308]
In stack 9.0, Ent. search nodes wont exist any longer. To upgrade to stack version 9.0, Enterprise search will needed to be first removed from the cluster - in the form of deleting the Ent. search CRD, and then performing the appropriate migration within Kibana Upgrade assistant.

Hence - we should block upgrades to 9.0 version of CRDs if we detect there's an Ent. Search CRD connected to the same Elasticsearch cluster/reference.

**Comment by pebrc** [comment]
For 2.16 we used our generic version validation to prevent the update (see linked PR) 
```
EnterpriseSearch.enterprisesearch.k8s.elastic.co "ent-sample" is invalid: spec.version: Invalid value: "9.0.0": Unsupported version: version 9.0.0 is higher than the highest supported version of 8.99.99
```

We can improve on that for 3.0.0 with more specific guidance.
