### ISSUE TITLE
Shutdown triggered before `pre-stop-hook-script.sh` runs

### ISSUE THREAD

**Issue by nicholasklem** [elastic/cloud-on-k8s#8373]
We expected the `pre-stop-hook-script.sh` to handle the shutdown and that PRE_STOP_SHUTDOWN_TYPE would be respected.

If we run the internal `pre-stop-hook-script.sh` directly we get the `type` as defined in an env variable:
```
PRE_STOP_SHUTDOWN_TYPE=remove
...
elasticsearch-01-es-master-2 elasticsearch {"type": "server", "timestamp": "2024-12-23T14:04:39,068Z", "level": "INFO", "component": "o.e.x.s.TransportPutShutdownNodeAction", "cluster.name": "elasticsearch-01", "node.name": "elasticsearch-01-es-master-2", "message": "creating shutdown record {nodeId=[tftUXjZURXyxS7_tnOuPGQ], type=[REMOVE], reason=[pre-stop hook]}", "cluster.uuid": "dYKeNRfXS7OnI3nM-LfPmw", "node.id": "AbyekU_cR2agjCIQpBEO9A"  }
```

but if we let the operator handle the restart the shutdown record is not created by the `pre-stop-hook-script.sh` but by the operator, ignoring the `PRE_STOP_SHUTDOWN_TYPE`?

```
elasticsearch-01-es-master-2 elasticsearch {"type": "server", "timestamp": "2024-12-23T14:16:20,325Z", "level": "INFO", "component": "o.e.x.s.TransportPutShutdownNodeAction", "cluster.name": "elasticsearch-01", "node.name": "elasticsearch-01-es-master-2", "message": "creating shutdown record {nodeId=[Sk8xiJWMSvyYVg1VpwNR_Q], type=[RESTART], reason=[568392500]}", "cluster.uuid": "dYKeNRfXS7OnI3nM-LfPmw", "node.id": "AbyekU_cR2agjCIQpBEO9A"  }
```

Specifically see `type, reason`:
```
type=[REMOVE], reason=[pre-stop hook]
type=[RESTART], reason=[568392500]
```

When the operator does the job we hit this stanza:
https://github.com/elastic/cloud-on-k8s/blob/main/pkg/controller/elasticsearch/nodespec/lifecycle_hook.go#L191-L194

and we never drain the node.

In effect we are not able to do `PRE_STOP_SHUTDOWN_TYPE=remove` with draining.

Is there a config flag somewhere to leave the shutdown call to the script?

**Comment by barkbay** [comment]
> We expected the pre-stop-hook-script.sh to handle the shutdown and that PRE_STOP_SHUTDOWN_TYPE would be respected.

This is only true if the container is stopped by an external event, like a K8s node being drained for example. If you update the ES specification to trigger a restart then this part of the script is not run.

Using this spec:

```yaml
    podTemplate:
      spec:
        containers:
        - env:
          - name: PRE_STOP_SHUTDOWN_TYPE
            value: remove
          name: elasticsearch
```

And running `kubectl drain --ignore-daemonsets --delete-emptydir-data gke-dev-default-pool-5c37895f-h1drt`, it produces the expected result, relying on `PRE_STOP_SHUTDOWN_TYPE` to drive the shutdown request type:

```json
{
    "log.level": "INFO",
    "message": "creating shutdown record {nodeId=[zJtpN1VeRjKXP2fgTecECg], type=[REMOVE], reason=[pre-stop hook]}",
    "log.logger": "org.elasticsearch.xpack.shutdown.TransportPutShutdownNodeAction",
    "elasticsearch.cluster.name": "elasticsearch"
}
```

**Comment by nicholasklem** [comment]
> > We expected the pre-stop-hook-script.sh to handle the shutdown and that PRE_STOP_SHUTDOWN_TYPE would be respected.
> 
> This is only true if the container is stopped by an external event, like a K8s node being drained for example. If you update the ES specification to trigger a restart then this part of the script is not run.

Oh this was surprising to me, that the restart mechanisms are different when triggered by kubernetes vs the operator itself?

We run an unrecommended amount of shards pr node, and node restarts without shard migration have intermittently produced cluster instability.

Any way we can use the "remove" shutdown mechanism for all predictable scenarios?

**Comment by barkbay** [comment]
> Any way we can use the "remove" shutdown mechanism for all predictable scenarios?

You can rename your nodeset, from an operator point of view this means that you want new Elasticsearch nodes, the controller should therefore use the `REMOVE` type automatically when deleting Pods to move from the old nodeset to the new one.
