### ISSUE TITLE
Semantically invalid podTemplate sections causes extra resources to be created.

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#852]
When experimenting with pod anti affinities, I misunderstood parts of the K8s documentation and ended up with affinities that were syntactically correct, but semantically wrong.

We do not perform any validation here, so it only turned into an error when the operator created a Pod based on the template and the K8s API returned an error.

Unfortunately, at this point we've already created a few supporting secrets/resources, and because of 1) these triggering a reconciliation 2) no backoff, 3) no clean up of resources created for the failed pod, the number of API resources we create (and don't clean up) for the cluster keeps growing.

**Comment by pebrc** [comment]
I think we can close this as https://github.com/elastic/cloud-on-k8s/pull/3020 added semantic PodTemplate validation.
