### ISSUE TITLE
Enable race condition detection flag

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#861]
From time to time, we should run tests (and the operator itself) with the `-race` flag to make sure we don't have any race condition in the code.

This does have a performance hit though:

> The cost of race detection varies by program, but for a typical program, memory usage may increase by 5-10x and execution time by 2-20x.

What's the best place to enable this? Should it run periodically in CI?

**Comment by pebrc** [comment]
This has been enabled in CI since https://github.com/elastic/cloud-on-k8s/pull/2863
