### ISSUE TITLE
Reported cluster health green when ES not reachable

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#874]
A bug we observed with @thbkrkr: in situations where the cluster has no master, we don't update the cluster health in ES status. This is leading to confusion since users might think the cluster is in a green health, but it is not.

To reproduce:
* Deploy a cluster, observe green health reported in ES status
* Find a way to kill some nodes so the cluster ends up with no master anymore (eg. downscale the k8s cluster so that some pods cannot be created anymore - not enough resources)
* When there are no master: some endpoints respond (eg. `/`), some don't (eg. `/_cat/health`)
* Observe the reported health in ES status stays green, even though the observer cannot get the actual health

The problem is in this piece of code:

https://github.com/elastic/cloud-on-k8s/blob/5a3bbbcd9ab23e400b8b68de398f6262f7c1e9d1/operators/pkg/controller/elasticsearch/driver/default.go#L216-L219

We should probably introduce some kind of `Unknown` status when the observer cannot fetch ES health, and still update the ES resource with that status.

**Comment by pebrc** [comment]
Can this be closed @sebgl I think we are now unconditionally calling the state update here:
https://github.com/elastic/cloud-on-k8s/blob/bed2c56aa163cef5ad8ebd679b21fdcab77ddbba/pkg/controller/elasticsearch/driver/driver.go#L246

**Comment by sebgl** [comment]
Yes I think that's OK, let's reopen if we observe something wrong.
