### ISSUE TITLE
GetOrphanedVolumeClaim does not manage multiple volumes

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#877]
GetOrphanedVolumeClaim does not take into account the potential difference between data volumes and any other volumes. 

In `volumeClaimTemplates[].metadata.name` we store `data` for the ES data volume:
* It needs to take into account `pod.spec.containers[].volumes[].volumeName` somehow.
* We should store this `volumeName` in an annotation or label on the PVC in order to match.

**Comment by pebrc** [comment]
#1122 fixes the immediate issue of repurposing the wrong volume claim on reuse. It does not address the issue of keeping re-use consistent across multiple volumes. Example: pod has two volumes, `logs` and `data` in theory it is possible that `data` is reused on one pod and `logs` on another.
