### ISSUE TITLE
Improve usage of labels/annotations on PVCs

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#878]
A PVC is only reused if there is perfect match between the labels of a Pod and the labels on the PVC.
It is too strict as some label may change and a PVC may still be reused.
For example the `version` label (which should be an annotation) should have a special handling and allow a PVC to be reattached to a node with same or newer ES version.

**Comment by sebgl** [comment]
Tackling this one while working on PVC reuse (#312).
