### ISSUE TITLE
Add .Name to NodeSpec to differentiate different nodes by name

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#882]
It's very useful to be able to give name pods based on their usage or configuration, e.g:

```
{cluster}-master-{counter}
{cluster}-data-{counter}
{cluster}-ingest-{counter}
{cluster}-coordinator-{counter}
```

This makes output of `kubectl get pods` as well as the ES apis easier to parse for humans.

**Comment by nkvoll** [comment]
@sebgl configuration changes would have to stay within the same node spec, so in some ways yes. This change effectively means that /in the future/, topology changes most likely will trigger data migration since changing a node name means the disk cannot be re-used.

This will actually help us in avoiding having master-only data volumes be re-used for data-only nodes and vice versa (+ a lot more possible, but unwanted combinations), which is a great plus.

As a side benefit, this also lays the foundation upon which we can ensure stable pod naming (e.g ordinal suffixes instead of randomized strings), which is something that has been requested.

**Comment by sebgl** [comment]
Just making sure I got it correctly: the name here would be user-provided and can be anything (not restricted to the node role)?

> This will actually help us in avoiding having master-only data volumes be re-used for data-only nodes and vice versa 
Sounds to me like we should rely on labels for that, especially if the above is true.

**Comment by nkvoll** [comment]
> Just making sure I got it correctly: the name here would be user-provided and can be anything (not restricted to the node role)?

Yes, it has to be user-provided, and can be logical infix name the user wants (subject to some regex), e.g `data-us-east-1a`, `ingest-ml`, `data-ssd`, `data-{storagetype}`, etc.

>> This will actually help us in avoiding having master-only data volumes be re-used for data-only nodes and vice versa

> Sounds to me like we should rely on labels for that, especially if the above is true.

We should rely on labels (or annotations) to ensure things like `data` volumes (as in mounted at `data/`) being used only as `data` volumes etc (there's a separate issue filed for this).

As for re-usability of volumes during topology changes, this would become a casualty in the name of having deterministic node names (/prefixes). AFAIK we can't use a volume used for `node-name-foo` as the volume for `node-name-bar` so we either can allow for the user to affect node naming (a requested feature) and we lose some re-usability, or we have opaque node names.

**Comment by pebrc** [comment]
What is the benefit of having this user configurable? Is this not a case of a setting nobody wants/needs? We already allow users to set custom labels via the pod template.

**Comment by nkvoll** [comment]
After some discussion we ended with the following:

- Want users to be able to configure parts of `node.name`, but not in its entirety, so `node.name` to stay blacklisted and new parameter to be added to `NodeSpec`:
- Add `.Name` to `NodeSpec`. This should be /optional/, defaulting to no prefix. Consequence is that we cannot do stable ordinals for the time being.
- Detaching `node.name` from pod name to be discussed in the future.
