### ISSUE TITLE
Improve error output of integration test of processmanager

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#884]
Attempting to run the integration tests without a Docker daemon available yields:

```$ go test -tags='integration' ./pkg/controller/elasticsearch/processmanager/...
exit status 1
FAIL	github.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch/processmanager	2.351s
```

It would be desirable to include more information about what is happening and what is failing instead of just an exit code.

**Comment by sebgl** [comment]
Fixed with https://github.com/elastic/cloud-on-k8s/pull/897
