### ISSUE TITLE
Expose external IP for quick-kibana service

### ISSUE THREAD

**Issue by sherry-ger** [elastic/cloud-on-k8s#894]
## Proposal
Expose external IP for quick-kibana service

**Use case. Why is this important?**

I am testing out the operator the first time on GKE.  It would be nice to expose the external IP for kibana service for the quick and easy get started experience.

**Comment by thbkrkr** [comment]
Do you mean when displaying Kibana resources?
```sh
> k get kb
NAME         HEALTH   NODES   VERSION   AGE
quickstart   green    1       7.1.0     5h
```

By declaring the `http.service.spec.type` as `LoadBalancer` in the Kibana CRD: 
https://github.com/elastic/cloud-on-k8s/blob/595c0a3c9e2c7b60976c857e6f556439d462db67/operators/config/samples/kibana/kibana_es.yaml#L82-L85

The external IP of the Kibana service `<name>-kibana` associated to the CRD is populated if the k8s cluster support load balancers:
```sh
> k get svc quickstart-kibana 
NAME                TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)          AGE
quickstart-kibana   LoadBalancer   10.19.247.90   35.111.222.333   5601:30952/TCP   4h
```

**Comment by sherry-ger** [comment]
Thank you @thbkrkr 
That worked great!  I wonder if we should share this as a part of the quick start documentation/guide for users who are on GKE.

**Comment by thbkrkr** [comment]
Thank you for your feedback.
A new documentation will be added in a future release (PR #925).
