### ISSUE TITLE
Security: Kibana HTTP-side certificates

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#90]
We are already mirroring the `http` attribute that we have in the Elasticsearch CRD in the Kibana CRD but no behaviour is currently associated with that structure. 

We should therefore:
* configure client/Kibana server TLS based on the `http.tls` attribute 
* default to off if not defined
* generate self-signed certificate if SAN is specified
* allow users to specify their own certificate

**Comment by OzzyKampha** [comment]
Is there a ETA for this?

**Comment by sebgl** [comment]
@OzzyKampha this is planned for the next release. There is no defined release date yet, but should be in the months to come (before summer ends).

**Comment by pebrc** [comment]
Discussed with @sebgl some additional insights:
```
   http:
     service:
       spec:
         type: LoadBalancer
     tls:
       selfSignedCertificate:
         enabled: true
```
* case of user user provided certificates seems straight forward
* self-signed is more problematic as we need a way of turning those off
      * we want to keep the API the same to Elasticsearch (see above the yaml snippet)
      * defaults should also be the same
      * we therefore think Kibana should by default use self-signed certs as well
      * we want to give users a way to turn those off
      * while the `selfSignedCertificate` struct is  pointer we don't want to rely on `{}` to turn it on which would also not be compatible with the semantics of that struct in the context of Elasticsearch
      * we therefore think we should introduce an explicit `enabled` attribute defaulting to true to allow user to turn self-signed certificates off
