### ISSUE TITLE
Quickstart should specify minimum requirements

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/cloud-on-k8s#909]
GKE requires version 1.11+ of k8s, and k8s requires a matching version of kubectl.  Two users saw this error because of a kubectl mismatch: `Error from server (NotFound): error when creating "STDIN"`

I realize that this is a poor error message from kubectl, but since the min version of k8s should probably be specified, then adding in `and a matching version of kubectl` with a link to the [kubectl page ](https://kubernetes.io/docs/tasks/tools/install-kubectl/)would be helpful.  I am happy to write the PR if this is acceptable to the team.

**Comment by alaudazzi** [comment]
Hi Dan, thanks for highlighting this. Have you received any feedback yet from the team? Can I help?

**Comment by DanRoscigno** [comment]
I have not seen any comments @alaudazzi I did add the info to the solution instructions on the landing page.

**Comment by thbkrkr** [comment]
> k8s requires a matching version of kubectl.

I don't think it's true. Why do you say that? I currently have no issue with:
```bash
> k version --short
Client Version: v1.14.0
Server Version: v1.13.6-gke.6
```

**Comment by DanRoscigno** [comment]
Sorry, matching is wrong word. kubectl version should be within one minor of k8s version.

[Reference](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew)

The reason I brought this up is three people have come to me with problems running the quick start, and the root cause was an old version of kubectl

**Comment by alaudazzi** [comment]
Hi @DanRoscigno,

@thbkrkr and I briefly discussed this issue offline. As you propose, it makes sense to add a link to the [kubectl page](https://kubernetes.io/docs/tasks/tools/install-kubectl/), there where needed. Do you mind creating the PR for that or shall I? Possibly in line with the info already added to the solution instructions on the landing page.
Thank you!

**Comment by alaudazzi** [comment]
@thbkrkr, @DanRoscigno
There is already a Note in the Quickstart requirements, mentioning the Kubernetes version to be used: 1.11+
Do you think we should also add the link to [kubectl page](https://kubernetes.io/docs/tasks/tools/install-kubectl/) to this Note?
