### ISSUE TITLE
Upload YAML for namespace and global during CI release job

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#912]
Also upload content of `operators/config/operator/namespace` and `operators/config/operator/global` during CI release job.

**Comment by artemnikitin** [comment]
@pebrc Am I correctly understand that to generate other YAML files I will need to add command similar to https://github.com/elastic/cloud-on-k8s/blob/master/operators/Makefile#L144?

**Comment by pebrc** [comment]
Yes, but I don't think we need to commit the result of the concatenation into the repository (also true for all-in-one)

**Comment by artemnikitin** [comment]
Decided to close it for now
