### ISSUE TITLE
PersistentVolumes are tied to the Pod and are lost when the Pod is deleted.

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#926]
## Proposal

When a pod is deleted, the replacement pod should be bound to the same PersistentVolume.

## Impact

In this scenario, a pod is deleted and replaced but the replacement has a new PV.

The impact of this is that Elasticsearch will need to spend energy recovering the lost data (creating new replica shards, etc). If the replacement pod keeps the old PV, then no data is lost, and when the pod returns, it will be a faster recovery.

On my larger clusters, I have 4TB PVs, so a lost PV means a possible recovery of up to ~3.5TB[1] of data which is not a fun experience ;)

[1] ~3.5tb is about what we have usable after accounting for the default 10% disk water mark.

## Background

At present, persistent volumes are tied to the pod (the names are the same). When a pod is deleted, this means the persistent volume would be lost as the new pod will have a new PV and the old PV is probably lost?

General maintenance (of kubelets and to "restart" pods) will cause PV loss, I believe, given this implementation. The following are some scenarios where pods are deleted as part of normal k8s life:

* A pod is stuck and needs to be bounced. The common path for this in Kubernetes[1] appears to be roughly `kubectl delete pod xyz`
* A kubelet node dies. This deletes all the pods running on that kubelet.[2]
* A kublet is drained (normal for k8s and OS upgrades, etc). This evicts all pods on the node by deleting them[3]

[1] For Deployments, StatefulSets, ReplicaSets, Jobs, and CronJobs (and maybe other resource types), deleting a pod generally causes the parent resource to create a replacement, effectively "restarting" the pod.

[2] Per [Kubernetes Pod docs](https://kubernetes.io/docs/concepts/workloads/pods/pod/): 
>  If a Node dies, the Pods scheduled to that node are scheduled for deletion, after a timeout period. 

[3] Draining deletes pods:

```
% kubectl get pods
kNAME                       READY   STATUS    RESTARTS   AGE
example-66c5646447-vndx8   1/1     Running   0          43s

% kubectl get deployments
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
example   1         1         1            1           47s

% kubectl drain gke-jls-test2-default-pool-ea432126-2zpx
node/gke-jls-test2-default-pool-ea432126-2zpx cordoned

% kubectl get pods
NAME                       READY   STATUS        RESTARTS   AGE
example-66c5646447-scvpj   1/1     Running       0          12s
example-66c5646447-vndx8   1/1     Terminating   0          74s
```

## Prior art

StatefulSets do what I've described above -- when you delete a pod in a statefulset, the replacement pod  is attached to the same PV.

**Comment by barkbay** [comment]
I just did a test and it seems to work as expected: 

```
$ k get pods -o wide
NAME                                 READY   STATUS    RESTARTS   AGE     IP          NODE                                                 NOMINATED NODE
elasticsearch-sample-es-bn7stx5w2m   1/1     Running   0          2m20s   10.28.2.6   gke-michael-dev-cluster-default-pool-81b73d52-8gg4   <none>
elasticsearch-sample-es-gqsdfljfvk   1/1     Running   0          2m20s   10.28.0.9   gke-michael-dev-cluster-default-pool-1ce73fa4-t3mg   <none>
elasticsearch-sample-es-ncpc6z5mx5   1/1     Running   0          99s     10.28.1.8   gke-michael-dev-cluster-default-pool-0d78d94e-bhjg   <none>
``` 

```
$ k get pvc
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
elasticsearch-sample-es-bn7stx5w2m-data   Bound    pvc-c407e001-7df6-11e9-9dab-42010a9c00dc   2Gi        RWO            standard2      2m36s
elasticsearch-sample-es-gqsdfljfvk-data   Bound    pvc-c416c4a3-7df6-11e9-9dab-42010a9c00dc   2Gi        RWO            standard2      2m36s
elasticsearch-sample-es-ncpc6z5mx5-data   Bound    pvc-c422722e-7df6-11e9-9dab-42010a9c00dc   2Gi        RWO            standard2      2m36s
``` 

``` 
$ k delete pod elasticsearch-sample-es-ncpc6z5mx5
pod "elasticsearch-sample-es-ncpc6z5mx5" deleted
```

pod `elasticsearch-sample-es-ncpc6z5mx5` is recreated and use the same PVC: 
```
k get pods -o wide
NAME                                 READY   STATUS     RESTARTS   AGE     IP          NODE                                                 NOMINATED NODE
elasticsearch-sample-es-bn7stx5w2m   1/1     Running    0          3m16s   10.28.2.6   gke-michael-dev-cluster-default-pool-81b73d52-8gg4   <none>
elasticsearch-sample-es-gqsdfljfvk   1/1     Running    0          3m16s   10.28.0.9   gke-michael-dev-cluster-default-pool-1ce73fa4-t3mg   <none>
elasticsearch-sample-es-ncpc6z5mx5   0/1     Init:0/4   0          4s      <none>      gke-michael-dev-cluster-default-pool-0d78d94e-bhjg   <none>
```

```
$ k get pod elasticsearch-sample-es-ncpc6z5mx5 -o yaml
[...]
  - name: data
    persistentVolumeClaim:
      claimName: elasticsearch-sample-es-ncpc6z5mx5-data
[...]

$ k get pvc
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
elasticsearch-sample-es-bn7stx5w2m-data   Bound    pvc-c407e001-7df6-11e9-9dab-42010a9c00dc   2Gi        RWO            standard2      7m51s
elasticsearch-sample-es-gqsdfljfvk-data   Bound    pvc-c416c4a3-7df6-11e9-9dab-42010a9c00dc   2Gi        RWO            standard2      7m51s
elasticsearch-sample-es-ncpc6z5mx5-data   Bound    pvc-c422722e-7df6-11e9-9dab-42010a9c00dc   2Gi        RWO            standard2      7m51s
```

**Comment by nkvoll** [comment]
Could there be special considerations we need to take into account for when draining happens? E.g possibly wait for the pod to finish terminating before we create the new pod?

**Comment by barkbay** [comment]
I did several tests with `kubectl drain ...` and I was not able to reproduce. The operator waits for the pod to be fully deleted before it creates a new one, event when using the `drain` command.

Here is an example with a pod using a zonal disk with no available nodes in the zone _(because they have been cordoned and drained)_ , the Pod stays in a `Pending` state:

```
NAME                                                              HEALTH   NODES   VERSION   PHASE         AGE
elasticsearch.elasticsearch.k8s.elastic.co/elasticsearch-sample   green    2       7.1.0     Operational   25m

NAME                                     READY   STATUS    RESTARTS   AGE     IP           NODE                                                 NOMINATED NODE
pod/elasticsearch-sample-es-7g9tfdck2v   0/1     Pending   0          6m34s   <none>       <none>                                               <none>
pod/elasticsearch-sample-es-7mwrqhfl7t   1/1     Running   0          25m     10.28.2.11   gke-michael-dev-cluster-default-pool-81b73d52-8gg4   <none>
pod/elasticsearch-sample-es-pv74bthlln   1/1     Running   0          25m     10.28.0.11   gke-michael-dev-cluster-default-pool-1ce73fa4-t3mg   <none>

NAME                                                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/elasticsearch-sample-es-7g9tfdck2v-data   Bound    pvc-4af7bcf6-8074-11e9-9278-42010a9c00d4   2Gi        RWO            standard2      25m
persistentvolumeclaim/elasticsearch-sample-es-7mwrqhfl7t-data   Bound    pvc-4b01fc5b-8074-11e9-9278-42010a9c00d4   2Gi        RWO            standard2      25m
persistentvolumeclaim/elasticsearch-sample-es-pv74bthlln-data   Bound    pvc-4b0b1a63-8074-11e9-9278-42010a9c00d4   2Gi        RWO            standard2      25m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                             STORAGECLASS   REASON   AGE
persistentvolume/pvc-4af7bcf6-8074-11e9-9278-42010a9c00d4   2Gi        RWO            Delete           Bound    default/elasticsearch-sample-es-7g9tfdck2v-data   standard2               25m
persistentvolume/pvc-4b01fc5b-8074-11e9-9278-42010a9c00d4   2Gi        RWO            Delete           Bound    default/elasticsearch-sample-es-7mwrqhfl7t-data   standard2               25m
persistentvolume/pvc-4b0b1a63-8074-11e9-9278-42010a9c00d4   2Gi        RWO            Delete           Bound    default/elasticsearch-sample-es-pv74bthlln-data   standard2               25m
```

Associated event:
```
FailedScheduling   Pod   0/6 nodes are available: 2 node(s) were unschedulable, 4 node(s) had volume node affinity conflict
```

**Comment by jordansissel** [comment]
Let’s close this. I’m content with the findings. Thank you :)

**Comment by harsh0522** [comment]
For me i just change this property in elastic search .... label: true
![image](https://github.com/elastic/cloud-on-k8s/assets/42672408/8242a7db-80f6-4dd4-a4c4-b2a3974971af)

and even after helm uninstall/install i was able to connect to my old PVC and got my data back 

so what it does it search for label in cluster and when it get that label it attaches to the pod .
![image](https://github.com/elastic/cloud-on-k8s/assets/42672408/100c735c-cded-4ae5-9529-6d4ebfb32152)
