### ISSUE TITLE
Consider features from the Elasticsearch helm-chart

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#928]
This is more of a meta issue to review the features in the Elasticsearch helm-chart and determine if they are appropriate for this project.

* a [PodDisruptionBudget](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) to [set maximum unavailable nodes](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/poddisruptionbudget.yaml#L8).
* Consider a default  [antiAffinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) policy to [limit one Elasticsearch node](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L65-L73) (for a given group of nodes) per kubernetes node 
* Compare the [helm-chart readiness probe](https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L130-L160) with the [operator Elasticsearch readiness probe](https://github.com/elastic/cloud-on-k8s/blob/master/operators/pkg/controller/elasticsearch/pod/readiness_probe.go#L27-L47)

**Comment by jordansissel** [comment]
> PodDisruptionBudget 

https://github.com/elastic/cloud-on-k8s/issues/914

> default antiAffinity 

https://github.com/elastic/cloud-on-k8s/issues/915.

**Comment by sebgl** [comment]
> Compare the helm-chart readiness probe with the operator Elasticsearch readiness probe

Historically we were requesting `/_cat/master` to ensure a ready node was part of the cluster. We changed it in https://github.com/elastic/cloud-on-k8s/pull/626 to ensure a node could still be requested for reads even though the cluster itself is unhealthy.
We're probably going to change the implementation again with https://github.com/elastic/cloud-on-k8s/issues/916, where we need to make our readiness check compatible with both the service & the pod disruption budget.

**Comment by staticdev** [comment]
Why there isn't a Helm chart for Elasticsearch cloud operator?

Ex.: https://github.com/storageos/charts/tree/master/stable/storageos-operator

**Comment by jordansissel** [comment]
@staticdev A helm chart is out of scope for this issue. This issue is specific to reviewing any lessons learned while building the Elasticsearch helm chart to understand if any of that can be applied to the operator (such as a default antiAffinity).

If you're interested in having a helm chart for this operator, can you open a separate feature request for that?

**Comment by staticdev** [comment]
@jordansissel sure! #938

**Comment by sebgl** [comment]
@jordansissel I propose we close that one since other issues have been opened for the features you mentioned. Let's reopen if needed?

**Comment by jordansissel** [comment]
++ to close this one.
