### ISSUE TITLE
Bug when cluster domain is different from the default (cluster.local)

### ISSUE THREAD

**Issue by selmison** [elastic/cloud-on-k8s#939]
## Bug Report
**What did you do?**
I installed Elastic Cloud on Kubernetes (ECK) using the step-by-step instructions contained in the [doc](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html)

**What did you expect to see?**
O ECK is working

**What did you see instead? Under which circumstances?**

The **cluster domain** in our environment is different from the default (`cluster.local`) so it is generating the error bellow.

Is it possible to change in the operator this default value (`cluster.local`)or just omit it leaving the relative path (**htt://quickstart-es.default.svc:9200**)?

> {"level":"error","ts":1558736467.8484528,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"elasticsearch-controller","request":"default/quickstart","error":"Put https: //quickstart-es.default.svc.**cluster.local**:9200/_cluster/settings: dial tcp: lookup quickstart-es.default.svc.**cluster.local** on 10.96.0.10:53: no such host","errorCauses":[{"error":"Put https://quickstart-es.default.svc.**cluster.local**:9200/_cluster/settings: dial tcp: lookup quickstart-es.default.svc.**cluster.local** on 10.96.0.10:53: no such host"}]

**Environment**

* Version information:
	0.8.0

* Kubernetes information:
	* On premise 	

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Logs:
```
{"level":"error","ts":1558736467.8484528,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"elasticsearch-controller","request":"default/quickstart","error":"Put https://quickstart-es.default.svc.cluster.local:9200/_cluster/settings: dial tcp: lookup quickstart-es.default.svc.cluster.local on 10.96.0.10:53: no such host","errorCauses":[{"error":"Put https://quickstart-es.default.svc.cluster.local:9200/_cluster/settings: dial tcp: lookup quickstart-es.default.svc.cluster.local on 10.96.0.10:53: no such host"}],"stacktrace":"github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by sebgl** [comment]
Related to #319.

**Comment by adrianlzt** [comment]
A workaround is to edit the coredns server to convert those queries to your cluster name.
In the coredns ConfigMap (Corefile) add a line like (before the kubernetes line):
```
    rewrite name substring svc.cluster.local.my.name svc.my.name
```

**Comment by selmison** [comment]
> rewrite name substring svc.cluster.local.my.name svc.my.name


Perfect @adrianlzt Thanks!!!

That worked!!!

`rewrite name substring cluster.local my.name`

**Comment by selmison** [comment]
@adrianlzt Thanks!!!

I edit the coredns.:
`rewrite name substring cluster.local my.name`

Now `quickstart-es.default.svc.cluster.local` is being resolved correctly. However, a new error arose:

> {"type":"log","@timestamp":"2019-05-29T16:00:05Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://quickstart-es.default.svc.cluster.local:9200/"}
{"type":"log","@timestamp":"2019-05-29T16:00:05Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}

**Comment by nkvoll** [comment]
Closed by: https://github.com/elastic/cloud-on-k8s/pull/990
