### ISSUE TITLE
Support for tolerations

### ISSUE THREAD

**Issue by ohardy** [elastic/cloud-on-k8s#940]
## Proposal

Support for tolerations in Elastic and Kibana `spec`

**Comment by nkvoll** [comment]
This is coming :)

We intend to add it as part of https://github.com/elastic/cloud-on-k8s/issues/765, where we will no longer be cherry-picking fields from the provided pod template, but actually using it as a base template for the pods we create.

**Comment by nkvoll** [comment]
Closed in #943
