### ISSUE TITLE
How to remove the example "QuickStart" Cluster

### ISSUE THREAD

**Issue by Keithsc** [elastic/cloud-on-k8s#949]
I ran the quickstart example code and would now like to remove the example cluster but it doesn't seem that easy, I reran the example code snippit that I used to create the cluster but replaced "apply" with "delete" and that remove a "statefull set" I think...   but the elastic pods are still there so I've tried deleting each of them but they keep reappearing. 

could someone help ?
Thanks

**Comment by Keithsc** [comment]
Oops I didn't see there was also a daemonset that I needed to remove...
kubectl delete ds elasticsearch-operator-sysctl
kubectl delete service kubernetes

**Comment by sebgl** [comment]
Hi @Keithsc,

This is the proper way to uninstall the quickstart resources:

```bash
kubectl delete elasticsearch quickstart
kubectl delete kibana quickstart
```

This should delete all underlying Elasticsearch and Kibana resources (pods, secrets, etc.).

Then to uninstall the operator itself:

```bash
kubectl delete -f https://download.elastic.co/downloads/eck/0.8.0/all-in-one.yaml
```

**Comment by Choongkyu** [comment]
I tried to run `kubectl delete elasticsearch quickstart` while connected to GCP, but it hangs forever. I tried to ctrl+c out of it after 40 minutes of hanging and still saw quickstart. Is there a way to force delete this cluster?  thank you!

**Comment by sebgl** [comment]
> I tried to run kubectl delete elasticsearch quickstart while connected to GCP, but it hangs forever. I tried to ctrl+c out of it after 40 minutes of hanging and still saw quickstart. Is there a way to force delete this cluster? thank you!

This looks like your GCP cluster might be unresponsive?
Additionally, you can inspect the content of that resource and look for the presence of any `finalizer` in the resource metadata: `kubectl get elasticsearch quickstart -o json`. Those finalizers could prevent the resource deletion.
The operator itself, in recent versions, does not set any finalizer on the resource.

**Comment by Choongkyu** [comment]
@sebgl thank you! Running that, I'm seeing this:
```
{...
"finalizers": [
            "expectations.finalizers.elasticsearch.k8s.elastic.co",
            "observer.finalizers.elasticsearch.k8s.elastic.co",
            "secure-settings.finalizers.elasticsearch.k8s.elastic.co",
            "dynamic-watches.finalizers.k8s.elastic.co/http-certificates"
        ]
}
```
I'm able to create and delete new elasticsearch clusters just fine, but this one quickstart cluster won't go away. Your suggestion to review the finalizer led me to [this stackoverflow thread](https://stackoverflow.com/questions/52009124/not-able-to-completely-remove-kubernetes-customresource).  I then ran `kubectl patch elasticsearch/quickstart -p '{"metadata":{"finalizers":[]}}' --type=merge` and that made me no longer be able to see anything under `kubectl get elasticsearch` even without deleting it. Thank you!
