### ISSUE TITLE
Revisit k8s resource naming scheme

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#951]
We are currently applying a combination of random strings and type specific infixes (`kb`, `es` also not consistently sometimes we use `kibana`) to make sure we don't have name conflicts in certain types of k8s resources (secrets and pods) 

For example secrets:
```
quickstart-ca                     Opaque                                1         6d
quickstart-ca-private-key         Opaque                                1         6d
quickstart-elastic-user           Opaque                                1         6d
quickstart-es-ca                  Opaque                                1         6d
quickstart-es-rnlh6bhzlt-certs    Opaque                                3         6d
quickstart-es-rnlh6bhzlt-config   Opaque                                1         6d
quickstart-es-roles-users         Opaque                                3         6d
quickstart-extrafiles             Opaque                                1         6d
quickstart-internal-users         Opaque                                3         6d
quickstart-kibana-user            Opaque                                1         6d
quickstart-secure-settings        Opaque                                0         6d
```

Second example pods:
```
quickstart-es-rnlh6bhzlt             1/1       Running   0          6d
quickstart-kibana-787cf6b458-42v2l   1/1       Running   0          6d
```

@nkvoll  Raised the following questions around this: 

* Is the suffixing we’re doing the right thing?
* Other resources do not do this (e.g statefulsets only add -{ordinal})
* Not doing so would cause our Kibana and ES etc pods to potentially conflict (but extremely unlikely due to the randomized suffixing we do) if Kibana and ES is named the same.
* Could we call some of this user errors? E.g.  someone complaining they cannot tell the difference whether a pod is related to Kibana or ES by name should use the labels instead, or rename the Kibana resource?
* But what about internal/public secrets, services etc?

One implication of our current approach is the user defineable name is very short as we reserve a lot of characters for this naming scheme.

Discussed approaches: 
* only use random strings and avoid the type infixes 
* shorten the random string

**Comment by nkvoll** [comment]
For ES, we now use the pattern `{es.name}-es-{suffix}`, which at least is consistent.

**Comment by nkvoll** [comment]
I believe we discussed this and are at a place where we're decently happy, and we can always revisit later. Closing for now.
