### ISSUE TITLE
operator should run in runasany mode

### ISSUE THREAD

**Issue by das-chick** [elastic/cloud-on-k8s#953]
Wanted to start elastic-operator pod in openshift. does not come up due to access restrictions. all binaries are in /root and pod is running in runasany mode

* Version information:
0.8.0

* Kubernetes information:
	* On premise
	* Kubernetes distribution: Openshift 3.11

**Comment by barkbay** [comment]
Hi,

We are aware of some incompatibilities when the operator is deployed on Openshift, unfortunately there is no easy workaround for the moment.
The support of Openshift is on the roadmap and you should expect some improvements in one our next releases.

**Comment by thbkrkr** [comment]
Related to #541.

**Comment by thbkrkr** [comment]
Closing because OpenShift support is tracked by #541.
