### ISSUE TITLE
Compare supported PV type performance

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#961]
In order to give better recommendations for persistent volume use with the operator we need to run a few baseline benchmarks to a better indication of performance differences between 
* elastic-local volumes
* Cloud provider PVCs (GCE PD, AWS EBS)

**Comment by thbkrkr** [comment]
Interesting: https://engineering.mongodb.com/post/repeatable-performance-tests-ebs-instances-are-the-stable-option.

**Comment by david-kow** [comment]
Cloud provider PVCs were benchmarked, local volume provisioner benchmarking will be revisited in the future.
