### ISSUE TITLE
ability to set default elastic user password

### ISSUE THREAD

**Issue by djschny** [elastic/cloud-on-k8s#967]
## Proposal

**Use case. Why is this important?**

In many environments, being able to set the password to something assumed is important. For example in a training course where we provide instructions, it is cumbersome to have unique passwords for each student's install and have to make them find out what the password is from a secret and then populate it in configuration files like for filebeat, etc. 

I've tried work arounds with this. For example the `bin/elasticsearch-setup-passwords` command does not work from a cluster deployed by the operator which leads me to believe it was already changed. I then try to work around this by changing it with the API:

```
ES_GENERATED_PASSWORD=$(kubectl get secret es-k8s-logging-elastic-user -o=jsonpath='{.data.elastic}' | base64 --decode)
curl -X POST --insecure --user elastic:$ES_GENERATED_PASSWORD https://localhost:30920/_security/user/elastic/_password -H 'Content-Type: application/json' -d '{ "password" : "foobar" }'
```

However the above does not work because apparently the built-in users are not found and/or allowed to be changed with the API. Below was the error returned from the API:

`Validation Failed: 1: user must exist in order to change password;`

**Comment by nkvoll** [comment]
As you've noticed, it's not currently possible to configure the password of the `elastic` user. It's defined in the file realm which is managed by the operator internally. The only thing that can currently be done with the `elastic` user is to reset the password to a new random one by deleting the `<cluster-name>-es-elastic-user` Secret.

Would using those credentials once to create a new user (in the native realm) work for you? E.g along the lines of:

```bash
$ AUTH=elastic:$(kubectl get secret testing-es-elastic-user -o=go-template='{{ .data.elastic | base64decode }}')

$ curl -k -XPOST -u $AUTH https://localhost:9200/_security/user/my-user -H 'Content-Type: application/json' -d '{
  "password":"my-password",
  "roles":["superuser"]
}'
{"created":true}

$ curl -k -u my-user:my-password https://localhost:9200
{
  "name" : "testing-es-2qvmzzn9sl",
  "cluster_name" : "testing",
  ...
  "tagline" : "You Know, for Search"
}
```

**Comment by nkvoll** [comment]
Actually it's possible to set the password to a well known value by creating the `{clusterName}-es-elastic-user` Secret *before* creating the Elasticsearch resource:

``` bash
$ kubectl create secret generic testing-es-elastic-user --from-literal=elastic=foobar
secret/testing-es-elastic-user created
$ cat <<'EOFTEST' | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: testing
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 1
EOFTEST
elasticsearch.elasticsearch.k8s.elastic.co/testing configured
$ # set up any forwarding you need after the ES pod is done initializing, e.g in another terminal:
$ kubectl port-forward service/testing-es 9200:9200
$ curl -k -u elastic:foobar https://localhost:9200
{
  "name" : "testing-es-5ps8sl8sfn",
  "cluster_name" : "testing",
  ...
  "tagline" : "You Know, for Search"
}
```

Thanks to @agup006 for pointing this one out to me.

I would file this under "workaround" for now, and not an officially supported feature.

**Comment by djschny** [comment]
Wonderful @nkvoll and @agup006, this works great!

**Comment by MrRexZ** [comment]
[This PR](https://github.com/elastic/cloud-on-k8s/pull/2682) has been merged, so in the future after its release we'll be able to specify a custom creation of user & password in a secret file, so that should satisfy your use case.

**Comment by pantelis-karamolegkos** [comment]
Does the PR above creates a **complementary** mechanism for the `{{ cluster-name }}-es-elastic-user` secret creation? I mean this super user defined in  `{{ cluster-name }}-es-elastic-user` is going to be created either way, right?

**Comment by thbkrkr** [comment]
> Does the PR above creates a **complementary** mechanism for the `{{ cluster-name }}-es-elastic-user` secret creation?

You provide and reference secrets in the Elasticsearch resource containing custom users and roles, see the documentation: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s_file_realm.

> I mean this super user defined in `{{ cluster-name }}-es-elastic-user` is going to be created either way, right?

Yes!

**Comment by pantelis-karamolegkos** [comment]
Τhanks @thbkrkr .

So I assume there is no way foreseen to rotate this (say in case of a security incident) without destroying / recreating the cluster?
Or will creating a new `{{ cluster-name }}-es-elastic-user` cause a smooth rolling update with replacement of the old one?

I was considering using an `init` container to create the secret (with the appropriate RBAC permissions of course) but I don't know this would work out in case of a rolling update

**Comment by barkbay** [comment]
> So I assume there is no way foreseen to rotate this (say in case of a security incident) without destroying / recreating the cluster?
> Or will creating a new `{{ cluster-name }}-es-elastic-user` cause a smooth rolling update with replacement of the old one?

Maybe [this section in the documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-rotate-credentials.html#k8s-rotate-credentials) could help ?

**Comment by pantelis-karamolegkos** [comment]
@barkbay yes that was really helpful.

Thanks.

**Comment by siplo** [comment]
Hi, 

probably I miss point where is describe how to create filerealm definition in advanced - before elasticsearch instance is created. 

Tool for creating user and password  -  https://www.elastic.co/guide/en/elasticsearch/reference/current/users-command.html 
is installed on elasticsearch which I don't have right now - I just want to create one with pre populated userrealm.
Is this possible ? If not can you explain to me what is right order ?

I assume I have to create elasticsearch, log to this instance, create users, copy these information and then create kubernetes manifest to create secret and last step is update elastic configuration to use this secret. Am I right ?

Michal

**Comment by willzhang** [comment]
it help

**Comment by vishalk663** [comment]
> Actually it's possible to set the password to a well known value by creating the `{clusterName}-es-elastic-user` Secret _before_ creating the Elasticsearch resource:
> 
> ```shell
> $ kubectl create secret generic testing-es-elastic-user --from-literal=elastic=foobar
> secret/testing-es-elastic-user created
> $ cat <<'EOFTEST' | kubectl apply -f -
> apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
> kind: Elasticsearch
> metadata:
>   name: testing
> spec:
>   version: 7.1.0
>   nodes:
>   - nodeCount: 1
> EOFTEST
> elasticsearch.elasticsearch.k8s.elastic.co/testing configured
> $ # set up any forwarding you need after the ES pod is done initializing, e.g in another terminal:
> $ kubectl port-forward service/testing-es 9200:9200
> $ curl -k -u elastic:foobar https://localhost:9200
> {
>   "name" : "testing-es-5ps8sl8sfn",
>   "cluster_name" : "testing",
>   ...
>   "tagline" : "You Know, for Search"
> }
> ```
> 
> Thanks to @agup006 for pointing this one out to me.
> 
> I would file this under "workaround" for now, and not an officially supported feature.


But what will happen when the the cluster is already present and we want to change the elastic superuser password. we can't recreate elasticsearch cluster again
