### ISSUE TITLE
Document how/when to configure setVmMaxMapCount

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#970]
It defaults to `true` and causes us to use a privileged init container to set this according to https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html.

If this is configured on the host level instead, the privileged container can be skipped, which is preferable from a general security standpoint.

**Comment by thbkrkr** [comment]
Duplicate of #1031.
