### ISSUE TITLE
Elasticsearch resource name not recognized in 1.11.2 environment (client and server)

### ISSUE THREAD

**Issue by eedugon** [elastic/cloud-on-k8s#971]
**What did you do?**
Bring up a fresh new 1.11.2 Kubernetes cluster with kube-up.sh and deploy the Quickstart example of ECK.
kubectl also in version 1.11.2

**What did you expect to see?**
ECK working and being able to create a resource of `kind: Elasticsearch`

**What did you see instead? Under which circumstances?**
```
$ cat <<EOF | ./kubectl apply -f -
> apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
> kind: Elasticsearch
> metadata:
>   name: quickstart
> spec:
>   version: 7.1.0
>   nodes:
>   - nodeCount: 1
>     config:
>       node.master: true
>       node.data: true
>       node.ingest: true
> EOF
Error from server (NotFound): error when creating "STDIN": the server could not find the requested resource (post elasticsearchs.elasticsearch.k8s.elastic.co)

# if a yaml file is provided, the error is the same:
$ ./kubectl apply -f es_quickstart.yaml 
Error from server (NotFound): error when creating "es_quickstart.yaml": the server could not find the requested resource (post elasticsearchs.elasticsearch.k8s.elastic.co)

# And...
$ ./kubectl get elasticsearch
No resources found.
Error from server (NotFound): Unable to list {"elasticsearch.k8s.elastic.co" "v1alpha1" "elasticsearchs"}: the server could not find the requested resource (get elasticsearchs.elasticsearch.k8s.elastic.co)
```

However, Kibana resources can be created and listed without issues, which is weird.

Looking at the error (`elasticsearchs.elasticsearch.k8s.elastic.co`) it looks the problem might be related with the plural, as the custom resource is called `elasticsearches.elasticsearch.k8s.elastic.co`.

**Environment**
kubectl 1.11.2
Kubernetes 1.11.2

* Version information:
```
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes information:
- On GCE, installed via kube-up.sh

**Notes & Findings**
It looks the problem might be related with the client, because with kubectl 1.14.2 (and same 1.11.2 server), all works as expected, and the Elasticsearch resource can be created.

Also with a fresh new 1.14.2 cluster all works fine too.

This issue is reported just for reference, as per the doc 1.11+ should be supported, so feel free to ignore or close it if you conclude there's nothing to fix at Operator side.

**Comment by devdattakulkarni** [comment]
I also ran into this issue with kubectl version 1.11. When upgraded to 1.14 ElasticSearch Custom Resource creation worked.

**Comment by thbkrkr** [comment]
Related to #909.

**Comment by ccshih** [comment]
Except for upgrading to 1.14, any workaround for this issue?

**Comment by akaipham** [comment]
Same, any updates for 1.12 or lower?

**Comment by akaipham** [comment]
Update: My kubectl client version was 1.6 so that it yields the above error. After updating to latest version (`Client Version: v1.16.0`), the problem is solved, hope it helps.

**Comment by thbkrkr** [comment]
> Update: My kubectl client version was 1.6 so that it yields the above error. After updating to latest version (`Client Version: v1.16.0`), the problem is solved, hope it helps.

Good news :) Thanks for the update.

I checked and everything seems fine with kubectl `v1.11.10`.
