### ISSUE TITLE
Declarative Snapshot creation

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#976]
In the snapshot documentation at 
https://github.com/elastic/cloud-on-k8s/blob/master/docs/snapshots.md

there is following piece in the Spec. 

           command:
            - /bin/bash
            args:
            - -c
            - 'curl -s -i -k -u "elastic:$(</mnt/elastic/es-basic-auth/elastic)" -XPUT "https://elasticsearch-sample-es:9200/_snapshot/my_gcs_repository/%3Csnapshot-%7Bnow%2Fd%7D%3E" | tee /dev/stderr | grep "200 OK"'
          restartPolicy: OnFailure
          volumes:

For users, the curl command is difficult to understand. Also, providing such a command goes against the declarative model. Wouldn't it be better to hide these details from the user? 

I understand that this example is shown using CronJob so such a command is necessary. But why not create a SnapShot CRD that hides these details and expose only certain things through its Spec for users? 

On a related note I came across some recent merges relating to Snapshots, but it was not clear whether they were related to a Snapshot related CRD.

**Comment by sebgl** [comment]
Interesting question :)

As you may have noticed, we did have a snapshot management feature a while back, including a Snapshot CRD that would allow you to specify a S3/GCS repository and a CRON-like expression. The operator would then be responsible for managing something similar to the CronJOb described in https://github.com/elastic/cloud-on-k8s/blob/master/docs/snapshots.md.

However, we realised Snapshot lifecycle management will be available in Elasticsearch upcoming releases, see https://github.com/elastic/elasticsearch/issues/38461. At that point we don't want to keep on maintaining our own snapshot feature that would probably not be as good as Elasticsearch's builtin one. So we'd probably have to deprecate this feature only a few months after releasing it.

We decided to remove the Snapshot CRD to fallback on the CronJob sample that people can set up according to their need for that reason. The `curl` command itself does look a bit complex, but I think it's still fairly straightforward to setup and customise.

**Comment by devdattakulkarni** [comment]
Ah okay, makes sense. Thanks for the explanation.

Will take a look at the links and add questions/comments if any.

**Comment by sebgl** [comment]
Let's close this issue and reopen if needed @devdattakulkarni?

**Comment by devdattakulkarni** [comment]
👍
