### ISSUE TITLE
Understanding Licenses

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#979]
Given that this repo is licensed under the Elastic License, I just wanted to understand in simple terms what things are allowed vs. not allowed with respect to the repo.

Also, the licenses that are referenced in the codebase (License CRDs and/or eventually Secrets), are the end-user licenses and not this repo's Elastic License, correct?

**Comment by papko26** [comment]
I second that question. As I can see at https://www.elastic.co/subscriptions, all functionality of Elastic Cloud on Kubernetes is available with basic license. So, сan I depend on deploying elastic cloud cluster on our bare-metal k8s without any licensing issues with basic license, or I should expect to met any limitations of functionality, until enterprise license will not be purchased?

**Comment by agup006** [comment]
@devdattakulkarni @papko26 ECK has functionality that exists both under basic (Free to use) and enterprise (paid)

The subscription table referenced shows the functionality that exists within basic (Free to use) today. To answer the question you can depend on deploying Elasticsearch on bare metal k8s for your own use. As we continue to build additional functionality we will be clear on what is Free and what is Paid and like the Elastic Stack, all (and only) the free features will be available by default, and any paid features can be easily enabled with a trial.

The License CRDs were a way to unlock aspects of that enterprise functionality, and of course, as this is an alpha release, we are continuing to change how a user can enable and try some of this functionality.

If you have any specific questions for your circumstance feel free to email elastic_license@elastic.co

**Comment by uric** [comment]
To clarify a bit more: the current functionality licensed under the Basic tier will stay so. This includes the following (screenshot from the subsctions page linked above): 

![image](https://user-images.githubusercontent.com/167374/58981885-f59ff800-87db-11e9-8435-6faa68e1cd78.png)

Over time, we intend to add additional functionality to both the Basic and Enterprise tiers. 
As @agup006 mentioned, the functionality licensed under the Enterprise tier will not be enabled by default, and enabling it will require an explicit step of enrolling into a time-limited trial, or installing an Enterprise license.

**Comment by devdattakulkarni** [comment]
@agup006 @uric Thanks for the explanation 👍

**Comment by simply-news** [comment]
Hi, I am still confused... how do i enable custom cluster topographies (hot-warm-cold)? 
How do i enable Elastic Cloud Enterprise dashboard on Kubernetes too?
Thanks.

these are my CRDs:
apmservers.apm.k8s.elastic.co                     2019-09-10T08:36:23Z
elasticsearches.elasticsearch.k8s.elastic.co      2019-09-10T08:36:23Z
eniconfigs.crd.k8s.amazonaws.com                  2019-09-10T07:28:01Z
kibanas.kibana.k8s.elastic.co                     2019-09-10T08:36:23Z
trustrelationships.elasticsearch.k8s.elastic.co   2019-09-10T08:36:23Z
