### ISSUE TITLE
Move samples folder out of operators folder tree?

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#980]
Currently examples are in https://github.com/elastic/cloud-on-k8s/tree/master/operators/config/samples

These are hard to find from the repo root. 

Could the samples be moved under docs/ or at the repo root itself?

**Comment by nkvoll** [comment]
I think we have some work to do regarding making sure the samples detail more of the features, and making them significantly more prominent. This likely includes linking to them from the operators Readme.

Whether they should move out of the operators tree I'm less certain of, they seem to have some natural coupling there. Discoverability matters and I agree it's hard to find right now.

**Comment by sebgl** [comment]
+1 with what @nkvoll said. Improving our docs should help a lot here.
Closing this for now.
