### ISSUE TITLE
Why two different ways to deploy Kibana

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#981]
In Kibana samples 
https://github.com/elastic/cloud-on-k8s/tree/master/operators/config/samples/kibana

there are two different ways to configure Kibana with ElasticSearch instance.

I was wondering what is the difference between them?

The option where Kibana references ElasticSearch via Name running in same cluster seems understandable. What would be the use-case where second approach, which requires ElasticSearch instance URL to be provided in the Spec, will be useful?

**Comment by sebgl** [comment]
I think there are 3 reasons for this:

1. This allows you to deploy only Kibana in your Kubernetes cluster, targeting any Elasticsearch cluster that may live outside the Kubernetes cluster.
2. In the future, it may help targeting an Elasticsearch cluster living on a distant Kubernetes cluster.
3. The way the code is implemented  allows us to decouple controllers:
    * The Elasticsearch controller focuses on Elasticsearch only
    * The Kibana controller focuses on Kibana only, using the Elasticsearch URL and credentials provided in the Kibana resource
    * The Elasticsearch-Kibana controller parses a Kibana resource referencing an Elasticsearch resource to derive the proper URL and credentials, that it injects back into the Kibana resource, for the Kibana controller to consume.

Does that answer your question @devdattakulkarni?

**Comment by devdattakulkarni** [comment]
@sebgl Yes, this answers the question. I had guessed that options 1 and 2 might be the reason for having two ways of configuring Kibana. The thing I thought was, probably it might make sense to accommodate remote ES endpoint in a future release, unless the end-to-end with Kibana in one cluster and Elasticsearch outside is already working. Based on the quick start and the examples I thought that both in the same cluster is the working configuration currently. But I can be wrong.

About point 3 -- is it possible to subsume the functionality of ES-Kibana controller inside the Kibana controller? Even there there are two ways to configure Elastic endpoint in Kibana Custom Resource, from code perspective wouldn't it be simpler to have only two controllers and not three?

**Comment by sebgl** [comment]
> About point 3 -- is it possible to subsume the functionality of ES-Kibana controller inside the Kibana controller? Even though there are two ways to configure Elastic endpoint in Kibana Custom Resource, from code perspective wouldn't it be simpler to have only two controllers and not three?

Yes, we asked ourselves that question a few times 😄 

That's also about namespace responsibilities: we want to support Elasticsearch running in one namespace, and Kibana(s) running in other namespace(s). Then there could be a future where you want: 
* the Elasticsearch controller running in the ES namespace (controlled by one team in your organization) with permissions restricted to that particular namespace
* the Kibana controller running in the Kibana resource namespace (controlled by another team in your organization) with permissions restricted to that particular namespace
*the Kibana-ES Association controller running in another namespace (or one of the 2 above) having permission to access both namespace

We're not sure yet this is something people would actually need. But the current split in 3 different controllers would allow that. We decided to keep that door open, the side-benefit being the code split into 3 different controllers whose responsibility can be individually tested.

(I'm not saying this is a hard decision we won't revert at some point, let's see what the future is made of! 😄 )

**Comment by sebgl** [comment]
Let's close this issue and reopen if needed @devdattakulkarni?

**Comment by devdattakulkarni** [comment]
Thanks @sebgl for explanation. Sounds good.
