### ISSUE TITLE
How to access Kibana on same LoadBalancer IP as ES instance?

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#982]
After successfully deploying ES (https://github.com/elastic/cloud-on-k8s/issues/975), I wanted to deploy Kibana on the same cluster.

Note that I have ES exposed on a GKE through service of type LoadBalancer. I am able to access ES instance through LoadBalancer IP and 9200 port over https.

When Kibana is added to the mix I want to be able to access Kibana instance on the same LoadBalancer IP but on 5601 port. How to achieve this result?

I looked at the Kibana Type definition to understand if it would be possible to provide static IP to use in the http section in Kibana Spec.

https://github.com/elastic/cloud-on-k8s/blob/master/operators/pkg/apis/common/v1alpha1/common.go#L80

But it seems to support ClusterIP, LoadBalancer, NodePort only.

(May be I can use NodePort for both ES and Kibana? Hmm..I will try that.)

If you have any alternate suggestions, please let me know.

**Comment by sebgl** [comment]
Load balancer service types in Kubernetes have a few weaknesses:

* they focus on routing L4 traffic (not L7)
* they usually rely on a dynamic IP address upon which you don't really have static control
* they focus on a single service, you can't really setup multiple services behind a single LoadBalancer IP

An alternative to that is using an [ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/). It does require a bit more configuration, but allows you to:

* setup multiple services behind a single ingress proxy
* setup some advanced rules for URL and port rewriting (example: expose ES on https://es.my-dns.com:443 and Kibana on https://kibana.my-dns.com)  

It's up to you to setup an ingress resource the way you'd like, pointing to both Elasticsearch and Kibana existing services. If you do that you should probably also remove `type: LoadBalancer` from the Elasticsearch and Kibana specs.

Using ingresses require you to deploy an ingress controller in your Kubernetes cluster. [If you are using GKE, you can rely on the default one](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer).

**Comment by sebgl** [comment]
Ingress configuration is very specific to the provider and ingress controller people are using.
I don't think we can support setting it up in the operator: it's probably best to leave it up to the user to create their own ingress resources pointing to ES and Kibana services.

I'm closing this issue, please reopen if you think it should be @devdattakulkarni!

**Comment by devdattakulkarni** [comment]
@sebgl Thanks for the explanation. Your points about LoadBalancer type make sense. I will try with Ingress and see how that goes.
