### ISSUE TITLE
Https setup for kibana

### ISSUE THREAD

**Issue by OzzyKampha** [elastic/cloud-on-k8s#985]
I cant seem to find a way to activate https for kibana, is it possible in alpha?

**Comment by sebgl** [comment]
Hi @OzzyKampha! Unfortunately it's not implemented yet in the alpha release.
I would suggest putting an additional proxy in front of the Kibana service to handle TLS termination. I think most k8s ingress controllers can do that.

We plan to have https support for Kibana in the next release.

**Comment by sebgl** [comment]
I'm closing this one, let's keep #90 open though.
