### ISSUE TITLE
Randomize GKE region for e2e tests on CI

### ISSUE THREAD

**Issue by artemnikitin** [elastic/cloud-on-k8s#994]
Recently, we had an issue with inability to create instances in GCP. To prevent or minimize such situations in the future it make sense to randomize selection of GKE regions for e2e tests on CI

**Comment by nkvoll** [comment]
Won't this cause us to randomly run out of resources? Wouldn't it be better to ensure we have the right limits in place with GKE in one specific region?

**Comment by artemnikitin** [comment]
> Won't this cause us to randomly run out of resources?

It's possible

> Wouldn't it be better to ensure we have the right limits in place with GKE in one specific region?

The thing is that at the moment it's not fully clear if it's because we hit limit or because there are no more instances in GCP region. Also, it's possible that someday region in GCP may fail. It happened with AWS in the past. In such cases in the future with random regions, we will have partially working CI instead of not working at all CI until we fix it.

I opened `infra` ticket to dig into that happened. If it was because we hit limit, then for sure it make sense to increase limit instead of launch in random regions.

**Comment by thbkrkr** [comment]
Closure because it is no longer an issue and the randomization of the region does not seem the best way to manage this kind of problem.
