### ISSUE TITLE
Example of connecting/exporting application logs to ES

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#998]
In normal setups there is Filebeat/Logstash/Fluentd that collects application logs and sends them to ElasticSearch.

When using the Operator how to configure this pipeline?

**Comment by sebgl** [comment]
We can probably improve [this section of the doc](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-accessing-elastic-services.html#k8s-request-elasticsearch-endpoint).

**Comment by pebrc** [comment]
We have a Beats recipe in the [repo](https://github.com/elastic/cloud-on-k8s/tree/master/config/recipes) and a PR to add a Beats CRD in review, which will also get documentation once merged. I don't see right now how log ingestion would be any different in ECK than in "normal setups" you still need Filebeat or any other log shipper, so any documentation related to these tools is also valid in an ECK context.
